### ISSUE TITLE
API Manager 2 node deployment gives an event error

### ISSUE THREAD

**Issue by bhathiya** [wso2/api-manager#1]
**Description:**
The following error occurs in the 2 node deployment of APIM. 

```
GatewayTokenRevocationMessageListener Event dropped due to unsupported message type class org.wso2.andes.client.message.AMQPEncodedMapMessage
```

**Affected Product Version:**
4.0.0

**Comment by bhathiya** [comment]
Solution: update the `deployment/server/eventpublishers/tokenRevokeEventJMSPublisher_2.xml` file's 

```
<mapping customMapping="disable" type="map"/>
```
to
```
<mapping customMapping="disable" type="json"/>
```

**Comment by hisanhunais** [comment]
The same issue has been reported in https://github.com/wso2/product-apim/issues/12831

**Comment by chashikajw** [comment]
Fixed in https://github.com/wso2/product-apim/pull/12840
