### ISSUE TITLE
Check and merge rest api version upgrade PRs

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#1010]
### Description

Need to check and merge the rest api version upgrade PRs in [1]

[1] https://github.com/wso2/api-manager/issues/958

### Affected Component

APIM

**Comment by tharikaGitHub** [comment]
##Sub tasks :

- [ ] Merge carbon-apimgt PR - https://github.com/wso2/carbon-apimgt/pull/11659
- [ ] Merge apim-apps PR - https://github.com/wso2/apim-apps/pull/386
- [ ] Merge product-apim version upgrade PR - https://github.com/wso2/product-apim/pull/13020
- [ ] Merge product-apim integration test PR - https://github.com/wso2/product-apim/pull/13017
- [ ] Merge apictl PR - https://github.com/wso2/product-apim-tooling/pull/958
- [ ] Merge Integration Studio PR - https://github.com/wso2/integration-studio/pull/1166

**Comment by tharikaGitHub** [comment]
This task is on-hold due to a build failure issue in apim-apps repo. There is an issue in publisher-api.yaml file download. This is currently tracked through https://github.com/wso2/api-manager/issues/1015

**Comment by tharikaGitHub** [comment]
After the fix for https://github.com/wso2/api-manager/issues/1015 there are unit test failures we need to look into. This is in progress.

**Comment by tharikaGitHub** [comment]
The 2 PRs [1] and [2] are reverted until the apim-apps unit tests are fixed.

[1] https://github.com/wso2/carbon-apimgt/pull/11659
[2] https://github.com/wso2/apim-apps/pull/386

**Comment by IsuruMaduranga** [comment]
Test failures are fixed with the following PRs. The following two PRs also contain changes done by reverted two PRs ( https://github.com/wso2/carbon-apimgt/pull/11659, https://github.com/wso2/apim-apps/pull/386 )

1. https://github.com/wso2/apim-apps/pull/397
2. https://github.com/wso2/carbon-apimgt/pull/11698

**Comment by tharikaGitHub** [comment]
Merged the 2 PRs below.

1. https://github.com/wso2/apim-apps/pull/397
2. https://github.com/wso2/carbon-apimgt/pull/11698

Waiting for the release build to complete in order to upgrade the rest of the repos.

**Comment by tharikaGitHub** [comment]
**Update** : apim-apps release build is still in progress. Need to merge PR https://github.com/wso2/product-apim/pull/13039 after that.

**Comment by tharikaGitHub** [comment]
**Update** : The product-apim version upgrade PR and the integration test PRs were merged. And a product-apim build is triggered.

1. https://github.com/wso2/product-apim/pull/13039
2. https://github.com/wso2/product-apim/pull/13017

**Comment by tharikaGitHub** [comment]
**Update** : The following PRs are added to fix the issue. Currently the build is in progress to check the test failures.

1. https://github.com/wso2/carbon-apimgt/pull/11709
2. https://github.com/wso2/product-apim/pull/13044

**Comment by tharikaGitHub** [comment]
**Update** : All PRs are merged. Hence closing.
