### ISSUE TITLE
Azure AD KM connector as OOTB KM in APIM-3.2.0 and onwards

### ISSUE THREAD

**Issue by hrandika** [wso2/api-manager#1014]
### Problem

Need a AzureAD as a Key manger for APIM

### Solution

Implement a customer key manger [1]

[1] - https://apim.docs.wso2.com/en/latest/administer/key-managers/configure-custom-connector/

### Affected Component

APIM

### Version

3.2.0 onwards

**Comment by thisaltennakoon** [comment]
**Task Breakdown** 

- [x]  Implementation
- [ ] Documentation Changes
- [ ] Testing
