### ISSUE TITLE
Multiple labels(gateway_labels) in GW doesn't work in APIM 4.0

### ISSUE THREAD

**Issue by ksankeerth** [wso2/api-manager#103]
## Steps to reproduce the issue :

- Get the latest APIM 4.0

- Add two GW environments in deployment.toml [“Default” and “Second”]

- Add two GW labels in deployment.toml [“Default” and “Second”]

eg: `[apim.sync_runtime_artifacts.gateway]
gateway_labels =["Default", "Second"]`

- Both environments “Default” and “Second” point to the same GW (All-in-one)

- Publish API to “Default'' environment ONLY.

- Invoke the API

- The response will be an error code: 900900

### How will you implement it

---

**Comment by hisanhunais** [comment]
The fix has been done using https://github.com/wso2/carbon-apimgt/pull/11275
