### ISSUE TITLE
Change the product display version in all UI components

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/api-manager#1049]
### Description

Change the APIM version to 4.2.0 in 
- Publisher
<img width="440" alt="Screenshot 2022-11-29 at 11 34 38 AM" src="https://user-images.githubusercontent.com/4861150/204451480-b71f2f5b-e102-4181-84fa-d3ed22a684be.png">

- dev portal, 
<img width="359" alt="Screenshot 2022-11-29 at 11 33 55 AM" src="https://user-images.githubusercontent.com/4861150/204451500-b082b2e2-dc53-48e3-aca0-6eebbdeb0656.png">

- admin portal 
<img width="671" alt="Screenshot 2022-11-29 at 11 33 49 AM" src="https://user-images.githubusercontent.com/4861150/204451524-624c84f2-d7bb-4489-8aa9-825844cc4545.png">

- carbon consol's about page. 

<img width="1728" alt="Screenshot 2022-11-29 at 11 33 10 AM" src="https://user-images.githubusercontent.com/4861150/204451544-332e7788-2912-4491-adcf-6988e0e3a219.png">

### Steps to Reproduce

-

### Affected Component

APIM

### Version

4.2.0

**Comment by tharikaGitHub** [comment]
The following PRs fixes this issue.

1. https://github.com/wso2/apim-apps/pull/392
2. https://github.com/wso2/product-apim/pull/13034

**Comment by tharikaGitHub** [comment]
Closing as the above 2 PRs are merged.
