### ISSUE TITLE
ELK support for MI (operational analytics)

### ISSUE THREAD

**Issue by heysulo** [wso2/api-manager#105]
### Describe your problem
Provide ELK stack support for MI in order to receive/process operational analytics 

### Describe your solution
Please refer the [design documentation](https://docs.google.com/document/d/1-nOnHk-yYcfKQ-A7DxhNC84Lr9dPWmeAbP7SwQbPdYQ/edit?usp=sharing)

### How will you implement it
Following are the implementation milestones

- [x] #230
- [x] #234
- [x] #236
- [x] #231
- [x] #232
- [x] #235
- [x] #233

### Affected Component
MI, WSO2-Synapse

### Version
4.1.0
---

**Comment by maneeshaheshan** [comment]
Hi @heysulo,

Do we have an update on the above task ? 

Regards
Maneesha

**Comment by heysulo** [comment]
Hi @maneeshaheshan,
We are still reviewing the implementation. As I'm (the feature developer) new to the product, this needs to be thoroughly reviewed and tested.

**Comment by tharikaGitHub** [comment]
Closing the issue as the feature is completed.
