### ISSUE TITLE
Generate Doc feature not working

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/api-manager#1050]
### Description

Generated doc does not have any resources related to the API.

<img width="1724" alt="Screenshot 2022-11-29 at 12 21 12 PM" src="https://user-images.githubusercontent.com/4861150/204461035-90908826-557e-4ca7-97d5-16e0808f746e.png">

### Steps to Reproduce

- Create an API and go to the documents section
- From the 'Generated Document' section, click view doc

### Affected Component

APIM

### Version

4.2.0

**Comment by msm1992** [comment]
- **This issue occurs only with the pizzashack API**. When tried with other APIs including swagger 2.0 and openapi 3.0 definitions, all of them listed the resources fine. 
- Checked the pizzashack API deifnition in stoplight live demo at https://elements-demo.stoplight.io/ but there the resources were getting listed without any issues. Therefore need to check this further in APIM.
