### ISSUE TITLE
http.nonProxyHosts not available for https transportSender

### ISSUE THREAD

**Issue by isurul28** [wso2/api-manager#106]
### Description:
In the deployment.toml file under the [transport.http] we have below properties to configure to let traffic go through a HTTP proxy server[1]

sender.proxy_host
sender.proxy_port
Like wise we have below properties to let traffic go through a HTTPS proxy server 

sender.secured_proxy_host
sender.secured_proxy_port
Issue : 
Also there is parameter named sender.non_proxy_hosts where we can put a list of hosts to which the HTTP traffic should be sent directly without going through the proxy server.

But when we apply the sender.non_proxy_host its only getting applied to HTTP transport sender. Its not getting applied to HTTPS transport sender. (sample deployment.toml file and resulting axis2.xml file is attached)
Further checking key-mapping.json file and axis2.xml.j2 file i can see that only below are available for HTTPS transport sender

 
```

"transport.http.sender.hostname_verifier": "transport.https.sender.parameter.'HostnameVerifier'",
  "transport.http.sender.secured_protocols": "transport.https.sender.parameter.HttpsProtocols",
  "transport.http.sender.secured_proxy_host": "transport.https.sender.parameter.'http.proxyHost'",
  "transport.http.sender.secured_proxy_port": "transport.https.sender.parameter.'http.proxyPort'",
```

 The sender.non_proxy_host is not mapped for https sender in the key-mapping file. 
 
After adding the below modification to axis2.xml.j2 file located in the path <MI_HOME>/repository/resources/conf/templates/conf/axis2/ directory. We can see the http.nonProxyHosts in the axis2.xml file under https sender. Also the use-case is working
Modification : (below snippet added to https sender)

```
{% if transport.http.sender.non_proxy_hosts is defined %}
        <parameter name="http.nonProxyHosts" locked="false">{% for parameter_value in transport.http.sender.non_proxy_hosts %}{{parameter_value}}{% if loop.index < transport.http.sender.non_proxy_hosts|length %}|{% endif %}{% endfor %}</parameter>
        {% endif %}
```

[1].https://apim.docs.wso2.com/en/latest/reference/config-catalog-mi/#https-transport-non-blocking-mode
### Steps to reproduce:
1.Create a proxy server as mentioned in [2]. 
2.Send HTTPS request to the configured proxy server via MI

[2].https://ei.docs.wso2.com/en/latest/micro-integrator/setup/configuring_proxy_servers/

### Affected product version:
MI 4.X

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by YasasRangika** [comment]
Closing this issue as the master branch PR: https://github.com/wso2/micro-integrator/pull/2715 has already been merged.
