### ISSUE TITLE
Registry resource related management APIs does not adhere to registry.xml config

### ISSUE THREAD

**Issue by arunans23** [wso2/api-manager#1062]
### Description

Registry resource-related management APIs are always reading registry files located at "MI_HOME/registry" even if we have configured different locations for the registry in registry.xml.

This is happening because we are creating a [new Registry object](https://github.com/wso2/micro-integrator/blob/v4.2.0-m1/components/org.wso2.micro.integrator.extensions/org.wso2.micro.integrator.management.apis/src/main/java/org/wso2/micro/integrator/management/apis/RegistryResource.java#L93) without reusing the existing registry. Hence, it is getting initiated with the default values.

### Steps to Reproduce

1. Configure registry.xml to point to a different location.
```
<!-- Registry declaration of the WSO2 micro-integrator -->
<registry xmlns="http://ws.apache.org/ns/synapse" provider="org.wso2.micro.integrator.registry.MicroIntegratorRegistry">
    <parameter name="cachableDuration">15000</parameter>
    <!--
        Uncomment below parameters (ConfigRegRoot, GovRegRoot, LocalRegRoot) to configure registry root paths
        Default : <EI_HOME>/wso2/micro-integrator/registry/{governance | config | local}
        Example : <parameter name="GovRegRoot">file:///Users/JohnDoe/registry/governance</parameter>
    -->
    <!--
    <parameter name="ConfigRegRoot">{Root directory path for configuration Registry}</parameter>
    <parameter name="GovRegRoot">{Root directory path for governance Registry}</parameter>
    <parameter name="LocalRegRoot">{Root directory path for local Registry}</parameter>
    -->
    <parameter name="ConfigRegRoot">file:///tmp/registry/config</parameter>
    <parameter name="GovRegRoot">file:///tmp/registry/governance</parameter>
    <parameter name="LocalRegRoot">file:///tmp/registry/local</parameter>
</registry>
```

2. Create some registry files in the above-mentioned location.
3. Configure MI to point to the dashboard, and start the server and dashboard.
4. If you view the registry resources, it will not list the registry files created in the above location.

### Affected Component

MI

### Version

4.2.0-m1

**Comment by AnuGayan** [comment]
By the preliminary analysis, it seems like the RegistryResource class and all the methods have been written in such a way that the registry location is provided as a single configuration and config, local and gov registry is inside of that root folder.  But according to the configurations, 3 separate locations can be provided for each location without sharing the same root folder.

**Comment by AnuGayan** [comment]
Hi All,

The API for registry resources has been written only considering the default registry path, Due to that, all the methods written to facilitate the function which uses the resource path have to be rewritten in order to mitigate the issue. 

Furthermore, since config, local and gov registry can be pointed to any folder, each scenario has to be handled individually when loading the file and folders.

Thank You,
Anusha
