### ISSUE TITLE
Key generation fails when a Custom Key Manager is created other than the IS Key Manager

### ISSUE THREAD

**Issue by ChinthakaJ98** [wso2/api-manager#1064]
### Description

When a custom key manager is created other than the WSO2 Identity Server, key generation fails due to not being able to initialize the created custom key manager. This occurs due to the logic mentioned in [1] which results in a null pointer exception as the required fields in that if block is not available in other key managers. Ideally only the Resident Key Manager should enter this if block as the REVOKE_TOKEN_ENDPOINT is only configured in the Resident Key Manager.

[1] https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AMDefaultKeyManagerImpl.java#L752

### Steps to Reproduce

Create a custom key manager other than WSO2 Identity Server and generate keys for an application.

### Affected Component

APIM

### Version

4.2.0-M1

**Comment by GihanAyesh** [comment]
Added the PR with the fix : https://github.com/wso2/carbon-apimgt/pull/11704
