### ISSUE TITLE
Enable ProxyServiceSecurityTestCase

### ISSUE THREAD

**Issue by chanikag** [wso2/api-manager#1067]
This is to enable https://github.com/wso2/micro-integrator/blob/master/integration/mediation-tests/tests-service/src/test/java/org/wso2/carbon/esb/proxyservice/test/secureProxy/ProxyServiceSecurityTestCase.java

**Comment by chanikag** [comment]
- [ ] UsernameToken
- [ ] Non-repudiation
- [ ] Integrity
- [ ] Confidentiality
- [ ] Sign and encrypt - X509 Authentication
- [ ] Sign and Encrypt - Anonymous clients
- [ ] Encrypt only - Username Token Authentication
- [ ] Sign and Encrypt - Username Token Authentication
- [ ] SecureConversation - Sign only - Service as STS - Bootstrap policy - Sign and Encrypt , X509 Authentication
- [ ] SecureConversation - Encrypt only - Service as STS - Bootstrap policy - Sign and Encrypt , X509 Authentication
- [ ] SecureConversation - Sign and Encrypt - Service as STS - Bootstrap policy - Sign and Encrypt , X509 Authentication
- [ ] SecureConversation - Sign Only - Service as STS - Bootstrap policy - Sign and Encrypt , Anonymous clients
- [ ] SecureConversation - Sign and Encrypt - Service as STS - Bootstrap policy - Sign and Encrypt , Anonymous clients
- [ ] SecureConversation - Encrypt Only - Service as STS - Bootstrap policy - Sign and Encrypt , Username Token Authentication
- [ ] SecureConversation - Sign and Encrypt - Service as STS - Bootstrap policy - Sign and Encrypt , Username Token Authentication

**Comment by chanikag** [comment]
PR https://github.com/wso2/micro-integrator/pull/2800

**Comment by nandika** [comment]
1. Remove the not supporting scenarios from studio
2. Add documentation on the scenarios that will no longer be supported in the product
3. Add documentation on how to use the working ws-security scenarios - how to setup and execute

**Comment by chanikag** [comment]
This will be tracked in https://github.com/wso2/api-manager/issues/1013
