### ISSUE TITLE
No input field to provide organization on Self Sign-up page

### ISSUE THREAD

**Issue by YasasRangika** [wso2/api-manager#1071]
### Description

There is no input field to provide organization on the Self Sign-up page, hence failing application sharing as in [1].

### Steps to Reproduce

Follow the steps in [1].

[1] https://apim.docs.wso2.com/en/4.2.0/consume/manage-application/sharing-applications/sharing-applications/on

### Affected Component

APIM

### Version

APIM-4.2.0-Alpha

**Comment by tharikaGitHub** [comment]
After the upgrade to be compatible with Identity Server 6.0.0, the self signup page does not contain the Organization field by default. Hence Application sharing feature does not work by following the steps previously mentioned in the documentation[1].

After configuring the organization claim from the management console specifically, this feature works. Hence this should be added to the documentation.

<img width="1512" alt="Screen Shot 2022-12-04 at 12 14 55 PM" src="https://user-images.githubusercontent.com/8557410/205478273-028c44c2-f222-4fe2-a419-aba5a34e72e4.png">

Tracked with doc type git issue - https://github.com/wso2/docs-apim/issues/6489

[1] https://apim.docs.wso2.com/en/latest/consume/manage-application/sharing-applications/sharing-applications/
