### ISSUE TITLE
Update postman collection in docs after rest api version upgrade

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#1076]
### Description

Need to upgrade postman collection in docs after rest api version upgrade

### Affected Component

APIM

### Version

4.2.0-SNAPSHOT
- [x] [Update postman collection of Quick Start Guide]
- [x] [Update postman collection of Publisher]
- [x] [Update postman collection of Devportal]
- [x] [Update postman collection of Admin]

**Comment by tgtshanika** [comment]
Fixed with following PRs
https://github.com/wso2/docs-apim/pull/6684
https://github.com/wso2/docs-apim/pull/6676
