### ISSUE TITLE
Integration studio 8.2.0-alpha release work

### ISSUE THREAD

**Issue by imsuneth** [wso2/api-manager#1080]
To track the progress related to $subject

- [x] Changes for 8.2.0-alpha release
- [x] Create 8.2.0-alpha pack locally for testing
- [ ] Testing
- [x] Trigger 8.2.0-alpha release

**Comment by imsuneth** [comment]
Made changes for 8.2.0-alpha release with MI 4.2.0-alpha pack and created packs locally for testing. Moving to on-hold until the test are started.

**Comment by madushadhanushka** [comment]
Updated Studio with latest MI version and changed the splash screen and banner.
https://github.com/wso2/integration-studio/pull/1179

**Comment by madushadhanushka** [comment]
Published GitHub release https://github.com/wso2/integration-studio/releases/tag/v8.2.0-alpha

**Comment by tharikaGitHub** [comment]
Closing as completed
