### ISSUE TITLE
APIM 4.2.0-Alpha Release Testing

### ISSUE THREAD

**Issue by imsuneth** [wso2/api-manager#1083]
- Throttling
  - [x] Application level throttling
  - [x] Subscription-level throttling
  - [x] Rate limiting (burst control)
  - [x] Block condition
  - [x] IP condition
  - [x] Header conditions
  - [x] Query param Conditions
  - [x] JWT Claim conditions
  - [x] Custom Policies
- [x] Oauth 2.0 backend support
- Test Key Manager types
  - [x] Okta Key Manager

**Comment by tharikaGitHub** [comment]
Closing as the tasks are complete.
