### ISSUE TITLE
APIM 4.2.0 Pre-Alpha Testing 

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/api-manager#1088]
### Description

This is to track APIM 4.2.0 release testing progress of @madushadhanushka 
- [x] Threat protection
- [x] AWS Lambda function
- [x] API Schema Validator
- [x] Configuring User Stores:primary/secondary
- [x] Basic auth - API Level
- [x] Async API/Websocket
- [x] Async API/Webhooks
- [x] Async API/SSE

### Affected Component

APIM

### Version

4.2.0-alpha

**Comment by madushadhanushka** [comment]
Tested threat protections for Regex, Json and XML format with the given documentation: https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/regular-expression-threat-protection-for-api-gateway/

**Comment by madushadhanushka** [comment]
`Async API/Websocket` has been tested against https://apim.docs.wso2.com/en/latest/tutorials/streaming-api/create-and-publish-websocket-api/ for supper tenant and tenants.
`Async API/Webhooks` has been tested against https://apim.docs.wso2.com/en/latest/tutorials/streaming-api/create-and-publish-websub-api/ for supper tenant and tenants.
Added following documentations gaps
[1] https://github.com/wso2/docs-apim/issues/6499
[2] https://github.com/wso2/docs-apim/issues/6501

**Comment by madushadhanushka** [comment]
`Async API/SSE` has been tested against https://apim.docs.wso2.com/en/latest/tutorials/streaming-api/create-and-publish-sse-api/ for supper tenant and tenants.

**Comment by madushadhanushka** [comment]
`Basic auth - API Level` has been tested against [https://apim.docs.wso2.com/en/latest/design/api-security/api-authentication/secure-apis-using-basic-authentication/](https://www.google.com/url?q=https://apim.docs.wso2.com/en/latest/design/api-security/api-authentication/secure-apis-using-basic-authentication/&sa=D&source=editors&ust=1670496161504941&usg=AOvVaw01y651XzjBE3ChicnxIIUK) for supper tenant and tenants.
`AWS Lambda function` has been tested against https://apim.docs.wso2.com/en/latest/tutorials/create-and-publish-awslambda-api/  for supper tenant and tenants.

**Comment by madushadhanushka** [comment]
`API schema validator` and `Configuring User Stores:primary/secondary` tested against the documentation for both tenant and super tenant.

**Comment by tharikaGitHub** [comment]
Closing as the tasks are completed.
