### ISSUE TITLE
APIM 4.2.0 pre-alpha testing

### ISSUE THREAD

**Issue by chanaka3d** [wso2/api-manager#1089]
This is to track APIM 4.2.0 release testing progress of @chanaka3d 

- [x]  Dynamic Endpoints
- [x] Publisher REST API
- [x] Store REST API
- [x] Admin REST API
- [x] Password Grant
- [x] Client Credentials Grant
- [x] Authorization Code Grant
- [x] Refresh Token Grant
- [x] JWT Grant
- [x] Mutual SSL
- [x] Basic auth

**Comment by tharikaGitHub** [comment]
Closing as the tasks are completed.
