### ISSUE TITLE
APIM 4.2.0 Pre-Alpha Testing 

### ISSUE THREAD

**Issue by BathiyaL** [wso2/api-manager#1096]
### Description

- [x] API Linters for validating the API Spec

### Affected Component

APIM

### Version

4.2.0-SNAPSHOT

**Comment by BathiyaL** [comment]
Completed testing on API Linters for validating the API Spec
issues:  https://github.com/wso2/api-manager/issues/1097

**Comment by BathiyaL** [comment]
reported issue 
https://github.com/wso2/api-manager/issues/1144

**Comment by tharikaGitHub** [comment]
Closing as the task is completed.
