### ISSUE TITLE
The WSO2-OAUTH Mediator does not send the URL-encoded value of the token request parameters 

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/api-manager#1100]
### Description

We could observe that the APIM server's OAUTH mediator does not send the URL-encoded value of the token request parameters even though the content type is sending as the "**application/x-www-form-urlencoded**"

 

### Steps to Reproduce

- Deploy a sample API
- Configure endpoint security with the OAuth 2.0
- Enable the http client wire log to trace the token request
logger.http-wire.name = org.apache.http.wire
logger.http-wire.level = DEBUG
- Invoke the API
- You will be able to see that the token request parameters send as the plain text values

### Affected Component

APIM

### Version

4.0.0

**Comment by lakshithagunasekara** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/11753
