### ISSUE TITLE
Change the linter message to more appropriate one

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/api-manager#1101]
### Description

When there are no errors in the linter, it shows in the following message. Seems this is not matching the theme of the product.

<img width="1725" alt="Screenshot 2022-12-09 at 11 05 43 AM" src="https://user-images.githubusercontent.com/4861150/206633506-72f4b67b-7826-4b0b-b9bc-fba4fe252a7a.png">

### Steps to Reproduce

Go to publisher portal and open api definition editor page

### Affected Component

APIM

### Version

4.2.0

**Comment by Tharanidk** [comment]
Update 2023-02-14

- Reproduced this issue.
- Changed the linter message appropriately
