### ISSUE TITLE
Errors when running the mysql script for apim DB on mysql 8

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#1105]
### Description

When running the mysql DB script, getting the following errors.

`ERROR 1146 (42S02): Table 'apim_db.idn_oauth2_token_binding' doesn't exist
`

`ERROR 1146 (42S02): Table 'apim_db.idn_scim_group' doesn't exist
`

due to 

`ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes`

This happens by the changes added through the following PRs. It does not support mysql 8

1. https://github.com/wso2/carbon-identity-framework/pull/3965
2. https://github.com/wso2/carbon-identity-framework/pull/3303

A workaround is to use charset latin 1 when creating the database.

`create database apim_db charset latin1;`

### Steps to Reproduce

Run the apim db script on a mysql version 8 database.

### Affected Component

APIM

### Version

4.2.0-SNAPSHOT

**Comment by GihanAyesh** [comment]
Tested a solution which worked but decided with the lead that a better solution can be done. Working on the better option

**Comment by GihanAyesh** [comment]
Made the fix PR https://github.com/wso2/carbon-apimgt/pull/11727

**Comment by GihanAyesh** [comment]
After a discussion instead of the code change a documentation change is agreed. Added the issue https://github.com/wso2/docs-apim/issues/6542

**Comment by tharikaGitHub** [comment]
Closing as this will be tracked by a separate documentation issue https://github.com/wso2/docs-apim/issues/6542
