### ISSUE TITLE
Issue in dev portal restful APIs

### ISSUE THREAD

**Issue by ruwanmadhusanka** [wso2/api-manager#1110]
### Description

We are able to access the dev portal restful APIs (Application, Subscription etc.) with the default scope. 

### Steps to Reproduce

- Update the API Manager.
- Generate the consumer key/secret key pair by calling the dynamic client registration (DCR) endpoint.
- Generate an access token with **no scope/ default scope.**
- Invoke a dev portal restful API which is required additional scopes.

Ex : Create an Application
```
curl --location --request POST 'https://localhost:9443/api/am/devportal/v2/applications' \
--header 'Authorization: Bearer b68a1dae-39fd-3c1a-abdc-8b38cabe2b4b' \
--header 'Content-Type: application/json' \
--data-raw '{
"name": "CalculatorApp0",
"throttlingPolicy": "Unlimited",
"description": "Sample calculator application",
"tokenType": "JWT",
"groups": [ ],
"attributes": { },
"subscriptionScopes": [ ]
}'
```
Response :
```
{
    "applicationId": "9f75e50b-95bc-48e2-b361-c514c79e7d01",
    "name": "CalculatorApp0",
...
```

### Affected Component

APIM

### Version

4.0.0

**Comment by rmsamitha** [comment]
@tharikaGitHub Let's get this shipped in 4.2.0 release.
