### ISSUE TITLE
Update commons.io version to 2.11.0 from 2.0 in synapse

### ISSUE THREAD

**Issue by prasa7** [wso2/api-manager#1117]
### Problem

Update commons.io version to 2.11.0 from 2.0

### Solution

Update commons.io version to 2.11.0 from 2.0

### Affected Component

Synapse

### Version

4.2.0-SNAPSHOT

**Comment by prasa7** [comment]
Hi All,

There is an issue in OGGi class exporting when updating the commons io dependency. Currently I'm checkin the difference of the two versions that can be a route cause for this issue. I'll update the progress in the due case of the day.

Thanks
@prasa7

**Comment by prasa7** [comment]
Hi All,

This issue is created for the4 tracking purpose of the synapse update to 4.0.0. [1]

There is an OSGI class loading conflict once we upgrade to this commons.io version. A detailed explanation of the issue that is happening is included in [1].

[1] - https://github.com/wso2/api-manager/issues/996

Thanks
@prasa7

**Comment by prasa7** [comment]
HI All,

As discussed offline with @nandika @rmsamitha this will be continued with the following github issue[1].

[1] - https://github.com/wso2/api-manager/issues/1203
Thanks
Prasanna

**Comment by npamudika** [comment]
This is done in https://github.com/wso2/api-manager/issues/1117 and tracked via https://github.com/wso2/api-manager/issues/1265
