### ISSUE TITLE
APIM 4.2.0 Pre-Alpha Testing

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/api-manager#1118]
### Description

This is to track APIM 4.2.0 release testing progress of @wasuradananjith

### Tests
- [x] GraphQL
- [x] GraphQL Analytics
- [x] Working with Observability
- [x] Adding Internationalization and Localization
- [x] GraphQL query complexity analysis
- [x] Choreo analytics

### Created Issues
- https://github.com/wso2/docs-apim/issues/6524
- https://github.com/wso2/api-manager/issues/1122
- https://github.com/wso2/api-manager/issues/1127
- https://github.com/wso2/api-manager/issues/1131
- https://github.com/wso2/docs-apim/issues/6527
- https://github.com/wso2/docs-apim/issues/6530
- https://github.com/wso2/api-manager/issues/1143
- https://github.com/wso2/api-manager/issues/1153

### Affected Component

APIM

### Version

4.2.0-Alpha

**Comment by wasuradananjith** [comment]
Tested the below flows related to **GraphQL** APIs
- Create, Deploy and Publish
- Change the lifecycle states
- Import and edit Schema definition
- Invoke GraphQL API GraphQL Queries and Mutations
- Application, Operation, API and Subscription level rate limiting with GraphQL Queries and Mutations
- The basic flow of GraphQL Subscriptions and identified the issue [1] which happens only with StarWarsAPI backend. Also, reported a documentation improvement [2] as well.
- Invoke Queries and Mutations with local scopes and global scopes
- Invoke Queries and Mutations by disabling the security. (An issue has been identified. I will contact the area experts and create an issue if it is applicable)
- Add documents, API Properties and update API by doing minor changes and deploying revisions

Tested **GraphQL Analytics** by configuring Choreo Insights
- Successful GraphQL Query, Mutations and Subscription invocations
- Throttled out GraphQL Query, Mutations and Subscription invocations
- Per Operation wise analytics (manually checked the tables)
- Monthly usage reports and custom reports for GraphQL Analytics

[1] https://github.com/wso2/api-manager/issues/1122
[2] https://github.com/wso2/docs-apim/issues/6524

**Comment by wasuradananjith** [comment]
Created an issue [1] identified yesterday when trying to invoke GraphQL APIs by disabling security.

Tested the **GraphQL Query Limits** including Query Depth Limit and Query Complexity Limit locally.

Tested working with **Observability**
 - Logging
   - Correlation Logs
   - HTTP Access Logs
   - Audit Logs
   - API Logs (with DevOps REST API and apictl)
- Tracing
   - OpenTracing (Jaeger, Zipkin, Log tracing) and found an issue in Log tracing [2].
   - OpenTelemetry (Jaeger, Zipkin, Log tracing). OLTP Tracing doc is not clear. Hence created an issue [3].

Tested **Internationalization and Localization** of the Developer portal and created a documentation issue [4], since none of the examples are working.


[1] https://github.com/wso2/api-manager/issues/1127
[2] https://github.com/wso2/api-manager/issues/1131
[3] https://github.com/wso2/docs-apim/issues/6527
[4] https://github.com/wso2/docs-apim/issues/6530

**Comment by wasuradananjith** [comment]
Tested GraphQL APIs and GraphQL query depth/complexity analysis in the *distributed setup*.

Tested **Choreo Analytics** (Insights) with the local setup.
- API successful invocation hits, latency, traffic and throttling with REST, GraphQL, WebSocket, WebHook and SSE APIs. Found a minor issue in WebSocket APIs and created an issue [1] for that.
- Report generation (monthly and custom)
- Alerts

[1] https://github.com/wso2/api-manager/issues/1143

**Comment by tharikaGitHub** [comment]
Closing as the tasks are completed and the other issues are tracked separately.
