### ISSUE TITLE
[APIM410]API revision can be deployed with the wrong vhost param using Publisher REST API

### ISSUE THREAD

**Issue by PrabhashDilhan** [wso2/api-manager#1125]
### Description

In APIM 410, an inconsistent behavior was observed where the revision deployment call(using publisher REST APIs) is getting passed without any issue even with the wrong vhost parameter.

### Steps to Reproduce

- create a new gateway environment us-region with us.wso2.com and foods.com vhosts.
- Then we use Publisher REST API to deploy a new revision with the below payload.
[
  {
    "revisionUuid": "194d5ba6-7d0c-4276-9089-d5e99077e167",
    "name": "us-region",
    "vhost": "ws.wso2.com",
    "displayOnDevportal": true
  }
]

- As you can see in the payload, we are passing a wrong vhost(ws.wso2.com) with the correct gateway name. 
- The API call is getting invoked without any issue and the new revision is getting deployed into the gateway with the wrong vhost.

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
Closing this issue as the public fix for this issue has been added via the PR: https://github.com/wso2/carbon-apimgt/pull/12022
