### ISSUE TITLE
Disabling securty does not allow invoking GraphQL APIs

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/api-manager#1127]
### Description

After disabling the security in GraphQL operations, we should be able to invoke that particular operation without a token or with an invalid token. But it does not allow it. 

### Steps to Reproduce

1. Create a GraphQL API as mentioned in [1].
2. Go to the operations tab of the created API in the Publisher portal and disable the security for the operations "droid" and "human".
3. Go to the developer portal, subscribe the API to an application and invoke the query mentioned in [2] without a token.
4. You will get an error response as below.
```
{
    "code": "900901",
    "message": "Invalid Credentials",
    "description": "Access failure for API: /t/test.com/swapi/1.0.0, version: 1.0.0 status: (900901) - Invalid Credentials. Make sure you have provided the correct security credentials"
}
```
5. Try to invoke the same query by providing an invalid token as well. You will get the same error.

[1] https://apim.docs.wso2.com/en/latest/design/create-api/create-a-graphql-api/
[2] https://apim.docs.wso2.com/en/latest/tutorials/create-and-publish-a-graphql-api/#step-51-optionally-try-out-a-query-operation

### Affected Component

APIM

### Version

4.2.0-Pre-Alpha

### Related Issues

- https://github.com/wso2/api-manager/issues/1118

**Comment by Tharanidk** [comment]
Update 2023-01-11

- Tried reproducing this issue
- Followed all the steps in the documentation and found that this issue is not reproducing in APIM 4.2.0

**Comment by Tharanidk** [comment]
As per the discussion with @wasuradananjith  this issue is not reproducing. Hence closing the issue.
