### ISSUE TITLE
Denying policy not working with WebSocket API

### ISSUE THREAD

**Issue by YasasRangika** [wso2/api-manager#1128]
### Description

When we apply deny policy using the admin portal in the WSO2 API manager, It doesn't block the requests which in turn gives the ability to invoke the WS API regardless of the blocking condition.

Same issue we resolved in [this issue](https://github.com/wso2/api-manager/issues/525) with the [PR](https://github.com/wso2-support/carbon-apimgt/pull/5304). Since the code base has been changed in the latest releases, we should follow the same effort to fix this issue in the master branch as well.

### Steps to Reproduce

- Follow the documentation [1] to create a WebSocket API
- Add a deny policy using the context of the created WebSocket API
- Try to invoke the API

[1] https://apim.docs.wso2.com/en/4.2.0/tutorials/streaming-api/create-and-publish-websocket-api/

### Affected Component

APIM

### Version

APIM-4.2.0-Alpha

### Related Issues

https://github.com/wso2/api-manager/issues/525

**Comment by lasanthaS** [comment]
Hi all,

I started working on porting the above fixes to the master branch and could almost complete the changes related to WebSocket. 

Regards,
Lasantha

**Comment by lasanthaS** [comment]
Hi all,

I completed forward porting the fix to master branch. Now there are some test failures related to the feature and now I am working on fixing those.

Regards,
Lasantha
