### ISSUE TITLE
Error loading keys page after rejecting Application Key Generation Workflow item

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#1129]
### Description

After rejecting the application key generation workflow approval item from the Admin portal, a blank page is shown when accessing the respective application keys or credentials page.

<img width="1512" alt="Screen Shot 2022-12-14 at 11 26 15 AM" src="https://user-images.githubusercontent.com/8557410/207517828-b0f618f3-60e7-43e5-aff2-7fe27468e6d5.png">

The following error is shown in the terminal.

<img width="1499" alt="Screen Shot 2022-12-14 at 11 33 55 AM" src="https://user-images.githubusercontent.com/8557410/207518972-d6212048-d95c-4e87-8de7-b74719c2de8e.png">

### Steps to Reproduce

1. Enable the Application Key Generation Workflow according to [1].
2. Generate keys after creating an Application.
3. Now access the admin portal and reject the approval request.
4. Go back to the devportal application page and try to access the keys page as below. (I have rejected the sandbox request)

<img width="1512" alt="Screen Shot 2022-12-14 at 11 28 19 AM" src="https://user-images.githubusercontent.com/8557410/207518122-5572d7a9-66b0-4453-a4f1-a72c2c82d4b1.png">

[1] https://apim.docs.wso2.com/en/latest/consume/manage-application/advanced-topics/adding-an-application-key-generation-workflow/

### Affected Component

APIM

### Version

4.2.0-SNAPSHOT

**Comment by DinithHerath** [comment]
Hi @tharikaGitHub 

Without rejecting, even if we try to access the page, same blank page appears in the devportal. Therefore in both rejection and pending approval cases, we can observer this empty page.
