### ISSUE TITLE
Getting invalid access token response for migrated application's access tokens

### ISSUE THREAD

**Issue by SupunTharakaSandaruwan** [wso2/api-manager#113]
### Description:

When the APIM  server is migrated from APIM 2.6.0 to APIM 4.0.0, API invocations with opaque tokens which are having long expiry times and shorter refresh tokens are get token validation failures when the refresh token validity is exceeded.

### Steps to reproduce:

- Create OAuth application with token issuer set to default
- Set access token expiry with 1000000000000 
- Set refresh token expiry as one minute
- Obtain an access token
- Try introspect/API invocation within one minute, it will be active
- Try introspect/API invocation after one minute, it will not be active

### Affected product version:

- APIM 4.0.0

**Comment by vithu30** [comment]
Public fix already added in https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1811
