### ISSUE TITLE
Log Tracing is not working as expected in OpenTracing

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/api-manager#1131]
### Description

When you enable log tracing as mentioned in [1], the log file will not contain correct information. It only prints something like, `n14:11:48,992 [-] [PassThroughMessageProcessor-1] TRACE `

### Steps to Reproduce

Follow the steps in [1]

### Affected Component

APIM

### Version

4.2.0-Pre-Alpha

### Relevant Log Output

```shell
n14:11:48,992 [-] [PassThroughMessageProcessor-1] TRACE 
n14:11:50,073 [-] [PassThroughMessageProcessor-2] TRACE 
n14:11:51,513 [-] [PassThroughMessageProcessor-3] TRACE 
n14:11:51,513 [-] [PassThroughMessageProcessor-3] TRACE 
n14:11:51,515 [-] [PassThroughMessageProcessor-3] TRACE 
n14:11:51,552 [-] [PassThroughMessageProcessor-4] TRACE 
n14:11:51,571 [-] [PassThroughMessageProcessor-4] TRACE 
n14:11:51,575 [-] [PassThroughMessageProcessor-4] TRACE 
n14:11:51,576 [-] [PassThroughMessageProcessor-4] TRACE 
n14:11:51,576 [-] [PassThroughMessageProcessor-4] TRACE 
n14:11:52,178 [-] [PassThroughMessageProcessor-5] TRACE 
n14:11:52,179 [-] [PassThroughMessageProcessor-5] TRACE 
n14:11:52,180 [-] [PassThroughMessageProcessor-5] TRACE 
n14:11:52,180 [-] [PassThroughMessageProcessor-5] TRACE
```

### Related Issues
- https://github.com/wso2/api-manager/issues/1118

[1] https://apim.docs.wso2.com/en/4.2.0/observe/api-manager/traces/monitoring-with-opentracing/#enabling-log-tracing

**Comment by wasuradananjith** [comment]
Potential fix can the one done in https://github.com/wso2/api-manager/issues/968 for OpenTelemetry. Doing the same for OpenTracing may solve this issue.

**Comment by rosensilva** [comment]
Fix: https://github.com/wso2/carbon-apimgt/pull/11781
