### ISSUE TITLE
Check axis2-transport build failure during maven release

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/api-manager#1132]
### Description

the build[1] is passing with a normal build. And it fails during the maven release. We have to revisit and see why it is failing only during the maven release.

[1] https://staging-supportbuilder-wilkes.wso2.com/jenkins/job/update-2/job/full/job/wso2-axis2-transports/job/wso2-axis2-transports-2.0.0-wso2v30.x-full/

### Affected Component

None

**Comment by arunans23** [comment]
Shall we check whether this fix https://github.com/wso2/wso2-axis2-transports/pull/282 fixes this issue?

**Comment by dulanjalidilmi** [comment]
Thank you @arunans23. The latest build and the maven release is successful.

**Comment by dulanjalidilmi** [comment]
Fixed with https://github.com/wso2-support/wso2-axis2-transports/pull/247
