### ISSUE TITLE
APIM 4.2.0 pre-alpha Testing

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#1138]
### Description

This is to track APIM 4.2.0 release testing progress of @msm1992

- [x] Okta Key Manager Integertion
- [x] KeyCloak Key Manager Integration

### Affected Component

APIM

**Comment by msm1992** [comment]
The above testing tasks were successfully completed on 14/12/2022.

**Comment by msm1992** [comment]
Reopened the ticket to track progress on alpha testing for below scenarios.

- [x] Swagger/Graphql to Postman Collection
- [ ] Application Owner change

**Comment by tharikaGitHub** [comment]
Closing as the tasks are completed.
