### ISSUE TITLE
Generated opaque token with a long validity period is expiring once used it one time. 

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/api-manager#114]
### Description:

If creating an opaque access token with a long validity period(e.g., 9223372036854775000), it can use one time. Next time it will respond as an invalid token.
The reason is that the first time, the expiry time of the opaque token will be set as minus and persist on the cache. Then next call, the token will get from the cache and respond as an invalid token. If we clear the cache again, we can use the token. 
 Here[1], we calculate the token expiry time, which returns a minus value. 
 The root cause is,
- Java long max value is "9223372036854775807".
- Then, as per the equation[1], when adding both validity period & token issue time value, this JAVA long max value will exceed. Therefore above equation gives a minus value. So Expiry time is set as the minus value. It should return an error like "integer number too large". Instead, it is set as minus and proceed.

- So, this is the reason to set the minus value for the expiry time.
- Above issue has been fixed with JWT tokens[2].

[1]. https://github.com/wso2-support/identity-inbound-auth-oauth/blob/8419ff9446401bbe62e6ca625ac8da5ed0602db0/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/validators/TokenValidationHandler.java#L442-L445
[2]. https://github.com/wso2-extensions/identity-inbound-auth-oauth/commit/186ff5638ad19f981cf36e4e5d4351ae6a393133

### Steps to reproduce:

- Create an opaque token with long validity period and try to invoke an API

### Affected product version:

APIM 3.2.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by hisanhunais** [comment]
Master fix done via https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1849
