### ISSUE TITLE
APIM 4.2.0 Pre-Alpha Testing

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#1140]
### Description

- [x] Import/Export of Operation Policies with APICTL

### Affected Component

APICTL

### Version

apictl-4.2.0

**Comment by vishmi49** [comment]
Tested the following features in local environment 

Import/Export of Operation Policies with APICTL
Throttle policy export import support for APIM

**Comment by tharikaGitHub** [comment]
Closing as the task is complete
