### ISSUE TITLE
APIM 4.2.0 Pre-Alpha Testing

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/api-manager#1141]
### Description

This is to track the APIM 4.2.0 alpha release testing progress of @SanojPunchihewa 

**Local Setup Tests**

- [x] Publisher Access control 
- Creating a new version
   - [x] Old API has no scopes
   - [x] Old API has scopes
- API product
   - [x] Runtime configs/Resources/Api definition/Invocation
   - [x] Basic info/Business info/Subscriptions/Documents/Properties
   - [x] With policies
- [x] Message Mediation
- [x] Prototype Implementation (Mock)
- [x] API/API Product Revision/ Restore
- [x] Service Catalogue

### Affected Component

APIM

### Version

4.2.0-alpha

**Comment by SanojPunchihewa** [comment]
Broken links were observed in the Mock Implementation with API Gateway page - https://github.com/wso2/docs-apim/issues/6533

**Comment by SanojPunchihewa** [comment]
Some Service Catalog related docs mention the APIM version as 4.1.0. Doc issue - https://github.com/wso2/docs-apim/issues/6534

**Comment by SanojPunchihewa** [comment]
Formatting issues in Create a Policy doc page - https://github.com/wso2/docs-apim/issues/6535

**Comment by SanojPunchihewa** [comment]
Tested **Service Catalogue** in the _local_ setup

- Exposing an Integration Service as a Managed API
- Exposing an Integration SOAP Service as a Managed API
- Develop an Integration From a Managed API
- Parameterize using the host and port combination in `metadata.yaml`

Tested **Prototype Implementation (Mock)** in both _local_ and _distributed_ setup

- With and without security
- Mock payload conditionally depending on user-sent path parameter 

Tested **Message Mediation** in both _local_ and _distributed_ setup

- Adding policies to Request, Response flows
- Creating a common policy and attaching it

**Comment by SanojPunchihewa** [comment]
Outdated Managing User Roles doc page - https://github.com/wso2/docs-apim/issues/6543

**Comment by SanojPunchihewa** [comment]
Minor update to Enable Publisher Access Control Steps - https://github.com/wso2/docs-apim/issues/6545

**Comment by SanojPunchihewa** [comment]
Tested **API/API Product Revision/ Restore** in the _local_ setup

- Creating a new revision
- Undeploying current revision
- Restoring an old revision

Tested **Creating a new version** in the _local_ setup

- Creating a new version of API which doesn't have any scopes
- Creating a new version of API which has scopes

Tested **API product** in both _local_ and _distributed_ setup

- Creating API product with APIs which contains policies
- Invoking API product
- Adding Basic info
- Adding Business info
- Updating Subscriptions
- Adding Documents
- Adding Properties

Tested **Publisher Access control** in  _distributed_ setup

- Restrict Acces using a single role and multiple roles and verified the API is visibility
- Added publisher access control role and verified the API is visible without login to devportal
- Created a role with capital letters and underscores and tested publisher access control
- Verified APIs with access control restricted are not listed in the publisher unified search
- Added publisher access control role and visibility control for devportal with a different role. Verified the API is not visible without login. Visible after login with a user with devportal visibility role.

**Comment by tharikaGitHub** [comment]
Closing as the task is completed.
