### ISSUE TITLE
APICTL tool is not available for Mac arm64

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/api-manager#1165]
### Description

Released binaries are not available for Mac arm64. But the mac amd64 is working with my Mac m1 maybe because I have already installed Rosetta2. It is nice to have a separate binary for mac arm64.

### Affected Component

APICTL

### Version

4.1.0

**Comment by renuka-fernando** [comment]
Just have to add the OS and arch here https://github.com/wso2/product-apim-tooling/blob/92da739ab910d7dc188c19d003aaeffbeaca1500/import-export-cli/build.sh#L90

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/product-apim-tooling/pull/967

**Comment by npamudika** [comment]
Reverted the PR https://github.com/wso2/product-apim-tooling/pull/967 as we are getting some integration test failures with the go version upgrade (to go 1.20) done to support the new archive changes.

Will be done after the 4.2.0 beta release.

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/product-apim-tooling/pull/976
