### ISSUE TITLE
Able to publish API Products without deploying

### ISSUE THREAD

**Issue by nelkon** [wso2/api-manager#1174]
### Description

In APIM4.1.0 able to publish the API Products without deploying them, but in the dev portal there we couldn't identify whether it is deployed. And the invocation is also not working. 
Since the API Product also has the lifecycle from APIM4.1.0 onwards, it shouldn't be published without deploying.

### Steps to Reproduce

1. Go to the publisher portal and create a new API Product.
2. Then go to the lifecycle and publish it.

### Affected Component

APIM

### Version

4.1.0

### Suggested Labels

APIM APIProduct

**Comment by lakshithagunasekara** [comment]
Fixed with https://github.com/wso2/apim-apps/pull/431
