### ISSUE TITLE
Compatibilty with Postgres 14

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#1176]
Need to add support for API-M 4.2 with Postgres 14. We can run the integration test suite for the same and confirm.

**Comment by AnuGayan** [comment]
Hi Al, 

Tested the basic functionality of API Manager 4.2.0 on PostgreSQL version 14.6, and executed the integration tests as well. 

No errors were found.

Thank You,
Anusha

**Comment by AnuGayan** [comment]
Hi All,

GraphqlSubscriptionTestCase failure was due to an intermittent issue and it was not related to the Database. Other test cases are also not related to the Postgres DB. So we can conclude that the APIM is compatible with Postgres 14.

Thank You,
Anusha
