### ISSUE TITLE
Make admin web app accessible with users with different roles and permissions

### ISSUE THREAD

**Issue by lakshithagunasekara** [wso2/api-manager#1187]
### Problem

Currently, admin web app is not developed to restrict different sections based on the scopes. Only the workflow sections check for the workflow-related scopes [1] before loading and because of it, we can't allow different roles of users to access the admin web app. 

[1] - https://github.com/wso2/apim-apps/blob/main/portals/admin/src/main/webapp/source/src/app/components/AdminPages/Dashboard/Dashboard.jsx#L43

### Solution

Evaluate the scopes of each section before render.

### Affected Component

APIM

**Comment by hasuniea** [comment]
We had a design review to finalize the design.
<div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span id="m_8315447747223262688gmail-docs-internal-guid-9f09068a-7fff-a7b6-07c8-965a224412ca"><p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; vertical-align: baseline; white-space: pre-wrap;">Admin web app is not developed to restrict different sections based on the scopes. Currently any user with apim:admin scope can view all the sections </span><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-family: Arial; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap;">(</span><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">Rate limiting policies, </span></p><p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-family: Arial; color: rgb(0, 0, 0); font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">Gateways, API Categories, Key Managers, Settings except Tasks</span><span style="background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-family: Arial; color: rgb(0, 0, 0); vertical-align: baseline; white-space: pre-wrap;">). </span><span style="white-space: pre-wrap; color: rgb(0, 0, 0); font-family: Arial;">We can restrict each section by checking each user's scopes from the UI. But if we can go with an in- built </span></p><p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="white-space: pre-wrap; color: rgb(0, 0, 0); font-family: Arial;">role(internal role) for </span><span style="white-space: pre-wrap; color: rgb(0, 0, 0); font-family: Arial;">common scenarios such as task managing, rate limiting, settings ..etc. we can reduce the overhead of </span><span style="white-space: pre-wrap; color: rgb(0, 0, 0); font-family: Arial;">assigning multiple scopes for the users. </span></p><p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="white-space: pre-wrap; color: rgb(0, 0, 0); font-family: Arial;">We will have to </span><span style="color: rgb(0, 0, 0); font-family: Arial; white-space: pre-wrap;">create internal roles for each operation as in below.</span></p></span></div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span><p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><font color="#000000" face="Arial"><span style="white-space: pre-wrap;"><br></span></font></p><blockquote style="margin: 0px 0px 0px 40px; border: none; padding: 0px;"><blockquote style="margin: 0px 0px 0px 40px; border: none; padding: 0px;"><div><h3 style="line-height: 1.38; margin-top: 16pt; margin-bottom: 4pt;">

Admin portal Section | Scopes | Suggested internal Role
-- | -- | --
Rate Limiting policies | apim:tier_view, apim:policies_import_export, apim:tier_manage, apim:bl_manage, apim:bl_view | Policy manager
Gateways | apim:environment_manage, apim:environment_read | Gateway manager
API categories | admin_operations | Category manager
KeyManagers | admin_operations | Keymanager admin
Tasks | apim:api_workflow_view, apim:api_workflow_approve, apim:tenantInfo ,apim:admin_settings | Workflow manager
Settings: Applications | apim:app_owner_change, apim:app_import_export, apim:admin_application_view | application manager
Settings: Scope Assignment | apim:scope_manage, apim:role_manage | scope manager

</h3></div></blockquote></blockquote><p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; vertical-align: baseline; white-space: pre-wrap;">

</span></p></span>In case of the design, the user experience may be easy as follows.</div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Customers want to restrict admin users for the work-flow functionalities, they just assign admin users to internal/workflowManger roles. When an admin user logs to the admin portal, he/she can only see the tasks left side menu.</div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><img src="https://mail.google.com/mail/u/0?ui=2&amp;ik=7ebf7fab98&amp;attid=0.1&amp;permmsgid=msg-a:r5890234908224946814&amp;th=1876aab8a2141f81&amp;view=fimg&amp;fur=ip&amp;sz=s0-l75-ft&amp;attbid=ANGjdJ9sljK9fGI_ZpshheiM10daNnRn4LMkIKqsoQL6QqXKy_xSiQ2hONviDODkp3HqqsOxi6Xn17g1l-W-ZV1EGDTBFJpvIc63_VjtNZrEbPrRGblV833lkWO24cg&amp;disp=emb&amp;realattid=ii_lgahmylv0" alt="Screenshot 2023-04-10 at 12.33.39.png" width="184" height="286" data-image-whitelisted="" class="CToWUd a6T" data-bit="iit" tabindex="0" style="cursor: pointer; outline: 0px; margin-right: 0px;"></div>

**Comment by hasuniea** [comment]
By considering the user experience and the maintainability,  we discussed to go with an internal/manager role which is bound to most common user scenarios such as tasks and rate limiting policies. It is the default role which will go with the pack. Besides that, if someone wants to add other functionalities to it or else if the user wants to restrict only for one operation, he/she has to follow the doc and create custom roles and map related scopes to it.

**Comment by hasuniea** [comment]
We had a code review and asked to create a new constant file and put the necessary constants in there without adding it to the public accessible settings.js.

**Comment by hasuniea** [comment]
I created separate file and still the PR is in review

**Comment by hasuniea** [comment]
Please find the doc [1].
[1]. https://docs.google.com/document/d/1a4hrjD3VrPJ81BpN21-x1DX8y54pXXByqgqAVeVk6uA/edit?usp=sharing

**Comment by chamilaadhi** [comment]
Additional Fixes
https://github.com/wso2/carbon-apimgt/pull/12182
https://github.com/wso2/apim-apps/pull/513

**Comment by chamilaadhi** [comment]
Integration test fixes
https://github.com/wso2/product-apim/pull/13287
https://github.com/wso2/product-apim/pull/13290

**Comment by chamilaadhi** [comment]
Remove invalid scopes https://github.com/wso2/apim-apps/pull/514
