### ISSUE TITLE
Need to provide the capability to generate access tokens via the dev portal by using provisioned applications - APIM 4.1.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/api-manager#1199]
### Problem

Cannot generate access tokens via the dev portal by using provisioned applications.

### Solution

Need to provide the capability to generate access tokens via the dev portal by using provisioned applications by showing the **GENERATE ACCESS TOKEN** button.

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
Closing this issue as per the comment [1].
[1] https://github.com/wso2-enterprise/wso2-apim-internal/issues/1522#issuecomment-1418711572

**Comment by YasasRangika** [comment]
closing this issue as per the comment mentioning the public fix is not applicable, in the internal issue.
