### ISSUE TITLE
Test failures in product-apim

### ISSUE THREAD

**Issue by rmsamitha** [wso2/api-manager#1204]
### Description

Below tests are failing in product-apim latest repo. The failures are observed in the public jenkins build #3010 [1] and also in the latest build #3019

- org.wso2.am.integration.tests.logging.CorrelationLoggingTest.testRetrieveDefaultCorrelationLoggingConfigsTest
- org.wso2.am.integration.tests.logging.CorrelationLoggingTest.testEnableAllCorrelationLoggingConfigsTest

Some other tests in this same Test class had failed earlier and fixed via the commit [2].

[1] https://wso2.org/jenkins/job/products/job/product-apim/3010/
[2] https://github.com/wso2/product-apim/pull/13042/commits/93306af3717d2f1bb697bf7f5dc8ac7940dfb351

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

4.1.0-alpha

### Relevant Log Output

```shell
Failure logs:

- testRetrieveDefaultCorrelationLoggingConfigsTest

java.lang.AssertionError: expected [{"components":[{"name":"http","enabled":"false","properties":[]},{"name":"jdbc","enabled":"false","properties":[{"name":"deniedThreads","value":["MessageDeliveryTaskThreadPool","HumanTaskServer","BPELServer","CarbonDeploymentSchedulerThread"]}]},{"name":"ldap","enabled":"false","properties":[]},{"name":"synapse","enabled":"false","properties":[]},{"name":"method-calls","enabled":"false","properties":[]}]}] but found [{"components":[{"name":"http","enabled":"true","properties":[]},{"name":"jdbc","enabled":"true","properties":[{"name":"deniedThreads","value":["MessageDeliveryTaskThreadPool","HumanTaskServer","BPELServer","CarbonDeploymentSchedulerThread"]}]},{"name":"ldap","enabled":"true","properties":[]},{"name":"synapse","enabled":"true","properties":[]},{"name":"method-calls","enabled":"true","properties":[]}]}] at org.wso2.am.integration.tests.logging.CorrelationLoggingTest.testRetrieveDefaultCorrelationLoggingConfigsTest(CorrelationLoggingTest.java:154)

	
- testEnableAllCorrelationLoggingConfigsTest

java.lang.AssertionError: expected [true] but found [false] at org.wso2.am.integration.tests.logging.CorrelationLoggingTest.testEnableAllCorrelationLoggingConfigsTest(CorrelationLoggingTest.java:181)
```

**Comment by imsuneth** [comment]
Observations from the console output

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR] org.wso2.am.integration.tests.logging.CorrelationLoggingTest.testEnableAllCorrelationLoggingConfigsTest
[ERROR]   Run 1: CorrelationLoggingTest.testEnableAllCorrelationLoggingConfigsTest:181 expected [true] but found [false]
[INFO]   Run 2: PASS
[INFO] 
[ERROR] org.wso2.am.integration.tests.logging.CorrelationLoggingTest.testRetrieveDefaultCorrelationLoggingConfigsTest
[INFO]   Run 1: PASS
[ERROR]   Run 2: CorrelationLoggingTest.testRetrieveDefaultCorrelationLoggingConfigsTest:154 expected [{"components":[{"name":"http","enabled":"false","properties":[]},{"name":"jdbc","enabled":"false","properties":[{"name":"deniedThreads","value":["MessageDeliveryTaskThreadPool","HumanTaskServer","BPELServer","CarbonDeploymentSchedulerThread"]}]},{"name":"ldap","enabled":"false","properties":[]},{"name":"synapse","enabled":"false","properties":[]},{"name":"method-calls","enabled":"false","properties":[]}]}] but found [{"components":[{"name":"http","enabled":"true","properties":[]},{"name":"jdbc","enabled":"true","properties":[{"name":"deniedThreads","value":["MessageDeliveryTaskThreadPool","HumanTaskServer","BPELServer","CarbonDeploymentSchedulerThread"]}]},{"name":"ldap","enabled":"true","properties":[]},{"name":"synapse","enabled":"true","properties":[]},{"name":"method-calls","enabled":"true","properties":[]}]}]

**Comment by imsuneth** [comment]
This 2 test seem to fail intermittently. However following are the suspecting reasons

1. Delay of writing the correlation logs in  Jenkins
2. Correlation configs of the server not getting reset between tests

**Comment by imsuneth** [comment]
Results from jenkins run

Run 1
testRetrieveDefaultCorrelationLoggingConfigsTest : PASSED
testEnableAllCorrelationLoggingConfigsTest: FAILED

Run 2
testRetrieveDefaultCorrelationLoggingConfigsTest : FAILED
testEnableAllCorrelationLoggingConfigsTest: PASSED (but SKIPPED)

**Comment by imsuneth** [comment]
Sample http correlations log observed is as below

2023-01-20 15:22:56,124|e8365836-9f3e-4dcd-9c15-da5286a0ce62|PassThroughMessageProcessor-23|897|HTTP|TestAPI1:v1.0.0|null|/testapi1/1.0.0/*|testapi1/1.0.0|null|null|null|null|null|15|15|200|DefaultApplication|e2QHrwQi8V7RMTPH_hva_eRl_18a|901

But, isHTTPLogLine() function checks whether the line contains "HTTP-In".

**Comment by imsuneth** [comment]
It takes some time to append logs to the correlation.log on Jenkins compared to testing locally. Therefore, most of the time tests pass locally but not on Jenkins.

The previous implementation (with thread sleeps) misses some logs due to this file writing issue.

Therefore a third-party library Awatility is now integrated to read the correlation.log file with a timeout.

**Comment by imsuneth** [comment]
Test failures mentioned in the issue are fixed now. However, as the dependent test are now running testSpecificCorrelationLoggingConfigsTest() test started failing intermittently.

The reason for this failure is frequent logging of JDBC logs once it is enabled

**Comment by imsuneth** [comment]
When only http correlation logging is enabled, http logs are not logged when API is invoked.
When both method-calling is enabled together with http, http logs are also logged among method logs.

Therefore, until we fix it, http related test is commented in testSpecificCorrelationLoggingConfigsTest.

**Comment by imsuneth** [comment]
This issue is fixed with https://github.com/wso2/product-apim/pull/13101 and tests passed both locally and on jenkins https://wso2.org/jenkins/job/products/job/product-apim/3048/
