### ISSUE TITLE
Devportal Incorrect curl command for file upload

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/api-manager#121]
### Description:
There is an issue related to the CURL command autogenerated by API Manager. In APIM-3.1.0 when we have form data, the CURL will be generated as below. (Correct CURL command)

`curl -X POST "https://localhost:8243/test/v1/order" -H "accept: */*" -H "Content-Type: multipart/form-data" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciO...4kvUvb5t7w" -F "req_json={"test":"hello"}" -F "file=@new.txt;type=text/plain"`

In APIM-3.2.0 when we have form data the CURL will be generated as below. (Incorrect CURL command)

`curl -X POST "https://localhost:8243/test/v1.0/order" -H "accept: */*" -H "Content-Type: multipart/form-data" -H "Authorization: Bearer eyJ4NXQiOiJNell4TW1Ga09HWXdNV....hPRNzcS1w" -d {"req_json":"{\"test\":\"hello\"}","file":{}}`

When we use the CURL command generated in APIM-3.2.0 it sends the data as RAW data to the backend. 

### Affected product version:
APIM-3.2.0

**Comment by Krishanx92** [comment]
This is swagger UI version update.
