### ISSUE TITLE
[4.2.0][Dependency Upgrade] Upgrade Netty Version in APIM 4.2.0

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#1221]
### Description

As of now there are two versions of netty available in APIM 4.2.0-alpha plugins both of which are affected by known vulnerabilities.
- 4.1.73.Final
- 4.1.79.Final

This task is created to check the progress on below action items.
- [ ] Check whether it is possible to remove netty 4.1.73.Final altogether
- [ ] Upgrade netty to latest non vulnerable version.

### Affected Component

APIM

### Version

4.2.0

**Comment by npamudika** [comment]
Will be continued after the APIM 4.2.0 Beta release.
