### ISSUE TITLE
[4.2.0][Dependency Upgrade] Snakeyaml Version Upgrade

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#1222]
### Description

This issue is created to track the progress on snakeyaml upgrade for APIM 4.2.0. 

On a side note, there are multiple versions of snakeyaml available in APIM 4.2.0 plugins as of now and it needs to be checked whether the unwanted versions can be removed.
- /repository/components/plugins/org.yaml.snakeyaml_1.28.0.jar
- /repository/components/plugins/snakeyaml_1.26.0.wso2v1.jar

### Affected Component

APIM

### Version

4.2.0

**Comment by dulithsenanayake** [comment]
Related PRs:

- [https://github.com/wso2/carbon-apimgt/pull/11767](https://github.com/wso2/carbon-apimgt/pull/11767)
- [https://github.com/wso2/product-apim/pull/13062](https://github.com/wso2/product-apim/pull/13062)
