### ISSUE TITLE
[4.2.0][Dependency Upgrade] Jackson Version Upgrade

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#1223]
### Description

This issue is created to track the progress of jackson components version upgrade from 2.13.1 to latest version.

### Affected Component

APIM

### Version

4.2.0

**Comment by dulithsenanayake** [comment]
Related PRs:

- [https://github.com/wso2/carbon-apimgt/pull/11767](https://github.com/wso2/carbon-apimgt/pull/11767)
- [https://github.com/wso2/product-apim/pull/13069](https://github.com/wso2/product-apim/pull/13069)

**Comment by msm1992** [comment]
PR[1] upgrades jackson componets version is lib/runtimes/cxf3 folder.

[1]. https://github.com/wso2/carbon-deployment/pull/383
