### ISSUE TITLE
[4.2.0][Dependency Upgrade] gson version upgrade

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#1237]
### Description

gson version used in carbon-identity-anonimization tool (available in SI 4.2.0 /wso2/tools/) has to be upgraded to 2.8.9.

[1]. https://github.com/wso2/identity-anonymization-tool/blob/master/pom.xml#L312 

### Affected Component

SI

### Version

4.2.0

**Comment by npamudika** [comment]
Used in identity-anonymization-tool
anonimization tool has been removed from SI distribution as per [https://github.com/wso2/streaming-integrator/pull/29](https://github.com/wso2/streaming-integrator/pull/299)
