### ISSUE TITLE
[4.2.0][Dependency Upgrade] H2 version upgrade

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#1238]
### Description

This issue is created to track the progress on H2 version upgrade used in carbon-identity-anonimization tool from 1.4.199 to 2.1.210 (or latest). The fix is already available in carbon-identity-anonimization master branch with [1].

Upgrading carbon-identity-anonimization tool version to latest in SI 4.2.0 should fix this issue.

[1]. https://github.com/wso2/identity-anonymization-tool/commit/05e225dc81cc0679e884275cc0b5440223509a14 

### Affected Component

SI

### Version

4.2.0

**Comment by npamudika** [comment]
Used in identity-anonymization-tool
anonimization tool has been removed from SI distribution as per [https://github.com/wso2/streaming-integrator/pull/29](https://github.com/wso2/streaming-integrator/pull/299)
