### ISSUE TITLE
[4.2.0][Dependency Upgrade] Snakeyaml version upgrade

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#1239]
### Description

As of now there are 3 versions of snakeyaml available in plugins. 
./wso2/lib/plugins/org.yaml.snakeyaml_1.23.0.jar
./wso2/lib/plugins/org.yaml.snakeyaml_1.31.0.jar
./wso2/lib/plugins/org.yaml.snakeyaml_1.33.0.jar

- [x] First need to check whether this can be reduced to a single version.
- [x] Need to upgrade snakeyaml version to 1.32 or latest

### Affected Component

SI

### Version

4.2.0

**Comment by RakhithaRR** [comment]
Multiple versions of snakeyaml jars will be reduced to a single one (1.33) with the above 2 PRs.
