### ISSUE TITLE
[4.2.0][Dependency Upgrade] commons-text version upgrade

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#1240]
### Description

Commons text version used in carbon-identity-anonimization tool need to be upgraded to 1.10.0. The fix is already available in master branch with PR [1]. Therefore just upgrading carbon-identity-anonimization tool version version in SI 4.2.0 should fix this issue.

[1]. https://github.com/wso2/identity-anonymization-tool/commit/f764e8e90a1dfd8b227ad5eaaaf6fc5984372766

### Affected Component

SI

### Version

4.2.0

**Comment by npamudika** [comment]
Used in identity-anonymization-tool
anonimization tool has been removed from SI distribution as per [https://github.com/wso2/streaming-integrator/pull/29](https://github.com/wso2/streaming-integrator/pull/299)
