### ISSUE TITLE
[4.2.0][Dependency Upgrade]libthrift version upgrade

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#1241]
### Description

This ticket is created to track progress on libthrift version upgrade from 0.92.0 in SI 4.2.0.

### Affected Component

SI

### Version

4.2.0

**Comment by RakhithaRR** [comment]
Maybe fixed with https://github.com/wso2/carbon-analytics-common/pull/819. We need to get this verified from someone with thrift expertise.
