### ISSUE TITLE
[4.2.0][Dependency Upgrade] Netty version upgrade

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#1247]
### Description

As of now there are two versions(4.1.79.Final, 4.1.73.Final) of netty available in MI 4.2.0 and both those versions are affected by known CVEs. Hence the netty version in MI 4.2.0 needs to be upgraded to 4.1.86.Final.

### Affected Component

MI

### Version

4.2.0

**Comment by npamudika** [comment]
Will be continued after MI 4.2.0 Beta release.
