### ISSUE TITLE
Need to remove swagger-codegen from APIM 4.2.0 pack

### ISSUE THREAD

**Issue by rmsamitha** [wso2/api-manager#1250]
### Description

Need to remove swagger-codegen from APIM 4.2.0 pack.
This was not available in 4.1.0, but needs to be removed.

### Affected Component

APIM

**Comment by dulithsenanayake** [comment]
Related PR:

- [https://github.com/wso2/carbon-apimgt/pull/11771](https://github.com/wso2/carbon-apimgt/pull/11771)
