### ISSUE TITLE
Remove deprecated profiles related profile optimisation scripts

### ISSUE THREAD

**Issue by rmsamitha** [wso2/api-manager#1258]
### Description

Once https://github.com/wso2/api-manager/issues/967 is done to remove  deprecated profiles from the pack, we need to remove the profile optimisation scripts from profileSetup.sh and profileSetup.bat.

### Affected Component

APIM

**Comment by Tharanidk** [comment]
Update 2023-01-13

- Fix is done

**Comment by Tharanidk** [comment]
The fix was reverted as it directed to an error page when accessing Admin and devportal.

**Comment by rmsamitha** [comment]
Fixed via https://github.com/wso2/api-manager/issues/1626
