### ISSUE TITLE
[4.2.0][Dependency Upgrade] odata-server version upgrade

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#1259]
### Description

This issue is created to track the progress of odata-server version upgrade in MI 4.2.0

### Affected Component

MI

### Version

4.2.0

**Comment by thisaltennakoon** [comment]
**Update 06-02-2023**

Since there is a big gap between existing version and nearest non-vulnerable version, code changes are needed.
Started debugging integration tests.
Identified the use cases to hit the debug points in the backend

**Comment by thisaltennakoon** [comment]
**Update 07-02-2023**

- Had to setup a Odata service to find out the reason for the integration test failures
- Identified the issue

**Comment by thisaltennakoon** [comment]
**Update 08-02-2023**

- Fix the integration tests failures

**Comment by thisaltennakoon** [comment]
**Update 09-02-2023**

- Tried to test complex data types in Odata
   - Had to figure out how to setup a Odata service
- Requested to edit the Time data type response when having zero second scenario

**Comment by thisaltennakoon** [comment]
**Update 10-02-2023**

- Tested complex data types manually
   - Had to setup mysql server
   - Had to create a Odata service using WSO2 Integration studio and add that to micro integrator
- Tried to edit the Time data type response when having zero second scenario
   - This couldn't be easily done as Odata library returns stream of data as the response to a query
