### ISSUE TITLE
[4.2.0][Dependency Upgrade] commons-io version upgrade

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#1265]
### Description

This issue is created to track progress of commons-io version upgrade in APIM 4.2.0.

Following commons-io versions are available in APIM 4.2.0.
- commons-io-2.5.jar : In apim alpha pack swagger-parser 2.0.20.wso2v1 is used and here the commons-io version used in 2.5 https://github.com/wso2/orbit/blob/master/swagger-parser/2.0.20.wso2v1/pom.xml#L64 
However with swagger-parser upgrade to 2.1.10.wso2v1 this issue is sorted.
- commons-io-2.4.jar : https://github.com/wso2/orbit/blob/master/openapi-generator/4.3.1.wso2v4/pom.xml#L256 

### Affected Component

APIM

### Version

4.2.0

**Comment by msm1992** [comment]
PR : https://github.com/wso2/carbon-kernel/pull/3485

**Comment by npamudika** [comment]
Reopened with https://github.com/wso2/carbon-kernel/pull/3500

**Comment by msm1992** [comment]
Could not upgrade commons-io version to latest 2.11.0 due to an OOM during startup, however the commons-io version available in APIM 4.2.0 is 2.7.0 which is not affected by known CVEs, hence resolving this issue.
