### ISSUE TITLE
Add option to set custom response headers in UI portals

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/api-manager#1272]
### Problem

Currently, we cannot set custom response headers for the web pages served in the portals(publisher, dev and admin). It's better to have this feature so any user can easily set response headers depending on their use cases. Such as setting a custom CSP header.

### Solution

Add the option to set custom response headers in UI portals

### Affected Component

APIM

### Related Issues

IS improvement : https://github.com/wso2/product-is/issues/9088

**Comment by Avishka-Shamendra** [comment]
Hi all,

 `ResponseHeaderSetFilter` class (https://github.com/wso2/carbon-kernel/pull/3071) which is already pre packed in the carbon-kernel can be used for this. However, currently we have to manually place the filter in the `tomact/web.xml.j2` when needed with the headers. https://github.com/wso2/carbon-kernel/pull/3627 introduces the option that allows users to set the headers through the `deployment.toml`

```
[[tomcat.custom_response_header_filters]]
headers = "X-WSO2-Test-Header:Test Value, X-WSO2-Test-Header-2:Test Value-2"
filter_url_pattern = "/*"
```

**Comment by Avishka-Shamendra** [comment]
- Docs Issue -  https://github.com/wso2/docs-apim/issues/7164
- CSP will be addressed in - https://github.com/wso2/api-manager/issues/2062
