### ISSUE TITLE
An Error occurs when importing policies through APICTL with both synapse and Choreo enabled

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#1274]
### Description

Error occurred when importing policies through APICTL with both synapse and Choreo enabled

<img width="1507" alt="Screenshot 2023-01-17 at 19 53 34" src="https://user-images.githubusercontent.com/54719880/212923807-2362ffe5-6e90-4471-b356-4e6af8027d11.png">

### Affected Component

APICTL

### Version

4.2.0

### Environment Details (with versions)

APIM 4.2.0

### Relevant Log Output

```shell
ERROR - ApiMgtDAO Failed to add common operation policy testpolicy
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_5D ON PUBLIC.AM_OPERATION_POLICY_DEFINITION(POLICY_UUID NULLS FIRST, GATEWAY_TYPE NULLS FIRST) VALUES ( /* key:36 */ 'cd9253ca-d0f2-4b64-8613-c69d62d9d30a', 'Synapse')"; SQL statement:
INSERT INTO AM_OPERATION_POLICY_DEFINITION  (POLICY_UUID, GATEWAY_TYPE, DEFINITION_MD5, POLICY_DEFINITION)  VALUES (?,?,?,?) [23505-210]
```

**Comment by wasuradananjith** [comment]
We need to add an integration test as well for this scenario in Go side

**Comment by wasuradananjith** [comment]
Hi all,

The fix and manual testing have been done. Still writing the integration tests. 

Thanks,
Wasura Wattearachchi

**Comment by wasuradananjith** [comment]
Hi all,

An integration test has been also added and is under review.

Thanks,
Wasura Wattearachchi
