### ISSUE TITLE
.gotmpl file is missing in choreo type policies when downloaded via UI

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#1275]
### Description

When the existing policies with choreo gateways downloaded via UI, .gotmpl file is not available in some of the policies. 
Ex: Add Header, Remove Header

Therefore an error occurs when importing policies through APICTL

<img width="1507" alt="Screenshot 2023-01-18 at 10 11 34" src="https://user-images.githubusercontent.com/54719880/213085782-b697eedb-547f-40ed-ba80-7f8c62a39fdf.png">

It should be possible to import policies successfully in APICTL

When the policy is imported after adding the .gotmpl file in APICTL ,  response message is displayed in console which is unnecessary. 

<img width="1507" alt="Screenshot 2023-01-17 at 19 53 34" src="https://user-images.githubusercontent.com/54719880/213087650-8691c28c-3f72-4004-8dec-c1d2a495120d.png">

### Steps to Reproduce

Export Add header policy 

apictl export policy api -n ccAddHeader -v v2 -e alpha -k

Delete Add header policy in UI

apictl delete policy api -n ccAddHeader -v v2 -e alpha

import the same exported Add Header policy 

apictl import policy api -f  /<policyPath>/ccAddHeader_v2.zip -e alpha 

### Affected Component

APICTL

### Version

4.2.0

**Comment by wasuradananjith** [comment]
Hi all,

I reproduced both the issues above. The second screenshot displays an error that was due to network timeout. The correct screenshot for the second scenario is the below one.

![image](https://user-images.githubusercontent.com/25246848/213614719-33b7c015-4a57-413e-92d6-1667bdadf767.png)

Thanks,
Wasura Wattearachchi
