### ISSUE TITLE
Websocket api's Topics UI  shows wrong production URL 

### ISSUE THREAD

**Issue by Tharsanan1** [wso2/api-manager#1277]
### Description

Websocket api's Topics UI shows wrong production URL when we are editing Runtime->URL Mapping field. 

### Steps to Reproduce

1. Create a websocket API
2. Go to API Configuration -> Topics
3. Create a new Topic and add Ex: /notification 
4. Expand the Topic and try to add a url mapping, It will show a wrong url. In this case ws://<host>:<port>//notifications

![Screenshot from 2023-01-18 15-21-55](https://user-images.githubusercontent.com/25491225/213144043-9e85da62-8a29-4904-af34-0e812eb3a2ad.png)

### Affected Component

APIM

### Version

4.2.0

### Suggested Labels

bug

**Comment by madushadhanushka** [comment]
Fix PR https://github.com/wso2/apim-apps/pull/443
