### ISSUE TITLE
Subscription validation is not working as expected in cross tenant subscription scenario.

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/api-manager#128]
### Description:
The already subscribed API from an application on a different tenant can be still invoked after unsubscribing.
### Steps to reproduce:

- Enable cross tenant subscription in APIM.
```
[apim.devportal]
enable_cross_tenant_subscriptions = true
```
- Create two tenants on the APIM.
- From one tenant create an API an add "Available to all the tenants" option and publish the API.
- Login to the second tenant and create an application.
- Logout and login to the first tenant's dev-portal using second tenant's credentials.
- Subscribe the API using above create application and generate an access-token
- Invoke the API using a client like postman using the curl command in the try-out.
- Then unsubscribe the application from the API and try to invoke the API.
- API is still invokable.
- After the expiry time of the access-token which is 3600s by default, API cannot be invoked.

### Affected product version:
3.1.0

**Comment by hisanhunais** [comment]
The fix for APIM-3.1.0 is completed and available via an update. Issue is not reproducible in master pack. Hence, closing this issue.
