### ISSUE TITLE
Improve image file verification for Thumbnails

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#1280]
### Problem

We can improve the Thumbnail image file verification apart from the validation measures that are already set in place.

### Solution

Improve the Thumbnail image file content verification

### Affected Component

APIM

### Version

4.1.0

**Comment by hisanhunais** [comment]
Thumbnail content validation has been added with the following PRs
- https://github.com/wso2/carbon-apimgt/pull/11872
- https://github.com/wso2/apim-apps/pull/442

The following improvements have been done
- Used the Apache Tika dependency to detect the file media type using the input stream
- Validated the detected media type against the allowed media types (image/jpeg, image/png, image/gif, image/svg+xml)
- Converted svg media type images to png using the Apache Batik dependency
