### ISSUE TITLE
Slowness in rendering the users in the MI Dashboard

### ISSUE THREAD

**Issue by sarindufit** [wso2/api-manager#1282]
### Problem

Hi Team,

When log in to the MI Dashboard and try to view the users, the list is rendered very slowly in the browser. To be more specific, it takes around three minutes to render the user list in the Dashboard when the user count is significantly high. 

When investigating this issue, I noticed that Dashboard uses two distinct management API calls in MI to retrieve the user information.

Get a list of users via [1].

Get information about individual users via [2].

Basically the second HTTP call is made multiple times based on the number of users returned from the first call. In the customer's case where around 500 users are available, the second HTTP call is made that many times to get individual user details. This process seems to be quite costly and time consuming. As a result, it takes a long time to render the user list in the dashboard.

I would highly appreciate it if you can check this issue and do the needful at earliest.

[1] - https://github.com/wso2/product-mi-tooling/blob/v4.2.0-alpha/monitoring-dashboard/components/org.wso2.ei.dashboard.core/src/main/java/org/wso2/ei/dashboard/micro/integrator/delegates/UsersDelegate.java#L167

[2] - https://github.com/wso2/product-mi-tooling/blob/v4.2.0-alpha/monitoring-dashboard/components/org.wso2.ei.dashboard.core/src/main/java/org/wso2/ei/dashboard/micro/integrator/delegates/UsersDelegate.java#L171

### Solution

1. Avoid sending the second call mentioned above to fetch individual user information. 

### Affected Component

MI

### Version

4.2.0-beta

**Comment by GDLMadushanka** [comment]
Started working on the issue. Created the setup and did an initial fix. Will be able to finalyze the fix tomorrow.

**Comment by GDLMadushanka** [comment]
Added the fix in https://github.com/wso2/product-mi-tooling/pull/331
