### ISSUE TITLE
Modify Stripe plugin to support latest invoices for Fixed pricing plan

### ISSUE THREAD

**Issue by NivethGoutham** [wso2/api-manager#1284]
### Problem

Earlier Stripe only supported invoices for dynamic plans and due to that, the product currently displays invoices only for dynamic plans. But now Stripe has invoice support for dynamic and fixed-price plans as well. 

### Solution

Requesting to support invoices for both plans.

### Affected Component

APIM

### Version

4.1.0

### Related Issues

https://github.com/wso2-extensions/wso2-am-stripe-plugin/issues/41

**Comment by IsuruMaduranga** [comment]
Hi,

We released v1.3.3 of strip plugin ( https://github.com/wso2-extensions/wso2-am-stripe-plugin/releases/tag/v1.3.3 ) fixing this issue.

Thanks,
Isuru
