### ISSUE TITLE
[4.2.0][Dependency Upgrade] carbon mediation version upgrade

### ISSUE THREAD

**Issue by rmsamitha** [wso2/api-manager#1285]
### Description

This issue is created to track progress on carbon mediation version upgrade from 4.7.157 in APIM 4.2.0 and from 4.7.153 in MI 4.2.0

### Affected Component

APIM

**Comment by rmsamitha** [comment]
@npamudika please track this in https://github.com/wso2/api-manager/issues/1203

**Comment by npamudika** [comment]
As discussed offline this won't be tracked with #1203 as it focuses on 3rd party dependencies only.

**Comment by rmsamitha** [comment]
This is done via [1] and [2] for APIM (upgraded to 4.7.163)

[1] https://github.com/wso2/product-apim/pull/13109
[2] https://github.com/wso2/carbon-apimgt/pull/11819

**Comment by rmsamitha** [comment]
Assigning @rosensilva to perform this for MI, prior to MI beta release.

**Comment by rosensilva** [comment]
PR for MI https://github.com/wso2/micro-integrator/pull/2853
