### ISSUE TITLE
Injecting values into endpoint template parameters and Kafka inbound endpoints via file.properties

### ISSUE THREAD

**Issue by sarindufit** [wso2/api-manager#1289]
### Problem

This feature request is related to injecting values into synapse artifacts by using a file or environment variables. The feature has been documented for MI 4.1.0 at [1]. 

Currently this feature does not support the following scenarios. 

1. Injecting values into endpoint template parameters. For example, something similar to following. 

```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/config" name="ConfigAPI" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="GET">
        <inSequence>
         <call>
            <endpoint template="ep_template">
               <parameter name="name" value="$FILE:endpointName"/>
               <parameter name="uri" value="$FILE:endpointURL"/>
            </endpoint>
         </call>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```

2. Injecting values into Kafka inbound endpoints is possible. But, this feature cannot be used along with below parameters according to the documentation.  

```
<parameter name="topic.name">$FILE:topic</parameter>
<parameter name="auto.offset.reset">$FILE:auto.offset.reset</parameter>
<parameter name="interval">$FILE:interval</parameter>
<parameter name="bootstrap.servers">$FILE:bootstrap.servers</parameter>
<parameter name="sasl.jaas.config">$FILE:sasl.jaas.config</parameter>
<parameter name="schema.registry.url">$FILE:abc_xyz.schema.registry.url</parameter>
```

[1] - https://apim.docs.wso2.com/en/latest/integrate/develop/injecting-parameters/

### Solution

Improve the current feature available to inject values into synapse artifacts in a way that it supports the above mentioned scenarios. 

### Affected Component

MI

### Version

4.2.0-Beta

**Comment by imsuneth** [comment]
Hi @sarindufit,

The fix for the bullet point 1 is done in this PR https://github.com/wso2/wso2-synapse/pull/2047 and under review.

Regarding the 2nd point, When analyzing the code, I noted that the requested feature is already there. I tried it on MI 4.2.0 alpha pack and works. Please check it and let me know.
