### ISSUE TITLE
[APIM 3.0.0] High response time on publisher's REST API "/subscriptions"

### ISSUE THREAD

**Issue by ruwanmadhusanka** [wso2/api-manager#1290]
### Description

When there is a large number of subscriptions to a particular API, the /subscription invocation takes a long time.

### Steps to Reproduce

-

### Affected Component

APIM

### Version

3.0.0

### Related Issues

https://github.com/wso2/product-apim/issues/9668
https://github.com/wso2/product-apim/issues/11837

**Comment by lakshithagunasekara** [comment]
Public fix: https://github.com/wso2/carbon-apimgt/pull/9580
