### ISSUE TITLE
Using $FILE:wsdlendpoint syntax for publishWSDL attribute in integration studio

### ISSUE THREAD

**Issue by sarindufit** [wso2/api-manager#1299]
### Problem

Hi Team,

This ticket is related to [1].

MI 4.2.0-alpha currently supports injecting values into publishWSDL attribute of the proxy services via a properties file. For example, the following.

```
<?xml version="1.0" encoding="UTF-8"?>
<proxy name="SampleProxy" startOnLoad="true" transports="http https" xmlns="http://ws.apache.org/ns/synapse">
    <target>
        <inSequence/>
        <outSequence/>
        <faultSequence/>
    </target>
    <publishWSDL uri="$FILE:endpointURL"/>
</proxy>
```

However, this syntax ($FILE:endpointURL) is not allowed in the integration studio 8.1.0. I tried this after updating the integration studio as well, but experienced the same result. To be more specific, the following error is shown in the integration studio.

![image](https://user-images.githubusercontent.com/5381817/213981950-f327bdc6-552d-40a5-9bd5-bc68b42cd666.png)

[1] - https://github.com/wso2-enterprise/wso2-apim-internal/issues/1622

### Solution

Update integration studio to support $FILE:wsdlendpoint syntax for publishWSDL attribute in proxy services.

### Affected Component

MI

### Version

4.2.0-Beta

**Comment by imsuneth** [comment]
Did the change in wso2-synapse integration-studio branch. But still a error pops up without the reason.
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/18381372/217159736-c7fb037d-d017-470b-839e-09dfd3283994.png">

**Comment by imsuneth** [comment]
It was identified that the above Error message is a result of an NPE thrown from synapse-core.jar, when accessing the value of endpointURL attribute from a Map which should be initialised and populated reading file.properties file.
Unlike in MI where we have file.properties inside the conf directory,  in an integration-studio project file.properties file is not available.
