### ISSUE TITLE
When accessing Admin and devportal urls, it redirects to a 405 error

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#1303]
### Description

When accessing Admin and devportal it redirects to the [https://localhost:9443/carbon/admin/index.jsp](url), and when logged in user is directed to an error page.

<img width="1507" alt="Screenshot 2023-01-23 at 13 46 37" src="https://user-images.githubusercontent.com/54719880/214013579-e70b7f5f-61a7-41e8-ab33-a15e246f5c14.png">

### Steps to Reproduce

[https://wso2.org/jenkins/job/products/job/product-apim/org.wso2.am$wso2am/3037/artifact/org.wso2.am/wso2am/4.2.0-SNAPSHOT/wso2am-4.2.0-SNAPSHOT.zip](url)

Access admin url [https://localhost:9443/admin/](url)

### Affected Component

APIM

### Version

4.2.0

### Environment Details (with versions)

local environment
Mac Monterey M1 Pro chip

**Comment by BLasan** [comment]
Hi,

Tried the publisher portal URL as well. Same `405` was received.

Thanks,
Benura

**Comment by DinithHerath** [comment]
Hi @vishmi49 

What version is this on? Is it on latest master build or 4.2.0-alpha pack.

**Comment by BathiyaL** [comment]
@DinithHerath this is from latest master, this is the pack we tried https://wso2.org/jenkins/job/products/job/product-apim/org.wso2.am$wso2am/3037/ 
cc : @rmsamitha

**Comment by DinithHerath** [comment]
Seems like this is breaking from the https://github.com/wso2/product-apim/pull/13072. I have asked @Tharanidk to look in to that. Meanwhile that PR was reverted with https://github.com/wso2/product-apim/pull/13094. Triggered the jenkins product build to verify all the webapps are there without her change.

**Comment by DinithHerath** [comment]
Reverted the https://github.com/wso2/product-apim/pull/13094 but there is another issue on top of that. Seems like this issue is happening due to that. This will be tracked in https://github.com/wso2/api-manager/issues/1317.

**Comment by DinithHerath** [comment]
This is fixed in the latest APIM-4.2.0 build (https://wso2.org/jenkins/job/products/job/product-apim/org.wso2.am$wso2am/3048/). Hence closing the issue now.
