### ISSUE TITLE
Issues with Lambda API when saving the Lambda API endpoint configs

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/api-manager#1306]
### Description

We experienced an intermittent issue when saving the lambda API endpoint configurations by selecting the "Using IAM role-supplied temporary AWS credentials" access method.

When clicking on the "Using IAM role-supplied temporary AWS credentials" access method and saving the configs, the amznAccessKey and amznSecretKey are sending as admin intermittently which is not expected.
The complete endpointConfig object is as follows when observing this issue.

{
"endpointConfig": {
"access_method": "role-supplied",
"amznAccessKey": "admin",
"amznRegion": "",
"amznRoleArn": "",
"amznRoleRegion": "",
"amznRoleSessionName": "",
"amznSecretKey": "admin",
"assume_role": false,
"endpoint_type": "awslambda"
}
As we are selecting, "Using IAM role-supplied temporary AWS credentials", it is expected to amznAccessKey and amznSecretKey to be empty.

As discussed at the internal[1], please share an ETA for the fix.

### Steps to Reproduce

1. Followed the exact same steps mentioned in the documentation [1].

[1] https://apim.docs.wso2.com/en/latest/tutorials/create-and-publish-awslambda-api/

### Affected Component

APIM

### Version

4.1.0

### Environment Details (with versions)

AWS EC2

### Relevant Log Output

```shell
Missing AWS Credentials
```

**Comment by lakshithagunasekara** [comment]
Closing as the master fix is merged.
