### ISSUE TITLE
[4.2.0][Dependency Upgrade] org.apache.poi Version Upgrade

### ISSUE THREAD

**Issue by thisaltennakoon** [wso2/api-manager#1315]
### Description

This issue is created to track the progress on org.apache.poi version upgrade in APIM 4.2.0.

### Affected Component

APIM

### Version

4.2.0

**Comment by npamudika** [comment]
Putting this On Hold due to some issues identified as mentioned in https://github.com/wso2/api-manager/issues/1256#issuecomment-1413547284
