### ISSUE TITLE
Add support to configure API lifecycle from the admin portal

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/api-manager#132]
### Describe your problem(s)
Currently lifecycle is changed from the carbon console. Move this to admin portal and do the configuration from that dashboard.

**Comment by shnrndk** [comment]
Test Comment

**Comment by dushaniw** [comment]
tracking the same with https://github.com/wso2/api-manager/issues/194

**Comment by dushaniw** [comment]
reso
