### ISSUE TITLE
Number of assigned APIs are not showing in  the API categories list.

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#1330]
### Description

Number of assigned APIs are not showing in the API categories list. It allows user to successfully delete categories that are already assigned to APIs. 

This is not reproducible in 4.1.0 version

<img width="1114" alt="Screenshot 2023-01-27 at 09 35 53" src="https://user-images.githubusercontent.com/54719880/215007351-2a98ba2b-243c-44b7-a751-f1a5ba4cf887.png">

### Steps to Reproduce

1. Create an API category from Admin
2. Create and publish an API 
3. Assign the API to the particular category
4. Check API Category list

### Affected Component

APIM

### Version

4.2.0

### Environment Details (with versions)

Mac Monterey - version 12
M1 chip
JDK 11

**Comment by msm1992** [comment]
Duplicate issue https://github.com/wso2/api-manager/issues/1338. Hence closing this issue.
