### ISSUE TITLE
Request always directed to production endpoint when using API Key

### ISSUE THREAD

**Issue by ruwanmadhusanka** [wso2/api-manager#1334]
### Description

When trying to invoke the API by using the API key and even the API key was generated by using the SANDBOX application, the backend request is always going to the production environment.

### Steps to Reproduce

- Started the API Manager 4.1.0 pack.
- Went to the publisher portal.
- Created an API (TEST_API)
- Under the Endpoints section, added both production and sandbox endpoints.
- Under the Application Level Security section inside the Runtime section, selected only the API Key.
- Deployed the API into the gateway.
- Went to the dev portal and subscribed to the API by using an application.
- Generated an API key under the SANDBOX section and invoked the API.
- We got the response from the production endpoint instead of the sandbox endpoint.

### Affected Component

APIM

### Version

4.1.0

### Related Issues

https://github.com/wso2/product-apim/issues/8483

**Comment by Heinrich24** [comment]
Any update with regards to a resolution for this?

**Comment by chamilaadhi** [comment]
@Heinrich24 we have sent the fix as an Update for apim 4.1.0 . Please update APIM 4.1.0 to the latest update level. Refer https://updates.docs.wso2.com/en/latest/updates/update-tool/

**Comment by Heinrich24** [comment]
Hi @chamilaadhi, Thank you for this. We proceeded to update to the latest level for apim 4.1.0 and this issue has now been resolved.

I believe this ticket can be closed and marked as resolved!

**Comment by chamilaadhi** [comment]
Closing this since the fix is in the master branch from https://github.com/wso2/apim-apps/pull/431 as well.
