### ISSUE TITLE
Script Mediator importClass does not work in MI-4.1.0

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/api-manager#1337]
### Description

The Script Mediator throws an error when using the `importClass` method in the script as follows,

```js
<script language="js"><![CDATA[var log = mc.getServiceLog();     
    log.info("Logging inside Script Mediator");
    importClass(Packages.java.util.UUID);
    var uuid = java.util.UUID.randomUUID().toString().replace('-','');
    log.info("UUID " + uuid);
    mc.setProperty('uuid',uuid);]]></script>
```

### Steps to Reproduce

1. Create an API
2. Add the aforementioned script to a Script Mediator
3. Invoke the API

### Affected Component

MI

### Version

4.1.0

### Relevant Log Output

```shell
Error: Caused by: org.mozilla.javascript.EcmaError: TypeError: Method "importClass" called on incompatible object (com.sun.phobos.script.javascript.ExternalScriptable is not an instance of org.mozilla.javascript.ScriptableObject). (<Unknown Source>#2)
```

**Comment by SanojPunchihewa** [comment]
Orbit PR: https://github.com/wso2/orbit/pull/917

**Comment by FiveO** [comment]
Before doing a downlgrade to thino, if you remove the importClass line, the script works. It looks like rhino can import classes without importClass declaration

**Comment by SanojPunchihewa** [comment]
Hi @FiveO,

Thanks for your suggestion. When we don't use `importClass` we need to define the class with the full package name in the script body, which needs changes to existing synapse configs. Therefore to ensure backward compatibility, rhino will be downgraded.
