### ISSUE TITLE
Update APIM On Pre Analytics Docs to add OpenSearch and Datadog Realated Documentation

### ISSUE THREAD

**Issue by AnuGayan** [wso2/api-manager#1348]
As we have added support for Amazon OpenSearch and Datadog as On Pre Analytics Solutions for APIM and we have a few customers who are interested in using the solution. Need to add this to the official documentations.

**Comment by Tharanidk** [comment]
Update 2023-02-15

- Added documentation for DataDog As the On-prem Analytics Solution For API Manager.
- Started working on documentation for Elastic Stack-Based Operational Analytics WSO2 Micro Integrator

**Comment by AnuGayan** [comment]
Need to add OpenSearch documentation

**Comment by YasasRangika** [comment]
Closing this as the public PR at https://github.com/wso2/docs-apim/pull/6752 has already been merged into the master branch.
