### ISSUE TITLE
'Organization' field is not getting enabled in self registration form

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#1355]
### Description

'Organization' field is not getting enabled in self registration form after updating the relevant configurations in deployment.toml file

Issue is not reproducible in 4.1.0

### Steps to Reproduce

1. Enable following configurations in deoloyment.toml file
         [apim.devportal]
         enable_application_sharing = true
         application_sharing_type = "default"

2. Restart the server
3. Try to add a user with Self registration process in devportal

### Affected Component

APIM

### Version

4.2.0

### Environment Details (with versions)

Tested in local environment

Mac Monterey 
version 12.3.1- M1 chip

**Comment by chanaka3d** [comment]
After enabling the application sharing feature as above, the "organization" claim is not retrieved from the backend from the following code. Also there is no specific logic to show or hide the organization in the following file.

repository/deployment/server/webapps/accountrecoveryendpoint/self-registration-with-verification.jsp
```java
 try {
        claimsList = usernameRecoveryApi.claimsGet(user.getTenantDomain(), false);
        uniquePIIs = IdentityManagementEndpointUtil.fillPiisWithClaimInfo(uniquePIIs, claimsList);
        if (uniquePIIs != null) {
            claims = uniquePIIs.values().toArray(new Claim[0]);
        }
        IdentityManagementEndpointUtil.addReCaptchaHeaders(request, usernameRecoveryApi.getApiClient().getResponseHeaders());

    }
```

**Comment by msm1992** [comment]
In the identity version used in APIM 4.1.0 Organization claim is marked as supported by default. But in the identity version used in APIM 4.2.0 Organization claim is not marked as supported by default hence that field is not shown in the user registration form.
<img width="1491" alt="Screenshot 2023-02-06 at 09 11 27" src="https://user-images.githubusercontent.com/28379317/216879029-2be0f01c-7942-4f23-908c-811f162066b8.png">

We can use below instructions as a workaround to the above issue.
1. Visit management console and locate Organization Claim under `http://wso2.org/claims` claimset.
2. Edit and tick `Supported By Default`.
<img width="1520" alt="Screenshot 2023-02-06 at 09 15 27" src="https://user-images.githubusercontent.com/28379317/216879381-d1fac0a8-66e9-4a8a-996e-469a41048bf9.png">
3. Now the organization field should be prompted in the user registration form.

**Comment by msm1992** [comment]
PR : https://github.com/wso2/carbon-identity-framework/pull/4433

**Comment by msm1992** [comment]
There was a test failure in carbon-identity-framework due to a recent apache poi version upgrade, hence added below fix[1].
Once the carbon-identity-framework release is done, identity version has to be upgraded in APIM.

[1]. https://github.com/wso2/carbon-identity-framework/pull/4436/files

**Comment by msm1992** [comment]
Identity version was updated in APIM with PRs [1] and [2].

[1]. https://github.com/wso2/carbon-apimgt/pull/11847 
[2]. https://github.com/wso2/product-apim/pull/13137
