### ISSUE TITLE
[MI 4.2.0-Alpha] CApps are not listing in MI Dashboard when trying to deploy faulty CAPP 

### ISSUE THREAD

**Issue by LayaniMal** [wso2/api-manager#1360]
### Description

Hi Team,

If there is any faulty CApp deployed in the MI 4.2.0-Alpha version, then MI Dashboard does not list any Carbon Application. Even the correct CAPPs are not getting listed and displaying the loading page as below.
![image](https://user-images.githubusercontent.com/25350433/215727393-5d196bb1-6e1f-4d62-a34c-52e85e7857ea.png)

Also, the network tab, it is showing a 500 - internal server error, for the below request.

Request URL:
`https://localhost:9743/dashboard/api/groups/mi_dev/capps?nodes=dev_node_2&searchKey=&lowerLimit=0&upperLimit=5&order=asc&orderBy=name&isUpdate=false`

Response:
```
{
	"message": "Internal server error"
}
```
It is not showing any errors (except the faulty CAPP) in the MI server side or MI dashboard logs. 

However when trying to Get Carbon Applications with the Management APIs[1] it is listing all the CAPPs(faulty CAPP and correct CApps).

**Request:** 

```curl -X GET "https://localhost:9164/management/applications" -H "accept: application/json" -H "Authorization: Bearer eyJraWQiOiJmMWUzY2VhYS0wYjIzLTRkYzYtYTc0MS03NDhlMTFjMjYzY2QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvMTI3LjAuMC4xOjkxNjRcLyIsInN1YiI6ImFkbWluIiwiZXhwIjoxNjc1MTU1NDMxLCJzY29wZSI6ImFkbWluIn0.BXXT2R0Twj9EWcSOvZE95YtmN9sblrOGtufbFl1pG2nQHg-Zam21Hrk1S7oS_6TUIsdl1owVrHXr5E_DFVrdserSpN5_l-JebMNz-MU4-WMDn4emaOhKBrocdWR_GLYYNoXg7UgZr7NYBPxBnbHKbKrKDqN79bBekqsHZ_bsk9De7Pxp-MFH44uQFmuP1Cr72EANvaj_-j3TsSLi2spP1TaK76VT9J_wrYmc66SnUrH8WOf-Jhq02FqzdstfhvxHE07KTkmlPfMzVXz3OGvedNUfFJT0YjrtZWV1yk3OT-PjQ1De3fAIrytmwH83a8PT2pNr-br2ADG8HKymTAkSjA" -k -i```

**Response:**

```
HTTP/1.1 200 OK
Authorization: Bearer eyJraWQiOiJmMWUzY2VhYS0wYjIzLTRkYzYtYTc0MS03NDhlMTFjMjYzY2QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvMTI3LjAuMC4xOjkxNjRcLyIsInN1YiI6ImFkbWluIiwiZXhwIjoxNjc1MTU1NDMxLCJzY29wZSI6ImFkbWluIn0.BXXT2R0Twj9EWcSOvZE95YtmN9sblrOGtufbFl1pG2nQHg-Zam21Hrk1S7oS_6TUIsdl1owVrHXr5E_DFVrdserSpN5_l-JebMNz-MU4-WMDn4emaOhKBrocdWR_GLYYNoXg7UgZr7NYBPxBnbHKbKrKDqN79bBekqsHZ_bsk9De7Pxp-MFH44uQFmuP1Cr72EANvaj_-j3TsSLi2spP1TaK76VT9J_wrYmc66SnUrH8WOf-Jhq02FqzdstfhvxHE07KTkmlPfMzVXz3OGvedNUfFJT0YjrtZWV1yk3OT-PjQ1De3fAIrytmwH83a8PT2pNr-br2ADG8HKymTAkSjA
activityid: 5b3615ab-a7a5-4688-a6e4-c95be7898356
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE,OPTIONS, PATCH
Host: localhost:9164
Access-Control-Allow-Headers: Authorization, Content-Type
accept: application/json
Content-Type: application/json; charset=UTF-8
Date: Tue, 31 Jan 2023 08:06:54 GMT
Transfer-Encoding: chunked

{"count":2,"list":[{"name":"helloCAR","version":"1.0.0","artifacts":[{"name":"head_jaxrs_basic","type":"api"},{"name":"head_yahooapis","type":"api"},{"name":"head_starbucks","type":"api"},{"name":"helloep","type":"endpoint"}]},{"name":"testnewcar","version":"1.0.0","artifacts":[{"name":"calsignatureunlock","type":"sequence"},{"name":"calsignatuteconfirm","type":"sequence"},{"name":"calsignature","type":"sequence"},{"name":"max_money","type":"proxy-service"}]}]}
```

[1] https://apim.docs.wso2.com/en/latest/observe/mi-observe/working-with-management-api/#get-carbon-applications

### Steps to Reproduce

-  Downloaded the wso2mi-4.2.0-alpha and wso2mi-dashboard-4.2.0-alpha product versions from here[2]
-  Configured the MI with the MI dashboard.
-  Created and deployed sample erroneous CAPP in the wso2mi-4.2.0-alpha. (MI_HOME/repository/deployment/server/carbonapps,)
-  Login to the dashboard and navigate to the carbon application section.

[2] https://github.com/wso2/micro-integrator/releases

### Affected Component

MI

### Version

4.2.0-alpha

### Suggested Labels
4.2.0-alpha
4.2.0-beta

**Comment by GDLMadushanka** [comment]
Did a fix, will test further and finalyze tomorrow.
