### ISSUE TITLE
DefferedParsingException while using XML mapper in SI Tooling

### ISSUE THREAD

**Issue by lasanthaS** [wso2/api-manager#1363]
### Description

While using XML mapper in SI Tooling, the editor shows `DefferedParsingException` and doesn't allow running the Siddhi app. But in SI worker, the same Siddhi app works fine.

<img width="881" alt="Screenshot 2023-01-31 at 20 20 25" src="https://user-images.githubusercontent.com/2142703/215794354-8cf2860f-ff58-44d6-9501-03889b92a2fc.png">

### Steps to Reproduce

Create a Siddhi app and add the following Stream definition with the XML source mapper.

```
@Source(type = 'http', receiver.url='http://localhost:8006/productionStream', basic.auth.enabled='false',
    @map(type='xml'))
define stream SweetProductionStream (name string, amount double);
```

### Affected Component

SI

### Version

4.2.0-alpha

### Environment Details (with versions)

SI Tooling 4.2.0-alpha

**Comment by AnuGayan** [comment]
This was fixed by https://github.com/wso2/streaming-integrator-tooling/pull/226
