### ISSUE TITLE
Thumbnail uploading feature is not working for API Products

### ISSUE THREAD

**Issue by Tharanidk** [wso2/api-manager#1375]
### Description

When a thumbnail is updated for an API Product it gives the message 'Thumbnail uploaded successfully', but it has not been updated in the publisher portal.
![Screenshot from 2023-02-02 11-49-01](https://user-images.githubusercontent.com/42825038/216247115-0f9b9604-65e8-44fb-b487-d2681f2b16bc.png)

After deploying a new revision, we can see it has been updated in the developer portal.
![Screenshot from 2023-02-02 11-48-51](https://user-images.githubusercontent.com/42825038/216247137-64f7f97b-e8e9-4c0e-9f7d-dca9b7953bc9.png)

### Steps to Reproduce

01. Create an API Product.
02. Try uploading the thumbnail image of the API Product (Portal configurations >> Basic info).
03. See the image of API Product.
03. Deploy a new revision.
04. Go to devportal and see the thumbnail of the created API Product.

### Affected Component

APIM

### Version

4.2.0-beta

**Comment by chanaka3d** [comment]
This issue can be fixed from UI side.

source/src/app/components/Apis/Listing/components/ImageGenerator/BaseThumbnail.jsx

```javascript
@@ -117,7 +117,8 @@ const BaseThumbnail = (props) => {
      */
     useEffect(() => {
         if (type !== 'DOC') {
-            if (api.hasThumbnail !== null && api.hasThumbnail) {
+            if ((api.hasThumbnail !== null && api.hasThumbnail) 
+                || (apiType === Api.CONSTS.APIProduct)) {
                 const promisedThumbnail = apiType === Api.CONSTS.APIProduct
                     ? new APIProduct().getAPIProductThumbnail(id)
                     : new Api().getAPIThumbnail(id);
```

But the proper fix is to set the `hasThumbnail` property value to true after uploading an image. This API put call is happening from the UI side after a successful image upload. But the backend is ignoring this and resetting it back to the original state ( false ). 

This issue can be fixed if we fix the following rest api issue for API product.

1. Send a API put request with the following payload { ..., hasThumbnail: true, ... }. 
2. Do a API get and examine the payload. The `hasThumbnail` property is set to false again.

**Comment by msm1992** [comment]
Status Update (08/02/2023)

- Backend issue was fixed with PR [1].
- However still the thumbnail on the header section does not get updated on updating the API product thumbnail for the first time. This needs to be further checked.

[1]. https://github.com/wso2/carbon-apimgt/pull/11849

**Comment by msm1992** [comment]
Had a discussion with UI Team and it seems the issue mentioned in above comment is there for APIs as well. Hence created a seperate issue [1] and it will be fixed by the UI team. 

[1]. https://github.com/wso2/api-manager/issues/1407
