### ISSUE TITLE
Incorrect year in portal footers

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/api-manager#1376]
### Description

The year mentioned in the footer of the portals (Publisher, Devportal, Admin) is 2022. This should be updated to 2023.

![Screenshot from 2023-02-02 14-02-42](https://user-images.githubusercontent.com/25485273/216272267-54e3c582-6058-43f1-b861-3c41e7ceb319.png)

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

4.2.0

**Comment by piyumaldk** [comment]
### Work Log [2022-03-01]

Started and completed this task.
