### ISSUE TITLE
Need additional logging for request/response flow

### ISSUE THREAD

**Issue by vikumkbv** [wso2/api-manager#1377]
### Problem

Hi Team,

We want some additional logs for each request-response flow that will clearly indicate 

- When the request is received by GW from client

- When the request is sent to the backend ( i.e. actually sent out to backend from transport side )

- When the response is received from backend ( as soon as it is received )

- When the response is sent out to the client from GW

Want to keep it enabled in normal mode in PROD also. But it will be good to have a switch/flag/control to turn off if we decide to.

Thanks,
Vikum

### Solution

Provide some logs for the above points

### Affected Component

APIM

### Version

197

**Comment by Lakith-Rambukkanage** [comment]
Fixed by : https://github.com/wso2/wso2-synapse/pull/2076
