### ISSUE TITLE
Sending more than one email for newly created versions of an API

### ISSUE THREAD

**Issue by Tharanidk** [wso2/api-manager#1390]
### Description

When the notification feature is enabled to send an email for newly created API versions, the following tests were done.
- First created the PizzaShackAPI 1.0.0
- Then created the PizzaShackAPI 5.2.0 from the PizzaShackAPI 1.0.0.
- Then created the PizzaShackAPI 6.3.0 from the PizzaShackAPI 5.2.0.
- Then created the PizzaShackAPI 7.2.0 from the PizzaShackAPI 6.3.0.

Getting more than one email for the newly created version in some scenarios.
![Screenshot from 2023-02-07 00-36-14](https://user-images.githubusercontent.com/42825038/217062220-367949a8-2784-48bb-b7ee-12882485e56f.png)

Created the PizzaShackAPI 3.5.2 from the PizzaShackAPI 1.0.0. , getting only one email.

### Steps to Reproduce

1. Follow the [documentation ](https://apim.docs.wso2.com/en/latest/design/api-versioning/enabling-notifications/#enabling-notifications)to enable email notifications.
2. Publish a new API
3. Create a new user ( Add an email address to the user profile also ) and subscribe to the newly published API
4. Release a new version of the API
5. Test the above-mentioned scenarios.
6. User should get the emails to the email address given by them in the user profile.

### Affected Component

APIM

### Version

4.2.0-beta

**Comment by BLasan** [comment]
Hi,

Trying to reproduce the issue in `macos m1`. Seems like notifications are not getting sent to the preferred destination.

Thanks,
Benura

**Comment by BLasan** [comment]
Hi,

Tried reproducing the issue with a valid email. However, it's not properly sending the emails to the destination on a new API version creation. I'll start debugging the issue with the code base.

Thanks,
Benura
