### ISSUE TITLE
APIM-4.1.0 Multi-dc scripts are not updated as per the regular scripts

### ISSUE THREAD

**Issue by chaminda** [wso2/api-manager#1391]
### Description

OGG multi-dc scripts has not been updated in the APIM-4.1.0 distribution. These should be updated as per the product requirement.

Thanks,
Chaminda

### Steps to Reproduce

Validate the scripts against the regular scripts on oracle.sql

### Affected Component

APIM

### Version

4.1.0

### Environment Details (with versions)

Oracle Golden Gate.

**Comment by YasasRangika** [comment]
Closing this issue as the public fix: https://github.com/wso2/carbon-apimgt/pull/11877 has already been merged into the master branch.
