### ISSUE TITLE
Integrating with Google Analytics GA4

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/api-manager#1393]
### Problem

Support for configuring Google Analytics 4 (GA4) from APIM-2.6.0 as the UA is being sunsetted and will be discontinued as Google Analytics has announced.

### Solution

Provide the support for configuring Google Analytics 4 (GA4) from APIM-2.6.0

### Affected Component

APIM

### Version

2.6.0

**Comment by imsuneth** [comment]
Update:

Sent Public PRs:

https://github.com/wso2/carbon-commons/pull/469
https://github.com/wso2/carbon-apimgt/pull/11978
