### ISSUE TITLE
 Giving 403 error when logging into the portals with Federated Single Sign On with SAML

### ISSUE THREAD

**Issue by BLasan** [wso2/api-manager#1394]
### Description

$subject

### Steps to Reproduce

Followed the steps mentioned in the doc[1]. However, the configuration was successfully added but when trying to log into the publisher/devportal/admin portal it gives 403 error.
[1]https://apim.docs.wso2.com/en/latest/reference/customize-product/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso/#configuring-identity-server-as-idp-for-sso

Following error was showing up.
`The server could not verify that you are authorized to access the requested resource`

### Affected Component

APIM

### Version

4.2.0-SNAPSHOT

**Comment by Tharsanan1** [comment]
The documentation is missing some key steps. I have created the following git issue with the steps that need to be added to the doc: https://github.com/wso2/docs-apim/issues/6664

**Comment by rmsamitha** [comment]
Closing as the issue was in docs
