### ISSUE TITLE
When adding already deleted alias name for certificates  it gives a warning as 'aready exists'

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#1397]
### Description

1. When adding already deleted alias name for certificates  it gives a warning as 'already exists'. 
![Screenshot 2023-02-07 at 16 34 33](https://user-images.githubusercontent.com/54719880/217231633-7a4f1cb2-9213-4e83-bd1c-d4f57f82f539.png)
  

2. Also if user adds another certificate with  an existing alias name it only shows an error when saving the certificate. It should display a warning message if a user typed an existing name.

<img width="1442" alt="Screenshot 2023-02-07 at 16 52 48" src="https://user-images.githubusercontent.com/54719880/217232762-da3042af-13ad-41be-99fc-2b9150d21690.png">

### Steps to Reproduce

Scenario 1

1. Add certificate to an endpoint of an API
2. Delete the certificate
3. Add a certificate with same alias

Scenario 2

1. Add a certificate to an endpoint of an API
2. Try to add certificate with a same alias name to a another api.

### Affected Component

APIM

### Version

4.2.0

### Environment Details (with versions)

Local and DS

**Comment by rmsamitha** [comment]
@vishmi49 The scenario 2 cannot be reproduced for me. As per the below screenshot, I see the the error and cannot save the cert.
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/2484781/218103347-6bec972f-ae7c-4c3c-9caf-624f16723177.png">
