### ISSUE TITLE
Disable Email Username Validation is not working in APIM 4.1.0

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/api-manager#1409]
### Description

Hi team,

We have set up login using email as username in APIM-4.1.0. after setting this up we cannot log in to any portals (except /carbon portal) with the carbon super user. 
```
[super_admin]
username = "admin"
password = "admin"
```
It seems we have to set the `disable_email_domain_validation` configuration to true like below in order to allow non-email users to log in. 
```
[tenant_mgt]
enable_email_domain = true
disable_email_domain_validation = true
```
Even after disabling the email domain validation we cannot log in to any portals. 

[1] - https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords/#setup-an-e-mail-login

Thanks & Regards,
Niran Peiris

### Steps to Reproduce

- Keep the super admin configurations as below.
```
[super_admin]
username = "admin"
password = "admin"
```
- Enable enable_email_domain and restart the APIM server.
```
[tenant_mgt]
enable_email_domain = true
disable_email_domain_validation = true
```
- Try login into the admin portal.

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
As per the comment [1], this issue is not reproducing in the master branch. Hence closing the issue.

[1] https://github.com/wso2-enterprise/wso2-apim-internal/issues/1861#issuecomment-1425774820
