### ISSUE TITLE
MI and MI-dashboard 4.2.0-beta testing work

### ISSUE THREAD

**Issue by imsuneth** [wso2/api-manager#1418]
Test plan: ~~https://docs.google.com/spreadsheets/d/1TYiHM_LxTkAkPm9J9Hxg5bluCHh-iJDYrRbxlJb3S4k/edit#gid=619082802~~

New doc https://docs.google.com/spreadsheets/d/1hSX4eyEtm4omxzOW_MfIcDMZVTtpkvLTIeHBaJn_PIk/edit#gid=2016117240

**Comment by imsuneth** [comment]
Tested:

Verify the dashboard can be started succesfully with the enabled management API
Verify user can login to the dashboard when an external user store is configured - datastore - mysql
Verify management API login with external user store
Verify scopes in dashbaord with external user store
Verify user can login to the dashboard when the internal user store is configured

**Comment by imsuneth** [comment]
Tested:

Using a Simple Proxy Service
Publishing a Custom WSDL
Exposing a Proxy Service via Inbound Endpoints

Using a Simple REST API
Setting Query Parameters on Outgoing Messages
Exposing a SOAP Endpoint as a RESTful API
Handling Non-Matching Resources

Routing Based on Message Headers
Routing Based on Message Payload
Splitting Messages and Aggregating Responses

**Comment by imsuneth** [comment]
Tested:

Handling HTTP Status Codes
Transforming Content Types

Sending a Simple Message to a Service
Message Routing
Message Transformation
Service Orchestration

JMS Message Store
RabbitMQ Message Store

**Comment by imsuneth** [comment]
Tested:

Message Sampling Processor
Message Forwarding Processor
Securing the Message Forwarding Processor
Load Balancing with Message Forwarding Processor


Using the TCP Transport

**Comment by imsuneth** [comment]
Using the MQTT Transport
Accessing a Windows Share Using VFS
File connector
Exposing an RDBMS datasource
Asynchronous Messaging
Using GET with a Message Body
Using POST with Empty Message Body
Using POST with Query Parameters

**Comment by malakaganga** [comment]
Started testing from today

**Comment by malakaganga** [comment]
Update:

ciphertool.sh test

**Comment by malakaganga** [comment]
Update:
Connect to LDAP user store of APIM-4.2.0
Create user store out of APIM db script
Create user in MI and view in APIM
Create user in APIM and view in MI

**Comment by malakaganga** [comment]
Update:
Adding a new secondary user store / https://apim.docs.wso2.com/en/latest/administer/managing-users-and-roles/managing-user-stores/configuring-secondary-user-stores-mi/ and 
https://apim.docs.wso2.com/en/latest/install-and-setup/setup/mi-setup/user_stores/setting_up_a_userstore/#configuring-an-ldap-user-store
