### ISSUE TITLE
Porting SMB2 tests for Public & 4.1.0 branches

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/api-manager#1444]
### Description

Porting SMB2 tests for Public & 4.1.0 branches. Fixing SMB2 test failures as well.

### Steps to Reproduce

Run SMB2 tests on Jenkins.

### Affected Component

MI

### Version

4.2.0

**Comment by malakaganga** [comment]
Update:
We took 6 hrs call and changed the Jenkins configurations and were able to successfully run the tests on the master Jenkins.
