### ISSUE TITLE
Json Schema - $ref keyword is not working

### ISSUE THREAD

**Issue by akAsara** [wso2/api-manager#147]
### Description

Currently, JSON Schema file which has $ref keyword as a reference to another object is not supporting in the WSO2 Integration Studio. Even if we upload the schema without any error,we can't see the referred objects within the input section
![After_upload_input](https://user-images.githubusercontent.com/37328374/171986441-ffb2cb8a-da2d-48a0-a1d5-d7d1aa3e1c1b.png)

### Steps to Reproduce

1. Create a integration project and then create a API.
2. Add a Datamapper mediator and respond mediator.
3. Double click on Data mapper mediator and select JSON Schema as the input.
4. Add the below json Schema as the input.

````
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
   "title": "sss",
  "properties": {
    "Items": {
      "type": "object",
      "items": {
        "$ref": "#/definitions/Item"
      }
    }
  },
  "definitions": {
    "Item": {
      "type": "object",
      "properties": {
        "clm_id": {
          "type": "string"
        },
        "CLM_VRSN_NUM": {
          "type": "string"
        },
        "CLM_PRCSD_OR_PD_DT": {
          "type": "string"
        },
        "COND_CD": {
          "type": "string"
        }
      }
    }
  }
}


### Affected Component

IntegrationStudio

### Version

8.1.0

### Environment Details (with versions)

_No response_

### Relevant Log Output

_No response_

### Related Issues

_No response_

### Suggested Labels

_No response_

**Comment by imsuneth** [comment]
Integration studio com.google.gson is used for json related operations. The Json parser in gson does not handle $ref automatically and we have to implement it on top of gson.

https://github.com/google/gson/issues/1461
