### ISSUE TITLE
Save button Keep on Disabled  - Design configurations

### ISSUE THREAD

**Issue by shammijayasinghe** [wso2/api-manager#1478]
### Description

![Save Button Disabled Issue](https://user-images.githubusercontent.com/7627481/219791769-fefea074-6051-4858-8e97-31366149223f.png)

As you see in the image, Save Button keeps disabled until we refresh the page.

### Steps to Reproduce

1. Create an API
2. Go to Basic Info
3. "Developer Portal Visibility" , Change to Restricted by roles
4. Add invalid role and enter --> Getting highlighted in red and "save" button getting disabled
5. Remove that added role and change the field back to "Public"
6. Still the save button is disabled as you see in the image

### Affected Component

APIM

### Version

4.2.0-Beta

### Suggested Labels

Affected/4.2.0-Beta

**Comment by dakshina99** [comment]
This is not reproducible in APIM 4.3.0

If you encounter this problem again or have any additional concerns, please feel free to reopen the issue or create a new one.
