### ISSUE TITLE
Apple Silicon compatible distribution for Integration Studio

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/api-manager#1480]
### Problem

Currently, the Integration Studio distributions have been released for Intel only. It would be great if there is an Apple Silicon compatible Integration Studio distribution as well from the upcoming new releases onwards.

### Solution

N/A

### Affected Component

IntegrationStudio

### Version

8.2.0

**Comment by rosensilva** [comment]
Fixed with https://github.com/wso2/integration-studio/pull/1203
