### ISSUE TITLE
environment variable does not show when create kubernates exporter using integration studio 8.1.0

### ISSUE THREAD

**Issue by VihangaParanahewa** [wso2/api-manager#1486]
### Description

We have tested locally using integration studio of 8.1.0 and resolution of 1280X 800. Then we were able to reproduce the environment variable does not show when open create kubernates exporter window locally
![kubernetesExpoterWindow](https://user-images.githubusercontent.com/31098256/220084592-88c1c0a7-4cf1-4851-bcc6-1a4d7e26a5b2.jpg)

### Steps to Reproduce

- Change the resolution to 1280X720 or 1280X800 of the machine(OS can be any of them -> windows, linux, mac)
- Download and install the integration studio of 8.1.0(8.0.1 also can reproduce the issue)
- Then open the integration studio
- Select “New Integration Project” and not to select the checkbox of “Create Kubernetes Exporter”
- After the project creation, You can right click on an existing integration project and select New -> Kubernetes Exporter
- Then the open window does not have have enough height to display the environment variable and also no scroll bar visible to scroll down the window’s content

### Affected Component

IntegrationStudio

### Version

8.1.0

### Environment Details (with versions)

OS - windows, linux, mac

**Comment by YasasRangika** [comment]
closing as this issue is already closed in tracked issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/1902 with public PR: https://github.com/wso2/integration-studio/pull/1200
