### ISSUE TITLE
Bump IS-KM connector version

### ISSUE THREAD

**Issue by rmsamitha** [wso2/api-manager#1490]
### Description

Version of IS-KM connector needs to be bumped to the latest.
This should be reflected in the docs as well related to setting up WSO2 Identity Server as a Key Manager.
A doc issue [2] has been created to track this.

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/
[2] https://github.com/wso2/docs-apim/issues/6658

### Affected Component

APIM

### Version

4.2.0-Beta

**Comment by tgtshanika** [comment]
Fixed with https://github.com/wso2/product-apim/pull/13157

**Comment by tgtshanika** [comment]
Doc PR https://github.com/wso2/docs-apim/pull/6750/files
