### ISSUE TITLE
Publisher console test not working as expected in DS

### ISSUE THREAD

**Issue by BLasan** [wso2/api-manager#1496]
To reproduce create an API with subscriptions & working endpoints and then deploy it to the gateway. Then try to invoke the API via publisher test console. Will be getting the following error.

` "NetworkError when attempting to fetch resource."`

 If we check the network requests it shows "CORS missing Allow header" in OPTION method. But the curl invocation from the terminal works fine without any error.

**Comment by rmsamitha** [comment]
Fixing with https://github.com/GihanAyesh/ansible-apim/pull/1
This fix will be merged to the fork of GihanAyesh ATM since the 4.2.x branch is not yet merged to wso2/ansible-apim.
GihanAyesh/ansible-apim 4.2.x branch is to be merged to wso2/ansible-apim, so then issue will be resolved there too.
