### ISSUE TITLE
Cannot run APIM On windows as a Service with Java 17

### ISSUE THREAD

**Issue by BathiyaL** [wso2/api-manager#1497]
### Description

Cannot run APIM On windows as a Service with Java 17 and yajsw-stable-13.08 

### Steps to Reproduce

follow https://apim.docs.wso2.com/en/4.2.0/install-and-setup/install/installing-the-product/installing-api-m-as-a-windows-service/

1. setup yajsw-stable-13.08 (this support java 17) 
2. follow documentation and configure "wrapper.conf"
3. start the wrapper

Actual result : getting below error and terminated

NFO|wrapper|WSO2 Carbon|23-02-22 14:14:57|stopping process with pid/timeout 10428 45000
INFO|wrapper|WSO2 Carbon|23-02-22 14:14:58|process exit code: 1
system.env 58
INFO|wrapper|WSO2 Carbon|23-02-22 14:15:03|started process with pid 5480
INFO|wrapper|WSO2 Carbon|23-02-22 14:15:03|too many restarts: 5
INFO|wrapper|WSO2 Carbon|23-02-22 14:15:03|too many restarts: 5
INFO|wrapper|WSO2 Carbon|23-02-22 14:15:03|Shutting down Wrapper

NOTE:
same APIM pack is working with
java 11 and yajsw-stable-12.14"

### Affected Component

APIM

### Version

4.2.0

### Environment Details (with versions)

beta pack

### Relevant Log Output

```shell
INFO|wrapper|WSO2 Carbon|23-02-22 14:14:57|stopping process with pid/timeout 10428 45000
INFO|wrapper|WSO2 Carbon|23-02-22 14:14:58|process exit code: 1
system.env 58
INFO|wrapper|WSO2 Carbon|23-02-22 14:15:03|started process with pid 5480
INFO|wrapper|WSO2 Carbon|23-02-22 14:15:03|too many restarts: 5
INFO|wrapper|WSO2 Carbon|23-02-22 14:15:03|too many restarts: 5
INFO|wrapper|WSO2 Carbon|23-02-22 14:15:03|Shutting down Wrapper
```

**Comment by DinithHerath** [comment]
@BathiyaL @rmsamitha 
The issue can be resolved by following the below steps.

1. Download the latest version (13.05) of YAJSW from [here](https://sourceforge.net/projects/yajsw/files/yajsw/yajsw-stable-13.05/yajsw-stable-13.05.zip/download).
2. Extract the content of yajsw-stable-13.05.zip to <YAJSW_HOME>
3. Copy the wrapper.conf file found in the <APIM_HOME>/bin/yajsw/ directory and paste it in the <YAJSW_HOME>/conf/ directory.
4. Delete the wrapper.java.additional.4 = -XX:MaxPermSize=256m line in wrapper.conf file
5. Rename the subsequent wrapper.java.additional variables to be in consecutive order.
6. i.e. Rename wrapper.java.additional.5 to wrapper.java.additional.4. Rename wrapper.java.additional.6 to wrapper.java.additional.5 and so on.
7. Additionally wrapper.conf can be overwritten by wrapper.conf in [1] .

[1] [wrapper.zip](https://github.com/wso2/api-manager/files/10812066/wrapper.zip)

**Comment by DinithHerath** [comment]
Tested the functionality on both **JAVA11** and **JAVA17** with **YAJSW 13.05** on windows 11.
