### ISSUE TITLE
Publisher portal unified search count is wrong when API documents are included

### ISSUE THREAD

**Issue by Lakith-Rambukkanage** [wso2/api-manager#1510]
### Description

Note the count on top left corner

![image](https://user-images.githubusercontent.com/44548749/221162174-c4dd4e77-b7ee-438c-a32c-02074316f046.png)
![image](https://user-images.githubusercontent.com/44548749/221162190-ee7b1f88-cce1-4574-b6c5-4140174ce694.png)

Sub issue of :https://github.com/wso2/api-manager/issues/1491

### Steps to Reproduce

1. Create Several APIs
2. Add documents to the APIs
3. Search for docs in the search bar

### Affected Component

APIM

### Version

4.2.0

**Comment by HeshanSudarshana** [comment]
Hi @Lakith-Rambukkanage,

As per comment [1], we could fix the 2nd issue where the count is higher than the pagination limit. However, we couldn't reproduce the 1st issue where the count is lower than the pagination limit.

[1] https://github.com/wso2/api-manager/issues/1511#issuecomment-1449470282

Thanks,
Heshan

**Comment by HeshanSudarshana** [comment]
Hi all,

The 2nd issue is fixed and the 1st issue (both mentioned in the above comment [1]) is not reproducible. Hence, closing the issue.

[1] https://github.com/wso2/api-manager/issues/1510#issuecomment-1449532787 

Thanks,
Heshan
