### ISSUE TITLE
Search result pagination does not work as expected

### ISSUE THREAD

**Issue by Lakith-Rambukkanage** [wso2/api-manager#1511]
### Description

The search result pagination does not show the proper number of items per page and repeats items on other pages.

Page 1 : should show 10 items only, but shows 16
![image](https://user-images.githubusercontent.com/44548749/221163836-97e0aca9-6aa8-4642-af71-75a6f2d264ec.png)
Page 2 : shows the same items duplicated
![image](https://user-images.githubusercontent.com/44548749/221163964-e8c7b605-a40d-4b85-a1af-01022a158704.png)

The incorrect items per page is observed individually as well.
The example has 28 search results and should show 10 per page but only 7 is shown.
![image](https://user-images.githubusercontent.com/44548749/221164201-c4725956-21db-4a3c-b898-b337c0efd6d3.png)

Note : The issue is frequent and persistent, but has intermittent differenced when reproducing the bug. 

Sub issue of : https://github.com/wso2/api-manager/issues/1491

### Steps to Reproduce

1. Create several APIs
2. Add several documents for the APIs
3. Search for APIs/documents to get a number of result items greater than the per page count

**Note** : The issue is frequent and persistent, but has intermittent differenced when reproducing the bug. 

### Affected Component

APIM

### Version

4.2.0

**Comment by ashera96** [comment]
Hi @Lakith-Rambukkanage,

Managed to reproduce and fix the first couple of issues. However, we are unable to reproduce the doc issue where the search result count is lower than the actual result count. Can you please check if this is reproducible in the latest 4.2.0 pack?

Thanks,
Ashera

**Comment by Lakith-Rambukkanage** [comment]
Hi all,

Sure, will reproduce the issue and update
