### ISSUE TITLE
Getting 200 OK HTTP status for CORS Untrusted ORIGIN

### ISSUE THREAD

**Issue by vikumkbv** [wso2/api-manager#1519]
### Description

Hi Team,

This is regarding the CORS preflight request. APIM sending a 200 OK status code when the CORS is failing due to an untrusted origin. Instead, it should be sending a 4xx status code. When checking the code [1], we found that the status code is set as HttpStatus.SC_OK for both failed and successful calls. Is it possible to send the 403 status code for failed calls?

[1] https://github.com/wso2-support/carbon-apimgt/blob/f9de8855164f075aec5b0d358ca29b5c7dfbafac/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java#L240

Thanks,
Vikum

### Steps to Reproduce

invoke the API with untrusted origin, then you will get the response with 200 status code

### Affected Component

APIM

### Version

3.2.0

**Comment by npamudika** [comment]
Fixed via https://github.com/wso2/carbon-apimgt/pull/11926
