### ISSUE TITLE
Change WWW-Authenticate header's challenge string to Basic instead of Basic Auth

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#1526]
This can be fixed by updating the string in https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/basicauth/BasicAuthAuthenticator.java#L345

**Comment by RusJaI** [comment]
PR for the fix : https://github.com/wso2/carbon-apimgt/pull/11903
