### ISSUE TITLE
Users without necessary permissions can carry out operations

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/api-manager#1527]
### Description

Users without the necessary permissions (scope assignments) can carry out certain operations in APIM (such as creating Applications, etc.).

### Steps to Reproduce

1. Create a new user with a new role.
2. Assign `apim:subscribe` scope only to the role through the Admin portal.
3. Log in to the Devportal with the above user and try to create a new application.
4. Application creation will be successful even though it requires both `apim:subscribe`, and `apim:app_manage` scopes

### Affected Component

APIM

### Version

4.1.0, 4.2.0

### Environment Details (with versions)

Ubuntu 22.04
JDK 11

**Comment by Arshardh** [comment]
The two roles we have mentioned there is an OR condition and not an AND. Therefore a user having one of the two scopes is sufficient to access the API.
