### ISSUE TITLE
Use Github Issues Template in bug report template

### ISSUE THREAD

**Issue by tmkasun** [wso2/api-manager#154]
### Describe your solution
Simplified bug reporting form

Github docs related to `Github Issues Template Forms`

- [Syntax](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
- [Configuring issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

Example: https://github.com/gatsbyjs/gatsby/issues/new?assignees=&labels=type%3A+bug&template=BUG_REPORT.yml

**Comment by binodmx** [comment]
Issue form is already implemented for reporting a bug scenario.

Link: https://github.com/wso2/api-manager/issues/new?assignees=&labels=Priority%2FNormal%2CType%2FBug&template=issue_form.yml
