### ISSUE TITLE
Artifacts are not editable using ManagementConsole

### ISSUE THREAD

**Issue by asithamadhushanka12** [wso2/api-manager#1542]
### Description

Hi Team,

In EI 6.6.0 Update level 144 we cannot edit below Artifacts that deployed from a car file through the console.

-MessageProcessors.
-MessageStores.
-Templates.
-Sequences.
-Endpoints.
-Local entries.

### Steps to Reproduce

Deploy a car file that includes above Artifacts and try to edit the above Artifacts through the console.

### Affected Component

MI

### Version

EI 6.6.0

### Suggested Labels

EI 6.6.0

**Comment by YasasRangika** [comment]
This issue has already been fixed in the master branch.
