### ISSUE TITLE
Disabling self signup not migrated from 2.6.0 to 4.2.0

### ISSUE THREAD

**Issue by binodmx** [wso2/api-manager#1544]
### Description

Disabling self signup configs are not migrated properly from 2.6.0 to 4.2.0.

### Steps to Reproduce

1. Disable self signup in API-M 2.6.0 as in [docs](https://apim.docs.wso2.com/en/latest/reference/customize-product/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup/).
2. Migrate API-M to 4.2.0.
3. You can observe that self signup is enabled.

### Affected Component

APIM

### Version

4.2.0

**Comment by Lakith-Rambukkanage** [comment]
resolved by : https://github.com/wso2-enterprise/migration-docs/pull/115
