### ISSUE TITLE
SOAP to REST API publisher notification improvement

### ISSUE THREAD

**Issue by lkokila** [wso2/api-manager#1545]
### Problem

The publisher shows the following message when we try to create SOAP APIs (using WSDL). 

<img width="707" alt="Screenshot 2023-03-02 at 15 17 05" src="https://user-images.githubusercontent.com/5971789/222393220-33c01c32-31a7-4c50-ab9e-b7aa1bab0a67.png">

This is valid for the "Generate REST APIs" option. For passthrough (passing through SOAP messaging instead of JSON), since the API Manager doesn't do any mediation, this might not be relevant. Even with Passthrough, with the API Management features, there can be use cases we can address through the API Manager. 

### Solution

Suggest providing this notification only when someone selects the "Generate REST APIs" option. 

### Affected Component

APIM

### Version

4.2.0-Beta

### Suggested Labels

Affected/4.2.0-Beta

**Comment by lkokila** [comment]
The message has been updated through U2 as follows. 

![Screenshot 2023-08-04 at 11 50 54](https://github.com/wso2/api-manager/assets/5971789/99f7be8a-10cf-4a25-8590-cb2dcde19e94)

**Comment by GihanAyesh** [comment]
Fixes with the PR: https://github.com/wso2/apim-apps/pull/488
