### ISSUE TITLE
[APIM 4.0.0] - UserInfo endpoint returns "application/octet-stream" content type in error scenarios

### ISSUE THREAD

**Issue by sarindufit** [wso2/api-manager#155]
### Description

IIn success scenarios, "/userinfo" endpoint returns a JSON response with the Content-Type header set to "application/json". However, in failure scenarios (omitting Authorization header), the error response comes in JSON format, but with the Content-Type header set to "application/octet-stream". 

Note that this behavior can be recreated only in a U2 updated pack, and it cannot be observed in the vanilla pack. It can be reproduced with the latest U2 level (110). 

### Steps to Reproduce

1. Update APIM 4.0.0 to U2 level 110. 

2. Call the /userinfo endpoint without the Authorization header

### Affected Component

APIM

### Version

4.0.0

**Comment by chamilaadhi** [comment]
@prasa7 can you add the public pr as well please

**Comment by prasa7** [comment]
Hi @chamilaadhi ,

Please find the public PR https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1853
