### ISSUE TITLE
[SMPP-Connector-1.0.6] Invalid session handling issues

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/api-manager#1552]
### Problem

We have identified the below issues on handling invalid sessions.

1. When the session is in the CLOSED state the session is not null but the session is not bound. After the initial session we added to the session list, goes to the CLOSED state, each request will create a new session and the CLOSED session is in the ESTABLISHED state from the MI server side.

Solution: If the session is not null but not bound, call unbind()[2] method and create a new session

2. A SMPP session has three session states isBound(), isTransmittable() and isReceivable()[3]. Even though a session is bound, the session can be not transmittable and receivable. Therefore we need to reuse the session only if the session is bound, transmittable, and receivable.

We are facing the below error and during this time we can see multiple connections to the SMPP server exceeding the limit of the SMPP server session limit. ,

### Solution

Check the possibility of fixing the issues

### Affected Component

MI

### Version

4.1.0

**Comment by YasasRangika** [comment]
This issue has already been addressed in the master branch.
