### ISSUE TITLE
In Seperated GWs setup, only one GW can respond to newly added resources of API product

### ISSUE THREAD

**Issue by ksankeerth** [wso2/api-manager#1553]
### Description

- APIKeyValidator.getAPIProductURITemplates checks for the URI templates from the local entry swagger. However, the URI templates can be retrieved from the SubscriptionDataStore (in memory maps in API Gateway). In that way, we can remove the dependency in gateway for the local entry of API products as similar to APIs. 

- In API product update flow, the swagger which get saved in the local entry contains the old swagger.We call the updateAPIProductSwagger() after publishing to gateway with the old swagger. Inside updateAPIProductSwagger, after saving the swagger registry, it is published directly to Gateway as a synapse artifact .without saving in the DB as an GatewayArtifactDTO. Hence, in a scenario like in above comments (two node deployment) where GW relies on the event hub to retrieve the synapse artifact, the local entry does not get updated. Even though reported issue get fixed with first fix, features like Schema validation will still fail in similar deployments as updated swagger is not present in the local entry of the other gateway. 

### Steps to Reproduce

Steps to reproduce :

- Creats a setup : 2 CP nodes (active active) and 2 GWs (active active) (attached configs)

- Create an API product with resources

- Add new resources to API product

- Only one GW will be able to respond to requests to newly added resource (even after restart)

### Affected Component

APIM

### Version

3.2.0

**Comment by imsuneth** [comment]
Closing as completed 
Master fix: https://github.com/wso2/carbon-apimgt/pull/11928
