### ISSUE TITLE
Changes in Service Provider Listing in Carbon Console from 3.2.0 to 4.1.0 

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/api-manager#1556]
### Problem

Hi Team,

This is regarding the change from APIM 3.2.0 to 4.1.0 when listing the service providers and searching where we have replaced the SP name with its UUID.
218111027-468cde04-a746-43cc-9551-0537e38f1b6d

![image](https://user-images.githubusercontent.com/30020227/223348000-8090abab-8167-4527-9bd7-de52bb24338a.png)

When migrating APIM 3.2.0 to 4.1.0,  currently we have no way of identifying the applications in a logical manner or searching it with their name and even though the search box mentions search by name pattern, it's working only for the service provider ID only.

Product : wso2am-4.1.0

### Solution

N/A

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
As marked in the linked internal issue, this does not apply to the master branch.
