### ISSUE TITLE
Cannot publish Custom Analytics Events Data

### ISSUE THREAD

**Issue by dimuthnc** [wso2/api-manager#1569]
### Description

In APIM 4.2.0-RC, we cannot publish additional data elements using [this](https://apim.docs.wso2.com/en/latest/api-analytics/samples/publishing-custom-analytics-data/#!a) extension point. 

In APIM 4.1.0 and older versions, when [this](https://apim.docs.wso2.com/en/latest/api-analytics/samples/publishing-custom-analytics-data/#!) was correctly configured, we could see the additionally published data elements in the properties element inside the event as shown below. 

<code>
event: 
 {
    "apiName":"API1",
    "proxyResponseCode":200,
    "destination":"https://run.mocky.io/v3/d14fad1d-d57b-41bc-8be3-146b6aaddfaf",
    "apiCreatorTenantDomain":"carbon.super",
    "platform":"Linux",
    "apiMethod":"GET",
    "apiVersion":"2.0.0",
    "gatewayType":"SYNAPSE",
    "apiCreator":"admin",
    "responseCacheHit":false,
    "backendLatency":1866,
    "correlationId":"00a94b54-5579-4f5d-95c1-4bd909fd4c20",
    "requestMediationLatency":578,
    "keyType":"SANDBOX",
    "apiId":"fd5a22ee-144f-4fc1-9f22-ce5ff0382023",
    "applicationName":"AppUser",
    "targetResponseCode":200,
    "requestTimestamp":"2022-07-18T06:49:19Z",
    "applicationOwner":"admin",
    "userAgent":"Chrome",
    "eventType":"response",
    "apiResourceTemplate":"/test",
    "properties":{
         "tokenIssuer":"https://localhost:9443/oauth2/token",
         "apiContext":"/api1/2.0.0",
         "userName":"admin@carbon.super"
    },
    "responseLatency":2446,
    "regionId":"default",
    "responseMediationLatency":2,
    "userIp":"127.0.0.1",
    "applicationId":"5d6d0135-810a-4b4e-8f9a-45187e943fff",
    "apiType":"HTTP"
 }

</code>

The same was tried for APIM 4.2.0-RC, and therefore the data is persisted to a log file. But when we look at the log file, we cannot locate the additional data elements or the properties field even in the event. ( Refer to the below log extracted from the logs
<code>
{
   "apiName":"PizzaShackAPI",
   "proxyResponseCode":201,
   "destination":"https://localhost:9443/am/sample/pizzashack/v1/api/",
   "apiCreatorTenantDomain":"carbon.super",
   "platform":"Mac OS X",
   "apiMethod":"POST",
   "apiVersion":"1.0.0",
   "gatewayType":"SYNAPSE",
   "apiCreator":"admin",
   "responseCacheHit":false,
   "backendLatency":9,
   "correlationId":"c43d75da-bddc-4458-b3db-48a1bc2e0456",
   "requestMediationLatency":3,
   "keyType":"SANDBOX",
   "apiId":"d81e12b0-cc44-4fce-bd6a-9762bbfe9cbf",
   "applicationName":"TestApp",
   "targetResponseCode":201,
   "requestTimestamp":"2023-03-08T09:20:48.427Z",
   "applicationOwner":"admin",
   "userAgent":"Chrome",
   "userName":"admin@carbon.super",
   "apiResourceTemplate":"/order",
   "regionId":"default",
   "responseLatency":14,
   "responseMediationLatency":2,
   "userIp":"127.0.0.1",
   "apiContext":"/pizzashack/1.0.0",
   "applicationId":"f410b861-63a7-48dd-a2c2-cfdcc5d2bfde",
   "apiType":"HTTP"
}
</code>
### Steps to Reproduce

Mentioned above

### Affected Component

Analytics

### Version

4.2.0-RC

### Environment Details (with versions)

Mentioned above

### Relevant Log Output

```shell
Mentioned above
```

### Related Issues

Mentioned above

**Comment by chamilaadhi** [comment]
Issue is happening due to properties getting dropped from the filtered event map in https://github.com/wso2/apim-analytics-publisher/blob/main/component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/elk/ELKMetricEventBuilder.java#L58 . As a solution, introduce a new eventscheme similar to https://github.com/wso2/apim-analytics-publisher/blob/main/component/publisher-client/src/main/java/org/wso2/am/analytics/publisher/reporter/GenericInputValidator.java#L69 which contains `properties` and use it with ELKMetricEventBuilder

**Comment by chamilaadhi** [comment]
@YasasRangika  Please check this https://github.com/wso2/apim-analytics-publisher/pull/94 as well. This might fix the issue

**Comment by YasasRangika** [comment]
Merged the PR: https://github.com/wso2/apim-analytics-publisher/pull/96 to fix this issue.
