### ISSUE TITLE
Unable to logout of the admin console after a fresh start.

### ISSUE THREAD

**Issue by janithcmw** [wso2/api-manager#1571]
### Description

Once log in to the 'admin' portal after a restart of the APIM server, it is not possible to log out. There will be an auto-re-login task once the logout task was triggered.log in

### Steps to Reproduce

1. Enable SSO with IS-5.6.0 and APIM-2.5.0 for 'admin' portal in 'SP initiated' mode.
2. Log in to the 'admin' portal in the 1st place.
3. Then try to log out.

### Affected Component

APIM

### Version

2.5.0

### Environment Details (with versions)

N/A

**Comment by dulithsenanayake** [comment]
Closing this as the update is released.
