### ISSUE TITLE
Add audit log improvements

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#1589]
### Description

Need to improve audit logging in the product for the following.

1. Add audit logs for creation or modification of a policy which includes,
              - Rate limiting policies (Creation, Application of the policy to an API, Update)
              - Scopes
              - Mediation policies (Creation, Application of the policy to an API, Update)
2. Transmission(deployment) of policies to the Gateway
              - Need to be handled through API update events
              - Send ACK to PM when Gateway receives policies
3. Audit logging for several management operations.

### Affected Component

APIM

### Version

4.2.0

**Comment by Arshardh** [comment]
Update [14/03/2023]:

The log addition task is completed. I am working on finding any other places we have missed. I will be sending the PR once it is cleared.

**Comment by Arshardh** [comment]
Update [20/03/2023]:

I added new logs to confirm log deployments in the gateway via the event hub, which will adequately tell if a policy or a scope is updated in a particular gateway environment. I am testing the whole flow atm.

**Comment by YasasRangika** [comment]
Public fix PR: https://github.com/wso2/carbon-apimgt/pull/11940
