### ISSUE TITLE
Missing Jars in gateway-worker bundles.info

### ISSUE THREAD

**Issue by damoebius** [wso2/api-manager#159]
### Description

The following issue occurs when schema validation is enabled in a distributed setup.

`java.lang.ClassNotFoundException: io.swagger.util.Json cannot be found by swagger-request-validator-core_2.12.1.wso2v2`

### Steps to Reproduce

1. Get API Manager 4.0.0 pack.
2. Set a distributed deployment locally with 1 control plane and 1 gateway with a RDBMS.
3. Import the API that the customer provided on the ticket and set a mock endpoint.
4. If is disable, enable the schema validation for the API.
5. Make a request to a resource of the API.

I managed to copy repository/components/**default**/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info to repository/components/**gateway-worker**/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info and it fix the issue.

### Affected Component

APIM

### Version

4.1.0

### Environment Details (with versions)

Env (Docker/K8s):

### Related Issues

https://github.com/wso2/product-apim/issues/12815

**Comment by chamilaadhi** [comment]
@damoebius thanks for reporting this. Need to add following entries to repository/components/gateway-worker/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info file as a workaround. 

```
io.swagger.annotations,1.6.5,../plugins/io.swagger.annotations_1.6.5.jar,4,true
io.swagger.core,1.6.5,../plugins/io.swagger.core_1.6.5.jar,4,true
```
We will add this fix to the next release
