### ISSUE TITLE
Handle communication failures between CP and GW for proper policy enforcement.

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#1590]
### Description

We need to handle communication failures between the Control plane and Gateway for proper policy enforcement.

### Affected Component

APIM

### Version

4.2.0

**Comment by Arshardh** [comment]
[Update 20/03/2023]:

Subsequent to an analysis I found out that it is possible to implement a system to pull updates once a reconnection has occurred. We updated Udith about the matter and once this is cleared with JSEC, we can finalize this.

**Comment by Arshardh** [comment]
[Update 25/03/2023]:

Started implementing the repopulation mechanism for subscriptions and other data that the GW requires

**Comment by Arshardh** [comment]
[Update 03/04/2023]:

All implementations are completed for both GW maps and gateway runtime artifacts. Had to do some refactoring to improve performance of these operations. ATM, I am testing these flows rigorously to find probable issues that can crop up. Planning to have a review soon, along with Sahan's feature.

**Comment by Arshardh** [comment]
[Update 12/04/2023]

Had to change the recalling mechanism so that it is extensible, using a new interface. This will ensure code clarity and the chance to write extensions if necessary.
Changed the recalling implementation to be async.

**Comment by Arshardh** [comment]
[Update 20/04/2023]

Waiting for the code to be properly reviewed by multiple parties before shipping an update, considering this is a vital feature change.

**Comment by YasasRangika** [comment]
Public fix PR: https://github.com/wso2/carbon-apimgt/pull/12180
