### ISSUE TITLE
Fixes related to smb2, ftp and sftp concurrency issues not available in MI 1.2.0 

### ISSUE THREAD

**Issue by VinulaUthsara** [wso2/api-manager#1595]
### Description

Fixes related to the commits [1] are not available in the latest versions of MI 1.2.0. We have verified this against the change-log and source code with tag: [v2.2.0-wso2v8.10](https://github.com/wso2-support/wso2-commons-vfs/tree/v2.2.0-wso2v8.10).

[1] https://github.com/wso2/wso2-commons-vfs/pull/103/commits

### Steps to Reproduce

- Get an MI 1.2.0 pack U2 level: 119
- Start the MI pack using sh micro-integrator.sh -DosgiConsole
- Check the jar version commons-vfs2_2.2.0.wso2v8_10 using "ss vfs"
- Check out the tag: v2.2.0-wso2v8.10
- Check for the changes in commits in [1]

[1] https://github.com/wso2/wso2-commons-vfs/pull/103/commits

### Affected Component

MI

### Version

1.2.0

**Comment by YasasRangika** [comment]
Public PRs:
https://github.com/wso2/wso2-synapse/pull/2003
https://github.com/wso2/wso2-commons-vfs/pull/103
have already been merged.
