### ISSUE TITLE
WSO2 Secure Vault - Password containing special characters such as [ ] and @

### ISSUE THREAD

**Issue by dilshanfa** [wso2/api-manager#1603]
### Description

We are using Secure vault to encrypt the passwords in deployment.toml and we had the passwords rotated recently. The passwords has special characters mixture of [] and &#64; symbols such as 
K]E&#614;3VDn[9[abc]n   <br />(The above is just an example similar to the actual password) </p>

### Steps to Reproduce

1. Configure these entires in deployment.toml 
```
[super_admin]
username = "admin"
password="$secret{admin_password}"
create_admin_account = true

At the end of the file configure the password as well.

[secrets]
admin_password       = "[K]E&#614;3VDn[9[abc]n]"

```
2. Run the chipper tool

### Affected Component

APIM

### Version

wso2am-4.1.0

**Comment by YasasRangika** [comment]
This issue has already been resolved in the master branch.
