### ISSUE TITLE
Endpoint security is not working with API Product

### ISSUE THREAD

**Issue by selakap** [wso2/api-manager#1605]
### Description

Endpoint security (basic auth) is not working with API Product in wso2 APIM 3.0.0

### Steps to Reproduce

Latest update APIM 3.1.0.124

- Create 2 APIs (new1, new2) with endpoint basic security.
Username: selaka
Password:wso2123

In synapse artefact of those APIs
`<property name="Authorization" expression="fn:concat('Basic ', 'c2VsYWthOndzbzIxMjM=')" scope="transport"/>`

Basic Header:
selaka:wso2123

- Create an API product using the above APIs resource
    But in the product's API artefact, I could find the header
    `<property name="Authorization" expression="fn:concat('Basic ', 'c2VsYWthOnNlbGFrYQ==')" scope="transport"/>`

Basic Header:
selaka:selaka

Therefore on the BE side, the basic auth validation is failing.

### Affected Component

APIM

### Version

3.0.0

**Comment by dulithsenanayake** [comment]
Closing this since this is fixed with the master PR[1].
[1]: https://github.com/wso2/carbon-apimgt/pull/9285
