### ISSUE TITLE
Invalid expiration time shown under publisher tryout console token when server is running on a different timezone

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/api-manager#1606]
### Description

Setup apim on a server which is running on a different time zone

Check API and API product tryout console.  It says 17 hours

<img width="846" alt="Screenshot 2023-03-13 at 1 08 09 PM" src="https://user-images.githubusercontent.com/4861150/224637125-2de479d7-2d49-4c64-9ebe-00359b6309a1.png">

**Comment by BiyonFernando** [comment]
The JWT token generated in the tryout console has an expiration time of 17 hours, as shown on the page. Since JWT uses Unix Timestamp, timezones do not impact the expiration time.
