### ISSUE TITLE
Testing 4.2.0 Docker Images on Apple Intel Processor

### ISSUE THREAD

**Issue by prasa7** [wso2/api-manager#1617]
### Description

This is to track testing progress of 4.2.0 Docker Images in [1] on Apple Intel Processor

- [x] jdk17/centos
- [x] jdk17/ubuntu
- [x] jdk17/alpine
- [x] jdk11/centos
- [x] jdk11/ubuntu
- [x] jdk11/alpine

MI 4.2.0 Docker Images in [2] in Apple Intel Processor

- [x] centos
- [x] ubuntu
- [x] alpine

MI Dashboard 4.2.0 Docker Images in [2] in Apple Intel Processor

- [x] centos
- [x] ubuntu
- [x] alpine

SI 4.2.0 Docker Images in [2] in Apple Intel Processor
- [x] centos
- [x] ubuntu
- [x] alpine

[1] https://github.com/wso2/docker-apim/tree/4.2.x/dockerfiles/
[2] https://github.com/wso2/docker-ei/tree/4.2.x/dockerfiles

APIM version change to rc2 by https://github.com/wso2/docker-apim/pull/481

### Affected Component

APIM , MI , MI Dashboard, SI

### Version

4.2.0

**Comment by prasa7** [comment]
Tested the following images. 
<img width="705" alt="Screenshot 2023-03-15 at 02 01 06" src="https://user-images.githubusercontent.com/805274/225131442-4ffdac22-7411-488c-a326-8fca49efd26e.png">

**Comment by prasa7** [comment]
@chanaka3d 

<img width="1555" alt="Screenshot 2023-03-15 at 02 39 09" src="https://user-images.githubusercontent.com/805274/225136980-0c0c95db-c080-48ca-ac30-230a56fbc631.png">
<img width="1558" alt="Screenshot 2023-03-15 at 02 39 00" src="https://user-images.githubusercontent.com/805274/225137004-474f24e8-db7e-436d-b931-137527dea58b.png">
<img width="511" alt="Screenshot 2023-03-15 at 02 38 45" src="https://user-images.githubusercontent.com/805274/225137011-af614272-b153-480b-af75-a70d39166b4f.png">
<img width="1670" alt="Screenshot 2023-03-15 at 02 38 39" src="https://user-images.githubusercontent.com/805274/225137016-14d2b21b-0614-4583-bf34-dad41d275656.png">

**Comment by chanaka3d** [comment]
Can you share a HAR or the browser console output if it has any errors?

**Comment by prasa7** [comment]
The issue was resolved after updating the safari browser to 15.6.1

**Comment by prasa7** [comment]
All the following docker images are working fine with Apple intel processor. @chamilaadhi 


<img width="683" alt="Screenshot 2023-03-23 at 12 33 46" src="https://user-images.githubusercontent.com/805274/227128709-3404ff31-ac00-43e7-a309-bd53808c52eb.png">
