### ISSUE TITLE
bin/chpasswd.sh script isa not wrking

### ISSUE THREAD

**Issue by asithamadhushanka12** [wso2/api-manager#1624]
### Description

 In MI the chpasswd.sh script is failing with the attached error even after installing Ant.
```
Buildfile: MI_HOME/bin/build.xml
[taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.

setup:
   [copy] Copying 28 files to MI_HOME/wso2/lib
   [mkdir] Created dir: ] MI_HOME/wso2/tmp/setup
   [delete] Deleting directory MI_HOME/wso2/tmp/setup
   [move] Moving 59 files to MI_HOME/wso2/lib


BUILD SUCCESSFUL
Total time: 0 seconds
Error: Could not find or load main class org.wso2.carbon.core.util.PasswordUpdater
```

### Steps to Reproduce

- Install the ant
- Then navigate to the MI_HOME/bin using terminal
- Execute the below command
- sh chpasswd.sh -U admin -P admin
- Then response as below

### Affected Component

MI

### Version

4.1.0

**Comment by YasasRangika** [comment]
Public fixes:
https://github.com/wso2/product-ei/pull/5592
https://github.com/wso2/micro-integrator/pull/2901
have already been into the master branch.
