### ISSUE TITLE
Not throwing errors when deploying an API with invalid characters in the context

### ISSUE THREAD

**Issue by BLasan** [wso2/api-manager#1629]
### Description

If we create an API with a context consisting of a special character ("test`"), it allows to deploy the API into the gateway without any issue (refer to figure1). However, if we try to invoke the API, it logs the following error[1] in the console and returns a `404` error[2] mentioned as below.

[1] `[2023-03-19 10:56:48,497]  INFO - LogMediator STATUS = Message dispatched to the main sequence. Invalid URL., RESOURCE = /test%60/20/*, HEALTH CHECK URL = /test%60/20/*`

[2] `{"code":"404","type":"Status report","message":"Not Found","description":"The requested resource is not available."}% `

![Screenshot 2023-03-19 at 11 06 58](https://user-images.githubusercontent.com/43112139/226155951-42e1feee-43e1-4417-9430-3a90ff9fe243.png)

### Steps to Reproduce

1. Create an API with the context "test`".
2. Deploy the API
3. Invoke the API from the try out console in Publisher portal

### Affected Component

APIM

### Version

4.2.0-rc-2

**Comment by nisan-abeywickrama** [comment]
This issue has been resolved by the following PRs,

- https://github.com/wso2/apim-apps/pull/453
- https://github.com/wso2/apim-apps/pull/480
- https://github.com/wso2/carbon-apimgt/pull/12073
