### ISSUE TITLE
[APIM-4.0.0] API Product creation is not importing nested referenced schema

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/api-manager#163]
### Description

When an API swagger has nested schema references and if an API Product is created using API resources, those nested schema are not available in the generated API Product swagger.

### Steps to Reproduce

1. Create and publish an API with a swagger having nested schema.
2. Create an API Product including the resources that use nested schema.
3. Go to the Resources section of the API Product from the publisher.
4. An error will be displayed mentioning the reference does not exist.

### Affected Component

APIM

### Version

4.0.0

**Comment by vithu30** [comment]
Fixed in master with https://github.com/wso2/carbon-apimgt/pull/10583
