### ISSUE TITLE
Token Call is failing without Content-Type after U2 update

### ISSUE THREAD

**Issue by JanithaSampathBandara** [wso2/api-manager#1633]
### Description

Customer has recently migrated to U2 from WUM and after the update, they are observing token requests are failing in the production where clients invoke the /token without the content type.

### Steps to Reproduce

1. Get apim 2.0.0 pack with the customer's U2 level 17
2. Invoke the token API without Content-Type
3. Response returned from the key manager with 415 unsupported media type

We already have fixed this and backported it to a few versions.

The commit: https://github.com/wso2/product-apim/issues/3773
The fix is checking th existence of the Content-Type and appending the Content-Type at the SynapsePropertiesHandler

Can we backport the same and provide a hot-fix for the production?

### Affected Component

APIM

### Version

2.0.0

**Comment by dulithsenanayake** [comment]
Closing this since this is already fixed.
