### ISSUE TITLE
Unable to add API specific policy using YAML format via Publisher REST API

### ISSUE THREAD

**Issue by ug205** [wso2/api-manager#1635]
### Description

Unable to add an API specific policy through the publisher rest api as provided in the documentation[1] when using YAML format.
[1].https://apim.docs.wso2.com/en/latest/reference/product-apis/publisher-apis/publisher-v3/publisher-v3/#tag/API-Operation-Policies/operation/addAPISpecificOperationPolicy

### Steps to Reproduce

Start APIM Server.
Create an API.
Try to add the policy as below for the API_ID using policySpecFile=@setHeader.yaml and  policyDefinitionFile=@setHeader.j2 , policy spec file in YAML.

`curl -k -H "Authorization: Bearer ae4eae22-3f65-387b-a171-d37eaa366fa8" -H "Content-Type: multipart/form-data" -F policySpecFile=@setHeader.yaml -F policyDefinitionFile=@setHeader.j2 "https://127.0.0.1:9443/api/am/publisher/v3/apis/96077508-fd01-4fae-bc64-5de0e2baf43c/operation-policies"`

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
Need to merge the public fix: https://github.com/wso2/product-apim/pull/13191
