### ISSUE TITLE
Database call logs cannot be found in Correlation logs in APIM 4.1.0 

### ISSUE THREAD

**Issue by ug205** [wso2/api-manager#1641]
### Description

The Database call logs cannot be found in Correlation logs in APIM 4.1.0 as given in this documentation [1].
[1]. https://apim.docs.wso2.com/en/latest/observe/api-manager/monitoring-correlation-logs

### Steps to Reproduce

Start the server with flag -DenableCorrelationLogs=true

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
Closing this issue since the master fix has already been added.
