### ISSUE TITLE
TryIt console is not working 

### ISSUE THREAD

**Issue by lasanthaS** [wso2/api-manager#1642]
### Description

When trying to test a proxy service in the TryIt console in EI 6.6.0, the UI is broken and not working as expected.

### Steps to Reproduce

1. Login to the Carbon Portal.
2. Go to a proxy services list and select a proxy service and click "Try this service".
3. The TryIt console is broken and not working as expected.

### Affected Component

MI

### Version

EI-6.6.0

### Suggested Labels

bug

**Comment by YasasRangika** [comment]
This issue has already been resolved in the master branch.
