### ISSUE TITLE
[APIM-4.1.0] [APIM-4.0.0]  Migrated subscription plans are not visible for Websocket APIs 

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/api-manager#165]
### Description

Subscription plans in Websocket APIs prio to APIM-4.0.0 are not visible after APIM-4.0.0/4.1.0 migration. 

### Steps to Reproduce

1. Attach a **custom/unlimited subscription policy** to Websocket API in API-Manager prior to 4.0.0
2. Execute migration process
3. Check the subscription policies in a Websocket API. only async policies are visible.
<img width="1016" alt="Screen Shot 2022-06-06 at 9 00 24 PM" src="https://user-images.githubusercontent.com/29066805/172549647-85685a61-c1ba-4dd1-879c-aeed0ade542f.png">

### Affected Component

APIM

### Version

5.0.0/4.1.0

### Suggested Labels

**Comment by chameerar** [comment]
This is fixed in https://github.com/wso2/apim-apps/pull/315
