### ISSUE TITLE
User having required role and permissions is not allowed to invoke admin APIs

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/api-manager#1650]
### Description

When invoking an Admin services from an existing user who is having required role is failing. However, this admin call will be successful after we load/access the permissions of the particular role from the UI. Please find the steps to reproduce below.

### Steps to Reproduce

1. Create an Application role named test1(Application/test1) and set the permission "Admin Permission>Manage>Mediation"
2. Create an user user1 and assigned the role Application/test1
3. Try invoking the curl request from an existing user1.

`curl -vk https://localhost:9443/services/MessageProcessorAdminService.MessageProcessorAdminServiceHttpsSoap11Endpoint --header "Authorization: Basic <Base64EncodedUsernameAndPassword> --header "SOAPAction: \"urn:isActive\"" --header "Content-type: text/xml" --data "@test.xml"`

test.xml content is as follows
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.synapse/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <xsd:isActive>
         
         <xsd:processorName>ProcessorName</xsd:processorName>
      </xsd:isActive>
   </soapenv:Body>
</soapenv:Envelope>

Invoke the admin service from an existing user who is having required role assigned but failing to invoke.

4. Now if we load/access the permission tree of the particular role from the UI and try invoking same then it will allowing us to invoke it.
5. If you restart the server and try invoking it then it will not allowing again.

### Affected Component

MI

### Version

6.6.0

**Comment by YasasRangika** [comment]
This issue does not affect the master branch.
