### ISSUE TITLE
WSO2-Entrprise Integrator - v 7.1.0

### ISSUE THREAD

**Issue by sundeeptj-tonik** [wso2/api-manager#1655]
### Description

unable to find valid certification path to requested target.

"ErrorDetail": "javax.net.ssl.SSLHandshakeException: General SSLEngine problem\n\tat sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1521)\n\tat sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:528)\n\tat sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1197)\n\tat sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1165)\n\tat javax.net.ssl.SSLEngine.wrap(SSLEngine.java:469)\n\tat org.apache.http.nio.reactor.ssl.SSLIOSession.doWrap(SSLIOSession.java:220)\n\tat org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:254)\n\tat org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:391)\n\tat org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:119)\n\tat org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)\n\tat org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)\n\tat org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)\n\tat org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)\n\tat org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)\n\tat org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:584)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem\n\tat sun.security.ssl.Alerts.getSSLException(Alerts.java:192)\n\tat sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1709)\n\tat sun.security.ssl.Handshaker.fatalSE(Handshaker.java:318)\n\tat sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)\n\tat sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)\n\tat sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)\n\tat sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)\n\tat sun.security.ssl.Handshaker$1.run(Handshaker.java:970)\n\tat sun.security.ssl.Handshaker$1.run(Handshaker.java:967)\n\tat java.security.AccessController.doPrivileged(Native Method)\n\tat sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1459)\n\tat org.apache.http.nio.reactor.ssl.SSLIOSession.doRunTask(SSLIOSession.java:238)\n\tat org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:276)\n\t... 9 more\nCaused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\n\tat sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)\n\tat sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)\n\tat sun.security.validator.Validator.validate(Validator.java:262)\n\tat sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)\n\tat sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:289)\n\tat sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)\n\tat sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1626)\n\t... 17 more\nCaused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\n\tat sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)\n\tat sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)\n\tat java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)\n\tat sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)\n\t... 23 more\n"

### Steps to Reproduce

<profile>
    <servers>XX.XX.XXX.XX:XX</servers>
    <TrustStore>
        <Location>repository/resources/security/MyTrustStore.jks</Location>
        <Type>JKS</Type>
        <Password>123456</Password>
    </TrustStore>
</profile>

Kindly keep this in the senderprofile.xml

### Affected Component

MI

### Version

7.1.0

**Comment by nandika** [comment]
Please try the latest MI version and see if this issue is resolved

**Comment by sundeeptj-tonik** [comment]
Issue resolved configuration was missing in the AWS outgoing requests

**Comment by YasasRangika** [comment]
closing as per the https://github.com/wso2/api-manager/issues/1655#issuecomment-1512799717
