### ISSUE TITLE
[Feature] Custom API key header support

### ISSUE THREAD

**Issue by IsuruMaduranga** [wso2/api-manager#1672]
### Problem

This feature intends to implement support for using custom header names for api-key header. Currently `api-key` is the standard header name.

### Solution
Implementation functionality similar to Oauth token header https://apim.docs.wso2.com/en/latest/design/api-security/api-authentication/secure-apis-using-oauth2-tokens/#customizing-the-authorization-header

**Comment by chamilaadhi** [comment]
@IsuruMaduranga as the first step, lets get the basic flow working. you could breakdown the tasks as following

1	Add a new element to Rest API payload 
	2	Read from api payload from the update api call (PUT apis/{uuid}) and save it in the registry (read from config or registry can be done later)
	3	Return custom head from rest api GET apis/{uuid} call 
	4	Set new header as a property to apiauthenticationhandler 
	5	Feed the custom header to APIkeyauthenticator inside the apiauthenticationhandler 
	6	Invoke api (using curl) with the custom header
