### ISSUE TITLE
Problems when changing the app owner of an application

### ISSUE THREAD

**Issue by chaveeka** [wso2/api-manager#1673]
### Description

When trying to change the ownership of an application from the admin console, the following error is observed.

`ERROR - GlobalThrowableMapper User does not have scope. Username : B2E/87654321 Scope : apim:subscribe`

When multiple scope mappings are done through the Admin Console we could observe an additional space getting appended before the role name as below.

```
"RoleMappings": {
    "Internal/subscriber": "Internal/subscriber,B2E/ADAM_SUBSCRIBER, B2E/ADAM_SUB"
  }

```

Once we removed this space and tried out the same scenario, we could able to successfully change the ownership of the application.

### Steps to Reproduce

Reproducing Steps : APIM 4.0.0.155 and IS 5.11.0.201

1. Create a secondary user store which points to IS.
2. Create two users 12345678 and 87654321
3. Create two roles ADAM_SUBSCRIBER and ADAM_SUB
4. Assigned ADAM_SUBSCRIBER role to 12345678 user and ADAM_SUB role to 87654321 user.
5. Add scope assignment from admin console as below order.

```
     B2E/ADAM_SUBSCRIBER > Internal/subscriber
     B2E/ADAM_SUB > Internal/subscriber
```

6. Log into devportal using both users then created applications, generated keys and invoked sample API from both users.

```
     App Name                              App Owner


    12345678UserApp                   B2E/12345678


    87654321UserApp                   B2E/87654321
```

7. Tried to change ownership of 12345678UserApp application to B2E/87654321 user from the admin console.
Then observed the below error.

`ERROR - GlobalThrowableMapper User does not have scope. Username : B2E/87654321 Scope : apim:subscribe`

8. Navigated to **_Resource > Browse > /_system/config/apimgt/applicationdata/tenant-conf.json_** file and observed that additional space has been appended before to the role name as follows,

```
"RoleMappings": {
"Internal/subscriber": "Internal/subscriber,B2E/ADAM_SUBSCRIBER, B2E/ADAM_SUB"
}
```

9. Removed this additional space and tried again to change the ownership and was able to change successfully.

### Affected Component

APIM

### Version

4.0.0

**Comment by YasasRangika** [comment]
Need to merge master fix PR: https://github.com/wso2/carbon-apimgt/pull/12212
