### ISSUE TITLE
[APIM-4.0.0] Upgrade httpcore-nio to v4.4.15 to avoid CPU spike

### ISSUE THREAD

**Issue by Johnson66666** [wso2/api-manager#1675]
### Description

CPU getting spiked suddenly even with a very low load and never goes down. This results to a step by step CPU overload (20% then 40% etc until 100%), and the only thing to do about that is to restart the gateway.

This issue is known since [APIM-3.2.0](https://github.com/wso2/product-apim/issues/9685) as a httpcore-nio issue which causes [CPU leak](https://issues.apache.org/jira/browse/HTTPCORE-687?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel). It was resolved in httpcore-nio 4.4.15 version but APIM-4.0.0 still use httpcore-nio 4.4.14.

I found a link to download the last 4.4.x version [here](https://maven.wso2.org/nexus/content/repositories/releases/org/apache/httpcomponents/wso2/httpcore/4.4.15.wso2v1/) and pasted it in /repository/components/plugins folder. Now I want to manually patch APIM4.0.0 to use this httpcore-nio version instead of the buggy one.

**So my questions are :**
- Do I need to use httpcore 4.4.15 too if I use httpcore-nio 4.4.15 ?
- Which files do I need to modify to use v4.4.15 ? I found a file called repository/components/artifacts.xml, do I just need to replace the httpcore-nio version inside it ?

Any help would be very appreciated.

### Affected Component

APIM

### Version

4.0.0

### Environment Details (with versions)

- debian-11
- wso2am-4.0.0
- openjdk-11.0.2

### Related Issues

https://github.com/wso2/product-apim/issues/9685

**Comment by Johnson66666** [comment]
I replaced the three files impacted by 4.4.15 patch from 4.4.15 to 4.4.14 and re-created the 4.4.14 jar archive.
Here is a link if someone want to use it : https://filetransfer.io/data-package/btAL8nKz#link
Just rename it httpcore-nio_4.4.14.wso2v1.jar, overwrite the original one and restart.

**Comment by JollyGoal** [comment]
Hi @Johnson66666 ,
I'm having the same issue here with our production environment

Could you please share more in-depth instructions on resolving this issue or share needed jar files one more time? The link https://filetransfer.io/data-package/btAL8nKz#link seems expired.

More in-depth steps of issue resolution would be greatly appreciated :)
