### ISSUE TITLE
Monetization is getting disabled on the UI when updating an API

### ISSUE THREAD

**Issue by Thidasala** [wso2/api-manager#1682]
### Description

Following concerns are observed when we are trying to update a monetized API via publisher portal.

1. After updating a monetized API (Ex: Changing the endpoint) , “Enable Monetization” tick under the Monetization tab is getting disabled in publisher UI

<img width="622" alt="Screenshot 2023-03-29 at 15 58 14" src="https://user-images.githubusercontent.com/45654571/228735048-ffb57338-612e-4d72-a662-5be7b0df5d62.png">

2. When we enable the monetization for an API (Via the above screen) and click the save button, the UI does not render the saved information right back, we need to refresh the UI to reflect those changes.

### Steps to Reproduce

1. Enable monetization for the APIs with Stripe engine by referring to the documentation [1]
2. Check the “Enable Monetization” tick under the monetization tab in publisher (You can see that the monetization tick is enabled)
3. Update the endpoint of the particular API
4. Check the “Enable Monetization” tick again (You can see that the monetization tick is disabled)

[1]https://apim.docs.wso2.com/en/3.2.0/learn/api-monetization/monetizing-an-api/

### Affected Component

APIM

### Version

3.2.0.241

**Comment by GihanAyesh** [comment]
Closing the issue as the public fixes: https://github.com/wso2/carbon-apimgt/pull/11959, https://github.com/wso2/apim-apps/pull/460 are merged.
