### ISSUE TITLE
RabbitMQ-producer: message is not sent to correct queue/virtualhost

### ISSUE THREAD

**Issue by iloshinik** [wso2/api-manager#1685]
### Description

In MI 4.1.0, it is not possible to add the virtual host through deployment.toml file. Even if we add the virtual host, those changes are not reflected in the axis2.xml file. Due to this, every message is added to the default hostname rather than adding it to the correct hostname.

### Steps to Reproduce

Configure virtual host in RabbitMQ sender in MI 4.1.0.

### Affected Component

MI

### Version

4.1.0

**Comment by YasasRangika** [comment]
Public fix: https://github.com/wso2/micro-integrator/pull/2898 has already been into the master branch.
