### ISSUE TITLE
SSO fails with a 404 error in the MI-Dashboard 4.1.0

### ISSUE THREAD

**Issue by jichinthaka** [wso2/api-manager#1700]
### Description

while configuring the SSO in the MI-Dashboard 4.1.0, although we can login through the SSO process, finally we come for a blank page. 

### Steps to Reproduce

Furthermore, you were able to reproduce the same SSO issue with WSO2IS IDP.

### Affected Component

MIDashboard

### Version

4.1.0

**Comment by YasasRangika** [comment]
Public fix: https://github.com/wso2/product-mi-tooling/pull/355 has already been merged.
