### ISSUE TITLE
APIM 4.1.0-When searching for an API in the publisher, the image disappears

### ISSUE THREAD

**Issue by amiladeshapriya** [wso2/api-manager#1705]
### Description

When searching for an API in the publisher portal, the API thumbnail image disappears. Please refer to the below [1], [2] screenshots.

[1] [https://user-images.githubusercontent.com/82052036/228830725-25552a93-f4aa-4573-b757-920ed9b68e9c.png]
[2] [https://user-images.githubusercontent.com/82052036/228830738-75f81759-54ed-4bc9-b8f6-4a1baa90196c.png]

### Steps to Reproduce

- Update APIM 4.1.0 to the latest update level, start the server.
- Create an API in the Publisher portal providing an image for the thumbnail.
- Search the API using the search bar of publisher portal.

### Affected Component

APIM

### Version

4.1.0

**Comment by GihanAyesh** [comment]
Closing the issue as the the fix is released
