### ISSUE TITLE
Can't expand topics to display subtopics in Message Broker Topic List

### ISSUE THREAD

**Issue by Menuka-Senevirathne** [wso2/api-manager#1706]
### Description

We are currently experiencing an issue with the Topic List page in the Message Broker Manage Console where topics can't be expanded to display subtopics.

### Steps to Reproduce

1. In the Message broker web Management Console(https://localhost:9446/carbon), open the Topic List page.
2. Create a topic.
3. Create a subtopic underneath the first topic.
4. When you are returned to the Topic List page again, click on the plus sign to the left of the top-level topic, and nothing happens. (It should expand and list down the sub-topics)

### Affected Component

EI

### Version

EI 6.6.0 EI 6.3.0

**Comment by Lakith-Rambukkanage** [comment]
Public fix is N/A since EI public repo is not maintained anymore.
