### ISSUE TITLE
Cannot use json-eval() with Data Service Call mediator in the Integration Studio

### ISSUE THREAD

**Issue by amiladeshapriya** [wso2/api-manager#1707]
### Description

The `json-eval()`expression is not supported with the Data Service Call mediator.

<param evaluator="json" expression="json-eval($)" name="body_request"/>

![Screenshot 2023-03-31 at 7 34 27 PM](https://user-images.githubusercontent.com/82052036/229700567-b77da842-1965-43e4-a9ab-5945f4f120ab.png)

The above configuration is not getting saved with the Data Service Call mediator, and it is getting changed as below if we go to the Design View and back to the Source View.

![Screenshot 2023-03-31 at 7 34 44 PM](https://user-images.githubusercontent.com/82052036/229700669-b25df972-5afa-4921-915e-9531b4ddbf1b.png)

### Steps to Reproduce

- Configure a Data Service Call mediator with below config.
`<param evaluator="json" expression="json-eval($)" name="body_request"/>`
- Save the changes.
- Go to the Design view
- Go back to the Source view

### Affected Component

IntegrationStudio

### Version

8.1.0

**Comment by YasasRangika** [comment]
This issue has already been resolved in the master branch.
