### ISSUE TITLE
Update jsch library to the latest version in MI 1.2.0

### ISSUE THREAD

**Issue by iloshinik** [wso2/api-manager#1709]
### Description

The SFTP (jsch) library that is shipped with MI-1.2.0 is jsch_0.1.54.wso2v1.jar. But it seems that the latest is **jsch_0.1.55.wso2v1.jar** as published on the editor homepage [1] and also the maven repository [2].

Some issues can be observed with the current jsch library in the MI 1.2.0 as the specific encryption is not accepted with the usage of some SFTP servers which are resolved with the latest library version.

[1] http://www.jcraft.com/jsch/
[2] https://central.sonatype.com/artifact/com.jcraft/jsch/0.1.55/versions

### Steps to Reproduce

N/A

### Affected Component

MI

### Version

1.2.0

### Suggested Labels

mi

**Comment by malakaganga** [comment]
Fixed with 6932 in master already updated
