### ISSUE TITLE
Add health check support for MI Dashboard

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/api-manager#171]
### Describe your problem(s)
Currently, MI Dashboard does not provide an endpoint to perform health checks. This is a required feature as it is deployed in microservices and maintainers need to check the deployment status of the system.

### Describe your solution
Create a new endpoint on the MI Dashboard that responds with the current status of the deployment.

**Comment by madushadhanushka** [comment]
Resolution/Fixed

**Comment by 1akshitha** [comment]
Hi @madushadhanushka ,

Have we updated the documentation regarding this improvement? 

Thanks,
Lakshitha

**Comment by madushadhanushka** [comment]
Added documentation with https://github.com/wso2/docs-apim/pull/6019
