### ISSUE TITLE
Multi Endpoint Configuration from api_params.yaml

### ISSUE THREAD

**Issue by BLasan** [wso2/api-manager#172]
Description:
When importing an API using the API Controller, there is a requirement of mentioning multiple endpoints in the api_params.yaml file to handle the load balancing and failover scenarios with relevant configurations, as the publisher portal already supports those.

Suggested Assignees:
@BLasan 

Affected Product Version:
APICTL 3.1

Related PRs:
[product-apim-tooling-917](https://github.com/wso2/product-apim-tooling/pull/917)
[product-apim-tooling-918](https://github.com/wso2/product-apim-tooling/pull/918)

**Comment by BLasan** [comment]
@wasuradananjith please close the issue with a comment

**Comment by wasuradananjith** [comment]
This is already fixed in master via https://github.com/wso2/product-apim-tooling/pull/336
