### ISSUE TITLE
Subscribing: Insufficient Permissions

### ISSUE THREAD

**Issue by DaniduWijendra** [wso2/api-manager#1722]
### Description

After subscribing with an application, the page displays “**_Insufficient Permissions - You are not allowed to subscribe to this API_**”. while the subscription is successful. Please find the below attachment.

![Screenshot from 2023-04-07 14-52-49](https://user-images.githubusercontent.com/44566213/230866483-7fa04886-efb5-4475-893f-3f2f89585a6f.png)

### Steps to Reproduce

- Create and deploy an API from the publisher portal.
- Create an application from the developer portal and try to subscribe to the created API.
- After the subscription, you will see the mentioned warning message in the developer portal.

### Affected Component

APIM

### Version

3.2.0

**Comment by shilmyhasan** [comment]
Hi Team,

Closing the issue as u2 are relaeased and Public fix already available.

Thanks.
