### ISSUE TITLE
The api#am#publisher.war logs do not print in the console

### ISSUE THREAD

**Issue by SupunRandunu** [wso2/api-manager#1730]
### Description

The api#am#publisher.war lo4j2 logs do not print in the APIM 4.1.0 console.

### Steps to Reproduce

Enable debug logs for the org.wso2.carbon.apimgt.rest.api.publisher package and check whether the logs are printing in the console.

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
As mentioned in the linked internal ticket, this issue does not apply to the master branch. Hence closing the issue.
