### ISSUE TITLE
APIM 4.1.0 token endpoint error response change comparing APIM 3.1.0

### ISSUE THREAD

**Issue by isuru-udayanga** [wso2/api-manager#1741]
### Description

APIM 3.1.0:
With invalid Basic Authorization header (Removed one character from last and invoked token endpoint)
![image](https://user-images.githubusercontent.com/30107177/232731776-387c3564-d016-40d8-94ff-d13f37343834.png)

APIM 4.1.0:
With invalid Basic Authorization header (Removed one character from last and invoked token endpoint)
![image](https://user-images.githubusercontent.com/30107177/232731868-561a5bd3-ef32-47f2-ac68-c831d1c7936e.png)

### Steps to Reproduce

- Login APIM 4.1.0 devportal.
- Create an application.
- Generate keys.
- Copy the curl for generate token.
- Invoke it removing some values in Authorization header

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
closing as the public fixes:
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2027
https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2034
https://github.com/wso2/carbon-apimgt/pull/11942
https://github.com/wso2/product-apim/pull/13187
has already been merged.
