### ISSUE TITLE
Getting 2 different behaviour during the file upload scenario

### ISSUE THREAD

**Issue by riyazathali** [wso2/api-manager#1743]
### Description

When we tried out a file upload scenario with a backend and if we set the content length larger than the file size we are getting 2 different behavior according to the HTTP status code from the backend.

Test: Uploading a file in kB size.
File size - 2 kb.
Content length - 11000.

For the first request, we observed an endpoint timeout and the socket timeout in the logs. We are getting  200 ok HTTP status codes from the backend before the endpoint timeout.
When the endpoint timeout happens we haven't got any response to the client side and the request will wait until the socket timeout.
The client is getting a response only after the socket timeout occurs.
Below are the logs.

TID: [-1234] [] [2023-03-07 15:13:29,347]  INFO {org.apache.synapse.mediators.builtin.LogMediator} - {api:admin--sampleAPI:vv1} STATUS = Executing default 'fault' sequence, ERROR_CODE = 101504, ERROR_MESSAGE = Send timeout, transactionId = ercr2rf-8d25-4638-a35f-derweueey
TID: [-1234] [] [2023-03-07 15:13:29,369]  WARN {org.apache.synapse.core.axis2.TimeoutHandler} - Expiring message ID : urn:uuid:ercr2rf-8d25-4638-a35f-derweueey; dropping message after ENDPOINT_TIMEOUT of : 30 seconds for null, URI : http://localhost:90/upload1, Received through API : admin--sampleAPI:vv1
TID: [-1234] [] [2023-03-07 15:19:29,660]  WARN {org.apache.synapse.transport.passthru.SourceHandler} - STATE_DESCRIPTION = Socket Timeout occurred after reading the request headers but Server is still reading the request body, INTERNAL_STATE = REQUEST_BODY, DIRECTION = REQUEST, CAUSE_OF_ERROR = Connection between the client and the EI timeouts, HTTP_URL = /sample/v1/upload1, HTTP_METHOD = POST, SOCKET_TIMEOUT = 360000, CLIENT_ADDRESS = /127.0.0.1:09222, CONNECTION http-incoming-33444
TID: [-1234] [] [2023-03-07 15:19:29,661]  WARN {org.apache.synapse.core.axis2.SynapseCallbackReceiver} - Synapse received a response for the request with message Id : urn:uuid:ercr2rf-8d25-4638-a35f-derweueey and correlation_id : ercr2rf-8d25-4638-a35f-derweueey But a callback is not registered (anymore) to process this response

But, when we perform the same API invocation again, we are not getting the socket timeout in the logs (only an endpoint timeout occurs). In this request, the backend already has the file, it is returning a 4xx response. And we are getting a response to the client side with the following message within a few seconds (Seems like when the endpoint timeout happens)

```
<am:fault xmlns:am="http://apiresponse.com/message">
    <am:code>101504</am:code>
    <am:type>Status report</am:type>
    <am:message>Runtime Error</am:message>
    <am:description>Send timeout</am:description>
</am:fault>
```

Therefore the concern is, why we are getting 2 different behaviors when performing the same API invocations.
But, we are expecting consistent behavior of socket timeout in logs and getting a response after socket timeout for every request (same behavior as the first request).

Thanks,
Riyazath Ali.

### Steps to Reproduce

1. Create an API with a POST resource of a multipart/form-data, object data type (a file upload API).
2. Use a backend to respond 200 OK once the file is uploaded and if the file is already there respond with 4xx status code.
3. When invoking the API, set the content length to be larger than the actual file size.
4. Send the request twice and observe the difference in the response.
5. Please check wso2carbon.log also to understand the difference.

### Affected Component

APIM

### Version

3.2.0

**Comment by YasasRangika** [comment]
This issue has already been fixed the master branch via https://github.com/wso2/wso2-synapse/pull/2053
