### ISSUE TITLE
Error in Deleting a user via MI Dashboard using the UI.

### ISSUE THREAD

**Issue by Tharanidk** [wso2/api-manager#1747]
### Description

When trying to delete the admin user by login with another user who has the admin role(user3), it's giving out the error below.
![Screenshot from 2023-04-19 12-46-08](https://user-images.githubusercontent.com/42825038/233000497-17b5b8a0-fa3e-420c-837c-9a7d91a4b550.png)

```
 ERROR {Utils} - Error processing the request. java.io.IOException: Attempt to delete the logged in user. Operation not allowed. Please login from another user.
```

This error is represented because it detects the loggedin user(user3) as admin user.

In the following line, it detects the USERNAME as 'admin'.
https://github.com/wso2-support/micro-integrator/blob/support-4.0.0.x-full/components/org.wso2.micro.integrator.extensions/org.wso2.micro.integrator.management.apis/src/main/java/org/wso2/micro/integrator/management/apis/Utils.java#L96

### Steps to Reproduce

1. Go to MI Dashboard.
2. Delete the admin user(admin:admin) with the delete icon.

### Affected Component

MIDashboard

### Version

4.0.0

**Comment by YasasRangika** [comment]
This issue has already been resolved in the master branch.
