### ISSUE TITLE
Publisher portal REST APIs are not supported for JWT tokens.

### ISSUE THREAD

**Issue by Menuka-Senevirathne** [wso2/api-manager#1762]
### Description

The following error occurs once JWT tokens are used along with publisher portal REST APIs.

```
ID: [-1234] [api/am/publisher] [2023-04-06 14:58:28,428] ERROR {org.wso2.carbon.apimgt.rest.api.util.impl.OAuthJwtAuthenticatorImpl} - JWT token issuer validation failed. Reason: Issuer present in the JWT (https://api-manager-v4.dev.api-management.metoffice.cloud:443/oauth2/token) does not match with the token issuer ([])
TID: [-1234] [api/am/publisher] [2023-04-06 14:58:28,428] ERROR {org.wso2.carbon.apimgt.rest.api.util.impl.OAuthJwtAuthenticatorImpl} - Invalid JWT token :...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX31WOqJ2A

```

### Steps to Reproduce

1. Get APIM 4.1.0 and get the latest update.
2. Then obtain the consumer key/secret pair by calling dynamic client registration (DCR).
3. Then generate a token and try invoking REST APIs. It will work without an issue
4. Afterwards go to the management console and select the service provider created in the above steps.
5. Go to Inbound Authentication Configuration, and Oauth/OpenId connect Configuration and select JWT as token issuer instead of Default.
6. Then generate a token and try invoking a REST API and you’ll observe the above error.

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
JWT tokens support for rest APIs is not provided for APIM.
