### ISSUE TITLE
Configuring a proxy in Zipkin open tracing

### ISSUE THREAD

**Issue by shavinsenadheera** [wso2/api-manager#1767]
### Description

In the configurations, it is asked to use the proxy-host and proxy-port directly for the values of remote_tracer.properties.hostname and remote_tracer.properties.port. And that would work only if the proxy is dedicated to Zipkin and the proxy is going to route the traffic to the correct destination.

But in this scenario, the common proxy service is utilized and many services are engaging with that proxy service.

![image](https://user-images.githubusercontent.com/42552426/234257453-21d138ef-0926-4ed8-bf58-2b25a9a76282.png)

Therefore that needs to specify the destination separately as below the CURL command.

In this CURL command, data is being sent to the Zipkin side via the proxy called by the Gateway prod.

```
curl -x 'https://<proxyhost>:8080'  'https://<zipkinhost>/trace/v1' \
    -i -H 'Content-Type: application/json' \
    -H 'Api-Key: <KEY>' \
    -H 'Data-Format: zipkin' \
    -H 'Data-Format-Version: 2' \
    -X POST \
    -d '[
        {
            "traceId": "<trace_id>",
            "id": "<id>",
            "kind": "CLIENT",
            "name": "post",
            "duration": 508068,
            "localEndpoint": {
                "serviceName": "<service_name>",
                "ipv4": "127.0.0.1",
                "port": 8080
            },
            "tags": {
            }
        },
        {
            "traceId": "<trace_id>",
            "parentId": "<parent_id>",
            "id": "<id>",
            "kind": "CLIENT",
            "name": "<name>",
            "duration": 2019,
            "localEndpoint": {
                "serviceName": "<service_name>",
                "ipv4": "127.0.0.1",
                "port": 8080
            },
            "tags": {
                "error.message": "Invalid credentials"
            }
        }
    ]'
```

Please Note: Find the format of the CURL.

curl -x <PROXY ENDPOINT> <ZIPKIN ENDPOINT> {Rest of the cURL}

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

4.0.0

**Comment by YasasRangika** [comment]
Master PR: https://github.com/wso2/carbon-apimgt/pull/11989
