### ISSUE TITLE
Even though the endpoint time out occurs, the socket connection is not closed

### ISSUE THREAD

**Issue by WickramBug** [wso2/api-manager#1770]
### Problem

In WSO2 APIM 3.2.0 we can observe that the socket connection is not closed even after the endpoint time-out occurred as the socket connection is closed once the socket timeout. We suspect this can lead to some other issues.

### Solution

We believe that it is better to close the socket connection when the endpoint timeout occurs instead of keeping it open until the socket timeout.

### Affected Component

APIM

### Version

3.2.0

### Related Issues

https://github.com/wso2/api-manager/issues/1746

**Comment by YasasRangika** [comment]
Closing this issue as the public fixes [1] and [2] have already been merged.
[1]https://github.com/wso2/wso2-synapse/pull/2076
[2] https://github.com/wso2/wso2-axis2/pull/273
