### ISSUE TITLE
Unable to add and save the modules under profiles in the parent pom.xml file

### ISSUE THREAD

**Issue by PasinduGunarathne** [wso2/api-manager#1776]
### Description

Hi Team,

Currently we were not able to add and save the modules under profile level in the parent pom.xml file. According to the maven archetype we should be able to achieve the above scenario.

### Steps to Reproduce

1. Create a Maven Multi Module Project
2. Open the parent pom.xml file and then open the “Outlines” window
3. Add a child called under via the “Outlines” window
4. Add couple of child elements called under via the “Outlines” window
` “Outlines” window > project > profiles > profile > modules > module
`
5. Save the file.

<img width="286" alt="Screenshot 2023-04-18 at 12 11 53" src="https://user-images.githubusercontent.com/112062108/234855205-a2612a65-0b6d-48f4-be5f-9779a91c8621.png">

<img width="460" alt="Screenshot 2023-04-18 at 12 13 04" src="https://user-images.githubusercontent.com/112062108/234855248-ef5de57c-7790-423d-b778-f34b1a09dcfd.png">

### Affected Component

IntegrationStudio

### Version

8.2.0

### Environment Details (with versions)

OS version : Mac M1

**Comment by YasasRangika** [comment]
Public fix: https://github.com/wso2/integration-studio/pull/1213 has already been merged into the master branch.
