### ISSUE TITLE
Schema validation is not working as expected - APIM 3.2.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/api-manager#1783]
### Description

Schema validation is not working for some swagger definition files. The gateway is parsing the request to the backend instead of rejecting the request from the gateway level due to the missing parameters (required) in the request payload.

### Steps to Reproduce

- Go to the publisher and create an API by using the attached swagger definition [reproducing_swagger.yaml.txt](https://github.com/wso2/api-manager/files/11364378/reproducing_swagger.yaml.txt). In this definition, **TEST_KEY** should be in the request JSON payload to pass the schema validation.
- Enable the schema validation and publish the API.
- Invoke the API with the below payload.
```
{
  "hello": "world"
}
```

**Observations**

- The gateway will parse the request to the backend without rejecting it.

### Affected Component

APIM

### Version

3.2.0

**Comment by hisanhunais** [comment]
- Issue has been fixed in APIM 3.2.0
- Issue is not reproducible in master.
