### ISSUE TITLE
Unable to perform HTTPS health check in MI v4.0.0

### ISSUE THREAD

**Issue by PasinduGunarathne** [wso2/api-manager#1784]
### Description

Hi Team,

Currently we are not able to perform HTTPS health check in MI v4.0.0 according to the doc[1] we should be able to perform HTTPS health check.

### Steps to Reproduce

1. Add below configs to deployment.toml file

```
[management_api]
protocols = "http https"

[readiness_probe]
protocols = "http https"
```

2. Invoke the following curl request with verbose enabled.

`curl -X GET 'https://localhost:9164/healthz' -k -v 
`
### Expected behaviour

- Should be able to perform HTTPS health check with the following response.

`{"version":"4.0.0","status" : "ready"}%   
`
### Current behaviour

- Currently we are getting a 404 not found error
<img width="785" alt="Screenshot 2023-04-28 at 12 29 17" src="https://user-images.githubusercontent.com/112062108/235583336-64a11030-24dd-45c2-8c53-bec2efc5adee.png">

[1] https://apim.docs.wso2.com/en/4.0.0/install-and-setup/setup/deployment-best-practices/basic-health-checks/#micro-integrator-health-checks

### Affected Component

MI

### Version

4.0.0

**Comment by YasasRangika** [comment]
Public fix: https://github.com/wso2/micro-integrator/pull/2328 has already been merged into the master branch.
