### ISSUE TITLE
Case sensitive user issue in Edit/Delete applications in dev portal

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/api-manager#1786]
### Description

According to the current implementation of the APIM-4.0.0, the usernames are case insensitive and we can log in to the portals without the case sensitivity.
But, if we create an application, dev portal does not allow us to edit/delete applications in case insensitive manner. We have to log in to the dev portal with the exact name as the user that we have created.

### Steps to Reproduce

1. Create a user with the name "User_Apim".
2. log in to dev portal with User_Apim user name. At the top right corner of Devportal, you will see the username as USER_APIM.
3. Create an Application by clicking on "ADD APPLICATION" button.
4.  Click on Applications. It will allow you to delete/edit applications.
Dev1
5.    Now Please log out and log in to the dev portal with USER_APIM. The login will be successful.
6.   Go to Applications and check.
7.    Delete/Edit will be disabled for the applications.

### Affected Component

APIM

### Version

4.0.0

### Related Issues

https://github.com/wso2/product-apim/issues/12152

**Comment by IsuruMaduranga** [comment]
Hi @karunarathneeshani,

This issue is already fixed. Hence closing the issue.

Thanks,
Isuru
