### ISSUE TITLE
White spaces in role names are not supported in Admin portal

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/api-manager#1805]
### Description

When trying to add scope mappings to roles that contain whitespace in their name, the whitespace(s) are not supported at the Admin portal.

### Steps to Reproduce

1. Create a role name with the white spaces from the carbon Console.
2. Try to add it as the role name from the Admin portal.

### Affected Component

APIM

### Version

3.2.0

**Comment by YasasRangika** [comment]
This issue is not reproducible in the master branch since it has been fixed in the latest releases.
