### ISSUE TITLE
Issues in the DCR Endpoint

### ISSUE THREAD

**Issue by shavinsenadheera** [wso2/api-manager#1810]
### Description

We ran the following tests on wso2am-3.2.0-243 and wso2am-3.2.0 with the most recent update level (266) and also on a wso2am-3.2.0 vanilla pack.

### Behavior 01

1. We used a fresh APIM 3.2.0 setup with the update-level 243.
2. Went to the Carbon Console and create a new tenant called “shavindu.com” with the “admin@shavindu.com” user.
3. Created other users called “user1@shavindu.com” and “user2@shavindu.com” and assign them an “internal/subscriber” role.
4. Made the invocation to the DCR endpoint to get the client ID and client secret for the “user1@shavindu.com”.

$\textcolor{silver}{\textsf{CURL COMMAND}}$ 

```
curl --location 'https://localhost:9443/client-registration/v0.17/register' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic dXNlcjFAc2hhdmluZHUuY29tOmFkbWlu' \
--data-raw '{
    "clientName": "testing4",
    "owner": "user1@shavindu.com",
    "grantType": "password refresh_token client_credentials",
    "saasApp": true
}'
```

$\textcolor{silver}{\textsf{RESPONSE}}$ 

```
{
    "clientId": "oPQOQ359uuO7X5y0GItT_oqtIXga",
    "clientName": "testing4",
    "callBackURL": null,
    "clientSecret": "mUQJRTyGPKzvW5CKd7xVqRtZQX0a",
    "isSaasApplication": true,
    "appOwner": "user1@shavindu.com",
    "jsonString": "{\"grant_types\":\"password refresh_token client_credentials\",\"redirect_uris\":null,\"client_name\":\"testing4\"}",
    "jsonAppAttribute": "{}",
    "tokenType": null
}
```
Then, we obtained another client ID/client Secret with the above same client name "testing4" (that I used above for the "user1@shavindu.com" also) for the user "user2@shavindu.com". Please find the below results.

$\textcolor{silver}{\textsf{CURL COMMAND}}$ 

```
curl --location 'https://localhost:9443/client-registration/v0.17/register' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic dXNlcjJAc2hhdmluZHUuY29tOmFkbWlu' \
--data-raw '{
    "clientName": "testing4",
    "owner": "user2@shavindu.com",
    "grantType": "password refresh_token client_credentials",
    "saasApp": true
}'
```
$\textcolor{silver}{\textsf{RESPONSE}}$ 

```
{
    "clientId": "oPQOQ359uuO7X5y0GItT_oqtIXga",
    "clientName": "testing4",
    "callBackURL": null,
    "clientSecret": "mUQJRTyGPKzvW5CKd7xVqRtZQX0a",
    "isSaasApplication": true,
    "appOwner": null,
    "jsonString": "{\"grant_types\":\"password refresh_token client_credentials\"}",
    "jsonAppAttribute": "{}",
    "tokenType": null
}
```
As you can see the "user2@shavindu.com" also received the same SP results (same client id, same client secret, and etc) which "user1@shavindu.com" has received. Also, the "appOwner": "null" for the user2.

**Please Note: I have done the above same for default carbon.super tenant and observed the same results.**

### Question for Behavior 01

Is this the expected behavior?

If not,

### Behavior 02

Let's generate a token with client credentials for the obtained clientId and the clientSecret.

**TOKEN 1  - [ Grant Type = client_credentials ]**

$\textcolor{silver}{\textsf{CURL COMMAND}}$ 

```
curl --location 'https://localhost:8243/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic b1BRT1EzNTl1dU83WDV5MEdJdFRfb3F0SVhnYTptVVFKUlR5R1BLenZXNUNLZDd4VnFSdFpRWDBh' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'scope=apim:api_import_export apim:api_view apim:app_import_export apim:app_manage apim:subscribe'
```

$\textcolor{silver}{\textsf{RESPONSE}}$ 

```
{
    "access_token": "06479e77-ee6e-339a-8e33-ebb373f007e2",
    "scope": "apim:app_manage apim:subscribe",
    "token_type": "Bearer",
    "expires_in": 3600
}
```

**TOKEN 2 - [ Grant Type = password and User = user2@shavindu.com (The user who secondly created the testing4) ]**

$\textcolor{silver}{\textsf{CURL COMMAND}}$ 

```
curl --location 'https://localhost:8243/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic b1BRT1EzNTl1dU83WDV5MEdJdFRfb3F0SVhnYTptVVFKUlR5R1BLenZXNUNLZDd4VnFSdFpRWDBh' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'password=admin' \
--data-urlencode 'scope=apim:api_import_export apim:api_view apim:app_import_export apim:app_manage apim:subscribe' \
--data-urlencode 'username=user2@shavindu.com'
```

$\textcolor{silver}{\textsf{RESPONSE}}$ 

```
{
    "access_token": "1828358b-b79c-3baf-be8b-b38ed14a7c63",
    "refresh_token": "0a550b7b-6fe2-3d4b-ba45-1b624a169b70",
    "scope": "apim:app_manage apim:subscribe",
    "token_type": "Bearer",
    "expires_in": 3600
}
```

**TOKEN 3 - [ Grant Type = password and User = user1@shavindu.com (The user who firstly created the testing4) ]**

$\textcolor{silver}{\textsf{CURL COMMAND}}$ 

```
curl --location 'https://localhost:8243/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic b1BRT1EzNTl1dU83WDV5MEdJdFRfb3F0SVhnYTptVVFKUlR5R1BLenZXNUNLZDd4VnFSdFpRWDBh' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'password=admin' \
--data-urlencode 'scope=apim:api_import_export apim:api_view apim:app_import_export apim:app_manage apim:subscribe' \
--data-urlencode 'username=user1@shavindu.com'
```
$\textcolor{silver}{\textsf{RESPONSE}}$ 

```
{
    "access_token": "06479e77-ee6e-339a-8e33-ebb373f007e2",
    "refresh_token": "d92f441a-983c-3d7f-abc7-b0cadd99c934",
    "scope": "apim:app_manage apim:subscribe",
    "token_type": "Bearer",
    "expires_in": 3461
}

```
As you can see, here the TOKEN 1 is equal to TOKEN 3 since the client_id and client_secret initially generated for the "user1@shavindu.com".

**Please Note: I have done the above same for default carbon.super tenant and observed the same results.**

### Behavior 03

1. I already created above "testing4" for the user "user1@shavindu.com".
2. And, I received client id as "oPQOQ359uuO7X5y0GItT_oqtIXga" and client secret as "mUQJRTyGPKzvW5CKd7xVqRtZQX0a".
3. Then, I tried to generate the token for the "admin@shavindu.com" with above obtained client id and client secret.

$\textcolor{silver}{\textsf{CURL COMMAND}}$ 

```
curl --location 'https://localhost:8243/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic b1BRT1EzNTl1dU83WDV5MEdJdFRfb3F0SVhnYTptVVFKUlR5R1BLenZXNUNLZDd4VnFSdFpRWDBh' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'password=admin' \
--data-urlencode 'scope=apim:api_import_export apim:api_view apim:app_import_export apim:app_manage apim:subscribe' \
--data-urlencode 'username=admin@shavindu.com'
```

$\textcolor{silver}{\textsf{RESPONSE}}$

```
{
    "access_token": "2f041420-4244-3875-9d12-fe1f0c97a2d5",
    "refresh_token": "73aa726f-9119-376f-8188-83f4ad10222d",
    "scope": "apim:api_import_export apim:api_view apim:app_import_export apim:app_manage apim:subscribe",
    "token_type": "Bearer",
    "expires_in": 3590
}
```

**The user "admin@shavindu.com" was then able to generate a token for the application ("testing4") even that was not own.**

**Please Note: I have done the above same for default carbon.super tenant and observed the same results.**

### Steps to Reproduce

Steps are included in the description

### Affected Component

APIM

### Version

3.2.0

**Comment by YasasRangika** [comment]
In DCR, we expect behavior 1 which returns the existing app if the same client name is sent to the registration endpoint. The issue of the application owner receiving the same access token when using two different grant types has been resolved in the product IAM.
