### ISSUE TITLE
Admin Portal will only display up to 25 Approval Tasks

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/api-manager#1811]
### Problem

By default, in the admin portal, only 25 workflow approval tasks can be seen. If we have multiple approval tasks pending in order to view them we have to increase the "limit" parameter inside the `[APIM_HOME]/repository/deployment/server/jaggeryapps/admin/site/public/conf/settings.js` file. Since the default limit is 25, which is a smaller value. This git issue has been created to increase the value to a suitable higher value. 

### Solution

Increase the "limit" parameter inside the `[APIM_HOME]/repository/deployment/server/jaggeryapps/admin/site/public/conf/settings.js` file to a suitable higher value.

### Affected Component

APIM

### Version

4.1.0

**Comment by tharikaGitHub** [comment]
We can discuss and come to a conclusion whether this limit should be further increased. But we can consider changing the offset list limit values in the task table based on the above default value we select, for a future release as an improvement.

<img width="1064" alt="img" src="https://github.com/wso2/api-manager/assets/8557410/baf488cd-1e6c-4ab9-82b5-c1a126a9f87c">

**Comment by nandika** [comment]
If pagination is available and next page is loadable, this is sufficient functionality. However, if pagination is not available, we will fix it.

**Comment by riyazathali** [comment]
The same issue has been observed in APIM 3.2.0 as well.
