### ISSUE TITLE
tmp_<random_number>-.dat files are created when reading files from the registry

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/api-manager#1813]
### Description

**Problem:**
Please note the below code segment:

```java
	public static InputStream getRegistryResource(MessageContext context,
			String resourceKey) {
		log.trace("Getting resource from the registry...");

		InputStream is = null;
		Registry reg = context.getConfiguration().getRegistry();

		if (reg == null) {
			log.error("Unable to retrieve Configuration registry. Endpoint cannot be resolved");
			return is;
		}

		Object obj = reg.getResource(new Entry(resourceKey), null);
```

When `Object obj = reg.getResource(new Entry(resourceKey), null);` is called, a .dat file is created in the /tmp folder. Further narrowing down,  please do refer line 705 of `WSO2Registry.java` [1] -> the `new SynapseBinaryDataSource(inputStream, resource.getMediaType())` creates this temp file.

The problem here is that upon accessing the registry as stated above, each time the registry is accessed, the temp files are created. This means that upon some load, the temp files will be accumulated.

These files are deleted upon server restart. In my local environment I noticed the files being remove automatically after some time (like 10-15 mins). However, the customer is stating that there storage is being accumulated.

Can we improve the above logic in a better way so that the storage will not get used up upon some load.

[1] https://github.com/wso2-support/carbon-mediation/blob/v4.6.105/components/mediation-registry/org.wso2.carbon.mediation.registry/src/main/java/org/wso2/carbon/mediation/registry/WSO2Registry.java#L705

Product : wso2ei-6.4.0
Update level : Not Required

### Steps to Reproduce

N/A

### Affected Component

MI

### Version

6.4.0

### Environment Details (with versions)

N/A

### Relevant Log Output

```shell
N/A
```

### Related Issues

N/A

### Suggested Labels

patch, ei

**Comment by YasasRangika** [comment]
Extrction fom internal discussion:
