### ISSUE TITLE
Cannot export API when it has Files that are not yet associated with content

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#1814]
### Description

When an API that has a document that is not yet associated with any content is exported, a corruped zip archive is recieved and below error is logged.

```
Failed to get the document content. Artifact corresponding to document id dd6acb7b-7c0d-4af9-af5e-e367957dfd44 does not exist
``` 

However in my opinion this is not an error scenario, hence just logging an info is enough, no need to throw an exception. (we have two seperate REST endpoints to create a document and attach contents)

```
if (content != null) {
    docContent = DocumentMapper.INSTANCE.toDocumentationContent(content);
} else {
    String msg = "Failed to get the document content. Artifact corresponding to document id " + docId
            + " does not exist";
    throw new APIMgtResourceNotFoundException(msg);
}
```

[1]. https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/AbstractAPIManager.java#L473-L479

### Steps to Reproduce

1. Create an API
2. Add a markdown type document, do not add any content though.
3. Try to export the API in 1.

### Affected Component

APIM

### Version

4.2.0

**Comment by ashanhr** [comment]
This issue is no longer reproducible in the latest release as it has been fixed.
