### ISSUE TITLE
Error not showing on UI when document type is not provided

### ISSUE THREAD

**Issue by RusJaI** [wso2/api-manager#1816]
### Description

In the publisher portal's `Documents` section, when creating a new document or editing an existing document with type selected as `Other`, a new field called `Other Document Type` is appeared as a required field.
But in UI level, user is allowed to skip that field and proceed.

<img width="1489" alt="Screenshot 2023-05-12 at 09 52 49" src="https://github.com/wso2/api-manager/assets/48326709/950c5a07-2432-430d-86df-d19d9c232f3c">

When clicking on "Add Document" button or "Save" button (in edit scenario), the document is not created  or updated and the UI doesn't respond with any message.

But when checking the terminal, it shows the following error : 
`ERROR - ApisApiServiceImpl otherTypeName cannot be empty if type is OTHER.`

### Steps to Reproduce

1. Login to the publisher portal
2. deploy sample API
3. in left menu click on "Documents"
4. click "Add New Document"
5. give a name and summary to the document
6. select the type as "Other"
7. you may see "Other Document Type" filed. Keep it empty
8. Click on "Add Document" button

### Affected Component

APIM

### Version

3.1.0

### Environment Details (with versions)

mac os v13.3.1

### Relevant Log Output

```shell
ERROR - ApisApiServiceImpl otherTypeName cannot be empty if type is OTHER.
```

### Suggested Labels

Type/Bug

**Comment by dakshina99** [comment]
This error prompt is not required since the Other Document Type is a mandatory field (On APIM 4.3.0)
