### ISSUE TITLE
Unable to generate application keys when WSO2 IS 6.1.0 used as third party KM.

### ISSUE THREAD

**Issue by Jaiya94** [wso2/api-manager#1821]
### Description

When configuring the IS 6.1.0 as third party Key Manager with APIM 4.2.0 and trying to generate keys for the applications created by the users (having the Internal/subscriber role) who were created in the APIM (and not available in IS user store). It is getting failed.

### Steps to Reproduce

Setup WSO2 APIM 4.2.0 server with WSO2 IS 6.1.0 server as a third party KM.

- Log in to APIM 4.2.0 /carbon console.
- Create a user & assign the subscriber role to that user.
- Log in to the /devportal & create an application.
- Click on Generate Keys.

### Affected Component

APIM

### Version

4.2.0

**Comment by hisanhunais** [comment]
Master branch fix done via
- https://github.com/wso2/apim-apps/pull/472
- https://github.com/wso2-extensions/apim-km-wso2is/pull/108
