### ISSUE TITLE
The property 'include.by.regexp' which is used in File move/copy functions is not dynamic even if it is mentioned as dynamic in the documentation.

### ISSUE THREAD

**Issue by janithcmw** [wso2/api-manager#183]
### Description

The subjected property is mentioned as dynamic in the documentation[1] but when it is configured as a dynamic value it will only consider the 1st dynamic value. 

[1] https://siddhi-io.github.io/siddhi-io-file/api/2.0.18/

### Steps to Reproduce

Set up a siddhi application with the dynamic regex even if we have passed the different regex patterns via the stream, the action will only affect the pattern which we have passed in the 1st place.

```
define stream errorHandlingStream (regex string);

from errorHandlingStream#file:copy('<souce location>', "<destination>", regex, true)
insert into filedCopied;
```

### Affected Component

SI

### Version

1.1.0

### Environment Details (with versions)

N/A

**Comment by AnuGayan** [comment]
Fixed by https://github.com/siddhi-io/siddhi-io-file/pull/150
