### ISSUE TITLE
Improve User Experience when using a Connector

### ISSUE THREAD

**Issue by rosensilva** [wso2/api-manager#1830]
### Description

Adding a connector to the Integration Project mainly have 2 issues.

1) Adding a connector to a project will only add the connector to the existing workspace. Exporting and importing the same project will crash the opened Integration since the connector is not available in the imported workspace.
2) Most of the new users forget to create a separate Connector Exporter project as they add the connector to the workspace. Having duplicating steps is causing the bad user experience.

### Steps to Reproduce

N/A

### Affected Component

IntegrationStudio

### Version

8.2.0

### Environment Details (with versions)

Windows 11

**Comment by rosensilva** [comment]
related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/3001

**Comment by imsuneth** [comment]
Hi all,
Please find the ETA for this as follows.

Best Case Estimate: 2023-06-14
Most Likely Estimate: 2023-06-21
Worst Case Estimate: 2023-07-07

**Comment by imsuneth** [comment]
Sent PR: https://github.com/wso2/integration-studio/pull/1225

**Comment by imsuneth** [comment]
PR merged
