### ISSUE TITLE
Publisher hang on viewing lifecycle of API version

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/api-manager#1835]
### Description

When viewing the lifecycle of API revision, the UI is loading infinitely. In the network tracer, we can see the "lifecycle-state" GET request returns 500 as the response.

### Steps to Reproduce

1. Create and publish the PizzaShack API.
2. Create multiple Revisions.
3. Select the PizzaShack API.
4. Select an old revision from the top dropdown.
5. Click on Lifecycle from the left menu.

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
closing as the public fix: https://github.com/wso2/carbon-apimgt/pull/12018 has already been merged.
