### ISSUE TITLE
Registry Artifact View Support for MI Management API/Dashboard

### ISSUE THREAD

**Issue by SavinduDimal** [wso2/api-manager#185]
### Problem

The latest version of MI does not provide the ability to view or modify Registry Artifacts, their metadata or properties through MI-Management API or MI-Dashboard.

### Solution

The new feature will support,
- View Registry Artifacts through MI-Management API and MI-Dashboard
- Add or Modify Registry Artifacts through MI-Management API

The solution can be divided into subtasks as follows.

- [x] #316 
- [x] #384
- [x] #338
- [x] #385
- [x] #386
- [x] #387

### Affected Component

MI

### Version

4.2.0

**Comment by tharikaGitHub** [comment]
Closing as the feature is completed.
