### ISSUE TITLE
Missing parameters in SOAP to REST conversion

### ISSUE THREAD

**Issue by PasinduGunarathne** [wso2/api-manager#1857]
### Description

HI Team,

There is an issue regarding SOAP to REST conversion[1] and you can follow the below steps to reproduce the issue.

[1] https://apim.docs.wso2.com/en/latest/integrate/develop/creating-artifacts/creating-an-api/#creating-the-api-artifact

### Steps to Reproduce

1. Crete a Hello world project
2. Create a schema file(.xsd) with a complex type element

```
<xsd:element name="SAMPLE" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="PARAM" minOccurs="0" maxOccurs="unbounded">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="NAME" type="xsd:string" />
                                    <xsd:element name="VALUE" type="xsd:string" />
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
```
3. Set the correct location of the schema file in the wsdl file which needs to be converted.
4. Generate an API with this wsdl file(browse the wsdl file and import it to the ESB project).
5. Go to the generated API and search for the relevant resource.

### Expected behaviour:

- The SOAP service under PayloadFactory mediator should include all the configured parameters in the schema.

### Current behaviour:

- Some of the paramters are missing in the SOAP service in generated API

### Affected Component

IntegrationStudio

### Version

8.2.0

**Comment by YasasRangika** [comment]
This issue has already been resolved in the master branch.
