### ISSUE TITLE
Enable failover config when importing api via apictl tool

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/api-manager#1859]
### Description

When importing the API using apictl tool even though we defined "failOver: true" in the params.yaml , we could observe that the load-balanced configs specified in the params.yaml are not reflected in the publisher portal. 

### Steps to Reproduce

1. Tried to import an API using apictl tool version "Version: 4.1.0 Build Date: 2022-04-05" 05:22:20 UTC." in the latest APIM 4.1.0 update level 187 by following the below steps.

2. To enable the "Enable Failover" config in the endpoint configuration, I have defined "failOver: true" in the params.yaml as follows.
environments:
  - name: dev3
    configs:
        endpointType: rest
        endpointRoutingPolicy: load_balanced
        failOver: true
        loadBalanceEndpoints:
            production:
                - url: http://dccdlvg0060.com:8080/
                - url: http://dccdlvg0061.com:8080/
            sandbox:
                - url: http://dccdlvg0060.com:8080/
                - url: http://dccdlvg0061.com:8080/
            sessionManagement: transport
            sessionTimeOut: 5000
            algoClassName: org.apache.synapse.endpoints.algorithms.RoundRobin
        deploymentEnvironments:
            - displayOnDevportal: true
              deploymentEnvironment: Production and Sandbox
              deploymentVhost : api-devi.com
            - displayOnDevportal: true
              deploymentEnvironment: External
              deploymentVhost : DCCxxx0061.com

3. Imported the API using the following command.
./apictl import api -f PetstoreProject --environment dev --params params.yaml.

4. Then when we checked the load-balanced configs of the imported API, from the publisher portal. we could observe that the load-balanced configs specified in the params.yaml are reflected in the publisher portal as follows but the "Enable Failover" config is not selected.

![image](https://github.com/wso2/api-manager/assets/30020227/98934f46-3753-4835-9397-d12935097b2d)

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
closing as the master fix: https://github.com/wso2/carbon-apimgt/pull/12041 has already been merged.
