### ISSUE TITLE
Request to introduce a new thread pool to handle consume and discard

### ISSUE THREAD

**Issue by vikumkbv** [wso2/api-manager#1865]
### Problem

Hi Team,

Please introduce a new thread pool to handle consume and discard mechanism instead of using the existing thread pool

Thanks,
Vikum

### Solution

Provide new thread pool to handle consume and discard

### Affected Component

APIM

### Version

3.2.0

**Comment by GihanAyesh** [comment]
Public PRs

https://github.com/wso2/wso2-synapse/pull/2076
https://github.com/wso2/wso2-synapse/pull/2077
