### ISSUE TITLE
API Logging doesn't work without providing version

### ISSUE THREAD

**Issue by sashansamarajeewa** [wso2/api-manager#1870]
### Description

When using API logging feature [1], if an API is invoked as the default version without specifying the version, there are no logs printed in the api.log file. When version is used, the logs are getting printed.

[1] https://apim.docs.wso2.com/en/latest/observe/api-manager/monitoring-api-logs/

### Steps to Reproduce

- Deploy the PizzaShack API
- Enable 'Make this the default version' property and redeploy
- Change the API log level to full using devops API
- Invoke the API with the version and without the version
- Check the api.log file

### Affected Component

APIM

### Version

4.1.0

**Comment by dilshanfa** [comment]
HI Team,

Appreciate your input on this.

Thank You
DilshanF

**Comment by Methma** [comment]
Hi Team,

Kind reminder on this.

Thanks,
Methma

**Comment by YasasRangika** [comment]
closing as the public fix: https://github.com/wso2/carbon-apimgt/pull/12063 has already been merged.
