### ISSUE TITLE
API Logging doesn't work without providing version 

### ISSUE THREAD

**Issue by prasa7** [wso2/api-manager#1871]
### Description

When using API logging feature [1], if an API is invoked as the default version without specifying the version, there are no logs printed in the api.log file. When version is used, the logs are getting printed.

### Steps to Reproduce

Deploy the PizzaShack API
Enable 'Make this the default version' property and redeploy
Change the API log level to full using devops API
Invoke the API with the version and without the version
Check the api.log file

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
closing as the public pr: https://github.com/wso2/carbon-apimgt/pull/12063 has already been mereged.
