### ISSUE TITLE
Cannot create REST API using Swagger Definition in Integration Studio 8.2.0

### ISSUE THREAD

**Issue by shashikab** [wso2/api-manager#1890]
### Description

 Cannot create REST API using Integration Studio 8.2.0

### Steps to Reproduce

1.Go to Integration Studio 8.2.0
2.Create an Integration project
3.Try to create a REST API using Swagger definition option. Please create Swagger file using the shared file content. [HelloWorld_swagger.txt]
![image](https://github.com/wso2/api-manager/assets/98796552/8e0bcbd8-24b1-4762-abc1-507fbbb9dc0d)
4.Note that nothing is generated .
5.Please add a forward slash(/) at the end of the server url as below and continue . It can generate the REST API without any issue
servers:
url: https://aci.aero/

NOTE: Please add content attached in txt file for yaml file.
[HelloWorld_swagger.txt](https://github.com/wso2-enterprise/wso2-apim-internal/files/11609590/HelloWorld_swagger.txt)

### Affected Component

Integration Studio

### Version

8.2.0

**Comment by YasasRangika** [comment]
Public fix: https://github.com/wso2/carbon-mediation/pull/1683 has already been merged.
