### ISSUE TITLE
Unable to find template files when starting as Windows service.

### ISSUE THREAD

**Issue by SupunRandunu** [wso2/api-manager#1906]
### Description

Unable to find  throttle_policy_template_sub.xml, throttle_policy_template_async_sub.xml, throttle_policy_template_app.xml, throttle_policy_template_resource.xml, and velocity_template.xml files when starting as Windows service.

### Steps to Reproduce

1. Update the APIM 4.1.0.
2. Start it as Windows service. 

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
There is no need for a public fix since the classpath does not include it, as stated in the comment on the linked internal ticket.
