### ISSUE TITLE
Missing implementation for LivenessProbe

### ISSUE THREAD

**Issue by selakap** [wso2/api-manager#1910]
### Description

There is a missing implementation related to LivenessProbe in MI 4.1.0 under conf/internal-apis.xml.

`<api name="LivenessProbe" protocol="http" class="org.wso2.micro.integrator.probes.LivenessProbe"/>`

This is to add the relevant implementation

### Steps to Reproduce

N/A

### Affected Component

MI

### Version

4.1.0

**Comment by YasasRangika** [comment]
This issue has already been resolved in the master branch.
