### ISSUE TITLE
Workflow for AM_SUBSCRIPTION_UPDATE is routing to Wrong tenant - APIM 3.2.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/api-manager#1911]
### Description

When making the subscription update after enabling the workflow extensions and cross tenant subscriptions, the subscription update approval requests are going to different tenant domains.

### Steps to Reproduce

<ul>
<li>Enabled the cross tenant subscription by adding the below configuration into the <strong>deployment.toml</strong> file.</li>
</ul>
<pre>[apim.devportal]
enable_cross_tenant_subscriptions = true
</pre>
<ul>
<li>Created 3 tenants via the carbon console. (<strong>tenant1.com, tenant2.com, tenant3.com</strong>)</li>
<li>Enabled the <strong>org.wso2.carbon.apimgt.impl.workflow.SubscriptionUpdateApprovalWorkflowExecutor</strong> for all 3 tenants by modifying the <strong>workflow-extensions.xml</strong> under the <strong>/_system/governance/apimgt/applicationdata/</strong> path. (Edited by browsing the file via the carbon management console's registry browser)</li>
</ul>
<pre>&lt;!--SubscriptionUpdate executor="org.wso2.carbon.apimgt.impl.workflow.SubscriptionUpdateSimpleWorkflowExecutor"/--&gt;
   <strong> &lt;SubscriptionUpdate executor="org.wso2.carbon.apimgt.impl.workflow.SubscriptionUpdateApprovalWorkflowExecutor"/&gt;</strong>
    &lt;!--SubscriptionUpdate executor="org.wso2.carbon.apimgt.impl.workflow.SubscriptionUpdateWSWorkflowExecutor"&gt;
         &lt;Property name="serviceEndpoint"&gt;http://localhost:9765/services/SubscriptionApprovalWorkFlowProcess/&lt;/Property&gt;
         &lt;Property name="username"&gt;admin&lt;/Property&gt;
         &lt;Property name="password"&gt;admin&lt;/Property&gt;
         &lt;Property name="callbackURL"&gt;https://localhost:8243/services/WorkflowCallbackService&lt;/Property&gt;
    &lt;/SubscriptionUpdate--&gt;
</pre>
<ul>
<li>Logged into the publisher portal and published 2 APIs from both<strong> tenant1.com</strong> and<strong> tenant2.com </strong>tenants.
<ul>
<li>tenant1.com: <strong>Tenant1_API</strong></li>
<li>tenant2.com: <strong>Tenant2_API</strong></li>
<li>Select multiple subscriptions for both APIs since we have to update subscriptions of APIs via the dev portal.</li>
<li>Made those 2 APIs available for all the tenants in the system.</li>
</ul>
</li>
<li>Logged into the dev portal by using the <strong>tenant3.com</strong> credentials and subscribed both APIs.</li>
<li>Then updated the <strong>Tenant2_API</strong> subscription and checked the database and noticed that the subscription workflow record got inserted correctly.</li>
</ul>
<p>SELECT * FROM AM_WORKFLOWS;</p>
<table cellspacing="0" cellpadding="0">
<tbody>
<tr>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_ID<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_REFERENCE<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_TYPE<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_STATUS<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_CREATED_TIME<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_UPDATED_TIME<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_STATUS_DESC<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">TENANT_ID<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">TENANT_DOMAIN<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_EXTERNAL_REFERENCE<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_METADATA<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_PROPERTIES<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
</tr>
<tr>
<td>9</td>
<td>6</td>
<td>AM_SUBSCRIPTION_UPDATE</td>
<td>CREATED</td>
<td>2023-06-12 18:38:05.564</td>
<td>2023-06-12 18:38:05.564</td>
<td>Approve API Tenant2_API - 2 subscription creation request from subscriber - admin@tenant3.com for the application - TENANT3_APP</td>
<td>2</td>
<td>tenant2.com</td>
<td>886ef48e-1b57-4889-9074-c38083e97dfb</td>
<td>7b7d</td>
<td>7b226170694e616d65223a2254656e616e74325f415049222c2261706956657273696f6e223a2232222c2273756273637269626572223a2261646d696e4074656e616e74332e636f6d222c2263757272656e7454696572223a2242726f6e7a65222c226170706c69636174696f6e4e616d65223a2254454e414e54335f415050222c2272657175657374656454696572223a22476f6c64227d</td>
</tr>
<tr>
<td>&nbsp;</td>
</tr>
</tbody>
</table>
<ul>
<li>Then updated the <strong>Tenant1_API</strong> subscription and checked the database and noticed that the subscription workflow record got inserted to the <strong>tenant2.com</strong> tenant which is not expected.</li>
</ul>
<p>SELECT * FROM AM_WORKFLOWS;</p>
<table cellspacing="0" cellpadding="0">
<tbody>
<tr>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_ID<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_REFERENCE<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_TYPE<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_STATUS<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_CREATED_TIME<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_UPDATED_TIME<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_STATUS_DESC<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">TENANT_ID<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">TENANT_DOMAIN<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_EXTERNAL_REFERENCE<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_METADATA<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
<th><a class="sortHeader" style="text-decoration: none;" href="http://localhost:8082/query.do?jsessionid=fcf50f997c3409806df0ce2e5a26b985#">WF_PROPERTIES<span class="sortArrow">&nbsp;&nbsp;</span></a></th>
</tr>
<tr>
<td>10</td>
<td>5</td>
<td>AM_SUBSCRIPTION_UPDATE</td>
<td>CREATED</td>
<td>2023-06-12 18:38:22.51</td>
<td>2023-06-12 18:38:22.51</td>
<td>Approve API Tenant1_API - 1 subscription creation request from subscriber - admin@tenant3.com for the application - TENANT3_APP</td>
<td>2</td>
<td>tenant2.com</td>
<td>3726f2b9-466a-4f48-b45a-08a218a333ff</td>
<td>7b7d</td>
<td>7b226170694e616d65223a2254656e616e74315f415049222c2261706956657273696f6e223a2231222c2273756273637269626572223a2261646d696e4074656e616e74332e636f6d222c2263757272656e7454696572223a2242726f6e7a65222c226170706c69636174696f6e4e616d65223a2254454e414e54335f415050222c2272657175657374656454696572223a22556e6c696d69746564227d</td>
</tr>
</tbody>
</table>
<ul>
<li>Furthermore, we logged into the <strong>tenant2.com</strong> admin portal and noticed that both the subscription update requests came as below.</li>
</ul>

![245157905-daa6f846-a772-4e88-b709-a882fc99cadd](https://github.com/wso2/api-manager/assets/18566908/23a0ff67-5406-4329-84f3-f5fc72f000e1)

### Affected Component

APIM

### Version

3.2.0

**Comment by RusJaI** [comment]
Closing this as the issue was not reproducible in latest APIM version.
