### ISSUE TITLE
Removing OAuth 2.0 authentication from swagger 2 definition

### ISSUE THREAD

**Issue by hasuniea** [wso2/api-manager#1913]
### Description

When an API authentication type is changed in wso2am-4.1.0 from the Oauth2 to apiKey or Basic, it won't be reflected in the API definition(swagger/openAPI) file under securitySchemes section. This is fixed in openAPI 3. Need to fix in Swgger 2

### Steps to Reproduce

When an API authentication type is changed in wso2am-4.1.0 from the Oauth2 to apiKey or Basic

### Affected Component

APIM

### Version

4.1

**Comment by YasasRangika** [comment]
closing as the master fix: https://github.com/wso2/carbon-apimgt/pull/12102 has already been merged.
