### ISSUE TITLE
Default version of published API is not working for some of the resources

### ISSUE THREAD

**Issue by AlexisStrife** [wso2/api-manager#1927]
### Description

Scenario Description:

I have an API with 2 POST resources and 1 GET resource. If I create a new version of it (2.0.0), and set it as "Default version", I can call the API by specifying the version OR not (which calls the new version if not detailed).
Example URL WITH Version: https://localhost:8243/test/2.0.0/token/.well-known/jwks.json
Example URL WITHOUT Version: https://localhost:8243/test/token/.well-known/jwks.json

Until update level 4.1.0.77, GET resource of that API WORKS, detailling the 2.0 in the url or not.

After updating to update level 78 onwards (tested on level 82), the API ONLY works if the version is specified in the URL. If it is not specified, even if it worked before, now it returns an error in the logs.
Example URL WITH Version: Works
Example URL WITHOUT Version:
INFO {org.apache.synapse.mediators.builtin.LogMediator} - STATUS = Message dispatched to the main sequence. Invalid URL., RESOURCE = /test/token/.well-known/jwks.json, HEALTH CHECK URL = /test/token/.well-known/jwks.json

Even if I delete all the different API versions and leave only 1, if I don't specify it in the url, it won't work.

Issue seems to be for the requests of default APIs containing /jwks in the path follows the newly introduced path yielding the error.

Thanks and regards,
Alexis. 

### Steps to Reproduce

1. Create an API with a GET resource, which endpoint path should include /jwks.
2. Update to version 4.1.0.78 or later.
3. Create a new version of that API and set it as default version.
4. Call that API without specifying the version in the URL.

### Affected Component

APIM

### Version

4.1.0.78 (onward)

### Relevant Log Output

```shell
INFO {org.apache.synapse.mediators.builtin.LogMediator} - STATUS = Message dispatched to the main sequence. Invalid URL., RESOURCE = /test/token/.well-known/jwks.json, HEALTH CHECK URL = /test/token/.well-known/jwks.json
```

**Comment by YasasRangika** [comment]
Closing this as this issue is not reproducing in the master branch.
