### ISSUE TITLE
Missing J2 mapping for the <phase> config on the "axis2_blocking_client.xml" - MI 1.2.0

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/api-manager#1928]
### Description

Need to add custom handlers to the axis2_blocking_client.xml" file on MI 1.2.0 product.

  <phase name="Dispatch" class="org.apache.axis2.engine.DispatchPhase">
: 
<handler name="SynapseMustUnderstandHandler"
                     class="org.apache.synapse.core.axis2.*************UnderstandHandler"/>
        </phase>
<phase name="Dispatch" class="org.apache.axis2.engine.DispatchPhase">
: 
<handler name="SynapseMustUnderstandHandler" class="org.apache.synapse.core.axis2.***********UnderstandHandler"/>       
        </phase>

However, if we checked the j2 file of "axis2_blocking_client.xml" file, we didn't see the particular J2 mapping to add a handler to the configuration section.

Need to port this fix[1] to MI 1.2.0.

[1]. https://github.com/wso2/micro-integrator/pull/2850

### Steps to Reproduce

Check the J2 files

### Affected Component

MI

### Version

1.2.0

**Comment by YasasRangika** [comment]
This issue has already been resolved in the master branch.
