### ISSUE TITLE
Token revocation event is not receiving through the event_duplicate_url - APIM 4.0.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/api-manager#1935]
### Description

When deploying a HA control plane cluster with gateway nodes, all the gateway nodes are not getting the token revocation event and hence, some of the gateways are allowing the API requests with the revoked access token.

### Steps to Reproduce

- Configure a 6 node deployment. (Attached the diagram below)
   - 2TM nodes
   - 2GW nodes
   - 2CP nodes

![245816961-5aa2d8c8-aae3-4c13-8082-68bee001a7aa](https://github.com/wso2/api-manager/assets/18566908/c5a7fa2d-5113-48d8-acd8-5bf07a9c9b0f)

- Configure the below log level in the **log4j2.properties** file of both the gateway nodes.
```
logger.GW_LOGS.name = org.wso2.carbon.apimgt.gateway
logger.GW_LOGS.level = DEBUG
```
- Start all the nodes and go to the one of the dev portal node.
- Generate access tokens few times and able to see the token revocation event only 1 gateway node.

### Affected Component

APIM

### Version

4.0.0

**Comment by lasanthaS** [comment]
The update is in `UATStaging` state now.
