### ISSUE TITLE
Throttling policies are getting undeployed before retrieving policies - APIM 4.0.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/api-manager#1936]
### Description

Traffic Manager is undeploying throttling policies before calling to the CP node to retrieve policies via the event hub service URL

### Steps to Reproduce

- Open the **log4j2.properties** file inside the **<APIM_HOME>/repository/conf** directory.
- Enable the **org.apache.http.wire** level **DEBUG** logs.
- Start the server.
- Able to see that the node is undeploying all the deployed throttling policies before making the service call to retrieve policies. Therefore, the throttling will not work until the node is deploying the retrieved policies.

### Affected Component

APIM

### Version

4.0.0

**Comment by GihanAyesh** [comment]
The fix PR: https://github.com/wso2/carbon-apimgt/pull/12074
