### ISSUE TITLE
Overflowing variable in the class 'EventListMapManager'.

### ISSUE THREAD

**Issue by janithcmw** [wso2/api-manager#1940]
### Description

It seems there is a possibility to observe an 'Overflowing' scenario if the debug logs are enabled for the class, 'org.wso2.carbon.streaming.integrator.core.event.queue.EventListMapManager'[1].

[1] https://github.com/wso2/carbon-analytics/blob/v3.0.69/components/org.wso2.carbon.streaming.integrator.core/src/main/java/org/wso2/carbon/streaming/integrator/core/event/queue/EventListMapManager.java#L52

### Steps to Reproduce

Enable the debug logs for the subjected class and allow the variable to overflow by switching the Active Passive state of a WSO2SI HA cluster. 

### Affected Component

SI

### Version

1.1.0

**Comment by YasasRangika** [comment]
This issue has already been resolved in the master branch.
