### ISSUE TITLE
APIM Analytics report shown mismatch result for same period with different granularities. 

### ISSUE THREAD

**Issue by ug205** [wso2/api-manager#1941]
### Description

Analytics report shown mismatch result for same period with different granularities. 
This is because the duration selected through the dashboard, and the aggregation execution are in two different time zones.

### Steps to Reproduce

Configure Analytics and populate with data.
Navigate to dashboard and select the time range and select different granularity levels.
Observe the differences for the same duration but  different granularity levels.

### Affected Component

Analytics

### Version

3.2.0

**Comment by YasasRangika** [comment]
Public fix PR: https://github.com/wso2/analytics-apim/pull/1545
