### ISSUE TITLE
Deleted Key Manager usages are not delete completely from APIM 4.2.0

### ISSUE THREAD

**Issue by VinulaUthsara** [wso2/api-manager#1943]
### Problem

When a Key Manager is created and then deleted from the APIM Admin portal, its usages are not completely cleared/deleted from the APIM which allows users to keep using the deleted Key Manager which leads to 401 Invalid Credentials when we choose the option of allowing a selected Key Manager for an API (Publisher portal -> API configurations -> Runtime -> Key Manager Configurations -> Allow selected).

This leads to a behavior which shows that the deleted Key Managers are cached within the API Manager and is not reset. The only way to clear this is to select Allow All and re-select Allow Selected.

During the Key Manager deletion there is no warning or indication to alert the user that the Key Manager being deleted has current usages and will cause an issue (similar to how the UI warns the user when an API which is subscribed to by applications is being deleted).

### Solution

It is best if this can be improved to delete all usages or existing usages in the APIM which can prevent this sort of caching behavior, since all usages are deleted once a Key Manager is deleted the user should be warned to either first remove all current usages of the Key Manager before deletion or alert the issue that since this is deleted all current usages will not work further.

### Affected Component

APIM

### Version

4.2.0

### Suggested Labels

4.3.0

**Comment by tharikaGitHub** [comment]
Closing as the public fixes are merged.
