### ISSUE TITLE
Cannot build the dev portal jaggeryapps (Advanced UI customization) - APIM 4.1.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/api-manager#1948]
### Description

Cannot build the dev portal component due to missing files and hence able to see the no ESLint error.

### Steps to Reproduce

- Take the APIM pack.
- Inside the **<APIM_HOME>/repository/deployment/server/jaggeryapps** directory, execute the below 2 commands.

```
npm install

npm run bootstrap
```

- Inside the **<APIM_HOME>/repository/deployment/server/jaggeryapps/devportal** directory, execute the below command and able to see the error.

```
npm run build:prod
```

### Affected Component

APIM

### Version

4.1.0

**Comment by shafik21** [comment]
i face the same issue
