### ISSUE TITLE
Unable to save resources for API

### ISSUE THREAD

**Issue by dinithnirman** [wso2/api-manager#1949]
### Description

Hi Team

After performing an update of WSO2AM (WSO2 API Manager) version 4.1 from U2 level 70 to level 83, we have encountered an issue regarding the saving of changes made in the 'Resources' tab for any registered APIs. It has been observed that the changes made in this tab are not being saved successfully. However, it should be noted that the changes made to the sample PizzaShackAPI were successfully saved.

Analysis
We have identified that the issue happened to APIs without the "securitySchemes" tag. Since the sample API (PizzaShackAPI) contains the "securitySchemes" tag, it allows saving the 'Resources' changes.

We have setup this locally and are able to reproduce the issue. Please refer to the below update levels which we tested this issue.

- wso2am-4.1.0 vanilla pack: Does not reproduce the issue and working fine
- wso2am-4.1.0 level 83: Reproduced the issue
- wso2am-4.1.0 level 85 (latest): Reproduced the issue

### Steps to Reproduce

- Get a updated wso2am-4.1.0 pack
- Create an API (API should not have "securitySchemes" tag in the API definition)
- Try to add Resources and save.
- Changes won't save and you will be able to see the below error in the browser console.

![error](https://github.com/wso2/api-manager/assets/31001784/8c53095e-fc02-4357-84f0-8fe4f43cd1c6)

### Affected Component

APIM

### Version

4.1.0

### Related Issues

[https://github.com/wso2-enterprise/wso2-apim-internal/issues/3522](url)

### Suggested Labels

Affected/APIM-4.1.0

**Comment by YasasRangika** [comment]
As mentioned in the linked internal ticket, this issue does not affect the master branch.
