### ISSUE TITLE
Payload encoding disappears after a restart

### ISSUE THREAD

**Issue by iloshinik** [wso2/api-manager#1955]
### Description

When a SOAP payload is formulated with CDATA and restart the server, we could see that the payload lost its encoding. This is resolved after updating and saving the API.

### Steps to Reproduce

1. Add below parameter to deployment.toml.
```
[xml_input_factory.properties]
"javax.xml.stream.isCoalescing" = false
```
2. Start the APIM Server.
3. Create a sample API with a POST method (with body parameter). For In flow, add a custom sequence that formulates a soap message that includes the CDATA tag and a Log Full mediator.
4. Send the request.
5. We could see the Log Full with encoding as expected.
6. Restart the server.
7. Again send a request with the same body as in the 4th step. Then could see the Log full without encoding.
8. Then edit the API, save it, and send a request again. The output is received similarly to the 5th step with encoding.

### Affected Component

APIM

### Version

3.2.0

### Suggested Labels

apim

**Comment by dulithsenanayake** [comment]
Closing this ticket since the update is released.
