### ISSUE TITLE
Accessing TelemetryTracer via custom class mediator

### ISSUE THREAD

**Issue by Thidasala** [wso2/api-manager#1960]
### Problem

In a case where we need to implement a mechanism to calculate the execution time for class mediator logic and display the time as a span in OTLP tracer, we have to deal with the TelemetryTracer in the appropriate methods, similar to the implementations done in [1].

In order to facilitate accessing the TelemetryTracer from a custom class mediator, It is required to provide a utility method that resides in the `org.wso2.carbon.apimgt.gateway` package and returns the TelemetryTracer, since the `org.wso2.carbon.apimgt.gateway.internal.ServiceReferenceHolder` has not been exposed from the `org.wso2.carbon.apimgt.gateway` bundle.  

[1] https://github.com/wso2/carbon-apimgt/blob/fdd00e7a8130612c6b49a8500b85fea96d6df9c2/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/CORSRequestHandler.java#L135

### Solution

Create a utility method to expose `org.wso2.carbon.apimgt.gateway.internal.ServiceReferenceHolder`

### Affected Component

APIM

### Version

4.2.0

**Comment by YasasRangika** [comment]
Closing as the public fix: https://github.com/wso2/carbon-apimgt/pull/12069 has already been merged.
