### ISSUE TITLE
[APIM][320] Load balancer endpoint security configuration

### ISSUE THREAD

**Issue by kaushi2142** [wso2/api-manager#1962]
### Description

Unable to set the "Endpoint Security Configurations" for load balancer endpoints in APIM 3.2.0.

### Steps to Reproduce

1. Log in to Publisher Portal and create a new API
2. Go to Endpoints > Load balance and Failover Configurations
3. Select Endpoint Type as 'Load Balanced'
4. Enter a value for Service URL and click '+'
5. Attempt to set Endpoint Security Configurations by click on the "shield" button
6. No popup displayed

### Affected Component

APIM

### Version

wso2am-3.2.0

### Related Issues

https://github.com/wso2-enterprise/wso2-apim-internal/issues/3563

**Comment by HiranyaKavishani** [comment]
Hi @kaushi2142, 

This is not a bug as it's the expected behavior to apply the endpoint security configuration globally for production and sandbox endpoints. Therefore, We will hide the sec button for the failover/load-balanced endpoints.

Thanks!
Hiranya
