### ISSUE TITLE
API validation getting failed in the basic authentication when updating local scopes 

### ISSUE THREAD

**Issue by nelkon** [wso2/api-manager#1987]
### Description

When updating(disabling and enabling) the basic authentication the JMS events have been sent in the wrong order hence the created local scopes have been removed from the memory of gateway nodes. Then the API invocation returns "scope validation failed, code:900910"

### Steps to Reproduce

1. Create a user and assign a role for the user
2. In the publisher create a local scope and assign the role which is created in step 1.
3. Restrict a resource with the above local scope and publish the API along with basic authentication.
4. Restart the server.
5. Go to the API run time configuration in the publisher portal and quickly disable and enable basic auth then save and deploy.
6. Invoke the API with the basic auth

### Affected Component

APIM

### Version

4.1.0

### Suggested Labels

APIM

**Comment by YasasRangika** [comment]
The public fix needs to be merged: https://github.com/wso2/carbon-apimgt/pull/12090
