### ISSUE TITLE
Need to remove the authentication from the server-startup-healthcheck endpoint - APIM 4.1.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/api-manager#1996]
### Description

Currently, we need to parse the basic authorization header for this **server-startup-healthcheck** API [1] call to see whether all the APIs got deployed in the gateway level. But this is kind of a health check endpoint and therefore, no need to have the authorization mechanism for this.

[1] https://apim.docs.wso2.com/en/4.1.0/reference/product-apis/gateway-apis/gateway-v2/gateway-v2/#/paths/~1server-startup-healthcheck/get

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
Merge-pending public PR: https://github.com/wso2/carbon-apimgt/pull/12213
