### ISSUE TITLE
Changing 'sendCookiesInRequests' property in deployment.toml.

### ISSUE THREAD

**Issue by shavinsenadheera** [wso2/api-manager#1999]
### Problem

In the context of providing a solution for integrating SSO on MI-4.1.0 with Azure AD, there is a need to change the value of the "sendCookiesInRequests" property. This change helps to address a CORS issue that occurred on the MI Dashboard when logging in via SSO.

When "sendCookiesInRequests" is set to false, the "Credentials" property of the fetch request is changed to "same-origin" instead of "include". This modification ensures that the client application (MI Dashboard) sends the origin header in the request. Including the origin header allows Microsoft Azure to respond with the "Access-Control-Allow-Origin" header, enabling access for all domains (*).

Currently, the property needs to be changed from the "config.js.j2" file, following these steps:

Locate the "<MI_DASHBOARD_HOME>/conf/config-parser/templates/server/www/conf/config.js.j2" file.
Open the file in a text editor.

Add the following property:

sendCookiesInRequests: false,

![Screenshot from 2023-07-07 10-13-43](https://github.com/wso2/api-manager/assets/42552426/f40d65a3-24f6-4ffe-8e25-5ee13e6c1155)

### Solution

Need a way to change this property from the deployment.toml file.

### Affected Component

MIDashboard

### Version

4.1.0

**Comment by YasasRangika** [comment]
This issue has already been fixed in the master branch.
