### ISSUE TITLE
High heap consumption in APIM 3.2 gateways due to Endpoint Mbeans.

### ISSUE THREAD

**Issue by Menuka-Senevirathne** [wso2/api-manager#2000]
### Problem

The endpoint-jmx-stat-collector has consumed a considerable amount of heap memory in APIM 3.2.0. Currently it's not possible to disable Endpoint Mbeans. 

### Solution

Introduced a new synapse property to disable endpoint view Mbean creation which can be configured through synapse.properties.

synapse.jmx.endpoint.view.enabled=false

### Affected Component

APIM

### Version

3.2.0

### Related Issues

https://github.com/wso2/product-apim/issues/11566

### Suggested Labels

apim

**Comment by HiranyaKavishani** [comment]
Closing the issue as this is tracked via issue[1].

[1] https://github.com/wso2/product-apim/issues/11566
