### ISSUE TITLE
chpasswd not working

### ISSUE THREAD

**Issue by lucas-wso2** [wso2/api-manager#2004]
### Description

The chpasswd.sh tool is not working properly, giving this error:

`Error: Could not find or load main class org.wso2.carbon.core.util.PasswordUpdater
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.core.util.PasswordUpdater`

Observation: 
We have tested with the MI 4.1.0. and MI 4.2.0 and both are giving the same error.

### Steps to Reproduce

Go to `<MI_4.1.0_HOME>/bin`
Execute `sh chpasswd.sh`

### Affected Component

MI

### Version

4.1.0.56

### Environment Details (with versions)

MI 4.1.0.56
macOS Ventura 13.4.1

### Relevant Log Output

```shell
lucas@lucas bin % sh chpasswd.sh
Buildfile: /Users/lucas/Documents/wso2/zip-files/wso2mi-4.1.0/bin/build.xml
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.

setup:
     [copy] Copying 32 files to /Users/lucas/Documents/wso2/zip-files/wso2mi-4.1.0/wso2/lib
    [mkdir] Created dir: /Users/lucas/Documents/wso2/zip-files/wso2mi-4.1.0/wso2/tmp/setup
   [delete] Deleting directory /Users/lucas/Documents/wso2/zip-files/wso2mi-4.1.0/wso2/tmp/setup
     [move] Moving 31 files to /Users/lucas/Documents/wso2/zip-files/wso2mi-4.1.0/wso2/lib

BUILD SUCCESSFUL
Total time: 0 seconds
Error: Could not find or load main class org.wso2.carbon.core.util.PasswordUpdater
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.core.util.PasswordUpdater
```

**Comment by YasasRangika** [comment]
Public fix: https://github.com/wso2/micro-integrator/pull/2901 has already been merged into the master branch.
