### ISSUE TITLE
Filterbox in the subscription list in the publisher displays values only in the current page

### ISSUE THREAD

**Issue by Kirishikesan** [wso2/api-manager#2006]
### Description

Filterbox in the subscription list in the publisher is only displaying values which are in the current page. All the values in the subscription list should populate the filterbox.

### Steps to Reproduce

1. Publish an api
2. Create two users 
3. Subscribe to the api multiple times through different applications : To create 2 or more pages in the subscription list
4. Go to subscriptions page for the api in Publisher portal.
5. Try to filter the Subscriptions based on the values available on the second page

### Affected Component

APIM

### Version

4.2.0

**Comment by nimsara66** [comment]
This is not reproducible in APIM 4.3.0

If you encounter this problem again or have any additional concerns, please feel free to reopen the issue or create a new one.
