### ISSUE TITLE
Need to remove the authentication from Health Check APIs

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/api-manager#2009]
### Description

In API Manager, we can check the health as below:

```
curl -k --header "content-type: text/soap+xml; charset=utf-8" -H "SOAPAction: urn:getServerStatus" --basic -u "$API_ADMIN_USER:$API_ADMIN_PASSWORD" -d @- https://localhost:9443/services/ServerAdmin?wsdl<<<'<soapenv:Envelope xmlns:soapenv=http://schemas.xmlsoap.org/soap/envelope/ xmlns:xsd=http://org.apache.axis2/xsd>
<soapenv:Header/>
	<soapenv:Body>
		<xsd:getServerStatus/>
	</soapenv:Body>
</soapenv:Envelope>'
```

However, when this is done, a server authentication happens. If in case there is a DB error or an issue with the key manager component, the health check will fail even if the services are supposed to run.
A health check API should ideally not do any DB transactions.

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

4.0.0

### Environment Details (with versions)

N/A

### Relevant Log Output

```shell
N/A
```

### Related Issues

- https://github.com/wso2/api-manager/issues/1996

### Suggested Labels

patch

**Comment by YasasRangika** [comment]
Need to merge the master PR: https://github.com/wso2/carbon-apimgt/pull/12213

**Comment by tharikaGitHub** [comment]
Closing as the master PR is merged.
