### ISSUE TITLE
Make keystore file locations configurable as absolute paths in the new config model

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#2012]
### Problem

In APIM 2.6.0, customers can point to a JKS residing in any location of the file system but due to the way it was written in the new config model, customers have to store the JKS files only inside the repository/resources/security directory. We need to make the keystore file locations configurable to an absolute path. 

### Solution

With the new configuration model, default key store location is hardcoded to the repository/resources/security path in several locations.
From deployment.toml we can set only the file_name and internally it derives the file path by appending the carbon.home and 'repository/resources/security'

 ex: ${carbon.home}/repository/resources/security/$ref{keystore.tls.file_name}

repository/resources/security/listenerprofiles.xml

repository/resources/security/sslprofiles.xml

/repository/resources/conf/axis2/axis2_TM.xml

Above files refer tls keystore w.r.t. the carbon.home <Location>repository/resources/security/wso2carbon.jks</Location>
These files can be fixed to refer an absolute path by changing the template files.

Where as other files refer the keystore file path including carbon.home as in the above example.

Similarly we will need to fix all the other files that refer keystore.
tls , primary and internal

### Affected Component

APIM

### Version

3.x, 4.x

**Comment by nisan-abeywickrama** [comment]
The keystore location is hardcoded to the repository/resources/security path to prevent security risks associated with having keystore files scattered throughout the system.

As a result, there is no need for the following requirement to resolve to the absolute path.

Therefore, this issue can be closed since the current implementation meets the expected requirement.
