### ISSUE TITLE
Integrator studio have soap to rest conversion issue

### ISSUE THREAD

**Issue by asithamadhushanka12** [wso2/api-manager#2018]
### Description

HI Team,

Below issues observed regarding SOAP to REST conversion and you can follow the below steps to reproduce the issue.

- While creating rest api using wsdl file, In Generated swagger we can see that rootElement_ is getting added for all the schemas but while reference it is applying only for request, not for the response.
- 'Default_Object' added when reading elements that contain '-' character.

### Steps to Reproduce

- Use wsdl file which contains '-' character in schema. 
- Generate an API with this wsdl file(browse the wsdl file and import it to the ESB project).
- Go to the generated API and search for the relevant resource and check the swagger definition.

### Affected Component

IntegrationStudio

### Version

8.2.0

**Comment by YasasRangika** [comment]
public fixes: https://github.com/wso2/soap-to-rest/pull/11
https://github.com/wso2/integration-studio/pull/1227 has already been merged.
