### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0 error when trying to commit in SI 1.1.0

### ISSUE THREAD

**Issue by ug205** [wso2/api-manager#2021]
### Description

Following issue when trying to use the commit function in SI 1.1.0 after reading data from one database and inserting into another when the event chunk is a batch of multiple events.

### Steps to Reproduce

Create siddhi application to insert and commit data into the database by reading from another database

### Affected Component

SI

### Version

1.1.0

**Comment by YasasRangika** [comment]
public PR: https://github.com/siddhi-io/siddhi-store-rdbms/pull/249

**Comment by lasanthaS** [comment]
Fixed in public. Hence closing this issue.
