### ISSUE TITLE
Missing "Third Party" Indicator in API Thumbnail - APIM 4.1.0.79

### ISSUE THREAD

**Issue by JanithaSampathBandara** [wso2/api-manager#2025]
### Description

Hi Team,

### Description

Once we mark the API as a Third Party API [1] from the Publisher portal, the indicator “Third Party” is visible within the API thumbnail as expected.

![third-party-tag](https://github.com/wso2/api-manager/assets/54787843/74535647-1180-4ea6-be16-6f163870e6f6)

But once we search for the same API, the indicator is getting disappeared.

### Steps to Reproduce

1. Create an API called “TestAPI”.
2. Mark the API as “third party” from the “Basic Info” page of Publisher portal.
3. Navigate to APIs page of the Publisher portal and you will see the Indicator “Third Party” is added to the API thumbnail successfully.
4. Type "TestAPI" in the search bar and press enter.
5. We can observe that the Indicator “Third Party” is not visible anymore within the API thumbnail.

### Affected Component

APIM

### Version

4.1.0

**Comment by HiranyaKavishani** [comment]
Closing the issue since the fix is already there in the master branch
