### ISSUE TITLE
Cannot start the API Manager server with the JDK 17.0.8 version - APIM 4.2.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/api-manager#2029]
### Description

Cannot start the API Manager server with the JDK 17.0.8 version and throwing some OGSi bundle loading issues during the server startup.

### Steps to Reproduce

- Start the API Manager 4.2.0 distribution on top of the JDK 17.0.8 version.

### Affected Component

APIM

### Version

4.2.0

**Comment by TomasTokaMrazek** [comment]
JDK 11.0.20 and JDK 17.0.8 enabled additional ZIP header verification.

Some of the component jars in distribution have those header wrong. Try to run the product with -Djdk.util.zip.disableZip64ExtraFieldValidation=true
