### ISSUE TITLE
Support to map multiple internal roles for a custom role - Admin UI - APIM 4.1.0

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/api-manager#2036]
### Problem

The current APIM Admin UI has a limitation in mapping multiple internal roles for a custom role. However, it's possible to do this through the RESTFull API[1]. Therefore this capability needs to add to the admin UI. 

[1]. https://apim.docs.wso2.com/en/4.1.0/reference/product-apis/admin-apis/admin-v3/admin-v3/#tag/System-Scopes/paths/~1system-scopes~1role-aliases/put

### Solution

Have to change the alias drop-down to a multi-select [1]

[1]. https://v4.mui.com/components/selects/#multiple-select

### Affected Component

APIM

### Version

APIM 4.1.0

**Comment by dulithsenanayake** [comment]
Hi all,

Closing this since the update has been released. 

Thanks!
Dulith
