### ISSUE TITLE
Disable "Next" button when having UI error on Scope-Role mapping UI on Admin UI - APIM 4.1.0

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/api-manager#2037]
### Description

Currently, Admin UI doesn't support mapping multiple internal roles to a custom role. If we try to do that, it shows a UI error. However, it still allows us to click the "Next" button. This "Next" button needs to be disabled if the UI shows an error.

<img width="1035" alt="Screenshot 2023-07-27 at 09 30 04" src="https://github.com/wso2/api-manager/assets/15210142/22e08610-b311-49d5-9d53-afe602035fc1">

### Steps to Reproduce

1. Log to the Admin UI
2. Tried to map multiple internal roles for a custom role through the Admin UI 
3. In the Second attempt, you will see the UI error when mapping the internal role.
4. And we possible to click next button even we have a UI error. 

### Affected Component

APIM

### Version

APIM 4.1.0

**Comment by dulithsenanayake** [comment]
Hi all,

Closing this since the update has been released. 

Thanks!
Dulith
