### ISSUE TITLE
Unable to start APIM 4.1.0 with JVM 11.0.20 version

### ISSUE THREAD

**Issue by isurul28** [wso2/api-manager#2038]
### Description

Hi Team,
When we start the APIM 4.1.0 pack with the latest update level 90 with JVM version 11.0.20-amzn we get OSGI bundle resolving error. When we downgrade the JVM version to 11.0.19 we are able to start the pack.

Steps to reproduce :

Get 11.0.20-amzn JVM and set it as the default JVM
Start the APIM 4.1.0 pack and you will see the errors

### Steps to Reproduce

Get 11.0.20-amzn JVM and set it as the default JVM
Start the APIM 4.1.0 pack and you will see the errors

### Affected Component

APIM

### Version

4.1.0.90

### Environment Details (with versions)

 JVM version 11.0.20-amzn

**Comment by YasasRangika** [comment]
merge pending public PR: https://github.com/wso2/product-apim/pull/13261
