### ISSUE TITLE
Disable the http_access log in APIM-3.2.0

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/api-manager#2044]
### Description

We are looking for a way to disable the access logs for the HTTP Servlet transport in the gateway profile of APIM-3.2.0.

We observed that there is no specific `deployment.toml` configuration to disable access logs for the HTTP Servlet transport.

We found the `deployment.toml` configuration was added for APIM-4.0.0

```
[http_access_log]
enabled = true
```

Please do backport this for API Manager 3.2.0 as well

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

3.2.0.289

### Suggested Labels

patch

**Comment by Lakith-Rambukkanage** [comment]
The fix is already added with https://github.com/wso2/product-apim/pull/13082, hence closing the public issue.
