### ISSUE TITLE
Api Manager 4.1.0 WWW-Authenticate header value : null Basic Auth

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/api-manager#2046]
### Description

Hi,
When a request with no authentication header is sent to the gateway the WWW-Authenticate header value contains a “null” value. I tested the same in 4.0.0 version and 3.2.0 and this “null” is not returned, check some samples below:
WWW-Authenticate header value

**Api Manager 3.2.0**
- Basic -> Basic Auth realm="WSO2 API Manager", error="invalid_token", error_description="The access token expired"
**Api Manager 4.0.0:**
- Basic -> Internal API Key realm="WSO2 API Manager", Basic Auth realm="WSO2 API Manager", error="invalid_token", error_description="The provided token is invalid"
- Oauth + Basic -> Internal API Key realm="WSO2 API Manager", Bearer realm="WSO2 API Manager", Basic Auth realm="WSO2 API Manager", error="invalid_token", error_description="The provided token is invalid"
**Api Manager 4.1.0:**
- Basic -> null Basic Auth realm="WSO2 API Manager", error="invalid_token", error_description="The provided token is invalid"
- Oauth + Basic -> null Bearer realm="WSO2 API Manager" Basic Auth realm="WSO2 API Manager", error="invalid_token", error_description="The provided token is invalid"

As per my understanding the null should be removed

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

4.1.0

### Suggested Labels

patch

**Comment by msm1992** [comment]
Public PR : https://github.com/wso2/carbon-apimgt/pull/11251
