### ISSUE TITLE
Unable to add the "initAxis2ClientOptions" property for the call/callout mediator in Integration studio

### ISSUE THREAD

**Issue by Thidasala** [wso2/api-manager#2051]
### Description

When we are configuring NTLM authentication[1], It is required to add the initAxis2ClientOptions="false" property for the call/callout mediator. However there is no option to set the "initAxis2ClientOptions" property to the call mediator using integration studio

<img width="770" alt="Screenshot 2023-08-01 at 15 13 22" src="https://github.com/wso2/api-manager/assets/45654571/31ec3841-cea9-4ec4-b3c7-1e9bb2a5fec8">

[1]https://apim.docs.wso2.com/en/4.1.0/reference/mediators/ntlm-mediator/

### Steps to Reproduce

1. Configure NTLM authentication flow by referring to the documentation [1] with integration studio
[1]https://apim.docs.wso2.com/en/4.1.0/reference/mediators/ntlm-mediator/#example

### Affected Component

IntegrationStudio

### Version

8.2.0

**Comment by YasasRangika** [comment]
Public fix: https://github.com/wso2/integration-studio/pull/1231 as already been merged.
