### ISSUE TITLE
[EI 6.6.0] Pagination not working in Dynamic sequences tab

### ISSUE THREAD

**Issue by PasinduGunarathne** [wso2/api-manager#2061]
### Description

Hi Team,

We may need to fix the below issue in EI management console when navigating between pages in Dynamic Sequences tab. Please follow the below steps to reproduce this issue.

### Steps to Reproduce

1. Open EI managemenment console and go to Sequences > Add Sequnce tab
2. Create 10+ dynamic sequnces
3. Then Click on any of the pagination buttons
4. Next, click on the Dynamic sequences tab

### Expected behaviour 

- After the 3rd step you should be redirected to the any of pagination tab(according to the selection of next/prev/last/first) in Dynamic sequences tab

### Current behaviour

- After the 3rd step you will be redirected to the Defined sequences tab

Further we notice that it will only redirect to the Defined sequences tab and however the selection we made persists on the Dynamic sequences tab since after coming back to the Dynamic sequences tab you can see that the pagination tab(according to the selection of next/prev/last/first).

Please refer to the JSP page[1] below for the implementation in carbon-mediation project.

[1] https://github.com/wso2/carbon-mediation/blob/v4.7.30/components/mediation-ui/org.wso2.carbon.sequences.ui/src/main/resources/web/sequences/list_sequences.jsp#L789-L795

### Affected Component

EI

### Version

6.6.0

**Comment by YasasRangika** [comment]
This issue does not affect the master branch.
