### ISSUE TITLE
Engaging an Approval Workflow when deploying a revision - APIM 4.3.0

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/api-manager#2070]
### Problem

There is no workflow to approve for API revision create. creation

### Solution

Engaging an Approval Workflow when deploying a revision for an API

### Affected Component

APIM

### Version

4.3.0

**Comment by Kamidu** [comment]
@dushaniw Do you have an ETA on the APIM 4.3.0 Release?

**Comment by dushaniw** [comment]
No we dont have any specific dates planned yet. As of now the plan is for Q1 2023.

**Comment by Kamidu** [comment]
> No we dont have any specific dates planned yet. As of now the plan is for Q1 2024. Please note its not finalized yet.

Thank you for the prompt response Dushani 👍

**Comment by GihanAyesh** [comment]
The feature progress will be tracked via https://github.com/wso2/api-manager/issues/2137
Closing since duplicated.
