### ISSUE TITLE
FTP connection retry and timeout null warning

### ISSUE THREAD

**Issue by TomasWso2** [wso2/api-manager#2074]
### Description

The following warning appears while the proxy polls the file via FTP using <parameter name="transport.vfs.FileURI"> and not the file connector.

WARN {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory} - Invalid connection timeout null. Set the connectionTimeout as 5000. (default) 
WARN {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory} - Invalid connection retry count null. Set the connectionRetryCount as 5. (default)

We identified a fix was done for MI 4.X.X  ( https://github.com/wso2-enterprise/wso2-apim-internal/issues/3603 , https://github.com/wso2-enterprise/wso2-apim-internal/issues/3752 , https://github.com/wso2-enterprise/wso2-apim-internal/issues/3753 )

I suspect this is still the same issue with the FTP connection being created with some parameters being passed as null.
Could we backport the fix to MI 1.2.0 ?

### Steps to Reproduce

- Create a file connector-based carbon application from the integration studio.
- Here, we need to use the FTP protocol since the issue does not reproduce in the SFTP protocol due to differences in the implementation.
- Invoke the API. The mentioned warning will be printed in the logs.

### Affected Component

MI

### Version

1.2.0

### Relevant Log Output

```shell
WARN {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory} - Invalid connection timeout null. Set the connectionTimeout as 5000. (default) 
WARN {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory} - Invalid connection retry count null. Set the connectionRetryCount as 5. (default)
```

### Related Issues

https://github.com/wso2/api-manager/issues/1969

**Comment by YasasRangika** [comment]
This issue has already been resolved in the master branch.
