### ISSUE TITLE
MI 1.2.0 fails if updated from update level 0

### ISSUE THREAD

**Issue by imsuneth** [wso2/api-manager#2076]
## Problem

Hi all,

We are following the instructions given in [1] when providing U2 base packs for customers.
This issue is regarding the MI 1.2.0 base pack downloaded from the s3 location given in the doc.

When we take a full update from level 0 to 136 ( latest ). Server is not starting correctly giving errors. Cause for this errors is snakeyaml dependency is not getting updated to 2.0.0 correctly.

Snakeyaml update from 1.33 to 2.0.0 is done is update level 129
If we update the base pack to level 129 we can see the snakeyaml is updated to 2.0.0 correctly. But if we take 136 we get the above issue.

As a test I first updated the pack to level 125 and then updated to 136 which resolves the issue.

Shall we update the MI 1.2.0 pack hosted in s3 bucket location in [1] before a customer also face this issue.

[1] https://docs.google.com/document/d/1y4me2dXuK4r7G3GQpToWhXr2_qdXr8_i6g2rovh5kNg/edit

## Solution:

In order to avoid this behavior happening for both the users who are already in U2 and who will migrate to U2 from the latest WUM updated pack in future, please do create an update with the following changes.

Remove wso2/components/plugins/snakeyaml_1.33.0.wso2v1.jar
Remove wso2/components/plugins/org.yaml.snakeyaml_1.33.0.jar
Add manual bundles info entry relavant to the wso2/components/plugins/org.yaml.snakeyaml_2.0.0.jar

### Affected Component

MI

### Version

1.2.0

**Comment by YasasRangika** [comment]
This issue has already been resolved in the master branch.
