### ISSUE TITLE
Cannot view API resources of the migrated APIs

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/api-manager#2080]
### Description

Cannot view API resources or download the API which was migrated from old version to the API Manager 4.1.0 due to the missing security definition of the swagger content. But this was worked previously.

### Steps to Reproduce

- Start the pack and go to the publisher portal.
- Create an API by using the attached swagger definition content. [1]
- Then go to the carbon management console.
- Browse the swagger file of the API through the registry resources browsing.
- Change the swagger file content by replacing with the attached file content. (Because when migrating APIs, we are not doing anything to the swagger definition and hence, we need to keep the old definition)
- Then save it.
- Go back to the publisher portal and try to load the Resources section or try to download the API.

[1] 
[new-not-working-api.txt](https://github.com/wso2/api-manager/files/12287651/new-not-working-api.txt)

### Affected Component

APIM

### Version

4.1.0

**Comment by Lakith-Rambukkanage** [comment]
Fixed by : https://github.com/wso2/carbon-apimgt/pull/12102/files#diff-8a21aa587423ad2248a05927197442d9f98436f3997c52a507cd530c213258a8
