### ISSUE TITLE
 Devportal API - Get Swagger Definition fetches Backend Endpoints

### ISSUE THREAD

**Issue by VinulaUthsara** [wso2/api-manager#2090]
### Description

When we use the “Get Swagger Definition” resource of the Developer Portal REST API [1] the production and sandbox endpoints are being returned in the response which is the swagger.

When importing the swagger via the APIM Publisher UI and after publishing the API we invoked the Get Swagger Definition resource from the Developer REST APIs and we did not observe the sandbox and production endpoints in the response.

However, when importing the API to the APIM using the APICTL tool and then invoking the “Get Swagger Definition” [1] we are able to observe the following in the response:

```
"x-wso2-production-endpoints": {
"urls": [
"https://run.mocky.io/v3/237623672"
],
"type": "http"
},
"x-wso2-sandbox-endpoints": {
"urls": [
"https://localhost:9443/am/sample/pizzashack/v1/api/"
],
"type": "http"
},
```

### Steps to Reproduce

To reproduce the issue we followed the following steps:

1. Download APIM 3.2.0 and APICTL 3.2.0
2. Download the PizzaShack API or any sample API with endpoints added
3. Create an environment and import the API using APICTL
4. Invoke the Developer Portal REST API -> Get Swagger Definition resource [1]
5. Production and Sandbox endpoints will be returned in the swagger definition.

### Affected Component

APIM

### Version

3.2.0

### Suggested Labels

3.2.0

**Comment by HeshanSudarshana** [comment]
Closing the issue since this change is not required in master since the MGW related vendor extensions are removed when importing an API through APICTL.
