### ISSUE TITLE
Errors in downloading API definition

### ISSUE THREAD

**Issue by iloshinik** [wso2/api-manager#2091]
### Description

When a new API is created with the swagger.json which is downloaded from an existing API and changed the name, context and version, it still has the previous name and the version in the API Definition. Also, when viewing the API Definition under API Configurations and refreshing the page, the Publisher portal becomes unavailable throwing an exception.

### Steps to Reproduce

1. Get APIM 4.1 latest pack.
2. Create a simple REST API and publish it.
3. Go to the Publisher portal, and go to the API Definition from the left side pane API Configurations.
4. Click on the Download Definition and get the swagger.json.
5. Go to the Publisher portal and initiate the Import Open API process.
6. Then import the download definition from step 3.
7. Change the Name, Context and version.
8. Once the API is created, it still has the previous Name and the Version under API Definition.
9. Furthermore, when trying to invoke the API it works as expected.
10. Also, in the downloaded Postman collection from the dev portal, the same Name and Version are available. 

### Affected Component

APIM

### Version

4.1.0

### Suggested Labels

apim

**Comment by GihanAyesh** [comment]
Public fix: https://github.com/wso2/carbon-apimgt/pull/12133
Resolving the issue.
