### ISSUE TITLE
[APIM-4.0.0] carbon UI shows wrong grant types for Service Provider

### ISSUE THREAD

**Issue by cbabey** [wso2/api-manager#2094]
### Description

The custom grant types, namely "customgrant_user," "customgrant_user_abc," and "customgrant_user_cba" were created in the APIM.  When we go to WSO2 Management Console under "Inbound Authentication Configuration" --> "OAuth/OpenID Connect Configuration"--> "Edit" action and select either the "customgrant_user_cba" or "customgrant_user_abc" grant type and save the changes, the "banking_user" grant type also gets automatically selected.

Upon investigating the database, it's apparent that only the grant type assigned to the user is visible for the Service Provider, and the "customgrant_user" grant type is not present. This leads to the assumption that the observed behavior might be a UI bug.

### Steps to Reproduce

1. Add the custom grant handler to /lib folder [custom-grant.zip](https://github.com/wso2-enterprise/wso2-apim-internal/files/12311449/custom-grant.zip)
2. Add the below configuration to deployment.toml file to enable the custom grants
```
[[oauth.custom_grant_type]]
name="customgrant_user"
grant_handler="org.wso2.sample.identity.oauth2.grant.mobile.MobileGrant"
grant_validator="org.wso2.sample.identity.oauth2.grant.mobile.MobileGrantValidator"

[[oauth.custom_grant_type]]
name="customgrant_user_abc"
grant_handler="org.wso2.sample.identity.oauth2.grant.mobile.MobileGrant"
grant_validator="org.wso2.sample.identity.oauth2.grant.mobile.MobileGrantValidator"

[[oauth.custom_grant_type]]
name="customgrant_user_cba"
grant_handler="org.wso2.sample.identity.oauth2.grant.mobile.MobileGrant"
grant_validator="org.wso2.sample.identity.oauth2.grant.mobile.MobileGrantValidator"
Restart the server, log in to the carbon console and add a service provider
```
3. Go to `"Service Provider" --> "Inbound Authentication Configuration" --> "OAuth/OpenID Connect Configuration"--> `"Edit" and untick all the grant types and tick only the customgrant_user_abc --> Update
4. Now again Go to "Service Provider" --> "Inbound Authentication Configuration" --> "OAuth/OpenID Connect Configuration"--> "Edit" and you will observe that both customgrant_user_abc and customgrant_user grant types are checked.

### Affected Component

APIM

### Version

4.0.0

**Comment by Kirishikesan** [comment]
Hi team,

Closing this as the public pr has been merged.
PR : https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2136

Thanks & Regards,
Kirishikesan
