### ISSUE TITLE
Remove the "Auth" from the WWW-Authenticate

### ISSUE THREAD

**Issue by shavinsenadheera** [wso2/api-manager#2095]
### Problem

Remove the Auth Header from the WWW-Authenticate and will need to get that header as the following.

```
WWW-Authenticate: Basic realm="WSO2 API Manager", error="invalid_token", error_description="The provided token is invalid"
```

### Solution

Will get the header value as below when they have only basic authentication enabled for resources.

```
WWW-Authenticate: Basic realm="WSO2 API Manager", error="invalid_token", error_description="The provided token is invalid"
```

### Affected Component

APIM

### Version

4.1.0

**Comment by imedyaosandi** [comment]
Hi @BLasan ,

Have we released this fix? Appreciate an update on this.

Thanks,
Imedya

**Comment by YasasRangika** [comment]
There is a fix: https://github.com/wso2/carbon-apimgt/pull/12138 that has been created and is awaiting merging into the public code.
