### ISSUE TITLE
Business Plan information name not visible when description is not available in dev portal and Incorrect error message when renaming an existing application to an already existing one.

### ISSUE THREAD

**Issue by charithjayasanka** [wso2/api-manager#2102]
### Description

Issue 1 :- If an Application Rate Limiting Policy was created without a description from the admin portal, the Business Plan will not be shown under the Application Overview in the dev portal.

issue 2:- when creating an application using same Application Name it returns "An application already exists with name " message. But when updating it returns "Error while updating application " message. It replaces the application name with a code in error message.

### Steps to Reproduce

Steps to reproduce Issue 01 :-

1. Login to Admin portal > Go to Application Policies
2. Add a Policy “TestPolicy”, do not add a description, add Request counts, unit time and Save.
3. Login to the Developer Portal
4. Go to Applications > Create an application by selecting the previous “ TestPolicy” and Save.
5. Then you can see that Business Plan information is not visible.
6. Go to Edit > Select 10PerMin > Save
7. Then the Business plan is visible.
8. Further analysis into the issue [1] The Business Plan information component is conditionally rendered if and only the Business Plan Description is available.
9. This issue was reproducible in wso2am-4.2.0 U2 level-23 and wso2am-3.2.0 U2 level 295

Steps to reproduce Issue 02 :- 

1. Login to the Developer Portal
2. Go to Applications
3. Add new Application > create two applications namely "Test1" and "Test2" and Save
4. Go to Overview of Application named Test2 and Go to Edit
5. Set the name to Test1 and click Save
6. The error displayed when trying to rename to an already existing application is not meaning full.
7. "Error while updating application "

### Affected Component

APIM

### Version

APIM-4.2.0-23

### Suggested Labels

devportal

**Comment by YasasRangika** [comment]
public fix has already been added.
