### ISSUE TITLE
Enhance API Tile Information for Marketplace Relevance

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/api-manager#2106]
### Problem

The current state of the API tile information lacks crucial business details necessary from a marketplace perspective. In order to improve the user experience and facilitate decision-making, it's essential that the API tile information provides relevant business insights.

### Solution

To improve the API tile information's relevance to the marketplace point of view, the APIInfo structure should be extended to accommodate optional properties like business information and external APIs. This extension will allow API providers to supply the essential business context and references to related APIs, making the tile information more informative and valuable to potential users.

### Affected Component

APIM

**Comment by dulithsenanayake** [comment]
**Update**

I have completed the initial UI design for the new API tiles. Currently, I'm working on the backend implementation for the REST API modification.

**Comment by nandika** [comment]
Test for performance impact if any after the implementation is completed

**Comment by dulithsenanayake** [comment]
**Update**

I have completed the UI enhancements for the new API tiles and the corresponding REST API modifications to the publisher portal. Currently, I'm working on the task of making it to be configurable. After completing this implementation, will add this to the dev portal.

**Comment by dulithsenanayake** [comment]
**Update**

Completed the configuring part by integrating it into the settings API, as discussed during the last sync-up. With this implementation, users are able to configure the business properties that need to be visible in the API tile through a global config. 

**Remaining Tasks**

Adding this implementation to the dev portal.
Doing performance testing.

**Comment by dulithsenanayake** [comment]
**Update**

Completed the implementation of the dev portal and conducted performance tests. Please find the below screenshot of the sample publisher portal UI with API tile enhancement.

![testss](https://github.com/wso2/api-manager/assets/31464477/a76f2f41-b24c-40fb-bf79-66794e402677)

**Remaining Tasks**

Finalize the code with a code review.

**Comment by dulithsenanayake** [comment]
Hi all,

The design document for the feature can be found here[1].

[1] https://docs.google.com/document/d/187z3HkyDiByosUA55COzGBP4WX_prgnTDRgobPsSgqM/edit

**Comment by dulithsenanayake** [comment]
Hi all,

The performance test results for the feature can be found here[1].

[1] https://docs.google.com/spreadsheets/d/1koUsHVeNbaXYBN-S-Uk5pnqB_pEGUK9HzCsYa7eQoj0/edit#gid=0

**Comment by dulithsenanayake** [comment]
**Update**

We conducted a feature code review last week, and during the review, some suggested changes were discussed. I am currently working on implementing the suggested changes.

**Additional Facts**

Based on the performance test results, it is recommended to proceed with the UI approach, as the backend approach results in longer response times.

While adding the feature for API products, it was noticed that monetization is not functioning correctly for API products. Please find the relevant Git issue[1].



In the email thread, there were requests to include additional details with this feature. The requests are as follows:

- Since we are adding the 'Third Party API' label in the API tile, there is a request to include details about its origin in the API Tile.

- Additionally, there is a request to add an optional empty key-value pair to accommodate any new requirements from specific customers in the future.

[1] https://github.com/wso2/api-manager/issues/2176

**Comment by dulithsenanayake** [comment]
**Update**

Opened the carbon-apimgt PR[1] & apim-apps PR[2] to this feature. Feature details are added in the PRs with screenshots.

Please note that we haven't introduced a new configuration for the 'display' property of external APIs, as this label is already displayed in the API tile of the publisher portal when an API is marked as a Third-Party API. Therefore, we have added the same behaviour to the dev portal as well.

Below are screenshots of the new API tile for reference.

**Publisher Portal**

![publisher_tile](https://github.com/wso2/carbon-apimgt/assets/31464477/6b2b3f29-d3fb-4f88-aeb7-6490c59a0ff0)

**Dev Portal**

![dev_tile](https://github.com/wso2/carbon-apimgt/assets/31464477/b5e0f7dc-e69b-4567-a4e1-8e1e2f5ce74e)

Here we have added a popover to display the email of the business owner & technical owner. But we are not going to add more details here by taking the performance impact into consideration.

**With Popover**

![With_popover](https://github.com/wso2/carbon-apimgt/assets/31464477/e9864734-3932-46a6-adce-1abf1b5c8604)

- [1] https://github.com/wso2/carbon-apimgt/pull/12161
- [2] https://github.com/wso2/apim-apps/pull/501

**Comment by dulithsenanayake** [comment]
Hi all,

Please find the Doc PR[1] for this feature.

[1] https://github.com/wso2/docs-apim/pull/7385

Thanks!
Dulith

**Comment by dulithsenanayake** [comment]
Hi all,

Closing this since feature changes and document changes have been completed. Please find the attached PRs [1], [2], [3]  & [4].

[1] https://github.com/wso2/carbon-apimgt/pull/12161
[2] https://github.com/wso2/apim-apps/pull/501
[3] https://github.com/wso2/apim-apps/pull/508
[4] https://github.com/wso2/docs-apim/pull/7385

Thanks!
Dulith
