### ISSUE TITLE
Error loading keys page after enabling the application registration workflow 

### ISSUE THREAD

**Issue by dinuka10** [wso2/api-manager#2108]
### Description

After enabling the application registration workflow [1], when users create an application through the developer portal and click on "Generate Keys" for OAuth Tokens, then proceed to click on "Production Keys" before appre from the admin, the entire page turns white.

### Steps to Reproduce

Please follow the steps below to reproduce the behavior:

1.) Enable the application registration workflow by following the documentation provided in [1].

2.) Proceed to the development portal and create a new application.

3.) Navigate to the "Production Keys" section and select the "OAuth2 Tokens" tab. Click on the "Generate Keys" . This action will lead you to the following page ( Screenshot from 2023-08-17 19-21-21.png) :

![Screenshot from 2023-08-17 19-21-21](https://github.com/wso2/api-manager/assets/44248646/7ac62236-84ba-4db8-afc3-ef907f71c77b)

4.) Now, Click on "Production Keys" tab or go back and then click on "Production Keys" tab ( Before approve from admin portal). You will notice that the screen becomes a completely blank white page, as depicted below (Screenshot from 2023-08-17 19-23-07.png):

![Screenshot from 2023-08-17 19-23-07](https://github.com/wso2/api-manager/assets/44248646/5761353f-695a-4b91-a6a5-fb9ecc2f9057)

Please also note that we did  not observe any error logs or any kind of logs during this behavior.

### Affected Component

APIM

### Version

wso2am-4.1.0

**Comment by maxwelljackosn** [comment]
To add on this error , even when you reject the request it also breaks and return the blank page instead of atleast a massage that says your request was rejected

**Comment by prasa7** [comment]
Fixed available in main branch https://github.com/wso2/api-manager/issues/1129
