### ISSUE TITLE
Enable role to view API endpoint configuration Internal/Observer

### ISSUE THREAD

**Issue by vikumkbv** [wso2/api-manager#2124]
### Problem

Hi Team,

We have a concern with the Internal/Observer role in APIM 4.1.0 where users are able to view the APIs but not able to view the endpoints and the advanced endpoint config as follows.

![Untitled Diagram drawio](https://github.com/wso2-enterprise/wso2-apim-internal/assets/33031034/6eb511a5-4073-456a-bcb0-5578021fc954)

But we want to view the advance endpoint configs (need to check the timeout values) and with the above role it can not be done, This can be done with a customization from UI level which allow user to view the advanced endpoint configs mark in red color in above screenshot, but we want to know whether it is possible to add this as a feature for internal/observer role.

Thanks,
Vikum

### Solution

ui customization 

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
closing as the public fix: https://github.com/wso2/apim-apps/pull/493 has already been merged.
