### ISSUE TITLE
Add Application Level Burst Control

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/api-manager#2136]
### Problem

Current product supports only subscription level burst control for product and this feature is to add application level burst control for APIs.

### Solution

Implement application level burst control by adding burst control configurations to application policies.

### Affected Component

APIM

### Version

4.3.0

**Comment by shilmyhasan** [comment]
### Developer Comment - Progress Update (19/06/2023 - 23/06/2023)
---

- Design document [1] has been created and the proposed solution is emailed to Architecture group.
- Backend code for the Application burst control feature has been created by hard coding the values at the API Key Validatot

## Action Items.

-  Test the implemented code with the hard coded values to ensure the basic functionality works properly
-  Write the front end code with data store and retrieval part from the database
-  Test the functionality end to end.

[1] - https://docs.google.com/document/d/1DOwYNz-o_WUmQ97CoPZ-YWph0hbxIDe1wvysWnaO3eQ/edit?usp=sharing

**Comment by shilmyhasan** [comment]
### Developer Comment - Progress Update (11/09/2023 - 15/09/2023)
---
- Tested the basic flows in application burst control with the code thats written by hard coding the values
- Fixed the issues in the basic flows and verified that basic functionality works as expected
- Implemented the datastore persistence and retrieval part.

**Comment by shilmyhasan** [comment]
### Developer Comment - Progress Update (18/09/2023 - 22/09/2023)
---
- Completed Implementation for both backend and front end
- Tested the flows end to end

Action items.

- Send/Merge the PRs

**Comment by shilmyhasan** [comment]
Hi Team, 

Please find the PRs associated with the feature.
 - [https://github.com/wso2/carbon-apimgt/pull/12162](https://github.com/wso2/carbon-apimgt/pull/12162)
 - [https://github.com/wso2/apim-apps/pull/503](https://github.com/wso2/apim-apps/pull/503)

Thanks.

**Comment by npamudika** [comment]
Docs - https://github.com/wso2/docs-apim/pull/7299

**Comment by npamudika** [comment]
Tests - https://github.com/wso2/product-apim/pull/13314, https://github.com/wso2/product-apim/pull/13315
