### ISSUE TITLE
[Feature] Engaging an Approval Workflow for API revision deployment

### ISSUE THREAD

**Issue by tgtshanika** [wso2/api-manager#2137]
### Problem

Currently, API revision deployment can be directly performed by the API Publisher and there is no approval workflow engaged with it. Hence, there is no way for the admin to control or review the API gateway artifacts, before deploying into production.

### Solution

A revision deployment workflow should be engaged with the product. By default, the API publishers should be able to deploy the revisions to desired gateways. When the revision deployment workflow is enabled, the revision should be moved into a pending state and should be deployed or rejected from deploying into the gateway, based on the admin's approval.

### Affected Component

APIM

### Version

4.3.0

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
Conducted a design review. Please find the design document below

**Comment by GihanAyesh** [comment]
Sub tasks for the feature

- [ ] Add revision creation via simple workflow
- [ ] Add revision deletion via simple workflow
- [ ] Add revision creation via approval workflow for publisher portal
- [ ] Add revision deletion via approval workflow for publisher portal
- [ ] Add revision approval flow for admin 
- [ ] Add revision rejection flow for admin
- [ ] Get revision pages changes for backend
- [ ] UI changes for publisher portal
- [ ] UI changes for admin portal
- [ ] Mapping UI changes to backend
- [ ] Testing
- [ ] Documentation

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
Started implementing the API revision creation via simple workflow. The application creation workflow will be used as the guideline for the implementation. This will introduce new classes,

- APIRevisionDeploymentSimpleWorkflowExecutor
- APIRevisionWorkflowDTO

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
Continue implementing the simple workflow. Made changes to the folllowing classes,

- APIProviderImpl
- ApiMgtDAO
- TenantWorkflowConfigHolder
- WorkflowConstants
- APIConstants
- default-workflow-extensions
- h2.sql

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
The simple workflow is working. Started working on the approval flow.

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
Currently writing the logic of the `APIRevisionDeploymentApprovalWorkflowExecutor`

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
Met with few errors in the logic and currently resolving them

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
The logic is implemented for the db entry to be created. Still working on finalizing the approval flow.

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
When implementing the admin approval workflow, a variable mismatch happens. Currently trying to resolve that issue.

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
Resolved the issue with admin approval flow. The implementation of the admin flow is almost done. Also sent the architecture mail. Also done the revision deletion via approval workflow for publisher portal.

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
Completed the admin approval flow and discussed with @chamilaadhi about the implementation. Apparently, adding the logic to executor complete function is the old method. Refactoring that now.

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
Had a design discussion regarding the deployment revision page. Two options were given.

Option 1

![Image](https://github.com/wso2/api-manager/assets/47550159/b85a0d04-31c0-4a48-b8d9-3945f0c86587)

Option 2

![Image](https://github.com/wso2/api-manager/assets/47550159/cfd9ba7f-2728-407b-adb7-7bc9a19e76f9)

The first option was picked with few alterations.

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
Admin portal UI changes are complete. Currently working on publisher portal UI changes.
With that following tasks needs to be done

- Cancel workflow request from publisher portal backend logic
- Hide a gateway from deploy new revision when it has revision with created status
- API Publisher Get logics
- Delete API logic

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
Implemented the cancel workflow request from publisher portal backend logic and tested it in the rest level. Faced with an error and resolved that. Working on delete API logic and main publisher portal UI changes.

**Comment by Kamidu** [comment]
@GihanAyesh , 

Small suggestion on this feature, will it be a possibility to provide an option where an admin can provide feedback to the API provider on the approval? specially when an API publication or revision is rejected what is the reason behind it so they can apply necessary changes promptly? WDYT?

**Comment by GihanAyesh** [comment]
Hello @Kamidu,
Since this suggestion is common for every workflow, it is under discussion on adding to APIM 4.3.0. Once the discussion is finalized I will give an update on that.

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
The delete API logic is completed. Currently working on the publisher portal UI and backend GET changes.

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
Added changes to the deployment UI page with pending updates and removing gateway which has pending revisions from the 'Deploy New Revision' page.

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
Completed the implementation. 
Made the changes to deployment, overview, deploy sample API, try out UI pages. Tested the flows and fixed the bugs occurred.
Tested multiple gateways, tenants and API Product flows.

Scheduled the code review on 9th of October.

**Comment by GihanAyesh** [comment]
Developer comments - Progress update

The carbon apimgt PR : https://github.com/wso2/carbon-apimgt/pull/12169
The APIM apps PR : https://github.com/wso2/apim-apps/pull/509

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update

The new UI is designed. 


![Image](https://github.com/wso2/api-manager/assets/47550159/9f83bcb2-2315-472f-9355-94ab90ac4f74)


A code review is scheduled for today.

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
A discussion was happened since the design that was selected on last Friday code review was not adequate. After the discussion a design with the two column structure with one column handling select revision drop down and the pending revisions and the other column solely handling deployed revisions is finalised. Currently developing that.

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
The new design is finalized. 


![Image](https://github.com/wso2/api-manager/assets/47550159/7f2eea88-f53c-4fe8-819c-95de684e1f22)

Started working on writing new test cases and fixing broken tests

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
Will close the issue once the PRs are merged.

**Comment by GihanAyesh** [comment]
Git Issue | https://github.com/wso2/api-manager/issues/2137
-- | --
Main PRs | https://github.com/wso2/carbon-apimgt/pull/12169, https://github.com/wso2/apim-apps/pull/509
Tests | https://github.com/wso2/carbon-apimgt/pull/12169, https://github.com/wso2/product-apim/pull/13283
Documentation | https://github.com/wso2/docs-apim/pull/7354

**Comment by GihanAyesh** [comment]
### Developer comments - Progress update
Closing this as PRs are merged.
