### ISSUE TITLE
[APIM-3.2.0] Unable to open/maximise the side navigation bar of the analytics dashboard

### ISSUE THREAD

**Issue by Hamool-Nizar** [wso2/api-manager#2141]
### Description

Hi All,

We are unable to view/open/maximise the side navigation bar of the APIM 3.2.0 analytics dashboard.

Upon selecting one of the widgets in the analytics dashboard, an issue arises where the side navigation bar automatically closes or hides itself. This behavior prevents us from subsequently reopening or maximizing the side navigation bar.

<img width="1440" alt="Analytics_Dashboard_Side_bar" src="https://github.com/wso2/api-manager/assets/87962341/bb7af5c8-6253-4d52-854e-5ad013416608">

Hence, could you kindly inform us whether this behavior observed in the analytics dashboard is an intentional behaviour or if it's a bug that requires addressing?

Your inputs/suggestions would be much appreciated

Best regards,
Hamool

### Steps to Reproduce

1. Log in to the APIM 3.2.0 Analytics dashboard.
2. Then select any of the widget in the Analytics homepage.
3. Then side-navigation bar automatically closes or hides itself.

### Affected Component

Analytics

### Version

3.2.0

**Comment by YasasRangika** [comment]
This issue does not affect the master branch.
