### ISSUE TITLE
[Removal of Token Persistence] Revocation due to internal events : User scenarios

### ISSUE THREAD

**Issue by Lakith-Rambukkanage** [wso2/api-manager#2159]
This issue tracks the sub task of **handling token revocation due to internal events : user scenarios** of the main feature implementation of Removal of Token Persistence [1] 

Design document draft [2]
Diagram draft [3]

[1] https://github.com/wso2/api-manager/issues/1664
[2] https://docs.google.com/document/d/1mzTZRBiwHlgjgivitUIavOYj13vRIhkk4jnNbidYmMY/edit?usp=sharing
[3] https://drive.google.com/file/d/1PBjxmo4-_N8UGejO6Kh-CwuWRz3OYN19/view?usp=sharing

**Comment by Lakith-Rambukkanage** [comment]
Ongoing task breakdown : 

- [ ] Document current behaviour with diagrams
- [ ] New behaviour with diagrams
- [ ] DB table and in memory cache model design
- [ ] Add new extension points for user operation event change listener in IS side
- [ ] Implement extension point in IS side
- [ ] Handle the propagated rules (events) on the GW and implement JWT validation logic

**Comment by Lakith-Rambukkanage** [comment]
Note : 
There are two calls coming from `KeyManagerUserOperationListener` from the CP side and `IdentityOathEventListener` from the KM side, for user operations.

**Comment by Lakith-Rambukkanage** [comment]
Note : Persistence notifier implementation for token revocation needs to be tested with ETCD setup. 

- [ ] https://github.com/wso2/api-manager/issues/2235

**Comment by dushaniw** [comment]
The PR will be merged once identity versions are bumped in carbon-apimgt.

**Comment by tharikaGitHub** [comment]
Closing as the task is completed.
