### ISSUE TITLE
Need to enforce the TLS 1.2 version for the API-Manager email sending.

### ISSUE THREAD

**Issue by Gayanthakaushal** [wso2/api-manager#2171]
### Problem

Currently, the APIM-2.6.0 version is using javax.mail version 1.4.1. But TLS1.2 is available javax.mail version 1.6 onwards[1].

[1] - https://sites.google.com/site/pawneecity/amazon-aws/aws-ses#h.dq6v2r7tq0gy 

### Solution

upgrade the javax.mail version 1.6 or above to support TLS 1.2 

### Affected Component

APIM

### Version

2.6.0

### Implementation

When implementing we can use these [1] dependencies.

[1] - http://www.java2s.com/example/jar/j/download-javaxmail160jar-file.html

**Comment by HeshanSudarshana** [comment]
Hi all,

The javax.mail version 1.4.1 used in axiom JAR was upgraded to jakarta.mail 1.6.4 to support TLS v1.2 in the APIM 2.6.0 latest update.

Thanks,
Heshan
