### ISSUE TITLE
[APIM 4.1.0] Error while getting documentation for imported SOAP API when imported through apictl

### ISSUE THREAD

**Issue by charithjayasanka** [wso2/api-manager#2174]
### Description

Issues when trying to export and import a SOAP API using the apictl tool which contains a document containing spaces for the name,

### Steps to Reproduce

1. Login to the publisher:

2. Create a SOAP API by importing WSDL file in the publisher

3. Add an inline documentation with the name containing a space ex :- "test name" and add some content to it.

4. Login to the particular environment using apictl:
apictl login dev --username xxxxx --password xxxxxx -k

5. Export the API from the particular environment:
apictl export api -in testApi -v v1 -e dev --preserve-status=true --format JSON -k

6. Delete the api from the publisher portal

7. Import the API to the dev environment using apictl:
apictl import api -f dev/testApi.zip -e dev -k

After the import the following error log could be observed.

and the document cannot be observed through dev portal nor publisher portal

ID: [-1234] [api/am/publisher] [2023-09-12 11:16:58,488] ERROR {org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ImportUtils} - Failed to locate the document files of the API/API Product: testApi java.io.FileNotFoundException: <File path ommited> (The system cannot find the file specified)

After testing the behaviour locally it was concluded that the issue happens when a name with spaces is used to name the documents added to the API.

### Affected Component

APIM

### Version

4.1.0.105

### Relevant Log Output

```shell
ID: [-1234] [api/am/publisher] [2023-09-12 11:16:58,488] ERROR {org.wso2.carbon.apimgt.rest.api.publisher.v1.common.mappings.ImportUtils} - Failed to locate the document files of the API/API Product: testApi java.io.FileNotFoundException: <File path ommited> (The system cannot find the file specified)
```

**Comment by YasasRangika** [comment]
Based on the comment in the internal ticket, this issue does not reproduce in the master branch. Therefore, closing the ticket.
