### ISSUE TITLE
OpenAPI 3.1.0 Specification support 

### ISSUE THREAD

**Issue by tgtshanika** [wso2/api-manager#2178]
### Problem

Currently, API Manager supports only OpenAPI 3.0.0 and Swagger 2.0 versions. It does not allow importing or creating new APIs out of OpenAPI 3.1.0

### Solution

Bringing OpenAPI 3.1.0 support by upgrading the following tooling to latest.
- Swagger Parser
- Swagger Core/Annotations/Models
- OpenAPIGenerator
- Swagger UI
- Swagger Editor

Following dependencies have to be upgraded to latest, in order to support above tooling dependencies.

- Snakeyaml
- Guava
- Netty
- Jackson-Databind
- ua-parser
- open telemetry

### Affected Component

APIM

### Version

4.3.0

**Comment by tgtshanika** [comment]
<google-sheets-html-origin><style type="text/css"></style>

PR | Upgraded Version | Changes
-- | -- | --
https://github.com/wso2/carbon-analytics-common/pull/831 | 5.3.6 | Upgraded guava, snakeyaml and jackson databind
https://github.com/wso2/carbon-event-processing/pull/328 | 2.3.7 | Upgraded guava, snakeyaml and analytics commons
https://github.com/wso2/transport-http/pull/469 | 6.3.47 | Upgraded guava, snakeyaml and netty
https://github.com/wso2-extensions/identity-inbound-auth-openid/pull/97/ | 5.8.1 | Upgarded guava
https://github.com/wso2/orbit/pull/1005/files | 1.11.0.wso2v5 | Upgraded guava and jackson dependency version range
https://github.com/wso2/wso2-synapse/pull/2101 | 4.0.0-wso2v48 | Upgraded guava, snakeyaml, jackson databind, netty and transport-http
https://github.com/wso2/carbon-business-messaging/pull/721 | 3.3.28 | Upgarded guava

**Comment by tgtshanika** [comment]
<google-sheets-html-origin><style type="text/css"></style>

Carbon-Mediation | https://github.com/wso2/carbon-mediation/pull/1686
-- | --
Carbon-deployments | https://github.com/wso2/carbon-deployment/pull/387
Kernal | https://github.com/wso2/carbon-kernel/pull/3675
apim-analytics-publisher | https://github.com/wso2/apim-analytics-publisher/pull/106

**Comment by tgtshanika** [comment]
Please find the draft PRs for carbon-apimgt https://github.com/wso2/carbon-apimgt/pull/12165

**Comment by tharikaGitHub** [comment]
Closing as this feature is already available in APIM 4.3.0-Alpha
