### ISSUE TITLE
Fix the behavior where updating an application via DevPortal changes the token type from Opaque to JWT

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/api-manager#2182]
### Problem

When updating an application via DevPortal, the token type of the application is getting changed to JWT from Opaque without knowing the user.

### Solution

Display a warning message indicating the change of the token type when updating the application via the dev portal or  Introduce a configuration to preserve the token type when updating the application via the dev portal.

### Affected Component

APIM

### Version

3.2.0

**Comment by YasasRangika** [comment]
Master fix: https://github.com/wso2/carbon-apimgt/pull/10897 has already been merged.
