### ISSUE TITLE
API-KEY authentication support web socket API

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/api-manager#2187]
### Problem

Currently, the web socket APIs only support the authorization bearer token. Therefore, this is created to track the implementation effort to support API-KEY authentication for web socket APIs in 4.2.0.

### Solution

N/A

### Affected Component

Analytics

**Comment by YasasRangika** [comment]
Public fixes:
https://github.com/wso2/carbon-apimgt/pull/12154
https://github.com/wso2/apim-apps/pull/498
https://github.com/wso2/docs-apim/pull/7264
https://github.com/wso2/product-apim/pull/13278
