### ISSUE TITLE
React version bumping from 17.x to 18.x

### ISSUE THREAD

**Issue by Tharanidk** [wso2/api-manager#2191]
### Problem

We need to bump the React version from 17.x to 18.x to allow developers the flexibility to use new libraries when they develop new features.

### Solution

- [ ] Bump the React version to 18.0.0 in devportal, admin portal, and publisher.
- [ ] Bump Material UI from V4 to V5
- [ ] Fix the incompatible dependencies after the bump in all three portals

### Affected Component

APIM

### Version

4.3.0

### Related Issues

React Bump to 17.X : https://github.com/wso2/api-manager/issues/2160

**Comment by Tharanidk** [comment]
### **Work Log**

- I researched the React update and identified the dependencies with issues when moving from React version 17.x to 18.x.You can find the detailed findings in this,
https://docs.google.com/spreadsheets/d/1tK_u5qh90uvqLoLESwJHGxxwqqgOP2wNleaoMpBX9Lc/edit#gid=0

- I updated the React version to 18.0.0 in the package.json file.
- I identified that Material-UI was incompatible with React 18.x and needed to be updated from version 4 to version 5, as previously identified.
- For one of the portals, I encountered over 100 file changes. After running the script, I am currently working on resolving the breaking changes.

**Comment by Tharanidk** [comment]
### **Work Log**

- Changed issues with imports after running the script. 
- Fixed the issues
- Remove unused import statements.

**Comment by Tharanidk** [comment]
Getting the below errors in devportal console

```
DevPortal.jsx:105 Error while receiving settings :  TypeError: Cannot read properties of null (reading 'IsAnonymousModeEnabled')
    at DevPortal.jsx:96:42

Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (react-dom.development.js:16227:1)
    at Object.useContext (react.development.js:1618:1)
    at useTheme (useTheme.js:4:17)
    at ThemeProvider (ThemeProvider.js:34:30)
    at ./source/src/app/components/Base/index.jsx (index.jsx:662:91)
    at __webpack_require__ (bootstrap:19:1)
    at ./source/src/app/ProtectedApp.jsx (LoginDenied.jsx:79:18)
    at Function.__webpack_require__ (bootstrap:19:1)
    
react-dom.development.js:18687 The above error occurred in one of your React components:

    at Lazy
    at Route (https://localhost:9443/devportal/site/public/dist/index.bundle.js:97162:29)
    at Switch (https://localhost:9443/devportal/site/public/dist/index.bundle.js:97364:29)
    at IntlProvider (https://localhost:9443/devportal/site/public/dist/index.bundle.js:96409:47)
    at Suspense
    at Router (https://localhost:9443/devportal/site/public/dist/index.bundle.js:96781:30)
    at BrowserRouter (https://localhost:9443/devportal/site/public/dist/index.bundle.js:10456:5)
    at StylesProvider (https://localhost:9443/devportal/site/public/dist/index.bundle.js:6179:24)
    at ThemeProvider (https://localhost:9443/devportal/site/public/dist/index.bundle.js:6347:24)
    at DevPortal (https://localhost:9443/devportal/site/public/dist/index.bundle.js:9989:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

started changing files manually to ignore these issues.

**Comment by lasanthaS** [comment]
## Work Log

- Migrated the components from `@material-ui/core` to `@mui/material` package [1]

**Comment by Tharanidk** [comment]
**Work Log**

- Started working on the Admin portal
- Migrated react from 17.0.0 to 18.0.0
- Migrated components from **@material-ui/lab (^4.0.0-alpha.61)** to  **@mui/lab**, **@mui/material**

**Comment by Tharanidk** [comment]
**Work Log**

- Migrated components from **@material-ui/core** to  **@mui/styles**, **@mui/material**
- Migrated components from **@material-ui/icons** to  **@mui/icons-material**

**Comment by Tharanidk** [comment]
**Work Log**

- After changing all imports admin portal works fine. 
- Working on setting up themes as previous

**Comment by Lakith-Rambukkanage** [comment]
### Admin portal

```diff
@@ -10,7 +10,7 @@
-        "build:prod": "rm -R site/public/dist/; npm rum i18n && NODE_ENV=production NODE_OPTIONS=--max_old_space_size=4096 webpack --mode production --stats=errors-only",
+        "build:prod": "rm -R site/public/dist/; npm run i18n && NODE_ENV=production NODE_OPTIONS=--
@@ -25,15 +25,13 @@
-        "@emotion/react": "^11.11.1",
+        "@emotion/react": "^11.11.3",
-        "@material-ui/core": "^4.12.4",
-        "@material-ui/icons": "^4.11.2",
-        "@mui/icons-material": "^5.14.12",
-        "@mui/lab": "^5.0.0-alpha.147",
-        "@mui/material": "^5.14.10",
-        "@mui/styles": "^5.14.10",
+        "@mui/icons-material": "^5.15.4",
+        "@mui/lab": "^5.0.0-alpha.160",
+        "@mui/material": "^5.15.4",
+        "@mui/system": "^5.15.4",
@@ -44,7 +42,7 @@
-        "mui-datatables": "^3.8.5",
+        "mui-datatables": "^4.3.0",
@@ -98,7 +96,7 @@
-        "react-hot-loader": "^4.13.0",
+        "react-refresh": "^0.14.0",
```

React-hot-loader has to be removed since it's no longer supported. react-refresh has to be used from here onwards which is supported officially by react.

**Comment by thisaltennakoon** [comment]
### DevPortal portal update

- Upgrade MUI version from v4 to v5
- Upgrade react version from 17 to 18
- Fixed all the compilation errors

**Comment by thisaltennakoon** [comment]
### DevPortal portal progress update

- [x] Fix issues in the react 16 to 17 upgrade
- [ ] Other Dependancy related issues
- [x] MUI 4 to 5 migration
- [x] MUI Breaking changes migrations
- [x] Build and Compilation issues
- [x] Runtime issues
- [ ] Smoke testing
- [x] Styling issues
- [x] UI Test Issues
- [x] Manual Testing

**Comment by tharikaGitHub** [comment]
Closing as the task is completed.
