### ISSUE TITLE
Publish button is disabled when only mutual SSL is enabled

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/api-manager#2197]
### Description

We can create an API-only MTLS, but we can't publish it through the Lifecycle tab. We can publish the API through the Overview page. 
This is an issue in the UI. This is working on the Overview page in "CustomizedStepper.jsx" as it was fixed with [1]. We will have to do a similar fix in "LifeCycleUpdate.jsx". The issue is when only mutual ssl is enabled, the API will not have any tiers. Due to this reason, the condition in [2] becomes true when deployments are also available, causing the button to be disabled. 

[1] wso2/product-apim#12462
[2] https://github.com/wso2-support/apim-apps/blob/support-9.0.432.x-full/portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/LifeCycle/LifeCycleUpdate.jsx#L259

### Steps to Reproduce

- Create an API with only MTLS through the publisher
- Try to publish the API through the "Lifecycle" page on the Publisher UI

### Affected Component

APIM

### Version

APIM 4.2.0

**Comment by YasasRangika** [comment]
This issue does not affect the master branch.
