### ISSUE TITLE
Application Role issue when changing the APPlication owner

### ISSUE THREAD

**Issue by dinuka10** [wso2/api-manager#2210]
### Description

After changing the ownership of an application multiple times, we have observed that the name (email) of the new application owner is appended to the application role. Additionally, it has been noticed that the UUID of the appended part is null as below.

Application/test4@gmail.comnulltest3@gmail.comnulltest4@gmail.comnulltest3@gmail.comnulltest4@gmail.comnulltest3@gmail.comnullPRODUCTION	

Please note that in this scenario both the original owner and the next owner use email address as the username

### Steps to Reproduce

1.) Please add below configration to enable Email as Username

[tenant_mgt]
enable_email_domain= true
disable_email_domain_validation = true

2.) Also, add/update the following configuration to allow the '@' character in the service provider name:

[service_provider]
sp_name_regex = "^[\sa-zA-Z0-9._@-]*$"

3.) Create two users with the Internal/Subscriber role (e.g., [test1@gmail.com](mailto:test1@gmail.com) and [test2@gmail.com](mailto:test2@gmail.com)).

4.) Go to the developer portal and log in using one of the above-created users (e.g., using [test1@gmail.com](mailto:test1@gmail.com)) to create an application and generate keys.

5.) Then, go to the admin portal -> Settings -> Applications and change the ownership of the above-created application multiple times as follows:

Original owner: [test1@gmail.com](mailto:test1@gmail.com)
Change to: [test2@gmail.com](mailto:test2@gmail.com)
Change to: [test1@gmail.com](mailto:test1@gmail.com)
Change to: [test2@gmail.com](mailto:test2@gmail.com)

If you go to the Carbon console and check the application roles, you will see something like this:

Application/[test1@gmail.com](mailto:test1@gmail.com) null [test2@gmail.com](mailto:test2@gmail.com) null [test1@gmail.com](mailto:test1@gmail.com) null [test2@gmail.com](mailto:test2@gmail.com) null [test1@gmail.com](mailto:test1@gmail.com) null PRODUCTION

### Affected Component

APIM

### Version

wso2am-4.1.0

**Comment by YasasRangika** [comment]
Public fix PR: https://github.com/wso2-extensions/apim-km-wso2is/pull/113
