### ISSUE TITLE
Schema validation report is not included in message context in APIM 4.1.0 and 4.2.0

### ISSUE THREAD

**Issue by Akila94** [wso2/api-manager#2212]
### Description

In APIM 4.0.0, the schema validation report is included in the message context so we can read that report and build and handle specific error scenarios when we send the error response to the client. However, the APIM versions 4.1.0 and 4.2.0 don't include this report in the message context.

- APIM 4.0.0: https://github.com/wso2-support/carbon-apimgt/blob/8a2bd265543da1e1afb923b73f50118cfcb4e51c/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/SchemaValidator.java#L70

- The above property is not appended to the message context in APIM 4.1.0 and 4.2.0.

Because of this many error-handling scenarios of the OB Berlin toolkit fail.

### Steps to Reproduce

The above property has been used by the OB Berlin Toolkit and with the latest APIM versions, many error scenarios fail.

Steps to reproduce,

1. Set up OB Berlin Toolkit.
2. Run schema validation scenario tests.

### Affected Component

APIM

### Version

4.1.0 and 4.2.0

**Comment by YasasRangika** [comment]
closing as per the master fix: https://github.com/wso2/carbon-apimgt/pull/12173 has already been merged.
