### ISSUE TITLE
APIM 4.1.0 - Add proxy support in Choreo data publishing

### ISSUE THREAD

**Issue by Manasha11** [wso2/api-manager#2213]
### Problem

Events are published to GW to EventHub over the AMQP and cannot be configured via a proxy. 

### Solution

Add support to publish data to choreo via a proxy.

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
closing as per the comment in the internal ticket indicating that the feature is functioning as expected.
