### ISSUE TITLE
Is Api using mediation policies

### ISSUE THREAD

**Issue by AnuGayan** [wso2/api-manager#2214]

**Comment by BLasan** [comment]
As an initial solution, the API object which is maintained in the gateway will be populated with URLMappings. It will consist of the `httpVerb`, `resource` and policy related data (`policyUUID`, `policyName`, `policyVersion`, `direction`)

**Comment by BLasan** [comment]
Implemented the solution in two ways.

1. **Approach 1** : Using join operations to fetch operation policies along with the resources (modified the existing `GET_URI_TEMPLATES` query)
2. **Approach 2** : Using a separate query to fetch operation policies and attach them to the corresponding resource.

Approach 2 was implemented to reduce the number of iterations needed to create `URITemplates` as the join query will produce a graph of data (with replicated ones).

API object now consists of operation policies and based on the request, it fetches only the corresponding operation policies of the resource method and send it in the analytics events.

**Comment by BLasan** [comment]
API object in gateway now consists of `APIPolicies` and `URIMap` with `OperationPolicies`. Based on the invocation, it populates the corresponding `APIPolicies` and `OperationPolicies` to the analytics event.

**Comment by BLasan** [comment]
Did a basic performance test for 3 APIs with 3-5 Operation Policies attached to some resources. Same resources with policies were maintained in both scenarios (with & without fix) and it was evident that there's a slight performance gap (degradation) with the fix introduced. In this scenario, 100 concurrent users were considered and iterated it 5 times. Then took the average latency of the resources of an API. Will re-perform the load test on multiple APIs + API Product with higher concurrent user count.

**Comment by BLasan** [comment]
Added a system property `operationPolicyEnableWithAnalyticsEvent` to enable/disable operation policies getting attached to the analytics event. By default, the value would be `false`
