### ISSUE TITLE
[Bug] Tenant Login dropping tenant domain and login with super tenant domain

### ISSUE THREAD

**Issue by Lakith-Rambukkanage** [wso2/api-manager#2217]
### Description

When logging in to the publisher and dev portals using the tenant admin login after creating a tenant it logins as the super tenant admin.

### Steps to Reproduce

1. create an API using the super tenant admin user (admin:admin)
2. create a new tenant using the carbon console. (tenant1, admin1@tenant1.com:admin1)
3. login with the new tenant admin.(admin1@tenant1.com:admin1)
4. the APIs published by the admin user is visible to the tenant admin user. 
5. new apis created will belong to the super tenant domain. (refer `AM_API` table `ORGANIZATION` column)

### Affected Component

APIM

### Version

4.3.0

### Related Issues

possibly introduced by :
https://github.com/wso2/api-manager/issues/1664
https://github.com/wso2/carbon-apimgt/pull/11976

**Comment by dushaniw** [comment]
fixed with https://github.com/wso2/carbon-apimgt/pull/12281 and https://github.com/wso2-extensions/apim-km-wso2is/pull/124
