### ISSUE TITLE
Keeping the old behaviour 

### ISSUE THREAD

**Issue by PrabhashDilhan** [wso2/api-manager#2219]
### Problem

We have fixed a bug via the fix in[1]. But we may need to keep the old behavior as it is because some integrations will fail with the new behavior. Previously it was dropping the duplicate header which are coming with lower case and upper case. With fix in[1], now we are sending those headers to the client as it is.

[1] https://github.com/wso2/api-manager/issues/1683

### Solution

Add a backward compatibility for the aforementioned fix.

### Affected Component

APIM

### Version

wso2am-3.2.0

**Comment by GihanAyesh** [comment]
PR: https://github.com/wso2/wso2-synapse/pull/2107
