### ISSUE TITLE
NoClassDefFoundError Error in the latest update level of APIM 4.0.0 when starting the server on Windows

### ISSUE THREAD

**Issue by VirajHasitha** [wso2/api-manager#2221]
### Description

Hi Team,

We could reproduce a NoClassDefFoundError in APIM 4.0.0 latest U2 level only in windows environment.
We couldn't reproduce the issue on Ubuntu OS, or on Mac OS as well. The issue only persisted in the windows environment and the issue can be observed during the server start up.

**Reproducing steps.**

Update the APIM 4.0.0 in a windows machine to latest update level.

Start the server in a windows environment.

Following startup error can be observed.

`TID: [-1234] [] [2023-10-12 06:58:52,796] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/authenticationendpoint]} - Exception sending context initialized event to listener instance of class [org.wso2.carbon.identity.application.authentication.endpoint.util.listener.AuthenticationEndpointContextListener] java.lang.NoClassDefFoundError: org/wso2/carbon/utils/CustomHostNameVerifier at org.wso2.carbon.identity.application.authentication.endpoint.util.MutualSSLManager.initMutualSSLConnection(MutualSSLManager.java:362) at org.wso2.carbon.identity.application.authentication.endpoint.util.MutualSSLManager.init(MutualSSLManager.java:175) at org.wso2.carbon.identity.application.authentication.endpoint.util.listener.AuthenticationEndpointContextListener.contextInitialized(AuthenticationEndpointContextListener.java:51)`

The issue was only occurred when the -Dhttpclient.hostnameVerifier value is set to DefaultAndLocalhost  in the <APIM_HOME>/bin/api-manager.bat file. If we change it to AllowAll, we cannot reproduce the error.

By default, this value is AllowAll in MacOS or Ubuntu startup script(api-manager.sh).

Thanks,
Viraj

### Steps to Reproduce

1. Update the APIM 4.0.0 in a windows machine to latest update level.

2. Start the server in a windows environment.

### Affected Component

APIM

### Version

4.0.0

**Comment by dulithsenanayake** [comment]
Hi all,

Closing this since the U2 update has been released.

Thanks!
Dulith
