### ISSUE TITLE
APICTL Publisher Access Control restrictions getting removed 

### ISSUE THREAD

**Issue by jichinthaka** [wso2/api-manager#2222]
### Description

Hi Team, 

We noticed that after executing the apictl init command and checking initiated Project/Meta-information/api.yaml file, only the accessControlRoles value was removed from the api.yaml file.

When Importing APIs Via Dev First Approach and Initialize the API Project using OpenAPI/Swagger Specification[1] approach only the issue is observed. 

But, if we manually edit the initiated api.yaml file with the accessControlRoles and import the API, the restrictions in API are added properly.

The problem doesn't happen during import, but during project initialization.

[1] - https://apim.docs.wso2.com/en/3.2.0/learn/api-controller/importing-apis-via-dev-first-approach/ 

Regards
-Imesh 

### Steps to Reproduce

Steps to Reproduce,
1. Add an environment,
apictl add-env -e dev --apim https://localhost:9443
 2. Login to an environment
apictl login dev -u admin -k
 3. Initialize an API Project using the OpenAPI/Swagger Specification approach
[petstore.yaml.zip](https://github.com/wso2-enterprise/wso2-apim-internal/files/12911861/petstore.yaml.zip)
[swagger.yaml.zip](https://github.com/wso2-enterprise/wso2-apim-internal/files/12911862/swagger.yaml.zip),
apictl init SwaggerPetstore-1.0.0 --definition petstore.yaml --oas /Users/chaveeka/Documents/Issues/TIETOOEMSUB-493/tien/swagger.yaml
4. After executing the apictl init command you will observe that in the SwaggerPetstore-1.0.0/Meta-information/api.yaml , the accessControlRoles value will get removed.

### Affected Component

APICTL

### Version

APIM 3.2.0.298

**Comment by npamudika** [comment]
This is fixed with the APICTL 3.2.9 release - https://github.com/wso2/product-apim-tooling/milestone/27?closed=1

**Comment by npamudika** [comment]
Closing as this is N/A to the master branch.
