### ISSUE TITLE
Subscriber filtering on API Publisher does not work as expected 

### ISSUE THREAD

**Issue by LayaniMal** [wso2/api-manager#2227]
### Description

There is a filtering issue with subscriber names not getting populated in the filter dropdown.

### Steps to Reproduce

- Create an API and subscribe to it with many applications created by different users.
- In Publisher, navigate to Relevant API > Portal Configurations > Subscriptions> Manage Subscriptions

### Affected Component

APIM

### Version

4.2.0

### Suggested Labels

APIM-4.2.0

**Comment by dulithsenanayake** [comment]
Hi all,

Closing this since the corresponding U2 update was released. 

Thanks!
Dulith
