### ISSUE TITLE
APIM GW becomes unresponsive when malformed requests are received with Analytics enabled.

### ISSUE THREAD

**Issue by Manasha11** [wso2/api-manager#2228]
### Description

In APIM 4.0.0, the GW becomes unresponsive when requests with context "/" is received, with Choreo Analytics enabled.

In GW logs, following WARN can be seen.

`WARN {org.apache.synapse.transport.passthru.ServerWorker} - Server worker thread queued time exceeds the expected max queueing time. Expected max queueing time : 30000ms. Actual queued time : 33664ms, CORRELATION_ID : xxxx`

In thread dumps, PassThroughMessageProcessor threads are blocked in AnalyticsMetricsHandler, when going through org.wso2.carbon.apimgt.keymgt.model.impl.SubscriptionDataStoreImpl.getApiByContextAndVersion method, which has a synchronized block.

### Steps to Reproduce

- In APIM 4.0.0, enable Choreo Analytics.
- Send requests with the context "/" in a high frequency (~1000 TPS)
- Observe the following WARN in the logs after some time.
`WARN {org.apache.synapse.transport.passthru.ServerWorker} - Server worker thread queued time exceeds the expected max queueing time. Expected max queueing time : 30000ms. Actual queued time : 33664ms, CORRELATION_ID : xxxx`
- Get a thread dump and check the state of PassThroughMessageProcessor threads.

### Affected Component

APIM

### Version

4.0.0

**Comment by PasanT9** [comment]
Same issue as https://github.com/wso2/api-manager/issues/2203. This is already resolved.
