### ISSUE TITLE
Error code '900800' for subscription limit exceeding scenarios in APIM-2.0.0.

### ISSUE THREAD

**Issue by janithcmw** [wso2/api-manager#2230]
### Description

As per the documentation the status code '900800' is there for the API level throttling limit exceeding scenarios. But when the 'advanced throttling' is disabled as follows in APIM-2.0.0 the status code '900800' can be observed when the subscription policy quota is exceeded.

`<EnableAdvanceThrottling>false</EnableAdvanceThrottling>`

As per the following image, there is no concept of API level throttling once the 'EnableAdvanceThrottling' is set to false. If this is the case can't we improve the code to return the subscription level exceeding the status code '900804' instead of '900800' in point[1]? Also once 'EnableAdvanceThrottling' is disabled it seems there is no concept as API Level throttling as per the UI.

[1] https://github.com/wso2/carbon-apimgt/blob/v6.0.4/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/throttling/ThrottleHandler.java#L419

### Steps to Reproduce

1. Set the 'EnableAdvanceThrottling' to false and stat up the APIM-2.0.0.
2. Add a subscription policy as follows and publish the API.

<img width="2056" alt="Screenshot 2023-10-18 at 20 20 09" src="https://github.com/wso2/api-manager/assets/47592448/7be7b42a-d955-4de9-aadb-07c900662e7d">

3. Then invoke the API and allow it to throttle out under the subscription policy and observe the status code.

### Affected Component

APIM

### Version

2.0.0

### Environment Details (with versions)

N/A

**Comment by YasasRangika** [comment]
This issue does not affect the master branch.
