### ISSUE TITLE
Payload encoding disappears after a restart while creating a SOAP API

### ISSUE THREAD

**Issue by DaniduWijendra** [wso2/api-manager#2238]
### Description

When a SOAP payload is formulated with CDATA and restart the server, we could see that the payload lost its encoding. This is resolved after updating and saving the API.

### Steps to Reproduce

- Add below parameter to deployment.toml.

```
[xml_input_factory.properties]
"javax.xml.stream.isCoalescing" = false
```

- Start API server
- Create a SOAP API by selecting the Generate REST API as the implementation type.
- Create a POST method (with body parameter). For In flow, add a custom sequence that formulates a soap message that includes the CDATA tag and a Log Full mediator.
- Send the request.
- We could see the Log Full with encoding as expected.
- Restart the server.
- Again send a request with the same body as in the 5th step. Then could see the Log full without encoding.
- Then edit the API, save it, and send a request again. The output is received similarly to the 6th step with encoding.

### Affected Component

APIM

### Version

3.2.0

**Comment by dulithsenanayake** [comment]
Hi all,

Closing this since the U2 update has been released.

Thanks!
Dulith
