### ISSUE TITLE
Use of deployment order for Siddhi applications.

### ISSUE THREAD

**Issue by janithcmw** [wso2/api-manager#2240]
### Problem

Hi All,

Currently, the Siddhi applications are deployed without any controllable order.

But if we consider a scenario of having in-memory sinks and in-memory sources in two different Siddhi applications, it is better if we can deploy the in-memory source prior to the in-memory sink. Otherwise, there will be an event loss. 

As per the current implementation, we are considering this source and sink deployment order only for a particular Siddhi application deployment process at a particular moment. Not considering all the Siddhi applications.

Most of the time the in-memory sinks and sources are not in the same Siddhi application. So the order will not be preserved. But if we can deploy the Siddhi application in some order, based on the Siddhi application name it is possible to use a Siddhi application name to order up the sinks and sources. 

Best Regards,
Janith.

### Solution

Make a deployment order.

### Affected Component

SI

### Version

1.1.0

**Comment by YasasRangika** [comment]
Public fix: https://github.com/wso2/carbon-deployment/pull/389 has already been merged.
