### ISSUE TITLE
Duplicate event consumption from Kafka via a Siddhi Kafka source under state persistence. 

### ISSUE THREAD

**Issue by janithcmw** [wso2/api-manager#2242]
### Description

When the events are consuming Kafka via a Siddhi Kafka source, duplicate events will be consumed after following log lines relevant to the state persistence cycle.

After each cycle, there will be considerable event duplications in the system.

Best Regards,
Janith

### Steps to Reproduce

Consume events via a Kafka Siddhi source and monitor the Kafka offset number and the partition number. After a persistence cycle, it is possible to observe duplicate events under the same partition number and the offset number.

### Affected Component

SI

### Version

1.1.0

**Comment by YasasRangika** [comment]
Public fix: https://github.com/siddhi-io/siddhi-io-kafka/pull/162 has already been merged into the master branch.
