### ISSUE TITLE
Advanced UI customization makes APIM 4.2.0 unstable

### ISSUE THREAD

**Issue by nuwankng** [wso2/api-manager#2246]
### Description

When we run the initialising commands on the Node Modules of the Advanced UI customization feature of APIM 4.2.0, Sever is hanging and not able to start properly.

### Steps to Reproduce

Follow the documentation on the Advanced UI customization[1]. 

- execute npm install in the webapps directory
- execute npm run bootstrap in the same directory
- Try to start the APIM server

[1]. [1]. https://apim.docs.wso2.com/en/latest/reference/customize-product/customizations/advanced-ui-customization/

### Affected Component

APIM

### Version

4.2.0

**Comment by YasasRangika** [comment]
The public fix has been released.
