### ISSUE TITLE
Can't add resource to API imported from OAS with clientCredentials security flow

### ISSUE THREAD

**Issue by TomasWso2** [wso2/api-manager#2248]
### Description

Can't add resource to API imported from OAS with clientCredentials security flow

### Steps to Reproduce

Steps to reproduce:

- Create an API

- Download the API swagger definition

- Then change the implicit flow config with client credentials flow config.

clientCredentials:      
	tokenUrl: https://test.com/token      
	scopes: {}

-Import the API definition file and create a new API.

-Add a new resource

-Then the following error appears.
[900754]: Error while parsing OpenAPI definition
attribute components.securitySchemes.default.scopes is missing

ERROR Error while parsing OpenAPI definition:attribute components.securitySchemes.default.scopes is missing {org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl}

--Additional steps:
-Go to edit API Definition, "clientCredentials" flow does not have "scopes", so it says "Error while updating API Definition"

-Add "scopes: {}" to "clientCredentials" and save. 

-The changes were not saved due to validation error.

We were able to reproduce the issue in 3.1.0 too, but there is a few validation in place while importing, so we were only able to reproduce by using the publisher Edit API definition feature instead of importing the modified API swagger.

This does not reproduce in APIM 4.1.0

### Affected Component

APIM

### Version

3.0.0

**Comment by YasasRangika** [comment]
This issue does not apply to the master branch.
