### ISSUE TITLE
Scope selection dropdown won't show more than 25 scopes in publisher

### ISSUE THREAD

**Issue by ksankeerth** [wso2/api-manager#2250]
### Description

Hi Team,

We have more than 25 shared scopes. But It only shows first 25 shared scopes in publisher dropdown. Please see the screenshot below.

<img width="1440" alt="Screenshot 2023-10-29 at 10 50 40" src="https://github.com/wso2-enterprise/wso2-apim-internal/assets/33720251/49ee46a3-5c34-43ad-8170-712b42a52533">

### Steps to Reproduce

- Create more than 25 shared scopes and visit scope selection dropdown  

### Affected Component

APIM

### Version

4.0.0

**Comment by dulithsenanayake** [comment]
This will be tracked from https://github.com/wso2/api-manager/issues/2354
