### ISSUE TITLE
'description' is null in search api-product rest API even configured the description

### ISSUE THREAD

**Issue by NishanthiWi** [wso2/api-manager#2253]
### Description

'Description' attribute is retrieved as null in the response of the get all api-products rest API which is exposed in the publisher portal even the description was configured.

https://apim.docs.wso2.com/en/latest/reference/product-apis/publisher-apis/publisher-v4/publisher-v4/#tag/API-Products/operation/getAllAPIProducts

Here is a sample response
{
"id": "7c1a03ff-5bac-4cc0-8ad4-a5f05de39087",
"name": "TestAPIProduct",
"context": "/test-product",
"description": null,
"provider": "admin",
"hasThumbnail": false,
"state": "PUBLISHED",
"securityScheme": [
"oauth2",
"oauth_basic_auth_api_key_mandatory"
],
"gatewayVendor": null
}

As per the documentation 'description' is there as a response attribute

### Steps to Reproduce

1. Create API-Product with description
2. Invoke the search API-Product endpoint
3. Check the response

### Affected Component

APIM

### Version

4.2.0.44

**Comment by YasasRangika** [comment]
public fix: https://github.com/wso2/carbon-apimgt/pull/12183 has already been merged.

**Comment by HiranyaKavishani** [comment]
Close the issue as per above commit
