### ISSUE TITLE
Receiving "No subject alternative DNS name matching" error when trying to connect to the Choreo analytics server with HTTP proxy configuration

### ISSUE THREAD

**Issue by imedyaosandi** [wso2/api-manager#2254]
### Description

When configured API manager 4.2.0 choreo analytics with HTTP proxy getting the below error.

`WARN {org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper} - No subject alternative DNS name matching somedns.example.org found.`

### Steps to Reproduce

Please refer the internal[1]

[1] https://github.com/wso2-enterprise/wso2-apim-internal/issues/4558

### Affected Component

Analytics

### Version

4.2.0

**Comment by YasasRangika** [comment]
This issue does not affect the master branch.
