### ISSUE TITLE
Missing scopes for admin portal in Scope Assignments section

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/api-manager#2255]
### Description

Under `admin` following scopes are missing. Cannot set scopes for user to view category or settings pages in admin portal

    apim:tier_view
    apim:policies_import_export
    apim:tier_manage
    apim:app_import_export

<img width="777" alt="Screenshot 2023-11-02 at 12 00 26 PM" src="https://github.com/wso2/api-manager/assets/4861150/7b2568de-b20c-442d-9807-03ae594118db">

### Steps to Reproduce

-

### Affected Component

APIM

### Version

4.3.0

**Comment by chamilaadhi** [comment]
Feature related to this issue https://github.com/wso2/api-manager/issues/1187

**Comment by chamilaadhi** [comment]
`apim:policies_import_export` and `apim:policies_import_export' are not needed for admin porta user. Can remove them.

**Comment by HeshanSudarshana** [comment]
Closing the issue since the fix is merged.
