### ISSUE TITLE
Assigning scopes using admin portal Scope Assignments not working

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/api-manager#2256]
### Description

$subject. User cannot generate tokens with provided scope. This works after restarting apim

### Steps to Reproduce

- Create a role from carbon console and assing it to a user
- login to admin portal and assign scopes to this role using `Scope Assignments ` UI in admin portal
- generate access token using password grant type with this scope and check whether token has this new scope
- Scope is not returned
- After a restart, this scope is returned

### Affected Component

Analytics

### Version

4.3.0

**Comment by HeshanSudarshana** [comment]
Closing since the fix is merged.
