### ISSUE TITLE
Dependency Upgrades for APIM 4.3.0

### ISSUE THREAD

**Issue by hisanhunais** [wso2/api-manager#2258]
### Problem

This issue is created to track the dependency upgrades that needs to be done for APIM 4.3.0 release

### Solution

The relevant dependencies which needs to be upgraded should be identified and upgraded

### Affected Component

APIM

### Version

4.3.0

**Comment by hisanhunais** [comment]
The openapi-generator needs to be upgraded to v6.6.0 or higher. With this upgrade, the commons-io which is packed with openapi-generator orbit bundle also can be removed.

**Comment by npamudika** [comment]
The io.netty packages should be upgraded to 4.1.100 or higher.

**Comment by npamudika** [comment]
The pdfbox, fontbox, xempbox jars should be upgraded to 3.0.1 or higher. Need to add the new pdfbox-io jar when going for 3.x pdfbox versions.

**Comment by HeshanSudarshana** [comment]
The jinjava version was bumped to 2.7.1 in APIM 3.2.0. However, currently the available 2.6.0 version in APIM 4.2.0 is also not vulnerable.

**Comment by GihanAyesh** [comment]
The slf4j version in openapi-generator was bumped to 1.7.36 from 1.7.32 in APIM 3.2.0. The fix PRs are https://github.com/wso2/orbit/pull/1034 and https://github.com/wso2/orbit/pull/1036. However when adding to 4.3.0 the openapi-generator version in orbit should be changed from 4.3.1.wso2v7 to 6.6.0.wso2v1.

**Comment by GihanAyesh** [comment]
The following jars were upgraded in APIM 4.2.0 to resolve `"No subject alternative DNS name matching" error when trying to connect to the Choreo analytics server with HTTP proxy configuration`

Dependency | Existing | Updated
-- | -- | --
reactor-core | 3.3.9 | 3.4.31
azure-messaging-eventhubs | 5.3.1 | 5.16.0
azure-core-amqp | 1.6.0 | 2.8.9
azure-core | 1.9.0 | 1.43.0

**Comment by Kirishikesan** [comment]
Need to bump zookeeper and jetty to the following versions
zookeeper to v3.8.3
jetty to v9.4.53.v20231009

**Comment by piyumaldk** [comment]
Need to bump bcprov from bcprov-jdk15on-1.70 to bcprov-jdk18on-1.74 or later.

**Comment by shilmyhasan** [comment]
Need to bump commons-codec version to 1.14 or above.

**Comment by piyumaldk** [comment]
Need to remove callhome from the pack as

**Comment by nandika** [comment]
This was completed
