### ISSUE TITLE
binding_federated_user_claims tomal configuration is not working

### ISSUE THREAD

**Issue by cbabey** [wso2/api-manager#2260]
### Description

The configuration introduced through fix[1] was not picked up during runtime and thus failed to add claims of federated users even though it was enabled. 

[apim.jwt]
binding_federated_user_claims = true

[1] https://github.com/wso2/carbon-apimgt/pull/10836

### Steps to Reproduce

1. Configure the external IDP for the APIM to work with the JWT bearer grant type by referring to the documentation[1].
2. Confiture the secondary user store for both the APIM and ID.
3. Generate JWT assertion from the IDP (for users in a secondary user store) and obtain the access token from the APIM token endpoint using the JWT bearer grant type. 
4. enable the backend JWT token generation with the blow properties
5. Invoke a API published on the APIM.

[apim.jwt]
enable = true
gateway_generator.enable_claim_retrieval = true
binding_federated_user_claims=true

[1] https://apim.docs.wso2.com/en/latest/design/api-security/oauth2/grant-types/jwt-grant/

### Affected Component

APIM

### Version

4.2.0

**Comment by YasasRangika** [comment]
The public fix: https://github.com/wso2/carbon-apimgt/pull/12188 has already been merged to the master branch.
