### ISSUE TITLE
Previous validation errors are showing for valid API definition - APIM 4.2.0 publisher

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/api-manager#2273]
### Description

Previous API definition validation errors are showing in the publisher UI (API creation page) even adding a valid API definition.

### Steps to Reproduce

- Start the API manager and go to the publisher portal.
- Go to the API creation page by using open API.
- Then add the below URL which should throw API definition validation errors because the URL is not a valid one.

https://petstore.swagger.io/v2/swagger.jso
![image1](https://github.com/wso2/api-manager/assets/18566908/c9cf12cf-d66f-4c81-b534-a7ca3bd6eab0)

- After this, add the below URL which has a valid API definition and you will be able to see the previously thrown error in that time as well.

https://petstore.swagger.io/v2/swagger.json
![image2](https://github.com/wso2/api-manager/assets/18566908/2eb5abed-43ab-4c9b-a694-745cd357d7fc)

### Affected Component

APIM

### Version

4.2.0

**Comment by Kirishikesan** [comment]
`Developer Comments`

- The staging pack is working as expected.
- Peer test passed
- Therefore update is promoted to UATStaging.

**Comment by YasasRangika** [comment]
public fix pr: https://github.com/wso2/apim-apps/pull/517 has already been merged into the main branch.
