### ISSUE TITLE
Throwing the 500 response when loading the API definition page and Business info section in the Publisher - APIM 4.2.0

### ISSUE THREAD

**Issue by ug205** [wso2/api-manager#2274]
### Description

 Observing 500 error due to the malformed URL when navigating to the Business Info section and API Definition section.

### Steps to Reproduce

We were able to reproduce using the below steps  in APIM 4.2.0 latest U2: 46

Started the server
Create an API
After creating the API, go to the API Definition page.
Then try to refresh the page and able to see the below error response.
{
  "traceId": "16b81d8d-6d56-4032-b810-caa6c7f7b21a",
  "code": 500,
  "description": "Operation is not permitted. You do not have permissions to make this request.",
  "message": "Forbidden"
}

### Affected Component

APIM

### Version

4.2.0

**Comment by YasasRangika** [comment]
public fix: https://github.com/wso2/apim-apps/pull/517 has already been merged into the main branch.
