### ISSUE TITLE
Missing ‘maxDays’ j2 mapping for APIM 400

### ISSUE THREAD

**Issue by jichinthaka** [wso2/api-manager#2279]
### Problem

We identified that the j2 mapping for the below toml configuration is available with both APIM 4.1.0  and APIM 3.2.0 . But not available with APIM 4.0.0.

[http_access_log]
maxDays = 1

We manually added this j2 mapping add tested in APIM 4.0.0. It works as expected.

### Solution

Please, can you give the missing ‘maxDays’ j2 mapping as a fix?

### Affected Component

APIM

### Version

4.0.0

**Comment by YasasRangika** [comment]
As mentioned in the linked internal issue, the fix for this issue is already available in the master branch.
