### ISSUE TITLE
Bump netty to a 5.x. version after its release

### ISSUE THREAD

**Issue by Lakith-Rambukkanage** [wso2/api-manager#2290]
### Description

Upgrade netty to a 5.x version after its release

Related Issues:
https://github.com/wso2-enterprise/wso2-apim-internal/issues/4896
https://github.com/wso2-enterprise/wso2-apim-internal/issues/4899
https://github.com/wso2-enterprise/wso2-apim-internal/issues/4901
https://github.com/wso2-enterprise/wso2-apim-internal/issues/5025 

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

4.3.0

**Comment by npamudika** [comment]
Removing from the 4.3.0 release, as the netty 5.x version is not yet available.

**Comment by npamudika** [comment]
Since there are no GA releases for netty 5.x after 2015, closing the issue.
