### ISSUE TITLE
Can't add resource to API imported from OAS with clientCredentials security flow

### ISSUE THREAD

**Issue by Manasha11** [wso2/api-manager#2295]
### Description

The following error gets printed when trying to add a resource to an API imported from OAS with clientCredentials flow.
`ERROR Error while parsing OpenAPI definition:attribute components.securitySchemes.default.scopes is missing {org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl}`

### Steps to Reproduce

- Create an API
- Download the API swagger definition
- Then change the implicit flow config with client credentials flow config.
```
clientCredentials:
tokenUrl: https://test.com/token
scopes: {}
```
-Import the API definition file and create a new API.
-Add a new resource

### Affected Component

APIM

### Version

3.0.0

**Comment by YasasRangika** [comment]
This issue does not apply to the master branch.
