### ISSUE TITLE
Masking User IP value

### ISSUE THREAD

**Issue by dilshanfardil** [wso2/api-manager#2296]
### Problem

Hi Team,

In this ticket, the customer mentioned when the analytic event collects data [1] and publishing, it sends the user IP value in an event to Choreo Analytics.

So, the customer has a requirement to mask the last 2 octet of the user IP address due to this information being classisfied as sensitive in their case.

Example: 10.102.92.23 must be changed to 10.102..

We would like to know since these information is sensitive in their usecase, is there a way to overcome this issue?

Highly appreciate your input on this.

### Solution

Rather than passing the same value we can mask the value [1]

https://github.com/wso2-support/carbon-apimgt/blob/support-9.28.116.x-full/components/apimgt/org.wso2.carbon.apimgt.common.analytics/src/main/java/org/wso2/carbon/apimgt/common/analytics/collectors/impl/SuccessRequestDataCollector.java#L93

### Affected Component

APIM

### Version

4.2.0

**Comment by YasasRangika** [comment]
Public PR: https://github.com/wso2/carbon-apimgt/pull/12190
