### ISSUE TITLE
[APIM 4.2.0] - API Name is exceeding limit

### ISSUE THREAD

**Issue by dilshanfardil** [wso2/api-manager#2303]
### Description

We have a requirement from the customer that they need to exceeding the limit of the API Name which is currently 60 and this is the curl that customer is using in order to create the API.

Getting this error 

```

{
	"code": 400,
	"message": "Bad Request",
	"description": "Validation Error",
	"moreInfo": "",
	"error": [
		{
			"code": "400_name",
			"message": "name: size must be between 1 and 60",
			"description": null
		}
	]
}

```

### Steps to Reproduce

Do a PUT request to update the api 

`curl --request PUT --url 'https://localhost:9443/api/am/publisher/v4/apis/`

With an existing api that the name exceed more than 60 characters. And we cannot update that particular API.

### Affected Component

APIM

### Version

4.2.0

**Comment by npamudika** [comment]
Fixed via https://github.com/wso2/carbon-apimgt/pull/12224/
