### ISSUE TITLE
Backport UPDATE USERS management API to EI 7.1.0

### ISSUE THREAD

**Issue by LayaniMal** [wso2/api-manager#2310]
### Problem

There is a requirement to change the password by using the UPDATE USERS management API in MI 1.2.0.

### Solution

As this[1] function is added via an update in MI 4.1.0, we need to backport it to MI 1.2.0.

[1] https://apim.docs.wso2.com/en/latest/observe/mi-observe/working-with-management-api/#update-users

### Affected Component

MI

### Version

1.2.0

### Suggested Labels

MI-1.2.0

**Comment by YasasRangika** [comment]
This issue has already resolved in the master branch.
