### ISSUE TITLE
Renew the access token without revoking the existing token

### ISSUE THREAD

**Issue by Manasha11** [wso2/api-manager#2326]
### Problem

The feature of renewing the access token without revoking the existing token, is not available of APIM 3.1.0.

### Solution

Add port following feature available in APIM 4.x to APIM 3.1.0.

```
[oauth.jwt.renew_token_without_revoking_existing]
enable = true
```

### Affected Component

APIM

### Version

3.1.0

**Comment by dulithsenanayake** [comment]
Hi all,

Closing this since the update is released & N/A in public.

Thanks!
Dulith
