### ISSUE TITLE
Linter Rules feature in APIM 4.2.0 not support for “schema” core function

### ISSUE THREAD

**Issue by jichinthaka** [wso2/api-manager#2335]
### Problem

Linter Rules feature in APIM 4.2.0 not support for “schema” core function [1]

[1] - https://meta.stoplight.io/docs/spectral/cb95cf0d26b83-core-functions#schema

### Solution

add the capability 

### Affected Component

APIM

### Version

4.2.0

**Comment by Lakith-Rambukkanage** [comment]
Fixed by : https://github.com/wso2/apim-apps/pull/522
