### ISSUE TITLE
Add searchable option for listings

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/api-manager#2354]
### Description

Introduce the searchable option in the necessary places where we have listings in the portals. 
**Hint**: we need to implement the searchable option instead of the scope selection dropdown.

### Affected Component

APIM

### Version

4.3.0

**Comment by Lakith-Rambukkanage** [comment]
## Identified places to add the Autocomplete field (Searchable option) [DRAFT]

Publisher portal
- [ ] Scopes list in API resources
- [ ] API Categories 
- [ ] Subscription filters in API subscriptions
    - [ ] Subscriptions
    - [ ] Applications
    - [ ] Tiers

Dev portal
- [ ] Subscription Tiers

Admin portal


[1] https://mui.com/material-ui/react-autocomplete/
