### ISSUE TITLE
API Groups page not showing groups properly in the DevPortal

### ISSUE THREAD

**Issue by shavinsenadheera** [wso2/api-manager#2358]
### Description

We have noticed some issues on the developer portal API Groups page on the latest U2 level (122) of APIM 4.1.0. Please refer to the below attached image.
 
![Screenshot from 2023-12-26 12-45-38](https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/3d594184-6a88-4081-be1c-9c954ff4abb6)

### Steps to Reproduce

Follow the [1] and create API groups.

[1] - https://apim.docs.wso2.com/en/3.0.0/learn/consume-api/customizations/customizing-the-developer-portal/customize-api-listing/categorizing-and-grouping-apis/

### Affected Component

APIM

### Version

4.1.0

**Comment by RakhithaRR** [comment]
Fixed with https://github.com/wso2/apim-apps/pull/527
