### ISSUE TITLE
API-M 4.3.0 Migration Effort

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#2382]
This issue is created to track the tasks for APIM 4.3.0 migration.

- [x] Creating migration data population script.
- [x] Manual Migration Testing with the populated data.
    - [x]  Mysql testing
    - [x]  Postgresql DB testing
    - [x]  Mssql DB testing
    - [x]  Oracle DB testing
    - [x]  DB2 DB testing
- [x] Creating initial DB script for migration based on the new changes to the product from features and dependency upgrades.
- [x] Fixing the code to support the migration based on the new changes introduced to the product.
- [ ] Creating automation for migration testing.
- [x] Fixing issues encountered during migration testing.
- [x] Creating migration documentation.

**Comment by npamudika** [comment]
Test the 4.0.0 -> 4.3.0 migration for https://github.com/wso2/api-manager/issues/1970 while doing the migration testings as well
