### ISSUE TITLE
API document name length in the APIM 4.2.0

### ISSUE THREAD

**Issue by shavinsenadheera** [wso2/api-manager#2388]
### Description

There is a validation for the API document name length (Max: 60 characters) on the APIM 4.2.0. Therefore, the migrated APIs from 3.2.0 could not update since they are having the API document name which the length is exceeded than 60 characters.be updated

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

4.2.0

**Comment by tharikaGitHub** [comment]
Closing as the public PR [1] is merged.

[1] https://github.com/wso2/carbon-apimgt/pull/12397
