### ISSUE TITLE
[4.3.0] Upgrade the rest api versions in APIM

### ISSUE THREAD

**Issue by npamudika** [wso2/api-manager#2405]
### Description

Rest API versions will be modified as bellow

publisher : v4--> v4.1 (major version: v4 , latest version : v4.1)
admin : v4 --> v4.1 (major version: v4 , latest version : v4.1)
devportal : v3 --> v3.1 (major version: v3 , latest version : v3.1)
gateway : v2.2 --> v2.3 (major version: v2 , latest version : v2.3)
serviceCatelog : v1.1 --> v1.2 (major version: v1 , latest version : v1.2)
devops : v0 --> v0.1 (major version: v0 , latest version : v0.1)

### Affected Component

APIM

### Version

4.3.0

**Comment by Lakith-Rambukkanage** [comment]
Closing since the PR is merged
