### ISSUE TITLE
Port fixes for wso2-extensions/identity-inbound-auth-oauth

### ISSUE THREAD

**Issue by RusJaI** [wso2/api-manager#2406]
Need to apply relevant fixes into https://github.com/wso2-extensions/identity-inbound-auth-oauth/tree/6.9.x

**Comment by RusJaI** [comment]
### Update [2024-01-23]
Started working on the issue after completing the commits doc, which contains the PRs for each identity component.

There are some commits that are already there in the corresponding  master branch.

Completed adding commits from support PRs.

**Comment by RusJaI** [comment]
Update [2024-01-24]

As per the README of the carbon identity inbound oauth repo, it should be able to build on jdk 11 and 17.

But the build is failing with both jdk versions and with jdk 8, it builds with errors of finding resource paths.

Checked the same issue in previous release checking out to tag 6.9.6. The same issue exists there as well.

Currently analysing the issue.

**Comment by RusJaI** [comment]
### Update [2024-01-25]

As per the Jenkins build it supports JDK 11 and Maven 3.5.4
It was identified that this issue is a known issue for Mac OS (with Apple Silicon)

Further when analysing the corresponding patch entries for the applied commits, identified that the fix is going to several repositories. Hence the fix to be fully applicable, need to apply the changes into corresponding branches of those repositories too.

Currently analysing that fixes and documenting them. This is stacked by : https://github.com/wso2/api-manager/issues/2428

**Comment by RusJaI** [comment]
### Update [2024-01-30]

As mentioned in the comment : https://github.com/wso2/api-manager/issues/2428#issuecomment-1916087280, since it was decided to change the kernel version, the component version for this repository will be changed to 6.11.x

Related work to this issue will be started after initial analysis and related kernel fixes.

**Comment by HiranyaKavishani** [comment]
Closing the issue as the task is done
