### ISSUE TITLE
[4.3.0] Upgrade REST API version in Docs

### ISSUE THREAD

**Issue by npamudika** [wso2/api-manager#2410]
### Description

This issue is used to track the REST API upgrade in Docs.

Major Rest API versions are modified as below

publisher : v4--> v5 (major version: v5 , latest version : v5)
admin : v4 --> v5 (major version: v5 , latest version : v5)
devportal : v3 --> v4 (major version: v4 , latest version : v4)

### Affected Component

APIM

### Version

4.3.0

**Comment by Lakith-Rambukkanage** [comment]
- [ ] Change 4.2.0 to 4.3.0 
- [ ] Update postman collections
- [ ] Update swagger github tags in api.yaml files

**Comment by Lakith-Rambukkanage** [comment]
Closing since the docs are updated and an issue is created to track the tasks required after release.
