### ISSUE TITLE
Version upgrade for json-smart and json-path

### ISSUE THREAD

**Issue by GihanAyesh** [wso2/api-manager#2419]
### Description

4.3.0 version upgrades,

- json-smart: 2.4.7 --> 2.5.0
- json-path: 2.6.0.wso2v1 --> 2.9.0.wso2v1

### Affected Component

APIM

**Comment by tgtshanika** [comment]
Test Scenarios:
- json-eval expression

**Comment by GihanAyesh** [comment]
Following usecases were tested

- Gateway JWT validation
- OIDC Login Flow
- Create a log policy with json-eval to get string, integer, array and object values
