### ISSUE TITLE
Remove the Client Secret View option in OAUTH2 Endpoint security

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/api-manager#2421]
### Description

Due to the security concerns, please remove the Client Secret View option in OAUTH2 Endpoint security same as the basic or digest Auth.

The reason is, for both Basic and digest auth, the password cant be seen by anyone who has access.
But in case of OAuth 2.0, if the API is public, all the users can see the masked client secret by clicking on view option, which is not available for passwords.

### Steps to Reproduce

1] Create a API from Publisher
2] Go to the Endpoint Section and, set the Endpoint Security
3] Set Basic Auth. There is no View Option in Password Field.
4] Set Auth2. For both Client credentials/resource owner password options, there is a View Option for the Client Secret

### Affected Component

APIM

### Version

4.1.0

**Comment by tharikaGitHub** [comment]
Closing as the following public PRs are merged.

1. https://github.com/wso2/carbon-apimgt/pull/12312
2. https://github.com/wso2/apim-apps/pull/588
3. https://github.com/wso2/product-apim/pull/13466
