### ISSUE TITLE
When importing a new schema definition the operations are getting modified to /*

### ISSUE THREAD

**Issue by chaveeka** [wso2/api-manager#2424]
### Description

Hi Team, 

We have observed that when importing a new schema definition to a created API all the operations are getting modified to **/***. 

Please note that when using the schema provided in our official documentation[1] with the same steps, this was not reproduced. The difference between the 2 schemas is that the schema attached to the official documentation[1] has object types defined as "Query", "Mutation" and "Subscription". But in the tested schema didn't have it defined with the same names. Because of this reason, it fails adding the correct operations. 

We were able to observe the same behaviour in the latest u2 update level-130 as well. 

[1]https://apim.docs.wso2.com/en/latest/design/create-api/create-a-graphql-api/#step-2-design-a-graphql-api

Thanks, 
Chaveeka 

### Steps to Reproduce

1. Create a GraphQL API by Importing GraphQL SDL definition. 
2. Provide GraphQL File. 
3. Provide the API name, context, version and endpoint and create the API. 
4. List the Operations under API Configurations. You will observe all the operations as follows, 

<img width="1501" alt="Screenshot 2024-01-24 at 17 38 20" src="https://github.com/wso2-enterprise/wso2-apim-internal/assets/61019902/140c9e07-3a66-4dbb-a5b2-89e917c2ee38">

5. Go to Schema Definition and import the updated GraphQL file. 

6. List the Operations You will observe all the operations are modified to /*. 

<img width="1496" alt="Screenshot 2024-01-24 at 17 38 57" src="https://github.com/wso2-enterprise/wso2-apim-internal/assets/61019902/546b724c-5f41-4505-9931-eb283e4e2f26">

### Affected Component

APIM

### Version

4.1.0

**Comment by chamilaadhi** [comment]
Fix merged in public branch from https://github.com/wso2/carbon-apimgt/pull/12241
