### ISSUE TITLE
Upgrade ReactJS 18 in Publisher Portal

### ISSUE THREAD

**Issue by lasanthaS** [wso2/api-manager#2438]
### Description

This is to track the progress related to ReactJS 18 upgrade in the Publisher portal.

### Affected Component

None

### Version

4.3.0

### Related Issues

- https://github.com/wso2/api-manager/issues/2191

**Comment by lasanthaS** [comment]
### Work log

- Migrated the ReactJS from 17.0.0 to 18.0.0
- Migrated the components from `@material-ui/core` to `@mui/material` package 
- Migrated the components from `@material-ui/icons` to `@mui/icons-material` package

**Comment by lasanthaS** [comment]
- Migrated all the `@material-ui/*` packages to `@mui/*` packages.
- Migrated the styles to MUI5.

After migrating the UI styles, now the publisher is working fine. However, UI styles are not properly rendering, so need to work on fixing those styles.

Thanks,
Lasantha

**Comment by tharikaGitHub** [comment]
Closing as the task is completed.
