### ISSUE TITLE
Kernal version upgrade to 4.9.x

### ISSUE THREAD

**Issue by RusJaI** [wso2/api-manager#2444]
Need to check all the repositories that depends on the kernel and their feasibility to build on the new kernel version.
With that, need to build the product on kernel version 4.9.x addressing the issues that encounter.

**Comment by RusJaI** [comment]
### Update [2024-01-30]

Listed out the relevant repositories that depend on the kernel (except the IS components)
Added the correlation log commits and built the kernel tag 4.9.0 (because we're going to proceed with those changes)
and built the kernel.
Built the listed repositories on kernel version 4.9.0. The observations were listed in the sheet "kernel-dependent-repos" in https://docs.google.com/spreadsheets/d/1HFoHn9Uaeo8J_iG3e6Q4PJs-ajOIQCIvC2kjvtnX5YY/edit?usp=sharing

**Comment by HiranyaKavishani** [comment]
Remove the older 4.9.x and re-created the 4.9.x branch from the 4.9.0 tag that is compatible with IS 6.1.0

[1] https://github.com/wso2/carbon-kernel/tree/4.9.x

**Comment by RusJaI** [comment]
### Update [2024-02-01]
@msm1992 and myself collaboratively worked on building the product with kernel upgrade and version changes of related components, to speedup the process since dependency upgrade process also was blocked by the build issues. 
Could build the repo successfully EoD.

Further @msm1992 was analysing a startup error and API deploy issue in the newly built pack

**Comment by HiranyaKavishani** [comment]
Close the issue since the task is done
