### ISSUE TITLE
Remove role validation when registering scopes in KM

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#2445]
### Problem

When there are multiple KMs and if such a KM not support the user-role model, the validation of roles in the scope creation does not make sense.

### Solution

Remove role validation from scope management UI in publisher portal. Allow adding any text as roles for a scope. It can be a direct userstore group or a username as well depending on the KM implementation.

### Affected Component

APIM

### Version

4.3.0

**Comment by PasanT9** [comment]
Role validation at scope creation can be disable by adding the sytem property **disableRoleValidationAtScopeCreation**
