### ISSUE TITLE
Issues when adding API Products with examples

### ISSUE THREAD

**Issue by LayaniMal** [wso2/api-manager#2451]
### Description

**_Token "examples" does not exist_** error observed when adding a resource that contains examples into an APIProduct and checked the **Resource** section.

### Steps to Reproduce

- Import or create API with examples. (sample: [sample-swagger.txt](https://github.com/wso2/api-manager/files/14155803/sample-swagger.txt))
- Create a new APIProduct using that API
- Include resource GET /ping
- Deploy this APIProduct
- Go to the resources section and it will show the following warning 
![Screenshot from 2024-02-04 12-12-34](https://github.com/wso2/api-manager/assets/25350433/49d99524-b2c9-4ffd-9612-eeff39a735f0)
- And when click the WARN icon _**Errors in OpenAPI definition: Token "examples" does not exist**_ error will pop up.
![Screenshot from 2024-02-04 12-12-42](https://github.com/wso2/api-manager/assets/25350433/476abddd-1bca-4f8a-8f7b-0dfae542f410)

### Affected Component

APIM

### Version

4.0.0

### Suggested Labels

APIM-4.0.0 APIProduct

**Comment by hisanhunais** [comment]
- Master fix added using https://github.com/wso2/carbon-apimgt/pull/12395
