### ISSUE TITLE
DevPortal - UI Issue in API Overview Page

### ISSUE THREAD

**Issue by vikumkbv** [wso2/api-manager#2452]
### Description

Hi Team,

The Devportal&#39;s API Overview page does not allow the user to select/view first resource if there are more than 10 resources defined for the API. Can we fix this? 

Please find the attached screenshot for your reference. (refer to the Resources section)
![ae67161693008650ee0c726d6cba1094](https://github.com/wso2-enterprise/wso2-apim-internal/assets/33031034/f744414b-90d3-4912-8fd1-b60a09439af7)

We have tested this in U2 level (338) as well. 

Regards,
Vikum

### Steps to Reproduce

1. Create an API and then add 10 or more resources, publish it
2. Go to the devportal overview page and refer to the "Resources" section you can find the overlapping issue.

### Affected Component

APIM

### Version

3.2.0

**Comment by chashikajw** [comment]
This is not applicable to master branch and latest products.
