### ISSUE TITLE
User couldn't manipulate APIs in the portal after removing an active GW using deployment.toml

### ISSUE THREAD

**Issue by NishanthiWi** [wso2/api-manager#2458]
### Problem

There is a potential improvement area concerning API loading within the portals. When a user removes a GW from the deployment.toml file after APIs have already been deployed, it prevents the API meta pages from loading. Consequently, users are unable to make modifications to the APIs to work with the remaining gateways.

Steps to Reproduce:

- Register the gateway environment in the CP.
- Deploy an API.
- Remove the specific gateway from the deployment.toml file.
- Attempt to open the API in the publisher portal.

As a result, the API will fail to load, and the following stack trace will be printed in the log.

TID: [-1234] [api/am/publisher] [2024-01-31 16:40:25,688] ERROR {org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl} - Error while adding retrieving API Revision for api id : fe70ab8f-3bf3-463a-a1c2-f4918cadd266 - Configured read only environment not found: AWS Pre-Production Gateways org.wso2.carbon.apimgt.api.APIManagementException: Configured read only environment not found: AWS Pre-Production Gateways at org.wso2.carbon.apimgt.impl.utils.APIUtil.getDefaultVhostOfReadOnlyEnvironment_aroundBody680(APIUtil.java:9843)

### Solution

The expected behaviour is for the APIs to load and operate with the available gateways, disregarding any unavailable ones

### Affected Component

APIM

### Version

4.0.0

**Comment by tharikaGitHub** [comment]
Closing as the public PR is merged.
