### ISSUE TITLE
Introduce SHA256 related thumbprint header for internal JWKS and backend JWT

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/api-manager#2459]
### Problem

Currently we use SHA-1 thumbprint (x5t) in our internal JWKS and backend jwt. SHA-1 algorithm is now deprecated. [1] 

[1] - https://www.nist.gov/news-events/news/2022/12/nist-retires-sha-1-cryptographic-algorithm

### Solution

Since this is deprevated, we need to introduce SHA-256 based thumbprint with x5t#S256 while keeping the x5t to preserve backward compatibility.

### Affected Component

APIM

### Version

4.3.0

**Comment by hisanhunais** [comment]
Fixed via https://github.com/wso2/carbon-apimgt/pull/12365
