### ISSUE TITLE
Malformed token calls with  wrong user inputs

### ISSUE THREAD

**Issue by ksankeerth** [wso2/api-manager#2460]
### Description

With special character:
 curl -k -X POST https://localhost:8243/token -d "grant_type=password&username=admin&password=admin" -H "Authorization: Basic TExuemRCSWVRWnRybFJtS1NTOFhhUmxnSmRjYTo0UkM1ZmdUdVdldHljQzJ2YUJRX1VxZTdRSlVh##***^^^"

With above value special characters we are able to get a token (200 status code) with this above invalid input. This should be a 401 status code.

Another observation is that when we append numbers we were able to get 500 errors with html response, but the above scenario customer is expecting 401 status code.

With numbers

curl -k -X POST https://localhost:8243/token -d "grant_type=password&username=admin&password=admin" -H "Authorization: Basic TExuemRCSWVRWnRybFJtS1NTOFhhUmxnSmRjYTo0UkM1ZmdUdVdldHljQzJ2YUJRX1VxZTdRSlVh1222222222" 

<!doctype html><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style>

### Steps to Reproduce

With special character:
curl -k -X POST https://localhost:8243/token -d "grant_type=password&username=admin&password=admin" -H "Authorization: Basic TExuemRCSWVRWnRybFJtS1NTOFhhUmxnSmRjYTo0UkM1ZmdUdVdldHljQzJ2YUJRX1VxZTdRSlVh##***^^^"

With above value special characters we are able to get a token (200 status code) with this above invalid input. This should be a 401 status code.

Another observation is that when we append numbers we were able to get 500 errors with html response, but the above scenario customer is expecting 401 status code.

With numbers

curl -k -X POST https://localhost:8243/token -d "grant_type=password&username=admin&password=admin" -H "Authorization: Basic TExuemRCSWVRWnRybFJtS1NTOFhhUmxnSmRjYTo0UkM1ZmdUdVdldHljQzJ2YUJRX1VxZTdRSlVh1222222222"

<!doctype html><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style>

### Affected Component

APIM

### Version

3.2.0

**Comment by chamilaadhi** [comment]
Master fix is added from https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2361 . @chashikajw shall we check whether this fix is included in 6.13.x as well for the 4.3.0 release

**Comment by tharikaGitHub** [comment]
Closing this issue as the public PR is merged.
