### ISSUE TITLE
No endpoint metrics displayed in ELK monitoring when endpoint is deployed as a registry artifact 

### ISSUE THREAD

**Issue by vikumkbv** [wso2/api-manager#2465]
### Description

Hi Team,

We found an issue when we deploy http endpoints as registry artifact, MI ELK analytics is not recording the relevant traffic, this works perfectly on the EI 6.6.0.

When we check the MI ELK logs we are getting only API related data as follows.
`
 18:49:08,268 [-] [message-flow-reporter-0-tenant--1234]  INFO ElasticStatisticsPublisher SYNAPSE_ANALYTICS_DATA {"serverInfo":{"hostname":"vikum","serverName":"localhost","ipAddress":"127.0.0.1","id":"wso2mi_server_1234"},"timestamp":"2024-02-05T13:19:05.398Z","schemaVersion":1,"payload":{"metadata":{},"entityType":"API","failure":false,"latency":629,"messageId":"urn:uuid:d8f64e64-574e-4a74-bc92-b754150359f3","correlation_id":"d8f64e64-574e-4a74-bc92-b754150359f3","apiDetails":{"method":"POST","apiContext":"/rmi","api":"RMI","transport":"https","subRequestPath":"/expedientes"},"faultResponse":false,"entityClassName":"org.apache.synapse.api.API","httpMethod":"POST"}}
 `

Thanks,
Vikum

### Steps to Reproduce

Deploy a API with a endpoint saved as registry artifact

### Affected Component

MI

### Version

4.2.0

**Comment by DedunuKarunarathne** [comment]
Moving to MI repo with https://github.com/wso2/micro-integrator/issues/3108
