### ISSUE TITLE
[Docs] Need to update latest api.yaml files, github release tag locations and postman collections in the docs after release

### ISSUE THREAD

**Issue by Lakith-Rambukkanage** [wso2/api-manager#2468]
Need to : 

- [x] Update github url for the swagger location in the api.yaml files with the public GitHub release tag (4.3.0 ref [1])
- [x] Update postman collection URLs (4.3.0 ref [2])
- [x] Update the api.yaml files in the docs after all feature PRs are merged / 4.3.0 release

_Originally posted in https://github.com/wso2/api-manager/issues/2410#issuecomment-1932124723_

[1] https://github.com/wso2/docs-apim/issues/6781
[2] https://github.com/wso2/api-manager/issues/1076

**Comment by HeshanSudarshana** [comment]
Closing since the API docs are updated.
