### ISSUE TITLE
Publisher portal deployment page is broken when refreshing page

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/api-manager#2472]
### Description

Publisher deployment page is broken when refreshing deployment page in Publisher portal

### Steps to Reproduce

1. Deploy sample API
2. Go to Deployement page
3. Refresh the page

<img width="1714" alt="Screenshot 2567-02-13 at 10 39 58 AM" src="https://github.com/wso2/api-manager/assets/29066805/a5dd8879-a318-46ac-b43b-ff027f80cae2">

### Affected Component

APIM

### Version

4.3.0

### Suggested Labels

Component/APIM

**Comment by GihanAyesh** [comment]
Fix for issue: https://github.com/wso2/apim-apps/pull/542
Please wait for @Krishanx92 to test the fix.

**Comment by Krishanx92** [comment]
This need to fix in all places in same jsx file @GihanAyesh

**Comment by GihanAyesh** [comment]
Please find the PR: https://github.com/wso2/apim-apps/pull/548
