### ISSUE TITLE
User can publish API when the deployment is in pending approval state

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2476]
### Description

User can publish APIs when the deployment is in pending approval state.

This behaviour can be observed in two scenarios.
1. Publish API from Lifecycle page
2. User Create & Publish APIs directly from create API page

<img width="677" alt="Screenshot 2024-02-14 at 12 31 35" src="https://github.com/wso2/api-manager/assets/54719880/aeb49dd9-5f2c-42e9-b848-df4275a7627b">

**Expected behaviour** 

 Publishing the API should be restricted until the deployment is approved. 
 API can be published without deployment only if user provides an endpoint to a third party API

### Steps to Reproduce

prerequisites - Enable the approval workflow for the revision deployment

1. Login to publisher portal
4. Create an API 
5. Navigate to deployment page and deploy the API (  deployment should be in pending approval state)
6. Navigate to Lifecycle page 
7. Click on publish button.

### Affected Component

APIM

### Version

4.3.0

### Environment Details (with versions)

Tested in Local Environment
MacOS

**Comment by chamilaadhi** [comment]
Fix for scenario 1 https://github.com/wso2/apim-apps/pull/602

**Comment by chamilaadhi** [comment]
Fix for scenario 2 https://github.com/wso2/apim-apps/pull/602/commits/f2244a13c0ee243aba4cd1b74c570a45e87ef9e6
