### ISSUE TITLE
Product version needs to be displayed under the context section in overview page

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2481]
### Description

In general API version is displayed under the 'Context' section in the API overview page.

Same as version needs to be added in API products overview page. Currently it is not displayed under the 'Context' section.

<img width="593" alt="Screenshot 2024-02-14 at 09 48 25" src="https://github.com/wso2/api-manager/assets/54719880/2bf0f224-9e54-43ec-af67-baf3b91e0425">

### Steps to Reproduce

1. Login to publisher portal
2. Create an API product
3. Navigation to API overview page
4. Check the Context section

### Affected Component

APIM

### Version

4.3.0

### Environment Details (with versions)

Local Environment

**Comment by tharikaGitHub** [comment]
Closing as this is fixed with PR https://github.com/wso2/apim-apps/pull/630
