### ISSUE TITLE
Devportal visibility role permission not getting reflected properly in registry resources

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/api-manager#2485]
### Description

When we update an API by adding a developer visibility role, the registry resource permission related to the new role won't be applied correctly. 

### Steps to Reproduce

The steps required to reproduce the issue are as below. 
1. Create three roles called "Internal/devportalrole1", "Internal/devportalrole2" and "Internal/publisherrole".
2. Log into the publisher portal and create an API called "testapi".
3. Add the "Internal/publisherrole" role under publisher visibility restricted roles.
4. Add the "Internal/devportalrole1" role under devportal visibility restricted roles.
5. Save the changes, deploy a new revision, and publish the API.
6. Then go back to the publisher portal and add the "Internal/devportalrole2" role under devportal visibility restricted roles.
7. Save the changes, and deploy a new revision.

### Affected Component

APIM

### Version

4.1.0

**Comment by tharikaGitHub** [comment]
Closing as the public PR is merged.

**Comment by GihanAyesh** [comment]
Fix PR: https://github.com/wso2/carbon-apimgt/pull/12286
