### ISSUE TITLE
Support JWT Tokens in portal apps

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#2496]
### Problem

Currently portal apps only work with opaque tokens. To add support for JWT tokens, OAuthJWTAuthenticatorImpl needs additional changes to validate issuer and signature from resident identity provider.

### Solution

Implement logic to local resident idp and validate token issuer and set certificate and other details in JWTValidator impl instance.

### Affected Component

APIM

### Version

4.3.0 - M2

**Comment by dushaniw** [comment]
To support tenant logins, it is mandatory to append tenant domain to the local subject identifier.

**Comment by chamilaadhi** [comment]
PR for identity-inbound-auth-oauth component https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/2384

**Comment by chamilaadhi** [comment]
carbon-apimgt fix https://github.com/wso2/carbon-apimgt/pull/12297

**Comment by chamilaadhi** [comment]
Integration test update to run with JWT https://github.com/wso2/product-apim/pull/13394

**Comment by chamilaadhi** [comment]
14 Integration tests failing. Currently checking them

        [INFO] Results:
        [INFO]
        [ERROR] Failures:
        [ERROR] org.wso2.am.integration.tests.api.lifecycle.APITagVisibilityByRoleTestCase.testAPITagVisibilityAuthorisedUser
        [INFO]   Run 1: PASS
        [INFO]   Run 2: PASS
        [INFO]   Run 3: PASS
        [ERROR]   Run 4: APITagVisibilityByRoleTestCase.testAPITagVisibilityAuthorisedUser:188 Restricted visibility tag is not available for authorised user expected [true] but found [false]
        [INFO]   Run 5: PASS
        [INFO]
        [ERROR] org.wso2.am.integration.tests.api.lifecycle.APIVisibilityWithDirectURLTestCase.testDirectLink
        [INFO]   Run 1: PASS
        [INFO]   Run 2: PASS
        [INFO]   Run 3: PASS
        [INFO]   Run 4: PASS
        [ERROR]   Run 5: APIVisibilityWithDirectURLTestCase.testDirectLink:152 Â» Api
        [INFO]
        [ERROR]   APIProductLifecycleTest.destroy:265 Â» Api
        [ERROR] org.wso2.am.integration.tests.apiproduct.lifecycle.APIProductLifecycleTest.testCreateAPIProduct
        [INFO]   Run 1: PASS
        [INFO]   Run 2: PASS
        [INFO]   Run 3: PASS
        [INFO]   Run 4: PASS
        [ERROR]   Run 5: APIProductLifecycleTest.testCreateAPIProduct:131 expected [true] but found [false]
        [INFO]
        [ERROR]   CrossTenantSubscriptionTestCase.testCreateSubscriptionFromTenant1AppToTenant2APIRestrictedPolicy:573 null
        [ERROR]   CrossTenantSubscriptionTestCase.testCreateSubscriptionFromTenant2AppToTenant1APIRestrictedPolicy:559 null
        [ERROR]   APIInvocationWithMessageTypeProperty.testInovkeAPIWithMessageTypePropertyInSequence:67 Â» NullPointer
        [ERROR] org.wso2.am.integration.tests.other.APIScopeTestCase.destroy
        [ERROR]   Run 1: APIScopeTestCase.destroy:517->APIMIntegrationBaseTest.undeployAndDeleteAPIRevisionsUsingRest:901 Unable to retrieve revisionsnull expected [200] but found [0]
        [ERROR]   Run 2: APIScopeTestCase.destroy:516->APIMIntegrationBaseTest.undeployAndDeleteAPIRevisionsUsingRest:901 Unable to retrieve revisionsnull expected [200] but found [0]
        [ERROR]   Run 3: APIScopeTestCase.destroy:516->APIMIntegrationBaseTest.undeployAndDeleteAPIRevisionsUsingRest:901 Unable to retrieve revisionsnull expected [200] but found [0]
        [ERROR]   Run 4: APIScopeTestCase.destroy:516->APIMIntegrationBaseTest.undeployAndDeleteAPIRevisionsUsingRest:901 Unable to retrieve revisionsnull expected [200] but found [0]
        [INFO]
        [ERROR] org.wso2.am.integration.tests.other.APIScopeTestCase.testSetScopeToResourceTestCase
        [INFO]   Run 1: PASS
        [ERROR]   Run 2: APIScopeTestCase.testSetScopeToResourceTestCase:219 Â» Api
        [INFO]   Run 3: PASS
        [INFO]   Run 4: PASS
        [INFO]   Run 5: PASS
        [INFO]
        [ERROR] org.wso2.am.integration.tests.other.PublisherAccessControlTestCase.destroy
        [ERROR]   Run 1: PublisherAccessControlTestCase.destroy:342->APIMIntegrationBaseTest.undeployAndDeleteAPIRevisionsUsingRest:901 Unable to retrieve revisionsnull expected [200] but found [0]
        [ERROR]   Run 2: PublisherAccessControlTestCase.destroy:342->APIMIntegrationBaseTest.undeployAndDeleteAPIRevisionsUsingRest:900 Â» NullPointer
        [ERROR]   Run 3: PublisherAccessControlTestCase.destroy:342->APIMIntegrationBaseTest.undeployAndDeleteAPIRevisionsUsingRest:900 Â» NullPointer
        [INFO]
        [ERROR] org.wso2.am.integration.tests.other.PublisherAccessControlTestCase.testAPIAdditionWithAccessControlRestriction
        [INFO]   Run 1: PASS
        [INFO]   Run 2: PASS
        [ERROR]   Run 3: PublisherAccessControlTestCase.testAPIAdditionWithAccessControlRestriction:197->APIManagerLifecycleBaseTest.createAndPublishAPIUsingRest:442 Â» Api
        [INFO]   Run 4: PASS
        [INFO]   Run 5: PASS
        [INFO]
        [ERROR] org.wso2.am.integration.tests.restapi.ContentSearchTestCase.testContentSearchWithAccessControl
        [INFO]   Run 1: PASS
        [INFO]   Run 2: PASS
        [INFO]   Run 3: PASS
        [ERROR]   Run 4: ContentSearchTestCase.testContentSearchWithAccessControl:268 Â» Api
        [INFO]   Run 5: PASS
        [INFO]
        [ERROR]   OpenIDTokenAPITestCase.setEnvironment:77 Â» Api
        [ERROR] org.wso2.am.integration.tests.token.TokenAPITestCase.testTokenAPITestCase
        [INFO]   Run 1: PASS
        [ERROR]   Run 2: TokenAPITestCase.testTokenAPITestCase:130 Â» Api
        [INFO]   Run 3: PASS
        [INFO]   Run 4: PASS
        [INFO]
        [INFO]
        [ERROR] Tests run: 1674, Failures: 14, Errors: 0, Skipped: 1

**Comment by chamilaadhi** [comment]
Fixed cross tenant scenario from https://github.com/wso2/carbon-apimgt/pull/12297/commits/448687f57c8b6c21754d6080ae9c862c32c28336 and secondary user store scenarios from https://github.com/wso2/carbon-apimgt/pull/12297/commits/99c404465b0cedeedb3d2ff87677d49ca14e8750

Now all integration tests pass

<img width="869" alt="Screenshot 2024-03-02 at 7 38 23 AM" src="https://github.com/wso2/api-manager/assets/4861150/c3a74ef9-1474-45ee-b509-22e201192b62">

**Comment by chamilaadhi** [comment]
Add config to enable JWT for portals with https://github.com/wso2/carbon-apimgt/pull/12297/commits/bc3869dca11fbda59c38f7fb211c558982d67d3c and https://github.com/wso2/apim-apps/pull/583

**Comment by chamilaadhi** [comment]
bug fix https://github.com/wso2/carbon-apimgt/pull/12323

**Comment by chamilaadhi** [comment]
Docs
4.3.0 https://github.com/wso2/docs-apim/pull/7783
