### ISSUE TITLE
[Token Persistence Removal] Authenticated user not found during portal login token introspection

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#2497]
### Description

`Authenticated user not found ` error is thrown from the in memory token introspection validator when JWT tokens are enabled for the publisher/devportal/admin portals. This is because, currently authenticated user is derived from the entity ID which is the user ID from the logged-in tenant's user store manager. In this case, the token introspection is called through the tenant unaware url and the credentials belong to the super tenant admin. Event if we use tenant aware URL and consumer app credentials for introspection , it will not work as we are using a SaaS application as the consumer app.

### Steps to Reproduce

1. Enable JWT tokens for portals as per https://github.com/wso2/api-manager/issues/2496.
2. Create tenants and log into the tenant portals with opaque tokens.
3. Enable token persistence removal as below.

Enable token persistence removal with following configs and database additions.

   - Start server with default configs and change token type of consumer apps of system portal to JWT and enable appending tenant domain to the local subject identifier.
   -  Shutdown server.
   -  Add to deployment.toml.

```
[oauth.token_persistence]
enable=false

[oauth.revoked_token_headers_in_response]
enable=false

[[oauth.extensions.token_types]]
name = "JWT"
issuer = "org.wso2.is.key.manager.tokenpersistence.issuer.ExtendedJWTTokenIssuer"

[transport.https.properties]
maxHttpHeaderSize = "12288"
```

  -  Create tables in AM_DB.

```
 CREATE TABLE IF NOT EXISTS IDN_INVALID_TOKENS (
 	UUID VARCHAR(255) NOT NULL,
 	TOKEN_IDENTIFIER VARCHAR(2048) NOT NULL,
 	CONSUMER_KEY VARCHAR(255) NOT NULL,
 	TIME_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 	EXPIRY_TIMESTAMP TIMESTAMP NOT NULL,
 	PRIMARY KEY (UUID)
  ) ENGINE=InnoDB;
 
CREATE TABLE IF NOT EXISTS IDN_APP_REVOKED_EVENT (
	EVENT_ID VARCHAR(255) NOT NULL,
	CONSUMER_KEY VARCHAR(255) NOT NULL,
	TIME_REVOKED TIMESTAMP NOT NULL,
	ORGANIZATION VARCHAR(100),
	PRIMARY KEY (EVENT_ID),
	CONSTRAINT CON_APP_EVT_KEY UNIQUE (CONSUMER_KEY, ORGANIZATION)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS IDN_SUBJECT_ENTITY_REVOKED_EVENT (
	EVENT_ID VARCHAR(255) NOT NULL,
	ENTITY_ID VARCHAR(255) NOT NULL,
	ENTITY_TYPE VARCHAR(100) NOT NULL,
	TIME_REVOKED TIMESTAMP NOT NULL,
	ORGANIZATION VARCHAR(100),
```
   -  Restart server

4. Try login to tenant portals.

### Affected Component

APIM

### Version

4.3.0 - M2

**Comment by tharikaGitHub** [comment]
Closing as this issue is fixed with JWT support for portals.
