### ISSUE TITLE
Maintaining minor OpenAPI document version 

### ISSUE THREAD

**Issue by shavinsenadheera** [wso2/api-manager#2500]
### Description

**APIM 3.2.0 U2 level 332 onwards**, we can see the following behavior.

- Go to the Publisher Portal and browse to the API definition.
- Change the "info.version" property value to "1.0.1" (Assuming the initial value is "1.0.0").
- Update the API.
- The "info.version" property value reverts back to the "1.0.0" (API's version)

Therefore, cannot maintain the minor version on the OpenAPI document.

### Steps to Reproduce

Mentioned in the description.

### Affected Component

APIM

### Version

3.2.0

**Comment by Avishka-Shamendra** [comment]
Hi all,

As per discussions within the team, this is not a recommended/valid approach. In 4.x.x versions, the API version in the OAS file should align with the version of the managed API. Hence, we will be closing this issue and we won't send a fix to master. 

Thank you
Avishka
