### ISSUE TITLE
An error occurs when accessing IS key manger after saving 

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2505]
### Description

 Admin user can add key manager details and save successfully. Following issue occurs when accessing key manger for update purpose.

<img width="1293" alt="Screenshot 2024-02-20 at 09 53 40" src="https://github.com/wso2/api-manager/assets/54719880/a75cea4e-9638-4f2f-9a35-27b7afa476aa">

### Steps to Reproduce

https://apim.docs.wso2.com/en/latest/administer/key-managers/configure-wso2is-connector/#configure-wso2-is-as-a-key-manager

prerequisites
--------------
Configure and setup IS following the steps in the doc

Steps
------
1. Login to admin portal
2. Configure ad IS key manager details
3. Save 
4. Click and open the  key manager

### Affected Component

APIM

### Version

4.2.0, 4.3.0

### Environment Details (with versions)

MacOS

**Comment by tharikaGitHub** [comment]
This is not reproduced in the latest pack. Hence closing.
