### ISSUE TITLE
Page goes blank when loading deployments page

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#2518]
### Description

The page goes blank as follows when loading the deployments page of an API. No errors are logged in the browser or the terminal.

<img width="849" alt="Screen Shot 2024-02-27 at 10 32 13 AM" src="https://github.com/wso2/api-manager/assets/8557410/acf66667-ef5e-472c-99e5-5441f8a0a937">

### Steps to Reproduce

1. Create an API in the publisher portal.
2. Visit the **Deployments** page.
3. You will see a blank page displayed as above

### Affected Component

APIM

### Version

4.3.0

**Comment by hisanhunais** [comment]
Fixed via https://github.com/wso2/apim-apps/pull/568
