### ISSUE TITLE
Improve error handling when custom property is missing during API update in Publisher Porta

### ISSUE THREAD

**Issue by tgtshanika** [wso2/api-manager#2531]
### Problem

A generic error is returned when mandatory property values are missing in the API update.

### Solution

Improve the error handling in [1] by returning the validation error for the corresponding property names in the error responses. 

[1] https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/impl/ApisApiServiceImpl.java#L663

### Affected Component

APIM

**Comment by tharikaGitHub** [comment]
@Lakith-Rambukkanage can you please add the public PR as well?

**Comment by Lakith-Rambukkanage** [comment]
Public PR : 
https://github.com/wso2/apim-apps/pull/590
https://github.com/wso2/carbon-apimgt/pull/12318
