### ISSUE TITLE
404 not found error occurs when adding documents to an API, and the page breaks when refreshing the document page

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2532]
### Description

Description:
404 error occurs when user trying to add document to an API and page breaks when refreshing document page.
<img width="815" alt="Screenshot 2024-02-29 at 13 06 03" src="https://github.com/wso2/api-manager/assets/54719880/4d80a624-55af-4eba-9e12-529b949edef3">
<img width="1510" alt="Screenshot 2024-02-29 at 13 06 47" src="https://github.com/wso2/api-manager/assets/54719880/78597336-55e9-4c8c-a40d-10f0487f5c74">

### Steps to Reproduce

1. Login to publisher portal
2. Create an API
3. Navigate to Documents tab -> Add New document\
4. Add document details and click on 'Add document' button (document is not saved)
5. Refresh the document page

### Affected Component

APIM

### Version

4.3.0

### Relevant Log Output

```shell
Console logs

Add Document

react-dom.production.min.js:106 Uncaught TypeError: f.addDocument is not a function
at onClick (Create.jsx:118:47)
at Object.je (react-dom.production.min.js:54:317)
at He (react-dom.production.min.js:54:471)
at react-dom.production.min.js:55:35

Refresh Page

react-dom.production.min.js:189 TypeError: Cannot read properties of null (reading 'docVisibilityEnabled')
```

**Comment by tharikaGitHub** [comment]
Closing as the fix is merged.
