### ISSUE TITLE
Local scopes are not working properly

### ISSUE THREAD

**Issue by LayaniMal** [wso2/api-manager#2534]
### Description

Local scopes are not working properly in the latest U2 update level(68) of the APIM 4.2.0 version.

Even though provides an invalid scope when generating an access token using the CURL command. Also, API can be invoked with that token. 

### Steps to Reproduce

1. Create a new REST API using the publisher portal. 
2. Create a new resource and Save it.
3. Create a Local Scope that is restricted to a specific role. Do not tie to it a resource yet.
4. Deploy and publish the API.
5. Subscribe to the API and generate the access token using /oauth2/token for an application belonging to a user that does NOT have the role required for the scope. 

**Eg:** 

`curl -k -X POST https://localhost:9443/oauth2/token -d "grant_type=password&username=admin&password=admin&scope=newscope" -H "Authorization: Basic ZTJQckJHVGFhZUFwYzdraTE5cFFpM3E1U0lZYTpDVUxvVHptNFRmcXNsdTdRTkhCcGd2OW01SG9h"`

- Even though with using the scope that does not exist, it will invoke the API without any issue. 

### Affected Component

APIM

### Version

4.2.0

### Suggested Labels

APIM-4.2.0

**Comment by RakhithaRR** [comment]
The docs have been updated through https://github.com/wso2/docs-apim/pull/8090
