### ISSUE TITLE
Page Goes Blank When Loading Deployments Page of API Products

### ISSUE THREAD

**Issue by hisanhunais** [wso2/api-manager#2536]
### Description

- The page goes blank as follows when loading the deployments page of an API Products. No errors are logged in the browser or the terminal.
- Similar Issue for API: https://github.com/wso2/api-manager/issues/2518

### Steps to Reproduce

1. Create an API Product in the publisher portal.
2. Visit the Deployments page.
3. You will see a blank page displayed as above

### Affected Component

APIM

### Version

4.3.0

**Comment by tharikaGitHub** [comment]
Closing as the fix is merged.
