### ISSUE TITLE
Issue on both the prototype and HTTP/REST Endpoints migration in APIM 2.6.0 to 4.1.0

### ISSUE THREAD

**Issue by jithma95** [wso2/api-manager#2548]
### Description

During the migration process from APIM 2.6.0 to 4.1.0, it has been observed that APIs are in the published state in APIM 2.6.0, with both prototype and HTTP/REST endpoints configured, do not migrate correctly to the target APIM 4.1.0 environment. Specifically, the API endpoint configuration in the publisher interface for these APIs indicates that none of the endpoint types were selected.

### Steps to Reproduce

- Configured the APIM 2.6.0 with the MSSQL
- Create the API in APIM 2.6.0 using the same url into the both HTTP/REST endpoint and prototype endpoint under the manage API section on the publisher UI.
- Published the API as a prototype API through the publisher UI.
- Take the DB dump from the source APIM 2.6.0.
- Complete the migration in to the APIM 4.1.0.
- Load the migrated APIM 4.1.0 publisher portal and check the endpoint configs as below.
<img width="626" alt="image" src="https://github.com/wso2/api-manager/assets/39775252/7a71de89-7004-4d4e-96a5-079cd62da38c">

### Affected Component

APIM

### Version

4.1.0

**Comment by dulithsenanayake** [comment]
Hi all,

Closing this as the U2 update was released & the fix is available on the public branch as well.

Thanks!
Dulith
