### ISSUE TITLE
Misalignment in API Manager logo in Login page

### ISSUE THREAD

**Issue by PasanT9** [wso2/api-manager#2551]
### Description
Misalignment in API Manager logo in the login page.

![image](https://github.com/wso2/api-manager/assets/43533314/b2bd3ba3-9512-4dd0-8e46-3e9a11198e47)

### Steps to Reproduce

1. Go to the login page

### Affected Component

APIM

### Version

4.3.0

**Comment by lasanthaS** [comment]
This issue comes from the Authentication Endpoint.

**Comment by tharikaGitHub** [comment]
Closing as this is fixed with https://github.com/wso2/product-apim/pull/13460
