### ISSUE TITLE
Single sign on feature does not work as expected for Developer portal

### ISSUE THREAD

**Issue by SavinduDimal** [wso2/api-manager#2553]
### Description

The single sign-on is not functioning as expected for the Developer Portal. Despite signing in to the Publisher Portal, when attempting to access the Developer Portal in the same browser session, it does not retain the signed-in state. As a result, users are required to click the sign-in button again. However, users are not prompted to re-enter their credentials.

In addition this works properly with admin portal.

![Screenshot 2024-03-01 at 17 13 55](https://github.com/wso2/api-manager/assets/55122994/8d4e4ec5-5128-4b92-afb5-cda527df5116)

![Screenshot 2024-03-01 at 17 14 28](https://github.com/wso2/api-manager/assets/55122994/10080479-2f9c-4461-9810-f2b71d6e7f42)

### Steps to Reproduce

1. Sign in to publisher portal
2. Using the same browser session open the developer portal

### Affected Component

APIM

### Version

4.3.0

**Comment by AnuGayan** [comment]
This is the expected behaviour since the Dev Portal is an open portal that anyone can access without logging in.
