### ISSUE TITLE
GraphQL API invocation fails for distributed setup

### ISSUE THREAD

**Issue by ashera96** [wso2/api-manager#2555]
### Description

GraphQL API invocations fail with the following error response. Note that if we copy-paste the curl from the network call, a successful response is received, but the GraphiQL console returns the following error message. This is the behaviour that was noticed for super tenant as well as tenant admin. The above-described behaviour was only reproducible in the distributed setup.

<img width="1258" alt="image" src="https://github.com/wso2/api-manager/assets/30475839/846d296b-f0f5-4805-a6d8-d5114f25551a">

### Steps to Reproduce

This was reproduced with the following setup for super-tenant admin, but should be the same with no rate limiting policy in place as well.

1. Create a GraphQL API
2. Create a Subscription Rate Limiting Policy using the Admin Portal for access control (i.e. with a depth limit and a complexity limit)
3. Attach the created policy to the API
4. Invoke the GraphQL API

### Affected Component

APIM

### Version

4.3.0

**Comment by RakhithaRR** [comment]
Not reproducible in alpha2
