### ISSUE TITLE
Add Document button is not working

### ISSUE THREAD

**Issue by HelaniUdara** [wso2/api-manager#2558]
### Description

When attempting to add a document to the API, users encounter an error message stating "Uncaught TypeError: f.addDocument is not a function". This occurs after filling out all the necessary details and clicking on the "ADD Document" button, as shown in the image.
![Screenshot from 2024-03-04 07-51-43](https://github.com/wso2/api-manager/assets/90105093/315e25a9-40f2-4f74-90ab-d561cc65dfb6)

### Steps to Reproduce

1. Login to the publisher portal
2. Click on any API
3. Develop --> Portal Configurations --> Documents  --> Add New Document
4. Click on the "ADD Document" button.

### Affected Component

APIM

### Version

4.3.0

**Comment by chamilaadhi** [comment]
This is working now in the latest 4.3.0 build
