### ISSUE TITLE
Refresh Token Not Generated for Password Grant (Distributed Setup)

### ISSUE THREAD

**Issue by DDH13** [wso2/api-manager#2562]
### Description

When trying to obtain an access token by providing the resource owner's username and password as an authorization grant, a refresh token is not generated. 
However, according to the documentation a refresh token must be included in the response. 

### Steps to Reproduce

Follow steps in [Documentation](https://apim.docs.wso2.com/en/4.3.0/design/api-security/oauth2/grant-types/password-grant/)

### Affected Component

APIM

### Version

4.3.0

**Comment by Chanuka-ChandraYapa** [comment]
If the 'Refresh Token' type is selected under grant types, a refresh token will be generated and included in the response.

**Comment by tharikaGitHub** [comment]
Closing as per the above comment.
