### ISSUE TITLE
Access Token not generated for Client Credentials Grant (Distributed Setup)

### ISSUE THREAD

**Issue by DDH13** [wso2/api-manager#2565]
### Description

When trying to generate the access token using client credentials grant the access token is not generated and instead returns 302 and redirects to the login page

### Steps to Reproduce

Follow the steps in [documentation](https://apim.docs.wso2.com/en/4.3.0/design/api-security/oauth2/grant-types/client-credentials-grant/)

### Affected Component

APIM

### Version

4.3.0

**Comment by chamilaadhi** [comment]
Do you have any error logs? I tried with the latest build of API 4.3.0 and I could get the token correctly

<img width="1715" alt="Screenshot 2024-03-05 at 12 37 05 PM" src="https://github.com/wso2/api-manager/assets/4861150/0f3f4aa3-e5ed-409f-a0cd-24c46dc6e299">

**Comment by chamilaadhi** [comment]
Issue not found in the 4.3.0 alpha pack distributed setup as well

![Image](https://github.com/wso2/api-manager/assets/4861150/b26d7142-df27-4898-b09b-bf4559f3fa64)
