### ISSUE TITLE
UI elements are misaligned in API Revision (Create & Deploy a new revision)

### ISSUE THREAD

**Issue by HelaniUdara** [wso2/api-manager#2566]
### Description

Drop-downs are misaligned in API Deployments page. 
1. Drop-down for delete a revision in the 'Deploy new revision' pop up dialog
![Screenshot from 2024-03-04 11-58-31](https://github.com/wso2/api-manager/assets/90105093/7eba71de-b3bb-45e3-9749-12fbd5354f34)

2. Drop-down for delete a revision in the 'Create new revision' pop up dialog
![Screenshot from 2024-03-04 11-51-20](https://github.com/wso2/api-manager/assets/90105093/06c59e5d-0b90-4e93-99d0-c218bd15052e)

### Steps to Reproduce

1. Login to publisher portal
2. Click on any API
3. Deploy -->  Deployments 
To navigate 'Deploy new revision' pop up dialog click on 'Deploy new revision'
To navigate 'Create new revision' pop up dialog click on the plus icon (+) in the revision timeline.

### Affected Component

APIM

### Version

4.3.0

**Comment by vishmi49** [comment]
Following misalignments in deployments  page needs to be fixed

<img width="347" alt="Screenshot 2024-03-13 at 12 57 05" src="https://github.com/wso2/api-manager/assets/54719880/bcbcb531-3e26-4aca-a725-abe602690216">.  

<img width="417" alt="Screenshot 2024-03-13 at 12 56 10" src="https://github.com/wso2/api-manager/assets/54719880/f1f81639-3459-4d2d-953b-6f41a801e86c">


<img width="459" alt="Screenshot 2024-03-13 at 12 54 21" src="https://github.com/wso2/api-manager/assets/54719880/b9bd75b7-1909-41cc-b22e-19d140e28d75">
