### ISSUE TITLE
[Publisher] UI Styling Issues in API Security Audit Report Viewing Page

### ISSUE THREAD

**Issue by SavinduDimal** [wso2/api-manager#2570]
### Description

UI for viewing API Security Audit Report is currently not aligned properly.
![Screenshot 2024-03-04 at 15 32 09](https://github.com/wso2/api-manager/assets/55122994/c25789eb-f1ee-4ecd-a2d1-0f676974dd14)

This should be fixed as shown in [1].

[1] - https://apim.docs.wso2.com/en/4.3.0/assets/img/learn/sample-audit-report.png

### Steps to Reproduce

Follow the steps given in doc [1].

[1] - https://apim.docs.wso2.com/en/4.3.0/design/api-security/configuring-api-security-audit/

### Affected Component

APIM

### Version

4.3.0

**Comment by piyumaldk** [comment]
Sent the PR - https://github.com/wso2/apim-apps/pull/656

**Comment by tharikaGitHub** [comment]
Reopening as the PR is not merged yet.
