### ISSUE TITLE
API Product creation not working

### ISSUE THREAD

**Issue by O-sura** [wso2/api-manager#2571]
### Description

According to the [docs](https://apim.docs.wso2.com/en/4.3.0/design/create-api-product/create-api-product/) a publisher should be able to create an API product to bundle a preferred set of resources from multiple APIs and expose it as a separate API interface which currently doesn't work as intended and leads to an error.

### Steps to Reproduce

Follow the same steps mentioned under [Create an API Product](https://apim.docs.wso2.com/en/4.3.0/design/create-api-product/create-api-product/) in the documentation and after creating and publishing it the following error gets showed up.

![Screenshot from 2024-03-04 15-35-40](https://github.com/wso2/api-manager/assets/84634723/2fa7d4c3-8150-47e0-b040-2b0b751eb6a1)

However after going to the API Product Homepage(_https://hostname/publisher/api-products_) the created product gets displayed but when try to go the overviews by clicking on it leads to the same error page given above.

![Screenshot from 2024-03-04 15-59-10](https://github.com/wso2/api-manager/assets/84634723/98a6ffac-a5fc-4725-b50c-b862d0b5b03f)

### Affected Component

APIM

### Version

4.3.0

### Related Issues

In the creation process the components in the following UI seems to be miss aligned, ill-spaced and there is a blue color border around the main div

![Screenshot from 2024-03-04 15-29-49](https://github.com/wso2/api-manager/assets/84634723/a06bb083-e06b-4b11-a5d1-d2bbae280d63)

**Comment by chamilaadhi** [comment]
This is fixed in the latest 4.3.0 build
