### ISSUE TITLE
[APIM][3.2.0] The banner is not displyaing correctly

### ISSUE THREAD

**Issue by ShehanRavindu** [wso2/api-manager#2572]
### Description

Hi Team, 

We tried to to add a banner according to the WSO2 documentation [1]. We could add the text. But the display is covered by the Menu on the page. We need to keep hold the banner when scroll down. But the banner also scroll down when scroll down.

[1] https://apim.docs.wso2.com/en/3.2.0/develop/customizations/customizing-the-developer-portal/enable-or-disable-banner/

Thanks and regards,
Shehan.

### Steps to Reproduce

1. Open the <API-M_HOME>/repository/deployment/server/jaggeryapps/devportal/site/public/theme/defaultTheme.js file in a text editor and set the themes.light.custom.banner.active attribute as true to show the banner.
2. Refresh the Developer Portal to view the changes.

The following attributes available for the banner
-----------------------------------------------------------------

`const Configurations = {
    custom: {
        banner: {
            active: true,
            style: 'text',
            image: '/site/public/images/landing/01.jpg',
            text: 'This is a very important announcement',
            color: '#ffffff',
            background: '#e08a00',
            padding: 20,
            margin: 0,
            fontSize: 18,
            textAlign: 'center',
        },
    },
};`

### Affected Component

APIM

### Version

3.2.0

**Comment by dulithsenanayake** [comment]
Hi all,

We are closing this issue as the update was released. 

Thanks!
Dulith
