### ISSUE TITLE
Add tenant to the application subscription UI

### ISSUE THREAD

**Issue by NishanthiWi** [wso2/api-manager#2576]
### Problem

Subscriber user wants to identify the tenant in the application subscription page in the dev portal. The majority of end-user applications utilize the commonly registered applications in the WSO2 devportal. It can be challenging to navigate through each tenant and inspect application subscriptions, particularly for new subscribers or returning subscribers after a period of time as there are number of tenants and APIs

### Solution

Provide a way to identify all the subscriptions along with the tenant which are subscribed to an application 

### Affected Component

APIM

### Version

4.0.0

### Related Issues

https://github.com/wso2/api-manager/issues/2514

**Comment by RakhithaRR** [comment]
This is no longer required according to https://github.com/wso2/api-manager/issues/2685
