### ISSUE TITLE
Getting 202 accepted response when invoking unavailable method of a tenant API

### ISSUE THREAD

**Issue by NishanthiWi** [wso2/api-manager#2577]
### Description

Getting 202 Accepted response for the unavailable http method of an API which is exposed in a tenant space

### Steps to Reproduce

- modify the configuration ( main.xml file) in the synapse templates wso2am-4.0.0/repository/resources/apim-synapse-config directory
- remove the tenant folder created in the wso2am-4.0.0/repository/tenants directory
- Restart the server and invoke an API in the tenant with a different context
- Results 202 Accepted.

Even though the above is consistent, we do observe the behavior when we start a fresh pack + create a tenant + publish an API in the tenant + invoke an API return 202

### Affected Component

APIM

### Version

4.0.0.265

**Comment by RakhithaRR** [comment]
Fixed with https://github.com/wso2/carbon-mediation/pull/1579
