### ISSUE TITLE
Placeholder for Specific tenant subscriptions is missing in publisher subscriptions page

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2579]
### Description

Placeholder for Specific tenant subscriptions is missing subscriptions page

<img width="1493" alt="Screenshot 2024-03-05 at 14 51 59" src="https://github.com/wso2/api-manager/assets/54719880/290fbe3e-3f3a-41ac-9e1c-fd38f81b9261">

### Steps to Reproduce

Prerequisites
-------------
1. Enable cross tenant subscription in deployment.toml
2. Create a tenant in management console

Steps
---------

1. Login to publisher portal
2. Create an API
3. Navigate to subscriptions
4. Select "Available to specific Tenants" option from the dropdown

### Affected Component

APIM

### Version

4.3.0

**Comment by chamilaadhi** [comment]
Seems issue is coming from the react version upgrade. https://github.com/wso2/apim-apps/blob/main/portals/publisher/src/main/webapp/source/src/app/components/Apis/Details/Subscriptions/TenantAutocomplete.jsx is causing some issues
