### ISSUE TITLE
Key manager visibility for user roles in devportal is not working properly for global key manager

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2585]
### Description

Key manager visibility for user roles in devportal is not working properly for global key manager. 

### Steps to Reproduce

Prerequisites
--------------

Configure IS and global key manager

steps
------
1. Login to admin
2. Open the global key manager
3. Set the key manager permission as 'Allow for roles'
4. Add a user role to allow permission
5. Login to devportal from a user with another user role.
6. Check the Applications ->OAuth2 tokens 

### Affected Component

APIM

### Version

4.3.0

**Comment by chamilaadhi** [comment]
Fix https://github.com/wso2/api-manager/issues/2585
