### ISSUE TITLE
Styling issues in Sample Integration Service Tile and Name

### ISSUE THREAD

**Issue by shnrndk** [wso2/api-manager#2586]
### Description

There are several styling issues in the Service Catalogue Page.
- Service Title Should be scaled up
- Tile is not aligned properly.
- Plus button is not aligned properly.

Pre Alpha
<img width="540" alt="image" src="https://github.com/wso2/api-manager/assets/43110114/15069ab8-de54-40ee-a7e0-0c30d475a196">

4.3.0-m2
<img width="540" alt="image" src="https://github.com/wso2/api-manager/assets/43110114/08e9ad32-bdb0-4625-9dd3-7000eeae99a4">

### Steps to Reproduce

1. Go to services
2. Click Add a sample Integration Service button.

### Affected Component

APIM

### Version

APIM 4.3.0

**Comment by tharikaGitHub** [comment]
Closing as the PR https://github.com/wso2/apim-apps/pull/589 is merged.
