### ISSUE TITLE
 Multiple UI Issues in Publisher Portal when using Chrome in Ubuntu

### ISSUE THREAD

**Issue by PasanT9** [wso2/api-manager#2590]
### Description

![Screenshot from 2024-03-07 14-17-24](https://github.com/wso2/api-manager/assets/43533314/0307972b-a809-40e9-80b3-fe2629ee53d1)

![Screenshot from 2024-03-07 11-26-20](https://github.com/wso2/api-manager/assets/43533314/a4e8a47e-58a2-42c4-83e6-3da3914344f8)

![Screenshot from 2024-03-07 14-17-41](https://github.com/wso2/api-manager/assets/43533314/af0b88cc-da14-419a-a141-b73508239298)

### Steps to Reproduce

1. Login to Publisher UI (Make sure you don't have any APIs deployed in the corresponding tenant).

### Affected Component

APIM

### Version

4.3.0

### Environment Details (with versions)

Ubuntu: 22.04.4 LTS
Browser: Mozilla Firefox 123.0

**Comment by Tharanidk** [comment]
In Firefox the issue is not reproducing.
Ubuntu: 20.04 LTS
Browser: Mozilla Firefox 123.0

Getting the same issue in chrome when the zooming value is 200%. Working on fixing that issue.
