### ISSUE TITLE
Incorrect response code being returned for adding document that already exists

### ISSUE THREAD

**Issue by Menuka-Senevirathne** [wso2/api-manager#2599]
### Description

APIM 4.1 responds with a 500 status code, when trying to add the same document (Duplicate document) again. Ideally it should be responded with 409.

### Steps to Reproduce

- Get an auth token specifically with the scopes apim:api_create apim:api_manage apim:document_create apim:document_manage
- Find an API with no added documents and get its Id.
- Add a document to that API:
- Verify in the publisher portal UI it is added.
- Try to add the same document again by repeating step 3, this leads to the 500 server error:

{"code":500,"message":"Internal server error","description":"Error while adding the document for API : <api_id>","moreInfo":"","error":[]} 

### Affected Component

APIM

### Version

4.1.0

**Comment by Lakith-Rambukkanage** [comment]
Fixed by : https://github.com/wso2/carbon-apimgt/pull/12333
