### ISSUE TITLE
JSON validator common policy's properties not being set

### ISSUE THREAD

**Issue by Shenavi** [wso2/api-manager#26]
### Description:
When engaging the common policy JSON Validator from the publisher Portal, it was noticed that the properties being set from the UI does not get added to the policy

### Steps to reproduce:
1. Create an API with a POST resource and a body
2. Under the Policies for the API drag and drop the JSON Validator policy to the request flow.
3. Update all the parameter values to 5.
4. Save and deploy the API.
5. Invoke the API with a JSON payload like the below.
{"name":"John Smith"}
6. Ideally above should generate an error for the JSON String Length. Afterwards I downloaded the same policy hard coded the values for the properties and uploaded as a new one, that seems to work. There seems to be an issue where the properties are not getting set for the OOTB policy. 

When invoking the policies endpoint for the API it returned the below without any of the added properties.

{
    "sequences": [
        "<sequence xmlns=\"http://ws.apache.org/ns/synapse\" name=\"BlockAPi:v1.0--In\"><property name=\"switchExpression\" expression=\"fn:concat($ctx:REST_METHOD,'_',$ctx:API_ELECTED_RESOURCE)\"/><switch source=\"$ctx:switchExpression\"><case regex=\"POST_\/\\*\"><log level=\"custom\"><property name=\"MESSAGE\" value=\"json_validator\"/></log></case></switch></sequence>"
    ]
}

### Affected product version:
apim 4.1.0

### Environment details (with versions):
- OS: MacOS
- Client: Safari Browser
- Env (Docker/K8s): N/A

---
#### Suggested labels:
Type/CommonPolicies

**Comment by SavinduDimal** [comment]
Closing this issue as it is fixed in the master branch with [1] and [2].

[1] https://github.com/wso2/carbon-apimgt/pull/11347
[2] https://github.com/wso2/carbon-apimgt/pull/11591
