### ISSUE TITLE
Handling accidental deletions of shared backend certificates

### ISSUE THREAD

**Issue by IsuruMaduranga** [wso2/api-manager#260]
### Problem

In the current APIM implementation, backend certificates are shared between APIs based on the endpoint. Thus any user who creates an API with an existing endpoint can delete an already uploaded certificate under the same endpoint. Hence, this new feature is supposed to discourage deleting backend certificates.

### Solution

1. When a user requests deletion of a certificate, If there are no other APIs using the certificate, the certificate is deleted straightly.
2. Else, a warning message is provided with the list of other APIs that use the certificate. If the user agrees to the warning the certificate gets deleted.

### Subtasks

- [x] #285
- [x] #286
- [x] #287
- [x] #463
- [x] #497
- [x] #498 
- [x] #499
- [x] #500
- [x] #757

### Affected Component

APIM

### Version

4.1.0

**Comment by tharikaGitHub** [comment]
Closing this as the feature is completed.
