### ISSUE TITLE
Basic Auth security not working when multiple types of application level security is enabled

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/api-manager#2603]
### Description

APIs cannot be invoked with Basic Auth when multiple types of security types are enabled from the application level. It seems the security scheme type is not picked up properly from the state in the UI. Hence, the Authorization header is set as Bearer instead of Basic. This doesn't happen when only basic auth is chosen from the publisher side.

<img width="1429" alt="Screenshot 2024-03-11 at 14 58 26" src="https://github.com/wso2/api-manager/assets/25485273/c06d318e-dc69-4462-866b-f1715fcf6239">

### Steps to Reproduce

1. Create an API
2. Select both Oauth and Basic security for application level security from runtime configs
3. Save and deploy the API
4. Try to invoke the API with basic auth. You can see the generated curl is incorrect

### Affected Component

APIM

### Version

4.3.0

**Comment by AnuGayan** [comment]
@PasanT9 This also can be due to the same issue https://github.com/wso2/api-manager/issues/2564
