### ISSUE TITLE
Issue in updating Provider field when Changing the Provider of an Api

### ISSUE THREAD

**Issue by shamin2021** [wso2/api-manager#2610]
### Description

According to the [APIM docs](https://apim.docs.wso2.com/en/4.3.0/consume/manage-application/advanced-topics/changing-the-provider-of-an-api/), when Changing the Provider of an API  in the distributed setup,  when the name of the provider is given to the provider field in the admin portal any number of empty spaces can be added after the name and provider name will be updated despite of the spaces

### Steps to Reproduce

1. Go to Admin Portal > change API provider > edit provider field of API 
![image](https://github.com/wso2/api-manager/assets/79569018/fba6f13b-1448-4e76-bb06-0585a53c90aa)

### Affected Component

APIM

### Version

4.3.0

### Related Issues

When validating the password of a new user in the APIM Management Console better to show pattern not matching error along with password field for better UX
![image](https://github.com/wso2/api-manager/assets/79569018/104c579d-fe04-40d9-a926-d37a6c7bd8cd)
Steps to recreate : 1. Go to management Console > Add new user > enter password 
APIM docs[https://apim.docs.wso2.com/en/4.3.0/administer/managing-users-and-roles/managing-users/#adding-a-new-user]

**Comment by tharikaGitHub** [comment]
Closing as the public PRs are merged.

1. https://github.com/wso2/apim-apps/pull/609
2. https://github.com/wso2/carbon-apimgt/pull/12339
