### ISSUE TITLE
Behaviour issue when assigned both roles internal/publisher and internal/observer 

### ISSUE THREAD

**Issue by shamin2021** [wso2/api-manager#2612]
### Description

According to the [APIM docs](https://apim.docs.wso2.com/en/4.3.0/design/api-security/authorization/publisher-portal-in-read-only-mode/), a user can be assigned with observer role where they can access the publisher portal in read only mode.
but users with Internal/publisher access can also be assigned internal/observer thereby making their publisher portal read only 
![image](https://github.com/wso2/api-manager/assets/79569018/8e058fb7-e3bd-4abd-bfd7-5affd87da1ab)
![image](https://github.com/wso2/api-manager/assets/79569018/c69e78da-9490-429b-acec-5f677fa3378d)

### Steps to Reproduce

1. Go to WSO2 Management Console > add user > assign roles 
2. Log into publisher using the same user credentials to view behavior 

### Affected Component

APIM

### Version

4.3.0

**Comment by dakshina99** [comment]
Thank you for reporting this issue. We have already fixed this, and it is no longer reproducible.

I'll be closing this issue now. Please feel free to reopen it if you encounter any further problems.
