### ISSUE TITLE
Current Password is displayed directly when trying to change password in devportal 

### ISSUE THREAD

**Issue by shamin2021** [wso2/api-manager#2613]
### Description

According to the [APIM docs](https://apim.docs.wso2.com/en/latest/consume/user-account-management/change-dev-portal-password/), the password can be changed through developer portal . In the distributed setup when trying to change the password the current password is automatically displayed in the given field , this can be a breach of privacy for the user 

### Steps to Reproduce

1. Go to Developer portal > click on username > change password
![image](https://github.com/wso2/api-manager/assets/79569018/4951451f-460b-44bc-b56d-9619bc08be75)

### Affected Component

APIM

### Version

4.3.0

**Comment by tharikaGitHub** [comment]
This issue is not reproducible in the distributed setup with the 4.3.0-alpha pack. @shamin2021 shall we check the same in a private window of your browser?

**Comment by RakhithaRR** [comment]
This cannot be reproduced in incognito mode either. Hence closing this issue.
