### ISSUE TITLE
Headers Section Not Included in API product swagger definition combining APIs

### ISSUE THREAD

**Issue by nuwankng** [wso2/api-manager#2617]
### Description

In this issue we were able to see that when using API with headers referenced from components section are not not included when we create a API product [1]. 

After we create an API product combining the APIs contains headers referenced from components section, getting an error in the devportal tryout section.

<img width="1636" alt="UiError" src="https://github.com/wso2/api-manager/assets/16064951/3b8f5e79-212b-4e19-bd7b-ef5490da2c56">

[1]. https://apim.docs.wso2.com/en/3.2.0/learn/design-api/create-api-product/create-api-product/

### Steps to Reproduce

1. Create 2 APIs with headers for the resources referenced from components section.
2. Create an API product combining the above APIs.
3. Open and try out the API product in devportal

### Affected Component

APIM

### Version

3.2.0

**Comment by HiranyaKavishani** [comment]
Public fix is already available via ==> https://github.com/wso2/carbon-apimgt/pull/12159
