### ISSUE TITLE
Add runtime configurable correlation logs infrastructure to the Synapse layer

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#262]

**Comment by pasindu-sandima** [comment]
- Introduced a data holder to keep track of the status of correlation logs ( enabled / disabled ). 
- This data holder value will get updated at the server start up from the system property ( enableCorrelationLogs ) and it will get updated during the runtime from the MI Management API / APIM devops API. 
- The value in the data holder will be checked before writing to the correlation logs.
