### ISSUE TITLE
Cannot access the Publisher Try out console in Safari

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#2624]
### Description

The following error occurs when trying to access the try out console in the Publisher portal. Also the issue seems to be intermittent. Refreshing the page after some time resolves the issue.

![Screen Shot 2024-03-13 at 10 29 18 AM](https://github.com/wso2/api-manager/assets/8557410/377e78ed-2dd8-4161-a302-898cb3a6260e)

### Steps to Reproduce

1. Login to the publisher portal using the Safari browser.
2. Create an API and try to access the Try out console.

### Affected Component

APIM

### Version

4.3.0

### Environment Details (with versions)

Safari Browser Version 15.6.1 (17613.3.9.1.16)

**Comment by lasanthaS** [comment]
This is working on Safari 16+. Hence closing the issue.
