### ISSUE TITLE
Global Policies feature does not work when we have multiple gateway environments defined

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#2628]
### Description

When trying to deploy a global policy to a gateway environment, the deployment fails with the following error in the terminal.

`ERROR - GatewayPoliciesApiServiceImpl Gateway policy mapping is not deployed in the gateway: Prod`

### Steps to Reproduce

1. Create another Gateway environment from the Admin portal or the deployment.toml file. The gateway host used is the same as the Default environment.
2. Login as the Admin to the publisher portal.
3. Create a Global level policy.
4. Try to assign the 'Default' gateway environment from the dropdown list and Click Deploy.
5. Assuming the new gateway environment added is named 'Prod', the following error is logged in the terminal.
`ERROR - GatewayPoliciesApiServiceImpl Gateway policy mapping is not deployed in the gateway: Prod`
6. When trying to assign the 'Prod' environment and deploy, the following error gets logged in the terminal.
`ERROR - GatewayPoliciesApiServiceImpl Gateway policy mapping is not deployed in the gateway: Default`

### Affected Component

APIM

### Version

4.3.0

**Comment by YasasRangika** [comment]
Fixed the newly identified issue with: https://github.com/wso2/carbon-apimgt/pull/12380

**Comment by tharikaGitHub** [comment]
This issue is fixed with https://github.com/wso2/carbon-apimgt/pull/12380
