### ISSUE TITLE
Add a Management API resource to cater the runtime configurable correlation logs

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#263]

**Comment by pasindu-sandima** [comment]
- Introduced a new API resource ( configsResource) to service the enable / disable correlation logs functionality during the runtime
- This API allows the users to read the status of the correlation logs ( enabled / disabled ) and to update the the status to enable / disable correlation logs during the runtime 
- The usage of the API resource is as follows. 

Resource Context : management/configs

GET method : 
This method will be used to query whether correlation logs are enabled or disabled.

Example Request : 
`curl -X GET https://localhost:9164/management/configs?configName=correlation`



Example Response: 
```
{   
    "configName": "correlation",
    "configs": {
			“enabled” : “false”
		   }
}
```

PUT method: 
This method will be used to update the dataholder value corresponding to the correlation logs enable/disable. 
Example Request: 
```
curl -X POST \
  https://localhost:9164/management/configs \
  -H 'content-type: application/json' \
  -d '{
    "configName": "correlation",
    "configs": {
			“enabled” : “true”
			}
}
```
