### ISSUE TITLE
Cannot deploy the global policies in the distributed setup

### ISSUE THREAD

**Issue by shnrndk** [wso2/api-manager#2631]
### Description

When the user select the gateway and click on the button it pops ups a error message saying Error occured while deploying the policy.
![Screenshot 2024-03-13 at 12 25 53](https://github.com/wso2/api-manager/assets/43110114/b461b8bf-5106-494c-bc6c-d4eeff4c5b4d)

In the network tab, the response is 400 and the description is `Gateway policy mapping is not deployed in the gateway: Default_Production`.
 

### Steps to Reproduce

1.) Go to global policies
2.) Click add new global policy
3.) Add some policies from policy list to resquest flow or response flow and click save.
4.) Select the gateway and click on the deploy button.
5.) When it gets deployed it shows the error message.

### Affected Component

APIM

### Version

4.3.0 Alpha

**Comment by tharikaGitHub** [comment]
Related issue https://github.com/wso2/api-manager/issues/2628
