### ISSUE TITLE
Page does not load when clicking on View Definition for Service catalog in Safari

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#2632]
### Description

When clicking on the View Definition link in a Service overview page of the Service Catalog, the page does not load. And it looks like follows. 

![Screen Shot 2024-03-13 at 2 11 23 PM](https://github.com/wso2/api-manager/assets/8557410/b0cf3648-995d-4064-9c05-4a35979cd6da)

![Screen Shot 2024-03-13 at 2 06 57 PM](https://github.com/wso2/api-manager/assets/8557410/7e71da5d-dc9b-4371-8585-b83d97dd2180)

### Steps to Reproduce

1. Login to the Publisher portal. 
2. Create the sample service.
3. Click on the created service and go to its overview page.
4. Click on View Definition link
5. You will get an error page like above.

### Affected Component

APIM

### Version

4.3.0

### Related Issues

https://github.com/wso2/api-manager/issues/2624

https://github.com/wso2/api-manager/issues/2630

**Comment by lasanthaS** [comment]
This is working on Safari 16+. Hence closing the issue.
