### ISSUE TITLE
Edit API Definition gives error page in Safari

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#2633]
### Description

When trying to click on the Edit option for an API Definition, the following error page is shown in the Safari Web browser.

![Screen Shot 2024-03-13 at 2 21 10 PM](https://github.com/wso2/api-manager/assets/8557410/5680c89a-7606-4c4d-8799-9af26bc3f047)

### Steps to Reproduce

1. Login to the Publisher portal using the Safari Web Browser
2. Create an API
3. Click on the API Definition tab for the API
4. Then click on the Edit option
5. You will see an error page like above

### Affected Component

APIM

### Version

4.3.0

### Related Issues

https://github.com/wso2/api-manager/issues/2632

https://github.com/wso2/api-manager/issues/2630

https://github.com/wso2/api-manager/issues/2624

**Comment by lasanthaS** [comment]
This is working on Safari 16+. Hence closing the issue.
