### ISSUE TITLE
UI issues related API Policies

### ISSUE THREAD

**Issue by ashera96** [wso2/api-manager#2637]
### Description

- The title "Policies > Create New Policy" is hidden as shown below when we navigate to the `Common Policies` page and try to add a new policy. 

<img width="1237" alt="image" src="https://github.com/wso2/api-manager/assets/30475839/616e395e-02fb-4761-9725-ef2f5d61df7a">

- Alignment issues when we try to add policy attributes. Spacing between text fields and vertical alignment between fields and icons needs to be fixed.

Current UI:
<img width="1149" alt="image" src="https://github.com/wso2/api-manager/assets/30475839/934e8c50-fc25-48e8-8979-03a1cbd54b79">

Earlier UI:
<img width="1149" alt="image" src="https://github.com/wso2/api-manager/assets/30475839/ab362474-51ed-4c9a-9826-3192da39fbf5">

- Horizontal line colour has changed. Better if it is in a grey colour.
 
Current UI:
<img width="1149" alt="image" src="https://github.com/wso2/api-manager/assets/30475839/f138eede-da4a-4184-9d77-d0d7df3f50ba">

Earlier UI:
<img width="1149" alt="image" src="https://github.com/wso2/api-manager/assets/30475839/9fbbcee1-af67-4d6a-90c2-9258953ad38b">

### Steps to Reproduce

Mentioned above

### Affected Component

APIM

### Version

4.3.0

**Comment by ashera96** [comment]
When a new policy is dragged and dropped the side drawer that shows is missing the heading (it is hidden due to the top navbar). Also, the styling of the horizontal line below the title needs to be grey as black is too prominent.

Current UI:
<img width="1149" alt="image" src="https://github.com/wso2/api-manager/assets/30475839/8f28f290-98b5-4357-84be-3f56dad48776">

Earlier UI:
<img width="1149" alt="image" src="https://github.com/wso2/api-manager/assets/30475839/f4ee8db4-17f0-41c9-9b35-91c7b2569d48">

**Comment by shnrndk** [comment]
Related Issue: https://github.com/wso2/api-manager/issues/2540 and Related PR for the missing header: https://github.com/wso2/apim-apps/pull/585
