### ISSUE TITLE
Cannot invoke a managed API

### ISSUE THREAD

**Issue by BLasan** [wso2/api-manager#2638]
### Description

After developing an integration from a managed API, on the invocation it returns the below error.
`Exception occurred :Illegal character in path at index 12: /healthcare/{uri.var.category}% `

### Steps to Reproduce

Follow the below doc (4.2.0)[1] as provided 4.3.0 link does not work

[1] https://apim.docs.wso2.com/en/latest/tutorials/develop-an-integration-with-a-managed-api/#!

### Affected Component

APIM

### Version

4.3.0

**Comment by BLasan** [comment]
Issue comes from the backend service mentioned in the doc. Checked in 420 GA and 420 latest U2 level. FYI @tharikaGitHub @lasanthaS

**Comment by tharikaGitHub** [comment]
Closing the issue as this was not reproduced in the APIM 4.3.0-beta pack according to the latest testing done by @BLasan.
