### ISSUE TITLE
Account unlocked state does not get notified to the users properly after locking.

### ISSUE THREAD

**Issue by O-sura** [wso2/api-manager#2639]
### Description

According to the [docs](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/user-account-management/#account-locking), after enabling account locking due to exceeding the maximum allowed failed login attempts, the account should be automatically unlocked and a mail should be sent to the user notifying them that the account is unlocked. 

![Screenshot from 2024-03-14 10-21-57](https://github.com/wso2/api-manager/assets/84634723/e8ce79cc-e15b-4824-ba70-b5100961bd96)

Even though the user can log in after the timeout period without any issue the state change doesn't get properly reflected in the system as no mail was sent to the user upon unlocking their account after the timeout and unless the user reattempt to login, the state of the account is also showed as locked in the management console as well. 

![Group 7](https://github.com/wso2/api-manager/assets/84634723/ee1f106f-2f35-4168-a85b-df554b65cc09)

### Steps to Reproduce

1. Enable the to account locking for failed login attempts by following the instructions given in the [docs](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/user-account-management/#account-locking-by-failed-login-attempts)

2. Follow the steps given under [Account locking by an administrative user](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/user-account-management/#account-locking-by-an-administrative-user) to make the Account Locked status appear in the user's profile in management console.

3. Using the username of a user with proper assigned roles, try to login to publisher or developer portal using an invalid password multiple times exceeding the allowed maximum failed attempts.

4. Wait till the defined timeout period is passed and check the management console for the account locked status for that user and the inbox of the user given mail for the account unlocked message

### Affected Component

APIM

### Version

4.3.0

**Comment by AnuGayan** [comment]
Couldn't reproduce this on the alpha2 version
