### ISSUE TITLE
Cannot add a resource in registry via carbon console

### ISSUE THREAD

**Issue by BLasan** [wso2/api-manager#2642]
### Description

When adding a resource to the registry via carbon console, it keeps on processing without returning a successful response

### Steps to Reproduce

Follow the steps under `Configure per tenant custom domain mappings` [1]

[1] https://apim.docs.wso2.com/en/4.3.0/reference/customize-product/customizations/customize-the-api-store-and-gateway-urls-for-tenants/

<img width="876" alt="Screenshot 2024-03-14 at 12 15 02" src="https://github.com/wso2/api-manager/assets/43112139/a511cf72-1521-47c0-a000-7a8a4099f078">

### Affected Component

APIM

### Version

4.3.0

**Comment by AnuGayan** [comment]
Tested this on the latest version and couldn't reproduce the behaviour

**Comment by shamin2021** [comment]
This issue still persists in the Firefox browser. Works fine with Chrome.

**Comment by AnuGayan** [comment]
Yes, observed the behaviour in Firefox 124.0.1 in the latest(Post alpha2) pack

**Comment by AnuGayan** [comment]
This issue is there in API Manager 4.2.0 version as well,
