### ISSUE TITLE
Error When Importing OAS 3.1.0 Defintion

### ISSUE THREAD

**Issue by hisanhunais** [wso2/api-manager#2646]
### Description

There is an error when importing the OAS 3.1.0 definition which is available in [1]

<img width="922" alt="Screenshot 2024-03-14 at 17 05 58" src="https://github.com/wso2/api-manager/assets/30455603/f37db3b8-82f8-48e2-b8cd-9511ecb436bb">

[1] https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.1/non-oauth-scopes.yaml

### Steps to Reproduce

Log into the Publisher an import the API definition available in [1]

[1] https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.1/non-oauth-scopes.yaml

### Affected Component

APIM

### Version

4.3.0

### Relevant Log Output

```shell
ERROR - ApisApiServiceImpl Error while parsing OpenAPI definition. Error code: 900754. Error: attribute paths.'/users'(get).responses is missing
```

**Comment by lasanthaS** [comment]
In OAS 3.1.0, the responses object is a mandatory field in the operation object[1]. Therefore, this is not an error.


[1] Refer "Operation Object" in https://swagger.io/specification/
