### ISSUE TITLE
"Revoking access tokens obtained with a JWT grant with CLIENT_ID" option is not working

### ISSUE THREAD

**Issue by piyumaldk** [wso2/api-manager#2647]
### Description

Refer the doc: https://apim.docs.wso2.com/en/4.3.0/design/api-security/oauth2/token-revocation/

Using given instructions, users can revoke tokens.

But it seems revoking access tokens obtained with a JWT grant with only using CLIENT_ID does not work. It gets a empty reply from server and after revocation, but JWT token still works.

### Steps to Reproduce

1. Follow this document - https://apim.docs.wso2.com/en/latest/design/api-security/oauth2/grant-types/jwt-grant/#step-1-obtain-a-jwt-from-an-external-identity-provider
(Note: I used IS 6.1)

2. Try invoking an API using the generated JWT to verify.

3. If it works, try revoking the token with below documents final curl.
https://apim.docs.wso2.com/en/4.3.0/design/api-security/oauth2/token-revocation/

Curl mentioned in the doc
```
curl -X POST -H "Content-Type: application/x-www-form-urlencoded;charset=UTF-8" -d "token=<ACCESS_TOKEN_TO_BE_REVOKED>&token_type_hint=access_token&client_id=<CLIENT_ID>" http://localhost:8243/revoke
```

4. Try to invoke the API with the revoked token. I was still able to invoke the API successfully. 

### Affected Component

APIM

### Version

4.3.0-Alpha

### Environment Details (with versions)

Local

**Comment by piyumaldk** [comment]
Token Revocation returns a 200 in the distributed setup. So no issue there. 

However, JWT revocation does not work does not work even in the distributed setup.

**Comment by piyumaldk** [comment]
Token Revocation in local setup returns a 200. So no issue there.

However, Revoking access tokens obtained with a JWT grant with only CLIENT_ID did not work locally.

**Comment by RakhithaRR** [comment]
> Token Revocation in local setup returns a 200. So no issue there.
> 
> However, Revoking access tokens obtained with a JWT grant with only CLIENT_ID did not work locally.

It seems this is not a valid scenario. This will be removed from the docs. The token revocation works fine with the usual approach.

**Comment by tharikaGitHub** [comment]
Closing as the doc PR https://github.com/wso2/docs-apim/pull/7782 is merged.
