### ISSUE TITLE
Selecting API Key type in the try out console still builds the request for normal auth

### ISSUE THREAD

**Issue by Arshardh** [wso2/api-manager#2648]
### Description

Selecting the API Key type in the try-out console still builds the request for normal auth. Adds Authorization header instead of apikey and adds Bearer keyword.
<img width="888" alt="image" src="https://github.com/wso2/api-manager/assets/15942605/a50d3889-6d45-499a-8fb8-2f8bdf2f887a">

<img width="1402" alt="Screenshot 2024-03-14 at 19 49 06" src="https://github.com/wso2/api-manager/assets/15942605/7256fc12-a11d-40bd-b143-e1bf20297705">

### Steps to Reproduce

1. Create and publish API with the tick for api key
2. Subscribe to API and access tryout console.
3. Select the Application and tick the API Key radio button.
4. Generate or provide an API key in the respective text box
5. Execute API invocation.

### Affected Component

APIM

### Version

4.3.0

**Comment by tharikaGitHub** [comment]
Related issue https://github.com/wso2/api-manager/issues/2564

**Comment by PasanT9** [comment]
This is fixed with https://github.com/wso2/apim-apps/pull/598
