### ISSUE TITLE
[Publisher] Getting an Error in Creating API Documents when trying to upload files with special characters in the name 

### ISSUE THREAD

**Issue by Chanuka-ChandraYapa** [wso2/api-manager#2649]
### Description

When creating Documents in the publisher portal, User can upload files after selecting the source as 'File'. If the file's name contains special characters, it can not be uploaded. But instead of showing an alert, it outputs an error in the console as below.

![Screenshot from 2024-03-14 19-33-36](https://github.com/wso2/api-manager/assets/118423471/cb162c40-56fb-48eb-a475-c5649ba985e7)

### Steps to Reproduce

1. Log in to the Publisher Portal
2. Select an API and go the Documents tab under Portal Configurations
3. Select 'Add New Document'
4. Select Type as 'How To'  and Source as 'File'
5. Try uploading a file clicking on the upload icon.
6. If the file name has special characters in it, console error will be appeared as above.

### Affected Component

APIM

### Version

4.3.0

**Comment by AnuGayan** [comment]
@Chanuka-ChandraYapa could you please provide a sample file name which you tried to reproduce this issue?

**Comment by Chanuka-ChandraYapa** [comment]
api-docs-sample(3).pdf
Issue#2649.pdf

I tried using Firefox.
