### ISSUE TITLE
Publish button getting disabled after enabling response caching

### ISSUE THREAD

**Issue by BLasan** [wso2/api-manager#2655]
### Description

When doing `Save and Deploy` with response caching enabled, `Publish` button on Lifecycle page getting disabled.

### Steps to Reproduce

1.) Create API
2.) Enable response caching 
3.) Save and Deploy
4.) Go to Lifecycle page and you'll see `Publish` button disabled

<img width="1252" alt="Screenshot 2024-03-15 at 11 29 52" src="https://github.com/wso2/api-manager/assets/43112139/44d09499-17f6-456e-bca9-67f99e292a20">
<img width="816" alt="Screenshot 2024-03-15 at 11 29 58" src="https://github.com/wso2/api-manager/assets/43112139/89c7cd62-afa1-4ac5-8a44-c9114a42b1a4">

### Affected Component

APIM

### Version

4.3.0

**Comment by tharikaGitHub** [comment]
Related issue https://github.com/wso2/api-manager/issues/2606

**Comment by PasanT9** [comment]
Fixed with https://github.com/wso2/apim-apps/pull/604
