### ISSUE TITLE
Add a file type restriction for operation policy definitions

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#2663]
### Problem

As of now we only have a note dtating that we accept `xml` and `j2` typed files as operation polciy definitions. But the UI and backend allows to upload any file type. It is nice to have a file type restriction here. 

### Solution

Add a file type restriction to disallow any file type other than `j2` or `xml`.

### Affected Component

APIM

### Version

4.3.0

**Comment by BLasan** [comment]
Fixed via - https://github.com/wso2/apim-apps/pull/634
