### ISSUE TITLE
Oauth2 token generated for product Rest APIs does not get revoked immediately 

### ISSUE THREAD

**Issue by piyumaldk** [wso2/api-manager#2670]
### Description

Oauth2 token generated for product Rest APIs does not get revoked immediately. However JWT tokens generated to access APIs (managed by APIM) can be revoked immediately using the revocation.

### Steps to Reproduce

1. Use Register DCP App API and get ClientID and ClientSecret 
(https://<host>/client-registration/v0.17/register)
2. Use Generate Access Token API and get Oauth2 token 
(https://<host>/oauth2/token)
3. Invoke an API using the token (In my case, I invoke listing APIs API)
(API will get a successful response with API list)
4. Invoke the token using token invocation API. You will get a 200.
(https://<host>/oauth2/revoke
5. Again try step 3 and see that API is still getting the response successfully which means token is still valid.

 This step 5 is however not possible when we start the server again which means there is a possibility that revocation works fine but cache is keeping the revoked token. 
 
Anyway this is a problem as 
- Normal JWT revocation works fine immediately as expected.
- We cannot ask users to start the server again when a revocation is done.
- We do not mention such behaviour in documentation.

### Affected Component

APIM

### Version

4.3.0-Alpha

### Environment Details (with versions)

Local and Distributed

**Comment by nandika** [comment]
This happens due to cache. Reducing the cache timeout duration is the correct approach
