### ISSUE TITLE
Validation Message not accurate when Creating Shared Scope with no Display Name

### ISSUE THREAD

**Issue by pabloa2022** [wso2/api-manager#2672]
### Description

Hi,
If you don't fill in the display name of the shared scope, it shows a validation message that the display name exceeds 255, which is incorrect, because it is empty. The validation message should change to something related to the field is not allowed to be empty and not say it has exceed the max 255 chars.
This a validation issue with the shared scope form. If you try to save the scope without any display name via API the backend will send you an error response mentioning that the scope display name is required.

The issue in the code is with the following [1], where we have validated the value based on the value is null or not and the value length. Ideally the length should be validated after checking whether the value is null. This way correct length logic will be displayed and evaluated.

https://github.com/wso2/apim-apps/blob/bf8dc3bb33a3d16212b28761ab5fff4a101560be/portals/publisher/src/main/webapp/source/src/app/components/Scopes/Create/CreateScope.jsx#L321-L331

Note to the patch creator:
Add the above mentioned logic in the apim-apps code and check the validation.

### Steps to Reproduce

Login into MI 4.2.0 publisher
Go to Shared scopes
Create a new one and not assign any value at "Display name" label
Click on Save

![image](https://github.com/wso2/api-manager/assets/98116074/b2ecdb2a-1462-49e6-8e0c-49b173918826)

### Affected Component

APIM

### Version

4.2.0

### Suggested Labels

APIM-4.2.0

**Comment by Lakith-Rambukkanage** [comment]
Fixed by https://github.com/wso2/apim-apps/pull/623
