### ISSUE TITLE
 Add improvement to acknowledge when query doesnt return data 

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/api-manager#2675]
### Problem

Currently the event stream gets dropped at rdbms:query() when the query doesn't return any data.

### Solution

Need to perform a null check on the return attributes.

### Affected Component

SI

### Version

1.1.0

**Comment by Avishka-Shamendra** [comment]
Hi all,

Closing this as fix is already in the master via https://github.com/siddhi-io/siddhi-store-rdbms/pull/229

Thank you
Avishka
