### ISSUE TITLE
Can't change owner application in APIM 4.2.0

### ISSUE THREAD

**Issue by Menuka-Senevirathne** [wso2/api-manager#2681]
### Description

Throwing the below error when trying to change the owner.
 
`ERROR - GlobalThrowableMapper User does not have scope. Username : COMUNE.MILANO.LOCAL/viviana.pezzano Scope : apim:subscribe`

### Steps to Reproduce

- Get APIM 4.2.0 latest version.
- Create an Internal role and assign that to a new user.
- Then go to the admin portal and assign Internal/Subscriber scope to the above role.
- Go to the devportal and create a new application with the admin user.
- Then try to change the user from admin to newly created user (step 02), you’ll see the above mentioned issue.

### Affected Component

APIM

### Version

4.2.0

**Comment by RakhithaRR** [comment]
Fixed via https://github.com/wso2/carbon-apimgt/pull/12212
