### ISSUE TITLE
workflow-extensions.xml and related Docs needs improvements

### ISSUE THREAD

**Issue by piyumaldk** [wso2/api-manager#2683]
### Problem

We give users below workflows.

User Creation
https://apim.docs.wso2.com/en/4.1.0/reference/customize-product/customizations/adding-a-user-signup-workflow/

Application Creation
https://apim.docs.wso2.com/en/latest/consume/manage-application/advanced-topics/adding-an-application-creation-workflow

Subscription Creation
https://apim.docs.wso2.com/en/latest/consume/manage-subscription/advanced-topics/adding-an-api-subscription-workflow/

Subscription Update
https://apim.docs.wso2.com/en/latest/consume/manage-subscription/advanced-topics/adding-an-api-subscription-tier-update-workflow/

Subscription Deletion
https://apim.docs.wso2.com/en/latest/consume/manage-subscription/advanced-topics/adding-an-api-subscription-deletion-workflow/

Application Registration
https://apim.docs.wso2.com/en/4.2.0/learn/consume-api/manage-application/advanced-topics/adding-an-application-key-generation-workflow/

API State Change
https://apim.docs.wso2.com/en/latest/design/advanced-topics/adding-an-api-state-change-workflow/#advanced-configurations

API Product State Change
- Same as API State

API Revision Deployment
https://apim.docs.wso2.com/en/master/deploy-and-publish/deploy-on-gateway/deploy-api/revision-deployment-workflow/

### ISSUE 1
However, in the xml, there are many unwanted properties. We need to clear the xml referring the docs.

### ISSUE 2
Also, if a user changed a workflow from approval to simple in the middle of a approval process (Before rejecting or approving), those workflow tasks get struck. We should handle this scenario or mention that user should not change the workflow from approval to simple before clearing pending workflow tasks. IMO, it's better to mention this in a comment in the xml file when we are improving the xml file.

### ISSUE 3
https://apim.docs.wso2.com/en/latest/consume/manage-subscription/advanced-topics/adding-an-api-subscription-deletion-workflow/ document need to be fixed. Line in the document is
```
<ubscriptionDeletion executor="org.wso2.carbon.apimgt.impl.workflow.SubscriptionDeletionAprrovalWorkflowExecutor"/>
```

However, it should be
```
<SubscriptionDeletion executor="org.wso2.carbon.apimgt.impl.workflow.SubscriptionDeletionApprovalWorkflowExecutor"/>
```

Please note that not only subscription, but also approval spelling is also wrong.

### ISSUE 4
Application Deletion is not working. Also there is no documentation for the Application Deletion. However, there is some implementation for that and in the Admin portal, there is a page for that. If product is not allowing to do so, it's better to remove them or if it should work, we have to address that a a bug and we have to fix it.

### Solution

Please read above each sections.

### Affected Component

APIM

### Version

4.3.0-Alpha

**Comment by chamilaadhi** [comment]
Adding `<ApplicationDeletion executor="org.wso2.carbon.apimgt.impl.workflow.ApplicationDeletionApprovalWorkflowExecutor"/>` will enable application deletion workflow

**Comment by chamilaadhi** [comment]
Doc issue to fix others https://github.com/wso2/docs-apim/issues/7786
