### ISSUE TITLE
Access Token is empty when click on the Generate Access button when using AzureAD as key manager

### ISSUE THREAD

**Issue by shnrndk** [wso2/api-manager#2691]
### Description

Access Token is empty when click on the Generate Access button when using AzureAD as key manager when the user generates a access token for the newly created app for the first time.

<img width="1494" alt="image" src="https://github.com/wso2/api-manager/assets/43110114/3d4f111f-d146-4fc7-b611-9d649e81ada0">

This issue has an intermittent behaviour. When we try again by clicking it sometimes show the access token.

### Steps to Reproduce

1.) Setup the azure as key manager.
2.) Create new application
3.) Go to Sandbox keys or production keys on the side menu bar and click on the oauth2 tokens. Select the Azure Ad key manager and click on generate keys.
4.) Then click on Generate access tokens button.
5.) The access token will be blank.

### Affected Component

APIM

### Version

4.3.0 Post Alpha

**Comment by tharikaGitHub** [comment]
Closing as the PRs are merged

**Comment by PasanT9** [comment]
Issue still exists.

<img width="601" height="403" alt="Image" src="https://github.com/user-attachments/assets/ca6b4c10-9bc7-4976-a1d0-32036682f55d" />
