### ISSUE TITLE
Cannot Access Admin Portal with Super Admin Credentials after updating.

### ISSUE THREAD

**Issue by janithcmw** [wso2/api-manager#2695]
### Description

After changing the following configurations it was not possible to access the Admin portal. It returns status 403.
    
```
[super_admin]
username = "testAdmin"
password = "testAdmin"    
create_admin_account = false
admin_role = "new_admin_role"
```

### Steps to Reproduce

1. Started the APIM server.

2. Stopped it.

3. Added Read Only User-store to the server.

4. Super_admin details

```
      [super_admin]
      username = "admin"
      password = "admin"
      admin_role="new_admin_role"
      create_admin_account = false
```
      
5. Started the server and tried to log in to the /admin portal using the super admin credentials and got failed the login with 403 HTTP response code.

### Affected Component

APIM

### Version

4.1.0

**Comment by RakhithaRR** [comment]
Fixed via https://github.com/wso2/carbon-apimgt/pull/12164
