### ISSUE TITLE
[APIM 4.2.0] Inability to Deploy New Revisions in APIM 4.2.0 Publisher Portal.

### ISSUE THREAD

**Issue by Hamool-Nizar** [wso2/api-manager#2705]
### Description

Hi Team,

We are unable deploy new revisions due to an inability to scroll down the API Gateway list and select the deploy button.

<img width="1440" alt="Deploy_New_Revision_1" src="https://github.com/wso2/api-manager/assets/87962341/1d38ab6f-b362-42c0-9705-d753d583908c">
<img width="1440" alt="Deploy_New_Revision_2" src="https://github.com/wso2/api-manager/assets/87962341/04adb503-83e2-4e7e-87d6-1a7c262117ad">

### Steps to Reproduce

1. Create and configure multiple gateways.
2. The login into the publisher portal.
3. Try to deploy a new revision on a API.

### Affected Component

APIM

### Version

4.2.0

**Comment by dulithsenanayake** [comment]
Hi all,

Closing this as the U2 update is released & fix is available on the public branch as well.

Thanks!
Dulith
