### ISSUE TITLE
[DevPortal] Cannot remove keys

### ISSUE THREAD

**Issue by lasanthaS** [wso2/api-manager#2712]
### Description

When trying to click remove keys after generating a client id/secret pair, the operation fails with a console error.

<img width="1451" alt="Screenshot 2024-03-26 at 02 30 18" src="https://github.com/wso2/api-manager/assets/2142703/c83aa266-9846-490d-82ec-92649ff6bd9b">

### Steps to Reproduce

1. Create an application
2. Generate client id/secret pair
3. Click on the "Remove Keys" button

### Affected Component

APIM

### Version

4.3.0

**Comment by AnuGayan** [comment]
This is not reproducible in the latest pack
