### ISSUE TITLE
APIM 3.2.0 - "context with version already exists" Error.

### ISSUE THREAD

**Issue by Manasha11** [wso2/api-manager#2723]
### Description

If an API with context /foo/bar and version 1.0.0 already exists, when attempting to create a new API with the context /bar and the same version 1.0.0, we could observe an error indicating that "/bar/1.0.0 context with version already exists" as below.

<img width="756" alt="Screen Shot 2024-03-27 at 19 28 25" src="https://github.com/wso2/api-manager/assets/21274746/93e8ff08-b2fb-4970-b611-59e6554ec61f">

### Steps to Reproduce

- Create an API with context /foo/bar and version 1.0.0.
- Created another API with context /bar and version 1.0.0.
- Observe the aforementioned error preventing the creation of API.

### Affected Component

APIM

### Version

3.2.0

**Comment by RakhithaRR** [comment]
The issue is not reproducible in latest versions.
