### ISSUE TITLE
Validate special characters during Publisher REST API add documentation

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#2726]
### Description

Since backend layer has no validation for special characters like `/`, in versions prior to 4.x.x, the documentation created with names like `/test/APIDocumentation` will be created inside a subdirectory `test` in registry's `.../documentation/` path. This is a bug and from 4.x onwards such documents are not loaded as the registry get documentation implementation is different (we no longer use registry associations for API documentations). 

To fix this, we need to add validation in the backend similar to UI to prevent creating documentation names with `/`.

### Steps to Reproduce

Pass the name  as "name": "Retrieve BIN/PRIN ranges for top client", it will create the directory "Retrieve BIN" inside the documentation directory. APIM 3.2.0 can load the API documentation successfully into the publisher portal and APIM 4.2.0 is not able to load the APIM documentation to the publisher portal.

### Affected Component

APIM

### Version

3.2.0, 4.1.0, 4.0.0, 4.2.0

**Comment by dulithsenanayake** [comment]
Closing this since the U2 update was released.
