### ISSUE TITLE
Unformatted response from API Chat

### ISSUE THREAD

**Issue by PasanT9** [wso2/api-manager#2730]
### Description

Response from API Chat is not not formatted 

![Screenshot from 2024-03-28 12-52-53](https://github.com/wso2/api-manager/assets/43533314/d03b2eee-b9b4-4fc3-aea5-84a409af3aa1)

### Steps to Reproduce

1. Publish any API
2. Go to API Chat page and execute a query.

### Affected Component

APIM

### Version

4.3.0

**Comment by RakhithaRR** [comment]
Fixed through https://github.com/wso2/apim-apps/pull/679
