### ISSUE TITLE
Issues with token auto generation in API Chat

### ISSUE THREAD

**Issue by PasanT9** [wso2/api-manager#2735]
### Description

Once we open **Configure Key** drawer a token is auto generated. This will revoke any token that was previously generated. This limits any modifications we can do on the token.

### Steps to Reproduce

1. Publish an API
2. Subscribe the API and generate a token. Copy the token and keep aside.
3. Go to API Chat. Open Configure Key drawer.
4. Remove the auto generated token and paste the token generated at step 2.
5. Use API chat to invoke a resource.

### Affected Component

APIM

### Version

4.3.0-alpha2

**Comment by ashera96** [comment]
Token auto-generation capability was removed via https://github.com/wso2/apim-apps/pull/657
