### ISSUE TITLE
API chat queries does not return correct response with basic auth

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2737]
### Description

API chat queries does not work with basic auth

<img width="1509" alt="Screenshot 2024-03-28 at 16 38 42" src="https://github.com/wso2/api-manager/assets/54719880/09ec7477-dbf4-406b-be42-f9cc20e0acd9">

### Steps to Reproduce

Prerequisites
----------------
Create an API and enable Basic level security under runtime configurations
Deploy the API

Steps
-----------
1. Login to devportal
2. Subscribe to API
3. Navigate to API chat
4. Open Configure key side panel 
5. Provide Basic auth credentials
6. Execute a query

### Affected Component

APIM

### Version

4.3.0

**Comment by tharikaGitHub** [comment]
Closing as this issue is fixed with https://github.com/wso2/apim-apps/pull/658
