### ISSUE TITLE
When basic auth credentials are added, API chat text box remain disabled when a user opens 'Configure Key' panel and close without making any changes

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2738]
### Description

When basic auth credentials are added, API chat text box remain disabled when a user opens "configure key" panel and close without making any changes 

<img width="1509" alt="Screenshot 2024-03-28 at 16 51 47" src="https://github.com/wso2/api-manager/assets/54719880/1559734d-7ce6-4d52-84aa-86d27df9a2cf">

### Steps to Reproduce

1. Login to developer portal
2. Navigate to API chat
3. Open configure key panel and provide basic credentials
4. Close the panel and execute a query.
5. Open the Panel and close without making any changes

### Affected Component

APIM

### Version

4.3.0

**Comment by ashera96** [comment]
Need to verify if this is reproducible once the issue [1] is fixed.

1. https://github.com/wso2/api-manager/issues/2737
