### ISSUE TITLE
Publishing API takes time and returns 504 error when AI features are enabled

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#2746]
### Description

In the Distributed setup, when the AI features are enabled, publishing an API takes time and the following 504 Gateway timeout error occurs.

![Screen Shot 2024-03-29 at 11 49 17 AM](https://github.com/wso2/api-manager/assets/8557410/e8bf7029-10a9-434c-8856-a4b10abce3e3)

After refreshing, could see that the API is Published successfully. This behaviour needs to be fixed. **This issue is not observed for the Pizzashack api.**

![Screen Shot 2024-03-29 at 11 49 53 AM](https://github.com/wso2/api-manager/assets/8557410/96bc2b58-6b3a-412c-92ae-9f01e1393dba)

### Steps to Reproduce

When AI features are enabled after configuring a token as well, try to create and publish an API from the publisher portal through the Stepper UI.

### Affected Component

APIM

### Version

4.3.0

**Comment by ashera96** [comment]
Fixed via https://github.com/wso2/carbon-apimgt/pull/12399
