### ISSUE TITLE
UI Alignment issue in View Generated Documentation for Rest APIs

### ISSUE THREAD

**Issue by HelaniUdara** [wso2/api-manager#2749]
### Description

There is an alignment issue in the Generated Documentation for Rest APIs as in the attached Screen shot.

![Screenshot from 2024-03-29 12-36-41](https://github.com/wso2/api-manager/assets/90105093/66edcf95-95a4-4f88-8092-36db334a1ea3)

### Steps to Reproduce

1. Log in to publisher portal
2. Click on an API
3. Navigate to Develop -> Portal Configurations -> Documents -> View Document

### Affected Component

APIM

### Version

4.3.0

**Comment by Tharanidk** [comment]
Fix the Issue in the button text.

![Screenshot from 2024-04-01 12-28-49](https://github.com/wso2/api-manager/assets/42825038/32973dfd-bffb-40d7-b3fb-b25f420fb88b)
