### ISSUE TITLE
Key Manager Usages UI does not work with Global WSO2 IS KM 7

### ISSUE THREAD

**Issue by AnuGayan** [wso2/api-manager#2750]
### Description

Following Error is getting displayed
<img width="1082" alt="Screenshot 2024-03-29 at 13 12 04" src="https://github.com/wso2/api-manager/assets/19290404/3768c91a-cfd4-4fff-bbe1-e29ce0ea4f39">

### Steps to Reproduce

1. Configure WSO2 IS as a global key manager
2. Enable cross tenant subscription in API manager GW
3. Genarate token from the dev portal

### Affected Component

APIM

### Version

4.3.0

**Comment by tharikaGitHub** [comment]
Closing as the fix is merged.
