### ISSUE TITLE
Visibility and Alignment Issues with Left Menu Icons in API Details - (Styling API Details Left Menu)

### ISSUE THREAD

**Issue by HelaniUdara** [wso2/api-manager#2751]
### Description

When minimizing the API details left menu, there are visibility and alignment issues with the icons as follows.
Icons become difficult to discern or entirely invisible when the left menu is minimized.

![Screenshot from 2024-03-29 14-39-25](https://github.com/wso2/api-manager/assets/90105093/d95e0b0f-cde7-4e67-bbcc-ac83b1b47233)

Misalignment issues occur, particularly with the "Try Out" icon when the leftMenu's position is set to vertical-right.

![Screenshot from 2024-03-29 14-42-18](https://github.com/wso2/api-manager/assets/90105093/b5770c97-0ee0-49fe-b55c-cdf2e274ab55)

When setting leftMenu's position to horizontal, the menu bar fails to occupy the full width of the page, stopping halfway. Also, it overlaps with the API overview.

![Screenshot from 2024-03-29 15-02-36](https://github.com/wso2/api-manager/assets/90105093/0448122f-91b5-4194-a27d-750675cd8851)

![Screenshot from 2024-03-29 15-01-00](https://github.com/wso2/api-manager/assets/90105093/42835cc7-9599-47de-8d52-8624d039151b)

### Steps to Reproduce

Follow this link - https://apim.docs.wso2.com/en/4.3.0/reference/customize-product/customizations/customizing-the-developer-portal/styling-api-details-left-menu/

### Affected Component

APIM

### Version

4.3.0

**Comment by Tharanidk** [comment]
The following issues can be found in the 4.4.0-alpha pack.

**1. Issues with Left Menu Icons in API Details when styling horizontally.**

![Screenshot from 2024-10-01 11-55-32](https://github.com/user-attachments/assets/daa341e1-60e4-4b13-9d1c-c7d4c4da8f60)
![Screenshot from 2024-10-01 11-55-48](https://github.com/user-attachments/assets/435a89b0-f906-452e-96d5-4d5452cdbb73)

**2. Misalignment issues occur, particularly with the "Try Out" icon.**

![Screenshot from 2024-10-01 14-10-00](https://github.com/user-attachments/assets/3ce9aa44-4dd6-4146-a349-119971940127)
