### ISSUE TITLE
Disabling OAuth2 password grant causes issues in APICTL 

### ISSUE THREAD

**Issue by VinulaUthsara** [wso2/api-manager#2754]
### Problem

When we disable the password grant type in WSO2 APIM, we are not able to execute operations such as exporting APIs using the APICTL tool.

Please find the reproducing steps below:

- Start APIM 4.2.0 and use APICTL 4.2.4
- Add the following configuration in the deployment.toml file:

```
[oauth.grant_type.password]
enable = false
```
 
- Create an environment in APICTL using the following command:

 `./apictl add env test --registration https://localhost:9443 --apim https://localhost:9443 --token https://localhost:8243/token --admin https://localhost:9443 --publisher https://localhost:9443 --devportal https://localhost:9443`
 
- Create an API in the Publisher Portal
 
- Export the API using the following command:
 
`./apictl export api -n PizzaShackAPI -v 1.0.0 -e test
` 

- Following will reproduce:

- APICTL log:

`Error getting OAuth tokens while exporting API:Unable to connect. Status: 400 
`
- APIM log:

`WARN - PublicClientAuthenticator The request contained grant type : 'password' which is not allowed for public clients.
`

### Solution

APICTL will need to be improved to support client-credentials grant type etc

### Affected Component

APICTL

### Version

4.2.0

**Comment by npamudika** [comment]
Personal Access Token (PAT) support is added to APICTL 4.2.x from 4.2.5 patch release onwards.

**Comment by npamudika** [comment]
Added changes to the master branch with https://github.com/wso2/product-apim-tooling/pull/1169 and https://github.com/wso2/docs-apim/pull/7994
