### ISSUE TITLE
Better to make average ratings of APIs are visible for every user

### ISSUE THREAD

**Issue by PasinduGunarathne** [wso2/api-manager#2758]
### Problem

Currently the average rating of an API is visible only the user is authenticated however the user can see the rating widget but not the numeric value of the average rating.

**Before Authentication**
<img width="614" alt="Screenshot 2024-03-30 at 00 28 29" src="https://github.com/wso2/api-manager/assets/112062108/4d626281-adeb-45e6-a64b-7b1eb47ed00a">

**After Authentication**
<img width="490" alt="Screenshot 2024-03-30 at 00 28 51" src="https://github.com/wso2/api-manager/assets/112062108/2be73657-c10b-40a8-9db8-ce6e7a4c0a0e">

### Solution

Make average rating visible for every user nevertheless the user is authenticated or not

### Affected Component

APIM

### Version

4.2.0

**Comment by AnuGayan** [comment]
Fixed by https://github.com/wso2/apim-apps/pull/662
