### ISSUE TITLE
Cannot login to portals with a tenant user with Oracle 23 as the Database

### ISSUE THREAD

**Issue by PasanT9** [wso2/api-manager#2761]
### Description

You can notice the following error message in the UI when trying to login to either one of the portals with a tenant user.

`
Application you are trying to access does not allow users from your organization`

The issue only happens with the UI. We can still use REST APIs with Tenant users.

### Steps to Reproduce

1. Connect a Oracle 23c database.
2. Login to carbon console and create a tenant.
3. Try to login to publisher with the tenant user created at step 2.

### Affected Component

APIM

### Version

4.3.0-beta

**Comment by tharikaGitHub** [comment]
Closing the issue as the public PRs are merged
