### ISSUE TITLE
500 error is observed when creating a version from a API product when the underlined API deprecated

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2763]
### Description

500 error is observed when creating a version from a API product when the underlined API deprecated. Note that in the present behaviour user is allowed create versions from deprecated APIs

<img width="1490" alt="Screenshot 2024-04-01 at 10 11 20" src="https://github.com/wso2/api-manager/assets/54719880/a3302451-5c5d-4bf3-9bee-5ee50affcf06">

### Steps to Reproduce

1. Login to publisher portal
2. Create an API product 
3. Deprecate the underlined API of the product 
4. Navigate to API products
5. Create a version of the product

### Affected Component

APIM

### Version

4.3.0

**Comment by tharikaGitHub** [comment]
Closing as the PR[1] is merged.

[1] https://github.com/wso2/carbon-apimgt/pull/12401
