### ISSUE TITLE
Error invoking published API from DevPortal in Firefox

### ISSUE THREAD

**Issue by HelaniUdara** [wso2/api-manager#2764]
### Description

When attempting to invoke a published API from the DevPortal using Firefox browser, encountered the following error:
`TypeError: NetworkError when attempting to fetch resource.`

![Screenshot from 2024-04-01 10-16-26](https://github.com/wso2/api-manager/assets/90105093/d309ac14-ac14-4c19-8c61-cdc08fa97507)

But it works correctly in Chrome.

![Screenshot from 2024-04-01 10-23-57](https://github.com/wso2/api-manager/assets/90105093/88728753-ad15-4596-8d14-360da00deed4)

### Steps to Reproduce

1. Log in to the DevPortal.
2. Select a published API.
3. Attempt to invoke the API using Firefox browser.

### Affected Component

APIM

### Version

4.3.0

**Comment by AnuGayan** [comment]
@HelaniUdara This happens because the browser does not trust the certificate.  copy and paste the Request URL in the browser and allow the certificate, and then retry invoking. this will fix the problem
