### ISSUE TITLE
Discrepancy between the API's available business plans in the developer portal and the UI

### ISSUE THREAD

**Issue by veneerac** [wso2/api-manager#2767]
### Description

When we select around 10 business plans for an API in the publisher portal,and then check the API through the developer portal, we observe that these selected policies appear under "Available Policies" in the API subscriptions. However, the list of policies does not align with what is displayed in the UI.

### Steps to Reproduce

Steps to Reproduce:

1.) Create 10-11 new subscription policies through the admin portal.

2.) Go to the publisher portal for the API and navigate to Subscriptions > Business Plans. Select all the

3.) newly created policies and save the changes.

4.) In the developer portal, select the API and then navigate to Subscriptions.

5.) Under "Available Policies," you will see that the list of policies does not match the UI

### Affected Component

APIM

### Version

4.1.0

### Environment Details (with versions)

Update level : 142

**Comment by RakhithaRR** [comment]
Already fixed in latest code
