### ISSUE TITLE
Dropdown alignment issue in Publisher

### ISSUE THREAD

**Issue by shnrndk** [wso2/api-manager#2769]
### Description

Dropdown alignment issues is appeared on deployment page and the publisher tryout console.

Publisher Tryout console
<img width="1162" alt="image" src="https://github.com/wso2/api-manager/assets/43110114/2ce778a0-e5a5-47e9-9eb2-14fc5f808c02">

Deployment page
<img width="1154" alt="image" src="https://github.com/wso2/api-manager/assets/43110114/fdcfd35b-2bb0-48fa-aab0-c01fb36b59e8">

### Steps to Reproduce

In publisher go to tryout console and to select the API gateways dropdown.

### Affected Component

APIM

### Version

APIM 4.3.0 beta

**Comment by Tharanidk** [comment]
Dropdown alignment issues can be found in the below places also.

![Screenshot from 2024-04-01 14-57-56](https://github.com/wso2/api-manager/assets/42825038/c859ddc7-7596-4901-a0d6-322ea5dccbda)

![Screenshot from 2024-04-01 14-59-18](https://github.com/wso2/api-manager/assets/42825038/8f31afed-bd24-45ff-89ae-8c4788bbc7dc)
