### ISSUE TITLE
Password grant is not working for users migrated from from non unique id user stores from APIM 2.6.0 to APIM 4.0.0

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#2775]
### Description

$subject

### Steps to Reproduce

- Started the APIM server 2.6.0 created few test users using and migrated the APIM 2.6.0 to APIM 4.0.0 U2 (218)
-    Generate access token using the previously created users using the Password grant & the Access token generation happens without issues.
 -   Update the APIM 4.0.0 to the Latest(278) or U2-219 & then the token generation for the migrated users will fail with the following response. But the token generation using the password grant will be working for the newly created users after the migration

### Affected Component

APIM

### Version

4.0.0

**Comment by GihanAyesh** [comment]
Fix PRs: https://github.com/wso2/carbon-kernel/pull/3974, https://github.com/wso2/carbon-kernel/pull/3973
