### ISSUE TITLE
TextBox overflow issues in publisher portal.

### ISSUE THREAD

**Issue by Tharanidk** [wso2/api-manager#2776]
### Description

TextBox overflow issues have appeared on the deployment page of the publisher portal.
<img width="1509" alt="Screenshot 2024-04-01 at 14 41 37" src="https://github.com/wso2/api-manager/assets/42825038/c8cf3d83-9125-4927-8c68-da78a8bc850b">

### Steps to Reproduce

1. Add a gateway environment with a name longer than usual.
2. When deploying a new revision.

### Affected Component

Analytics

### Version

4.3.0-beta

**Comment by tharikaGitHub** [comment]
Duplicate of https://github.com/wso2/api-manager/issues/2727. Hence closing as the PR is merged.
