### ISSUE TITLE
Error line during startup in the latest built pack

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#2783]
### Description

During the startup of the latest built pack, the following error line is observed.
```
Unexpected end of line, expected " or a character (line 72, column 14)
```

### Steps to Reproduce

1. Build the latest pack by building both carbon-apimgt and product-apim.
2. Start the server.
3. During the initial lines of startup logs, you will see the above error.

### Affected Component

APIM

### Version

4.3.0

**Comment by SavinduDimal** [comment]
Missing `"` at [1] seems to be the cause of this issue.

[1] - https://github.com/wso2/product-apim/pull/13461/files#diff-094840970e5b40691fca3b849b28631bdd2181c68df9be4d0fa04b78d6fef68dR76
