### ISSUE TITLE
[APIM 4.2.0] Disabling 'apim.lambda_mediator_config' Configuration

### ISSUE THREAD

**Issue by Hamool-Nizar** [wso2/api-manager#2794]
### Description

Hi Team,

We have concerns with AWS Lambda integration in APIM 4.2.0. Firstly, we have noticed the absence of the following 'apim.lambda_mediator_config' configuration, which they previously used in APIM 3.2.0 to manage the passing of request parameters to AWS Lambda backend.

```
[apim.lambda_mediator_config]
pass_request_params = false
```

But In APIM 4.2.0, the lambda_headers (path, query, and header) are enabled by default. Is there a method to disable them using the aforementioned configuration or any alternative configuration options? Upon inspecting the api-manager.xml.j2 file, I observed that the mentioned configuration is no longer present in APIM 4.2.0. Could you please confirm if there are alternative configurations or methods available for disabling these headers?

Best regards,
Hamool

### Affected Component

APIM

### Version

4.2.0

### Environment Details (with versions)

APIM 4.2.0

**Comment by YasasRangika** [comment]
Public fix: https://github.com/wso2/carbon-apimgt/pull/10694
