### ISSUE TITLE
Publisher page crashes when refreshing runtime configurations page of an API product created using an API with OpenAPI 3.1.0 Definition

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2801]
### Description

Publisher runtime configurations page crashes when API Product is created using open API definition 3.1.0 , update runtime configuration and refresh the page. 
<img width="1501" alt="Screenshot 2024-04-03 at 13 00 39" src="https://github.com/wso2/api-manager/assets/54719880/64a1c009-e162-40da-8283-ae1464bdd191">

### Steps to Reproduce

Prerequisites
---------------
Create a API using open API definition 3.1.0

Steps
---------

1. Login to publisher portal
2. Navigate to API products
3. Create an API product using the above created API
4. Navigate to Runtime configurations of the API products
5. Update runtime configurations ( Enable CORS) and save
6. Refresh the page 

### Affected Component

APIM

### Version

4.3.0

**Comment by tharikaGitHub** [comment]
Closing as the fix[1] is merged.

[1] https://github.com/wso2/apim-apps/pull/683
