### ISSUE TITLE
[APIM 4.1.0] 'isApplicationToken' in 'keyValidationInfoDTO' always returns false

### ISSUE THREAD

**Issue by SameeraSI** [wso2/api-manager#2815]
### Description

In APIM 4.1.0, when using X-JWT-Assertion with Opaque access tokens, the 'isApplicationToken' in 'keyValidationInfoDTO' always returns false, regardless of the access token grant type, as already identified[1] in APIM 4.0.0.
<img width="680" alt="Screenshot 2024-04-06 at 02 36 35" src="https://github.com/wso2/api-manager/assets/93453763/b4a0cfb1-f179-4c12-80cb-e42945baf393">

[1] https://github.com/wso2/product-apim/issues/12852

### Steps to Reproduce

APIM 4.1.0

### Affected Component

APIM

### Version

4.1.0

**Comment by dulithsenanayake** [comment]
Hi all,

Closing this since the update was released.

Thanks!
Dulith
