### ISSUE TITLE
Custom CallBackHandlerFactory is not Working on APIM 4.3.0

### ISSUE THREAD

**Issue by ug205** [wso2/api-manager#2829]
### Description

This issue and we have patched it for 4.2.0 for the org.wso2.carbon.user.core 4.9.25 version.
And it is not available in org.wso2.carbon.user.core 4.9.26 version.

### Steps to Reproduce

Please refer to [1].

[1].https://github.com/wso2/api-manager/issues/2125

### Affected Component

APIM

### Version

4.3.0

**Comment by YasasRangika** [comment]
Closing this issue as https://github.com/wso2/carbon-kernel/pull/3983 has been merged.
