### ISSUE TITLE
Adding Jira ticket handling workflow in WSO2 APIM to perform JIRA processes

### ISSUE THREAD

**Issue by Puja-Gitlab** [wso2/api-manager#283]
### Problem

Implementing an Integration of WSO2 APIM with work tracking applications like JIRA needs to be made easy. Currently users have to implement it using WSO2 EI , WSO2 APIM and connector of third party application. For implementing the use case logic with all these products, user need to have expertise on the coding part. Also, handling the integration with all three WSO2 EI, WSO2 APIM and connectors  in line seems a bit complicated to users. So, we can add a feature in APIM to make this easier. Users should be able to configure it with low code development in future.

### Solution

A Jira ticket handling workflow can be added to WSO2 APIM similar to other APIM workflows, workflow should do following things 

- Make a ticket-creation REST API call  to a Jira API from an WSO2 APIM workflow
- Jira server calls the WSO2 APIM back-end REST interfaces to complete the workflow  

Workflow can be implemented using java logic in the backend to integrate WSO2 APIM and JIRA platform.

### Affected Component

APIM

### Version

API Manager 3.2.0 All In One

**Comment by chamilaadhi** [comment]
Since extension points are provided to create custom workflows, we won't be adding a out-of-the box workflow for custom use cases.
