### ISSUE TITLE
Transformation Configurations are not visible when there are "_" in the WSDL operation name. 

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/api-manager#2839]
### Description

When using the WSDL file which has "_" for the operation name, meditations will not add properly. The "Transformation Configurations" for the resource do not appear in the publisher portal. 

### Steps to Reproduce

1. Create a SOAP API using a WSDL that has "_" for the operation name.
2. Then navigate to the resource section.
3. You will be able to see that the "Transformation Configurations" section is missing. 

### Affected Component

APIM

### Version

4.0.0

**Comment by AnuGayan** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/pull/12055
