### ISSUE TITLE
Introduce API linters for validating the API Spec

### ISSUE THREAD

**Issue by pubudu538** [wso2/api-manager#284]
### Describe your problem(s)

There can be cases where we want to validate certain fields such as email, descriptions, etc.
https://nordicapis.com/8-openapi-linters/

### How will you implement it

---
### Sub Tasks
- [x] https://github.com/wso2/api-manager/issues/437
- [x] https://github.com/wso2/api-manager/issues/354
- [x] https://github.com/wso2/api-manager/issues/641
- [x] https://github.com/wso2/api-manager/issues/657
- [x] https://github.com/wso2/api-manager/issues/355
- [x] https://github.com/wso2/api-manager/issues/639
- [x] https://github.com/wso2/api-manager/issues/640

**Comment by tmkasun** [comment]
feasible linting library https://github.com/zalando/zally

**Comment by tharikaGitHub** [comment]
Closing as the feature is completed.
