### ISSUE TITLE
Listed API count using REST API is Zero after the API subscription for a tenant user

### ISSUE THREAD

**Issue by jichinthaka** [wso2/api-manager#2841]
### Description

Hi Team,

We try to list the APIs (using REST APIs) from a user in a tenant after a API subscription. Although, the APIs can be listed before the API subscription, listed API count is Zero after the API subscription. 

APIM 3.2.0 - latest version

### Steps to Reproduce

Reproducing steps: 

1. Enable enable_cross_tenant_subscriptions [1] and Create a new tenant.

Note: All the APIs are created in carbon.super and enable visibility only for particular API which is used to subscribe below. 

2. Created a user in new tenant (I created using UI)
3. Register DCR Client using new user (REST API)
4. Get Access Token (REST API)
5. List Applications (REST API)
6. List API's - Success (REST API)
7. Add Subscription (REST API)
8. List Subscriptions (REST API)
9. List API's - Fail 

```
{
   "count": 0,
   "list": [],
   "pagination": {
       "offset": 0,
       "limit": 25,
       "total": 0,
       "next": "",
       "previous": ""
   }
}
```

### Affected Component

APIM

### Version

359

**Comment by AnuGayan** [comment]
This is only happens on older versions and already fixed in the latest releases.
