### ISSUE TITLE
 Issue with Importing API with Mutual SSL Certificates Using APICTL Tool

### ISSUE THREAD

**Issue by Hamool-Nizar** [wso2/api-manager#2842]
### Description

We have encountered an issue due to the inability to import an API with Mutual SSL certificates using the APICTL tool in APIM 4.2.0. The specific error message states:

`[2024-04-17 08:46:05,377] ERROR - GlobalThrowableMapper Error while importing API: The mentioned certificate file ./dev420/certs/FOMMEAPI_3.crt is not in the certificates directory
`

### Steps to Reproduce

Steps to Reproduce:

1. Create a "certificates" folder within the API project folder.
2. Copy the Mutual SSL certificates into the "certificates" folder.
3. Define the mutual SSL certificates and their paths in the "params.yaml".
4. Import the API using the APICTL tool.
5. Observe the aforementioned error in APIM.

### Affected Component

APICTL

### Version

4.2.0

**Comment by AnuGayan** [comment]
This works fine with the below approach. 

Create an API project from scratch or export an API (without mutual TLs configured) already exists in publisher portal and later delete it.

Followed the steps in [1]

First generate a deployment directory for exported API or API project created. ./apictl gen deployment-dir -s ../PizzaShackAPI_1.0.0.zip
Edit the params.yaml with following.

environments:
    - name: dev
      configs:
           mutualSslCerts:
              - tierName: Silver
                alias: wso2
                path: wso2.crt
Add the wso2.crt to DeploymentArtifacts_PizzaShackAPI-1.0.0/certificates.
Import the API with --params flag pointing out to DeploymentArtifacts_PizzaShackAPI-1.0.0 directory.
 ./apictl import api -f ../PizzaShackAPI_1.0.0.zip --params DeploymentArtifacts_PizzaShackAPI-1.0.0/  -e dev
The API is getting imported successfully with the mutual TLS enabled and with the certificate uploaded.

[1] https://apim.docs.wso2.com/en/4.2.0/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters/#handling-the-certificates-using-the-parameters-file
