### ISSUE TITLE
The logout return url configured in a SP accepts all url patterns by default 

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/api-manager#2844]
### Description

The default logout return url configured in a SP is .*. This means each SP needs to add a proper logout return url when created.

### Steps to Reproduce

1. Create a SP. The default logout return url configured in a SP is .*.

When .* is the logout return url configured at the SP, there should be a configuration to redirect to the server wide default logout url like follows.

[common_auth_caller_path]
enable_common_auth_caller_path_validation=true
default_url="https://www.bing.com/"
enable_fallback_to_default_on_no_return_url=true

The config is there in the IS side. We need to add the same configuration in to API-M 3.2.0

### Affected Component

APIM

### Version

3.2.0

### Related Issues

https://github.com/wso2/product-is/issues/20166

### Suggested Labels

Component/APIM

**Comment by AnuGayan** [comment]
This is not reproducible in the latest versions
