### ISSUE TITLE
APIM 3.2.0 - JSON Schema Validation

### ISSUE THREAD

**Issue by Manasha11** [wso2/api-manager#2847]
### Description

Schema validation not working as expected.
Ecen though the maxProperties is defined as a certain value, if the JSON payload includes more elements than that, but with duplicate keys, the number of properties is not validated.

### Steps to Reproduce

- Enable schema validation in Publisher.
- In swagger definition, maxProperties is set to 5.
- Send a request with 6 elements (with a duplicate key) in the request payload.
The request is forwarded to the backend.

### Affected Component

APIM

### Version

3.2.0

**Comment by AnuGayan** [comment]
This is not reproducible in the latest versions
