### ISSUE TITLE
Remove SHA1 Default Usages and Provide Support to Use SHA-256 

### ISSUE THREAD

**Issue by hisanhunais** [wso2/api-manager#2848]
### Problem

SHA1 is no longer considered as secure. It needs to be updated to SHA256 or higher.

### Solution

Removal of SHA-1 usages in applicable scenarios and provide a config to use SHA-256 in other scenarios keeping SHA-1 usage as the default

### Affected Component

APIM

### Version

4.3.0

**Comment by RakhithaRR** [comment]
Pending version upgrades 

https://github.com/wso2-extensions/identity-outbound-auth-samlsso/pull/179
https://github.com/wso2/carbon-kernel/pull/4040
