### ISSUE TITLE
Is API Name exist validation on UI failed in same tenant domain when having API with role based Publisher Access Control

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/api-manager#2851]
### Description

If we try to create an API with a duplicate name in the same tenant domain, its API name validation won't handle it properly if the existing API is created with role-based Publisher Access Control. Therefore, the API creator could try to make an API, but it will end up below the UI error, and API creation will fail. 

<img width="836" alt="Screenshot 2024-04-23 at 14 44 24" src="https://github.com/wso2/api-manager/assets/15210142/08d29ff9-c17d-469a-b049-330d60026970">

The expectation is that the API name should validate as already existing, but it won't enable the "create" button to create the API. 

### Steps to Reproduce

1. Create a tenant called "wso2.com": test@wso2.com is the admin tenant user
2. Create two tenant users under this "wso2.com" tenant as "user1@wso2.com" and "user2@wso2.com" via the management console by logging in as an admin tenant user. 
3. Create a role called "myrole" and assign it to the "user1@wso2.com" tenant user. 
4. Log into the Publisher UI by using the "user1@wso2.com".
5. Create an API - name "ABC" and Restrict the Publisher Access Control with "my role". 
<img width="942" alt="Screenshot 2024-04-23 at 14 52 45" src="https://github.com/wso2/api-manager/assets/15210142/2552191e-5232-48d2-95bb-e22df6a439f7">
 
6. Log into the Publisher UI using the "user2@wso2.com".  
7. Next, try to create an API with an "ABC" name and a different context & version. 
8. The expectation is that the "ABC" name should be validated as already existing. But it won't happen and allow us to create the API. 
9. When clicking the "Create" button, it showed the below UI error as " Error::API Context does not exist". The reason is that when validating the API context, it detects there is no version for the given API name, provider and domain.
```public static final String GET_VERSIONS_MATCHES_API_NAME_AND_ORGANIZATION_SQL=
            "SELECT API_VERSION FROM AM_API WHERE API_NAME = ? AND API_PROVIDER = ? AND ORGANIZATION = ?";
```
Hence, "isValidContext()[]" is false, and the above error is thrown. 
<img width="836" alt="Screenshot 2024-04-23 at 14 44 24" src="https://github.com/wso2/api-manager/assets/15210142/bec81689-9377-4b49-9b74-3216f85b0d84">

[1]. https://github.com/wso2-support/carbon-apimgt/blob/a469ed282ffecbc7f88f8ae66f60c28a47d1299f/components/apimgt/org.wso2.carbon.apimgt.impl/src/main/java/org/wso2/carbon/apimgt/impl/APIProviderImpl.java#L6606

### Affected Component

APIM

### Version

4.2.0

### Environment Details (with versions)

Latest update level: All in one APIM with multiple tenant domiansAll-in-one

### Relevant Log Output

```shell
ERROR - GlobalThrowableMapper 900977:Block Condition Error::API Context does not exist
```

**Comment by RakhithaRR** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/12495 and https://github.com/wso2/apim-apps/pull/716
