### ISSUE TITLE
[APIM][3.2.0]- Accessing Properties with XPath

### ISSUE THREAD

**Issue by Hashini-Deshappriya** [wso2/api-manager#2852]
### Problem

- It's possible to read values from a properties file as below with $FILE: when used along with uri.
- 				<call>
					<endpoint>
						<address uri="$FILE:APIM_LOG_JMS_ENDPOINT"/>
					</endpoint>
				</call>

- But the same expression is not working when used with a property mediator.
- In the latest version (4.2.0), it’s supporting the SCOPE_FILE  in the GetPropertyFunction but in the APIM 3.2.0 version, it was unavailable.

### Solution

- Improve the same logic used in the APIM 4.2.0 to APIM 3.2.0

### Affected Component

APIM

### Version

3.2.0

**Comment by AnuGayan** [comment]
This has already been fixed in the Master branch
