### ISSUE TITLE
The memory consumed by WSO2 APIM increases over time

### ISSUE THREAD

**Issue by hibernatefariala** [wso2/api-manager#2853]
### Description

I have an instance of WSO2 APIM version 4.2.0 installed on an Oracle Linux 8 server which has 16gb of ram. The problem noticed is that the more time passes, the more the consumption of physical memory increases even if no request is sent to wso2 APIM. This behavior manages to consume all the available memory to the point of making wso2 APIM unavailable and even the server on which it is installed.

What could be the reasons for this behavior and how can I resolve it please?

I tried to reinstall the product, but nothing changed, the same behavior returns

### Affected Component

APIM

### Version

4.2.0

### Environment Details (with versions)

Oracle Linux 8

**Comment by AnuGayan** [comment]
We have analyzed this but couldn't observe the behaviour. It seems like this is local to your environment. I suggest getting a few heap dumps and analysing what object retains memory. This will help to identify the root cause for this.

Please feel free to reopen this issue if you find any clues.
