### ISSUE TITLE
Applications which have larger number of (> 350k) Access tokens does not load in the Store Portal 

### ISSUE THREAD

**Issue by SupunTharakaSandaruwan** [wso2/api-manager#2859]
### Description

When there is an application which has more than 350k Active, EXPIRED or REVOKED access tokens in the IDN_OAUTH2_ACCESS_TOKEN table, that applications never get visible in the Store portal.

### Steps to Reproduce

- Create an application in the Store Portal and generate the keys.
- Generate more than 350k active access tokens with device_ scope.
- Once the tokens are generated, try to load the application from the Store portal.

### Affected Component

APIM

### Version

2.5.0

**Comment by AnuGayan** [comment]
This is only applicable for the older versions, hence closing
