### ISSUE TITLE
Add j2 mapping for  TokenPersistence configurations

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/api-manager#2861]
### Description

Currently, there is no J2 mapping for the following configuration in the identity.xml file

```
<!-- Configs related to OAuth2 token persistence -->
        <TokenPersistence>
            <Enable>true</Enable>
            <PoolSize>{{oauth.token_generation.pool_size}}</PoolSize>
            <RetryCount>{{oauth.token_generation.retry_count_on_persistence_failures}}</RetryCount>
        </TokenPersistence>
```

Therefore, It is required to add a j2 mapping for  TokenPersistence configurations.

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

3.2.0

**Comment by AnuGayan** [comment]
Documentation has been improved https://github.com/wso2/docs-apim/pull/7977
