### ISSUE TITLE
[APIM 4.0.0]: Issue with Business Information Retrieval in Devportal Rest API calls

### ISSUE THREAD

**Issue by Hamool-Nizar** [wso2/api-manager#2862]
### Description

We encountered an issue regarding the retrieval of business information in APIM 4.0.0. The problem arises when attempting to retrieve business information using the Devportal REST API call [1]. Specifically, the "technicalOwner" and "technicalOwnerEmail" fields return null values but when using this Rest API call [2] the customer was able to retrieve all the business information as expected.

While the API details retrieval API call [2] returns the expected business information, the search API call [1] returns null values for the business information fields.

We would appreciate your inputs on whether this behaviour is expected in APIM 4.0.0 or if it indicates a bug that needs to be addressed.

Your insights and suggestions would be much appreciated.

[1]. https://apim.docs.wso2.com/en/4.0.0/reference/product-apis/devportal-apis/devportal-v2/devportal-v2/#tag/APIs/paths/~1apis/get:~:text=%7D-,Get%20Details%20of%20an%20API,-Using%20this%20operation
[2]. https://apim.docs.wso2.com/en/4.0.0/reference/product-apis/devportal-apis/devportal-v2/devportal-v2/#tag/APIs/paths/~1apis/get

### Steps to Reproduce

Steps to Reproduce:

1. Create and publish an API with all required Business Information.
2. Invoke the Rest API call [2] to retrieve details of this API.
 ```
"businessInformation": {
        "businessOwner": "Jane Roe",
        "businessOwnerEmail": "marketing@pizzashack.com",
        "technicalOwner": "John Doe",
        "technicalOwnerEmail": "architecture@pizzashack.com"
    }
```
4. Invoke the Rest API call [1] to search for this API.

```
"businessInformation": {
                "businessOwner": "Jane Roe",
                "businessOwnerEmail": null,
                "technicalOwner": null,
                "technicalOwnerEmail": null
            },
            "avgRating": "0.0"
```

### Affected Component

APIM

### Version

4.0.0

**Comment by dakshina99** [comment]
Thank you for bringing this to our attention. This issue with the "technicalOwner" and "technicalOwnerEmail" fields returning null values in the Devportal REST API call has been identified and addressed in newer versions of APIM.

If you encounter any further problems, please feel free to reopen this issue.
