### ISSUE TITLE
Ciphertool.bat not working in SI 1.1.0 and 4.2.0

### ISSUE THREAD

**Issue by rizmir22** [wso2/api-manager#2869]
### Description

Hi All,

When running Ciphertool.bat in SI, we are observing the following error (with Open JDK 11, Oracle JDK 11 and Open JDK 8) ):

C:\Users\umesh\Downloads\wso2si-4.2.0\wso2si-4.2.0\bin> .\ciphertool.bat -runtime server
JAVA_HOME environment variable is set to C:\Program Files\Java\jdk-11
CARBON_HOME environment variable is set to C:\Users\umesha\DOWNLO1\WSO2SI1.0\WSO2SI~1.0\bin..
Error: Could not find or load main class org.wso2.carbon.secvault.ciphertool.CipherToolInitializer
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.secvault.ciphertool.CipherToolInitializer

Regards,
Rizmeer

### Steps to Reproduce

1. Define a password to encrypt in the secrets.properties file with the correct alias as below
`wso2.local_db.password=plainText root`
2. run the below ciphertool command to encrypt the password.
`.\ciphertool.bat -runtime server`

### Affected Component

SI

### Version

1.1.0

### Environment Details (with versions)

wso2si-1.1.0

### Suggested Labels

wso2si-1.1.0

**Comment by AnuGayan** [comment]
Fixed by https://github.com/wso2/streaming-integrator/pull/313
