### ISSUE TITLE
[APIM][4.0.0] Cache invalidation messages are not getting published when trying to delete an API

### ISSUE THREAD

**Issue by Hashini-Deshappriya** [wso2/api-manager#2872]
### Description

Hi Team,
- We are unable to perform API import and delete processes in a HA setup due to cache invalidation events are not getting published as expected.
- Please refer to the reproducing steps to have a more understanding on the flow.
### Steps to Reproduce

1. Configure an APIM 4.0.0 Active - Active setup(Single node also will be fine with cache invalidation logs turned on).
2. Add the following configuration to both nodes.
```
[apim.cache_invalidation]
enabled = true
```
3. Turn on the cache invalidation logs in the node 1 with carbon console -> event -> publishers --> add and fill the form as of below.
![Screenshot from 2024-05-03 10-07-17](https://github.com/wso2-enterprise/wso2-apim-internal/assets/39541942/e89b3ff9-f79c-46dd-ac98-e0721dd82724)
4.Publish pizzashack API in node 1.
5.Check the node 2 for the deployment of the API.
6.Delete pizzashack API in node 1 and check whether it is removed in node 2(In console you can not see any cache invalidation logs for the registry cache).
7.Try to publish pizzashack API in node 2.
8.You can observe the error in node 2.

### Affected Component
APIM
### Version
4.0.0

Product : wso2am-4.0.0
Update level : 272
WSO2 case id : ENELINSUB-236
Case number : CS0276968

**Comment by RakhithaRR** [comment]
This can be fixed by applying the following configuration

```toml
[apim.cache_invalidation]
enabled = true
excluded_caches = []
```
