### ISSUE TITLE
APIM 3.1.0 traffic manager startup issue

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/api-manager#2895]
### Description

Following error is printed if we take update from level 0 to latest. This error does not happen if you take update to a level 264 or below first and then update to the latest after that
<img width="1297" alt="328413026-f1ff012f-a3a8-4f07-be36-4335637ec68b (1)" src="https://github.com/wso2/api-manager/assets/4861150/4651d1c2-dd82-4eb9-88ad-431753ddb80d">

### Steps to Reproduce

- Update the 3.1.0 pack to the latest update level from 0 level
- Optimize for traffic manager profile ( profileSetup.sh -Dprofile=traffic-manager)
- Change the db configurations in deployment.toml file
- Start the server (wso2server.sh -Dprofile=traffic-manage

### Affected Component

APIM

### Version

3.1.0

**Comment by RakhithaRR** [comment]
Not applicable to latest products
