### ISSUE TITLE
Error in DevPortal when downloading swagger without being logged in

### ISSUE THREAD

**Issue by ug205** [wso2/api-manager#2896]
### Description

Unable to download the swagger definition from the overview page of Devportal without logging into the Dev portal .
Only for tenant specific APIs, for super tenant no issues observed.

### Steps to Reproduce

Create a tenant in carbon console and an API from the the tenant user in Publisher
Publish and view it in the Dev portal
Try to download from the overview page without logging in
Observe errors in front-end and back-end

### Affected Component

APIM

### Version

4.1.0

**Comment by RakhithaRR** [comment]
This has been fixed already
