### ISSUE TITLE
Cannot use export / import REST APIs to change lifecycle state from DEPRECATED to RETIRED

### ISSUE THREAD

**Issue by ksankeerth** [wso2/api-manager#2900]
### Description

Steps to reproduce

Create an API and change lifecycle to DEPRECATED
Export using REST API and get the zip file
Extract the zip file and modify json file to have "RETIRED" state
import again using REST APIs
Please check

### Steps to Reproduce

Steps to reproduce

Create an API and change lifecycle to DEPRECATED
Export using REST API and get the zip file
Extract the zip file and modify json file to have "RETIRED" state
import again using REST APIs
Please check

### Affected Component

APIM

### Version

3.2.0 / 3.2.1

**Comment by BLasan** [comment]
Tested the 4.3.0 latest pack and issue doesn't exist. Hence, closing the issue
