### ISSUE TITLE
Incosistant behaviour on thumbnail upload and remove scenarios [APIM 4.1.0] [PUBLISHER] [RESTFul APIs]

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/api-manager#2908]
### Description

ISSUE 1 - Behavior of the thumbnail attribute
- When calling the publisher REST APIs after removing the existing thumbnail image of the API, sending wrong values under the **hasThumbnail** attribute.

ISSUE 2 - Showing a wrong message

- When removing an existing thumbnail image from an API and saving it, the publisher UI is showing an uploading success message.

### Steps to Reproduce

**ISSUE 1 - Behavior of the thumbnail attribute**

- Start the pack and go to the publisher portal.
- Create an API.
- Under the **Basic Info** section, upload a thumbnail image and save it.
- Then remove the thumbnail from the API via the same publisher UI.
- After that, execute the below 3 REST APIs.

_Get all APIs [1]_
<img width="887" alt="Screenshot 2024-05-21 at 13 22 38" src="https://github.com/wso2/api-manager/assets/18566908/86026259-46af-4203-aa36-f4589869b081">

_Get details of the API [2]_
<img width="888" alt="Screenshot 2024-05-21 at 13 22 54" src="https://github.com/wso2/api-manager/assets/18566908/32fbb75e-afe6-48a5-98a8-1fd81ba61346">

_Get the thumbnail of the API [3]_
<img width="894" alt="Screenshot 2024-05-21 at 13 23 04" src="https://github.com/wso2/api-manager/assets/18566908/af3b9d41-e600-453c-a451-2a416c6a78e5">

**ISSUE 2 - Showing a wrong message**

- Go to the publisher portal and create an API.
- Then under the Basic Info section, upload a thumbnail image and save it.
- Then try to remove it.
- Able to see a wrong UI message (upload success) after removing the thumbnail.

https://github.com/wso2/api-manager/assets/18566908/fdc6c07d-0e54-4f1b-9971-4dfaf0a0ea17

[1] https://apim.docs.wso2.com/en/4.1.0/reference/product-apis/publisher-apis/publisher-v3/publisher-v3/#tag/APIs/operation/getAllAPIs
[2] https://apim.docs.wso2.com/en/4.1.0/reference/product-apis/publisher-apis/publisher-v3/publisher-v3/#tag/APIs/operation/getAPI
[3] https://apim.docs.wso2.com/en/4.1.0/reference/product-apis/publisher-apis/publisher-v3/publisher-v3/#tag/APIs/operation/getAPIThumbnail

### Affected Component

APIM

### Version

4.1.0

**Comment by piyumaldk** [comment]
Backend PR - https://github.com/wso2/carbon-apimgt/pull/12456
Frontend PR - https://github.com/wso2/apim-apps/pull/692

Tested the affected flows
