### ISSUE TITLE
Preserve existing token type when token type is not present in exported application zip file when importing

### ISSUE THREAD

**Issue by ksankeerth** [wso2/api-manager#2912]
### Problem

Steps to reproduce

- Exported an Application (application_01) from APIM 3.2.0 with JWT token type.

- Imported that application_01 to the next environment (Successful).

- Modified the exported application's json file (removed tokenType attribute from the Json file) to mimic the TOKEN_TYPE null and no records in the IDN_OIDC_PROPERTY table

- Imported the application with "update=true"parameter and above error was thrown.

### Solution

Preserve existing token type when token type is not present in exported application zip file when importing

### Affected Component

APIM

### Version

3.2.0/3.2.1

**Comment by RakhithaRR** [comment]
The issue is not reproducible in the latest versions. Hence the public fix is not applicable.
