### ISSUE TITLE
Token revocation not working if a Custom JWT issuer is used with usePersistedAccessTokenAlias = false

### ISSUE THREAD

**Issue by Jaiya94** [wso2/api-manager#2916]
### Description

when using the usePersistedAccessTokenAlias to false in a custom issuer the JTI should be extracted from the full JWT

### Steps to Reproduce

1. Create a ISKM setup with APIM 4.0.0 and IS 5.11.0
2. Create and add a custom token issuer with setting usePersistedAccessTokenAlias to false.
3. Create a new access token.
4. Revoke the token.
5. Try to invoke APIs with the revoked tokens.
6. API GW allows the API resource to be invoked.

### Affected Component

APIM

### Version

4.0.0

**Comment by ashera96** [comment]
Already fixed via https://github.com/wso2-extensions/apim-km-wso2is/pull/63
