### ISSUE TITLE
[APIM 4.0.0]: Issue with API Description Information Retrieval in APIM 4.0.0

### ISSUE THREAD

**Issue by Hamool-Nizar** [wso2/api-manager#2917]
### Description

We encountered an issue regarding the retrieval of business information in APIM 4.0.0. The problem arises when attempting to retrieve API Description information using the Devportal REST API call [1]. Specifically, the "description": field returns null values for APIs but when using this Rest API call [2] the customer was able to retrieve all the API Description information as expected.

We believe based on the above results that this could be a bug that needs to be addressed. Therefore, could you please do the needful and provide a fix/solution for this issue.

[1]. https://apim.docs.wso2.com/en/4.0.0/reference/product-apis/devportal-apis/devportal-v2/devportal-v2/#tag/Unified-Search/paths/~1search/get
[2]. https://apim.docs.wso2.com/en/4.0.0/reference/product-apis/devportal-apis/devportal-v2/devportal-v2/#tag/APIs/paths/~1apis~1{apiId}/get

### Steps to Reproduce

1. Create and publish an API with all required API Description.
2. Invoke the Rest API call [2] to retrieve details of this API.
```
{
            "id": "172ed1d5-d731-4c9c-b2b4-363b10061aec",
            "name": "PizzaShackAPI",
            "description": "This is a simple API for Pizza Shack online pizza delivery store.",
            "context": "/pizzashack",
            "version": "1.0.0",
            "type": "HTTP",
            "provider": "admin",
            "lifeCycleStatus": "PUBLISHED",
            "thumbnailUri": null,
            "avgRating": "0.0",
            "throttlingPolicies": [
                "Unlimited"
            ],

```
3. Invoke the Rest API call [1] to search for this API.
```
{
            "id": "172ed1d5-d731-4c9c-b2b4-363b10061aec",
            "name": "PizzaShackAPI",
            "type": "API",
            "transportType": null,
            "description": null,
            "context": "/pizzashack",
            "version": "1.0.0",
            "provider": "admin",
            "status": "PUBLISHED",
            "thumbnailUri": null,
            "businessInformation": {
                "businessOwner": "Jane Roe",
                "businessOwnerEmail": "marketing@pizzashack.com",
                "technicalOwner": "John Doe",
                "technicalOwnerEmail": "architecture@pizzashack.com"
            },
            "avgRating": "0.0"
        }
```

### Affected Component

APIM

### Version

4.0.0

**Comment by RakhithaRR** [comment]
Already fixed in the master
