### ISSUE TITLE
Create Dataservice From Datasource

### ISSUE THREAD

**Issue by stefanonegri** [wso2/api-manager#293]
### Description

The functionality 'Create Dataservice from Datasource' in Integration Studio is not working properly

### Steps to Reproduce

- once created the dataservice from a specific Datasource and spwcified a table, when I go in the Data Sources section I see the default data source configured only (the carbon data source) instead of the one selected at the beginning
- I used an Employee table identical to that one in the tutorial [1](https://apim.docs.wso2.com/en/latest/tutorials/integration-tutorials/sending-a-simple-message-to-a-datasource/); while the get and delete resources are fine, the PUT and POST operation are not editable. They are probably corrupted

### Affected Component

IntegrationStudio

### Version

8.1.0

### Environment Details (with versions)

MacOs Monterey 21.2.1

**Comment by SanojPunchihewa** [comment]
For the following issue,

> I used an Employee table identical to that one in the tutorial [1](https://apim.docs.wso2.com/en/latest/tutorials/integration-tutorials/sending-a-simple-message-to-a-datasource/); while the get and delete resources are fine, the PUT and POST operation are not editable. They are probably corrupted

We need to update the docs stating how GET, POST, PUT and DELETE operations are enabled depending on the database properties.
