### ISSUE TITLE
[Application-Token : opaque Token]Gateway is sending an expired backend JWT token to the backend

### ISSUE THREAD

**Issue by cbabey** [wso2/api-manager#2945]
### Description

The gateway is sending an expired backend JWT token to the backend endpoint, causing the endpoint call to fail. Upon investigation, it was found that this issue arises when the API is called using an opaque token (Application Token). 

### Steps to Reproduce

1. Configure the backend endpoint in the APIM to validate the expiry time of the received JWT.
2. Generate an opaque token and invoke the API with high TPS.
3. Occasionally, the APIM will send an expired token to the backend.

### Affected Component

APIM

### Version

4.0.0

**Comment by Tharanidk** [comment]
Hi @piyumaldk ,

Please share the public fix and close this issue.

Regards,
Tharani.

**Comment by piyumaldk** [comment]
Hi @Tharanidk, 

We are still in the process of doing the fix for the latest version. Once it's done, will do the public fix.

Thanks and Regards,
Piyumal

**Comment by piyumaldk** [comment]
Public fix - https://github.com/wso2/carbon-apimgt/pull/12497 (1st commit)
