### ISSUE TITLE
Operation policies are not getting removed from the Publisher

### ISSUE THREAD

**Issue by shavinsenadheera** [wso2/api-manager#2975]
### Steps to reproduce the issue

- Enable the API Level policies as mentioned in the documentation [1].
- Start the APIM Server.
- Go to the Publisher Portal (https://localhost:9443/publisher).
- Create an API with the following details.

<img width="888" alt="Screenshot 2024-06-19 at 10 48 09" src="https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/dede2bf0-bddd-491a-a7da-e7aea2875e47">

- Attach the API and Operations policies to the API as follows.

<img width="937" alt="Screenshot 2024-06-19 at 10 50 22" src="https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/b7119bcf-7362-4add-b2fa-79114c6d4e0e">
<img width="937" alt="Screenshot 2024-06-19 at 10 50 49" src="https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/0ac0dbf0-47ff-4adb-9b73-09d66e009ceb">

- Download the deployed API.

![Screenshot 2024-06-19 at 11 00 34](https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/081389ac-24b4-4422-87a3-6addc5f98cee)

- As you can see the “api.yaml” has the “apiPolicies” and also the “operationPolicies” as well.
<img width="932" alt="Screenshot 2024-06-19 at 11 03 31" src="https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/c122156e-46f3-4706-be3c-e26dfbda53a9">
<img width="932" alt="Screenshot 2024-06-19 at 11 04 23" src="https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/e15ca311-6d24-4161-bf08-a7fcb3a00048">

- I remove both “operationPolicies” and the “apiPolicies” from the “api.yaml” file. Also, remove the “Policies” directory from the API folder as well.

<img width="160" alt="Screenshot 2024-06-19 at 11 06 50" src="https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/a7555671-98a8-4191-9964-8f73bd0a4fc8">
<img width="160" alt="Screenshot 2024-06-19 at 11 07 16" src="https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/5ffb21a3-a6c3-4082-8168-8025be37fb46">
<img width="226" alt="Screenshot 2024-06-19 at 11 08 10" src="https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/11a01fca-a29f-4348-95d6-df46476acd11">

- Compress the API folder in which I have done the above changes and import the API via the following REST API.

```
curl --location --request POST 'https://localhost:9443/api/am/publisher/v4/apis/import?preserveProvider=false&overwrite=true&rotateRevision=true' \
--header 'Authorization: Bearer 1a771dca-d922-3367-aad3-beaa5a53524a' \
--form 'file=@"/Users/shavindusenadheera/WSO2/SUPPORT_TICKETS/FISGLOBALSUB-1165/SETUPS/SampleAPI2-1.0.0.zip"'
```

- Go inside of the API.
- The API Level policies are getting removed.

![Screenshot 2024-06-19 at 11 13 36](https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/232ca17f-610a-4c4c-846a-873527e2dbf0)

- Operation policies are not being removed and can still be seen in the Publisher Portal.

![Screenshot 2024-06-19 at 11 13 43](https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/e012bd30-c77d-42e1-9acf-4e712df0f7d4)

[1] - https://apim.docs.wso2.com/en/4.2.0/design/api-policies/attach-policy/#:~:text=You%20can%20utilize,restart%20the%20server.

### Steps to Reproduce

Mentioned in the description.

### Affected Component

APIM

### Version

4.2.0

**Comment by piyumaldk** [comment]
Public fix - https://github.com/wso2/carbon-apimgt/pull/12497 (2nd commit)
