### ISSUE TITLE
Slow loading on API Resource and Policies in publisher portal

### ISSUE THREAD

**Issue by vikumkbv** [wso2/api-manager#2993]
### Description

Hi Team,

We observed slowness while loading the resources and policies from the publisher portal when there are 100+ resource paths.

![image](https://github.com/wso2-enterprise/wso2-apim-internal/assets/33031034/bb0eb1db-0012-40c3-ae79-f677f9ec24b0)

![image](https://github.com/wso2-enterprise/wso2-apim-internal/assets/33031034/6f9d6e64-f97c-42a4-b014-a35851a1fc42)

Hope this is something that needs to be fixed in the UI component and are looking for your recommendations regarding this issue.

Thanks,
Vikum

### Steps to Reproduce

1. Create API and add 100+ resources
2. Then load the policies page and resource page from the publisher.

### Affected Component

APIM

### Version

4.1.0

**Comment by rmsamitha** [comment]
Closing as this issue was not reproduced from APIM-4.3.0 onwards.
