### ISSUE TITLE
API Endpoint OAUTH2 Password Issue

### ISSUE THREAD

**Issue by SupunTharakaSandaruwan** [wso2/api-manager#30]
### Description:

Identified an issue with securing endpoints with OAuth2.0 while modifying the endpoint security parameters for every API.

### Steps to reproduce:

- Created a mock API as the token API
- Created a testing API and under the endpoint configuration security section added OAuth2.0 endpoint security with Password grant type.
- Saved the changes
- Once the API synapse file of the testing API is investigated, could find that the username and password is stored to a synapse property with base64 encoding and once it is decoded a given username and password could be retrieved.
- Then 
 -- opened the security configurations under the endpoint again through the publisher portal.
 -- did not make any change
 -- clicked on the save button.
- After that, the same synapse property was investigated under the API and could identify the actual password was overwritten by a few * symbols.

### Affected product version:

APIM 3.2.0

**Comment by hisanhunais** [comment]
Issue is not reproducible in master. Hence, closing the issue.
