### ISSUE TITLE
SNI is missing in SSL Endpoint handshake APIM-3.2.1

### ISSUE THREAD

**Issue by janithcmw** [wso2/api-manager#3009]
### Description

The SNI is missing in the endpoint handshake.

### Steps to Reproduce

1. Start the APIM-3.2.1.3 pack with SSL debug logs.
2. Create an API with the endpoint 'google.com'.
3. Invoke the API.
4. Observe the SSL debug logs.

### Affected Component

APIM

### Version

3.2.1

**Comment by RakhithaRR** [comment]
Closing this since the public fix is already available
