### ISSUE TITLE
Third-Party Dependency Upgrades for APIM 4.4.0 Release

### ISSUE THREAD

**Issue by npamudika** [wso2/api-manager#3014]
### Description

This issue is created to track the third party dependency upgrades for the APIM 4.4.0 release.

### Affected Component

APIM

### Version

4.4.0

**Comment by npamudika** [comment]
Need to upgrade tomcat to 9.0.91 or higher - https://github.com/wso2-support/orbit/pull/437

**Comment by npamudika** [comment]
Need to upgrade poi dependencies - https://github.com/wso2/api-manager/issues/2974

**Comment by npamudika** [comment]
Need to upgrade cxf to 3.6.4 or higher - https://github.com/wso2-enterprise/wso2-apim-internal/issues/7232

**Comment by YasasRangika** [comment]
Closing this issue as all vulnerable dependencies have been upgraded and tracked in https://github.com/wso2/api-manager/issues/3105.
