### ISSUE TITLE
Shared scopes shows scope has been used but not showing usage list and not allowing to delete scopes in APIM 4.1.0

### ISSUE THREAD

**Issue by lucas-wso2** [wso2/api-manager#3029]
### Problem

Hello team,

+ Issue:

The customer has a requirement to delete shared scopes from the shared scopes list in the API publisher. However, the delete button is disabled, indicating a number of usages for the scope, but the usage list appears empty when clicked.

+ Steps to Reproduce:

1. Start an APIM 4.1.0 pack and log in to the publisher (tested with admin user).
2. Create multiple shared scopes (e.g., `team:create`, `team:update`) and assign the role of admin.
3. Deploy the Pizza Shack API and assign scopes to deploy the revision.
4. Remove the scopes and deploy a new revision.
5. Go to the resources, remove the scopes, and deploy it again.
6. Go to the shared scope tab and observe the issue mentioned.

+ Conclusion:

This issue appears to be related to revisions. When a new revision is deployed without scopes, references to the scopes remain in previous revisions.

If this is the expected behavior, the system should at least show the APIs and revisions using the scopes.

From local testing, we observed that even after deleting the scopes from previous revisions, it still shows one usage left on the shared scopes page.

Thank you.
Best regards

### Solution

Update to the UI that displays which revision the scope is linked to, making it easier to remove.

### Affected Component

APIM

### Version

4.1.0.133

**Comment by msm1992** [comment]
public PRs : https://github.com/wso2/carbon-apimgt/pull/12452, https://github.com/wso2/apim-apps/pull/704
