### ISSUE TITLE
[Feature] AI API Gateway for WSO2 API Manager

### ISSUE THREAD

**Issue by SavinduDimal** [wso2/api-manager#3034]
### Problem

Organizations face significant challenges in managing multiple AI services, each with different APIs, credentials, and usage patterns. These challenges include:

- Complex Management: Handling diverse AI services from different providers.
- Security and Compliance: Ensuring secure and compliant use of AI services.
- AI Analytics: Having a good insight on AI service usage in the organization.
- Cost Optimization: Managing and optimizing costs associated with AI service usage.
- Integration Complexity: Seamlessly integrating AI capabilities into API flows.
- Performance and Reliability: Ensuring efficient, reliable, and high-performance AI service usage.

### Solution

Enhance the WSO2 API Manager to support and ease AI APIs usage, transforming it into a central hub for managing and consuming cloud-based AI services within organizations. 

### Affected Component

APIM

### Version

4.4.0

**Comment by PasanT9** [comment]
**Meeting Notes**

[UI DESIGN REVIEW] APIM AI Gateway
Thursday, August 8 · 2:45 – 3:45pm
Time zone: Asia/Colombo
Google Meet joining info
Video call link: https://meet.google.com/ujv-snbo-woc
Or dial: ‪(US) +1 530-350-9596‬ PIN: ‪201 604 442‬#
More phone numbers: https://tel.meet/ujv-snbo-woc?pin=8195407594267

- In the API creation part. Use the same API drop downs and add the AI Options under the same sections. Under the REST API section under add a new blade called REST AI APIs. Under the Streaming APIs section add a new blade called REST SSE API.
- Add a new property to recognize Global endpoint configurations. This was missing in the presented UI design pages.
- All the endpoint configurations should only be modified at the global endpoints page.
- In the API Endpoint Configurations, change the endpoint selections to a drop down.
- Do not allow to update endpoints at the API level.
- Need an option to edit resources. Current UI and REST APIs doesn't support this.
- We will need the ability to add more reosurces in the future. Similar to what Kong do. To achieve this we might need to consider attaching endpoints at the resource level. That would means each resource will have different endpoints defined. Ones we send a request to a resource, we will use the llm-header to select the exact endpoint.
