### ISSUE TITLE
Add visibility restrictions in the developer portal based on the Organizations

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/api-manager#3061]
### Problem

Need to restrict API and applications based on the user organization. Refer https://docs.google.com/document/d/1U_rYpwpKyvM_hEzUzUVHJ7Gu-N-xu7Of97r4cRxlMQM/edit

Tasks
- [x] Add the capability to set API’s organization visibility from the publisher portal
- [x] Dev portal search based on organization.
- [x] Resolve user organization when login into the developer portal
- [x] Capability to create Application sharable to the organization.
- [x] Set available organizations for business plans

**Comment by chamilaadhi** [comment]
Initial implementation https://github.com/wso2/carbon-apimgt/pull/12512

This PR set visibility restriction for API using organization and filter API in the dev portal listing page based on the user organization

**Comment by chamilaadhi** [comment]
Add Application sharing for with the organization https://github.com/wso2/carbon-apimgt/pull/12517

**Comment by chamilaadhi** [comment]
Publisher side UI changes to set organization visibility to APIs https://github.com/wso2/apim-apps/pull/729

<img width="937" alt="Screenshot 2024-08-21 at 10 29 39 AM" src="https://github.com/user-attachments/assets/672ecfb3-20d9-45cd-b5e0-7896b895f869">

**Comment by chamilaadhi** [comment]
Add application sharing with the organization https://github.com/wso2/apim-apps/pull/730

<img width="897" alt="Screenshot 2024-08-22 at 10 40 06 AM" src="https://github.com/user-attachments/assets/1a3f2fb1-3df4-44c7-a658-38ff5923e1e5">

**Comment by chamilaadhi** [comment]
Add capability to add organizations to business plans and filter it in the devportal for the API based on user organization https://github.com/wso2/carbon-apimgt/pull/12523

**Comment by chamilaadhi** [comment]
Moving to registry property to store organization information instead of introducing new field to rxt. 
https://github.com/wso2/carbon-apimgt/pull/12528

**Comment by chamilaadhi** [comment]
Since there is a new property added to the API, we need to do a registry resource migration. To prevent this, we could add a default property value to all the migrated API when generating the indexed data. Following PRs do this

https://github.com/wso2/carbon-apimgt/pull/12529
https://github.com/wso2/carbon-registry/pull/441

When migrating to the new version, with this change, we have to do a reindexing only

**Comment by chamilaadhi** [comment]
Setup IS 7.0 with APIM developer portal. IS 7 is setup as a federated authenticator. We need to add custom oidc claims to retrieve organization and organization id since it is not available in APIM

Following flow is configured
<img width="735" alt="Screenshot 2024-09-04 at 5 38 12 PM" src="https://github.com/user-attachments/assets/35ecbd0e-3328-4cc0-af49-cc9a959638f1">

Steps on configuring can be found in https://docs.google.com/document/d/1MpsVrYCL4lT5p6rjB_ViAbU09yCCyzTLuDII9Clcsq0/edit?usp=sharing

**Comment by chamilaadhi** [comment]
Add organization visibility for subscription policy in admin porta

![Uploading Screenshot 2024-09-09 at 2.04.44 PM.png…]()

https://github.com/wso2/apim-apps/pull/738

**Comment by chamilaadhi** [comment]
Pending tasks

- [ ] Dev portal unified search, tag search restrictions based on organization
- [ ] Display Organization information on the dev portal 
- [ ] Keymanager connector changes for applications creation in org space
- [ ] Handle login when JWT is enabled instead of opaque token
- [ ] Organization information sent for analytics
- [ ] Workflows related improvements 
- [ ] Dev portal logout issue when IS 7 is configured as Federated IDP
- [ ] Fix Org feature with application sharing enabled

**Comment by chamilaadhi** [comment]
Show organization name in dev portal UI from https://github.com/wso2/apim-apps/pull/742

<img width="1728" alt="Screenshot 2024-09-13 at 11 07 40 AM" src="https://github.com/user-attachments/assets/ff4f164c-7be9-46c0-8c8a-bb224c9151e6">

**Comment by chamilaadhi** [comment]
Based on the review , moved the org visibility to its own field in publisher portal configuration section https://git
hub.com/wso2/apim-apps/pull/742/commits/cc7cf140b7a7beb129cb8eee93ca55b41d3665d2 

<img width="769" alt="Screenshot 2024-09-18 at 6 10 50 PM" src="https://github.com/user-attachments/assets/20c93e47-a121-4093-87f0-df6045990f53">

Additionally, introduced a config to enable org feature

        [apim.organization_based_access_control]
        enable = true

carbon-apimgt related changes for above two changes https://github.com/wso2/carbon-apimgt/pull/12572

**Comment by chamilaadhi** [comment]
Fix logout issue https://github.com/wso2/apim-apps/pull/751

**Comment by chamilaadhi** [comment]
After discussion, planned to get implement keymanager visibilty based on user organization. This way, we will have to register keymanager per organization.

Backend pr for this https://github.com/wso2/carbon-apimgt/pull/12592

This introduces new table

        CREATE TABLE IF NOT EXISTS AM_KEY_MANAGER_ALLOWED_ORGS (
          KEY_MANAGER_UUID VARCHAR(50) NOT NULL,
          ALLOWED_ORGANIZATIONS VARCHAR(50) NOT NULL,
          PRIMARY KEY (KEY_MANAGER_UUID, ALLOWED_ORGANIZATIONS),
          FOREIGN KEY (KEY_MANAGER_UUID) REFERENCES AM_KEY_MANAGER(UUID) ON DELETE CASCADE
        );

**Comment by chamilaadhi** [comment]
Add keymanager visibility UI https://github.com/wso2/apim-apps/pull/780

<img width="1189" alt="Screenshot 2024-10-04 at 10 44 06 AM" src="https://github.com/user-attachments/assets/92ec7643-a516-430c-9eed-b7f35b25c03e">

**Comment by chamilaadhi** [comment]
Add capability to enable/disable feature https://github.com/wso2/apim-apps/pull/783

config

      [apim.organization_based_access_control]
      enable = true

**Comment by chamilaadhi** [comment]
Refactor business plans https://github.com/wso2/carbon-apimgt/pull/12634

**Comment by chamilaadhi** [comment]
Add capability to use multiple keymanagers with same issuer with https://github.com/wso2/carbon-apimgt/pull/12652

To differentiate the keymanage, Need to configure 'Token Handling Options' section in the keymanager

Ex:
<img width="1090" alt="Screenshot 2024-10-09 at 4 09 13 PM" src="https://github.com/user-attachments/assets/86a4a49b-9b9b-4925-a23b-34069fb46597">

**Comment by chamilaadhi** [comment]
Add support for orgs with spaces in the name
https://github.com/wso2/carbon-apimgt/pull/12653
https://github.com/wso2/apim-apps/pull/791

**Comment by chamilaadhi** [comment]
Fix logout issue for publisher https://github.com/wso2/apim-apps/pull/795

**Comment by chamilaadhi** [comment]
Pending Tasks

- [ ]  Support unified search, definition search, etc and tag listing
- [ ] UI revamp 
- [ ] On the fly migration using CustomAPIIndexer. add default 'all' to the org property in the API
- [ ] Enabling Application sharing feature with org feature
- [ ] Update db schemas for all the database types
- [ ] Handle apictl related scenarios
- [ ] Analytics related data population
- [ ] Integration test and unit test fixing

**Comment by HiranyaKavishani** [comment]
Closing the issue as the pending tasks are added to major task.
