### ISSUE TITLE
Documentation Sorting in APIM 4.1.0 DevPortal

### ISSUE THREAD

**Issue by ug205** [wso2/api-manager#3077]
### Description

The ordering of documentations are deviated from the following list when listed in the Devportal

HOW TO
SAMPLES
PUBLIC FORUM
SUPPORT FORUM
OTHER

### Steps to Reproduce

Create the following kinds of documentations from the Publisher portal per API
HOW TO
SAMPLES
PUBLIC FORUM
SUPPORT FORUM
OTHER

Observe when viewed from the Dev-portal the sorting is changed.

For example 

OTHER
SAMPLES
HOW TO
PUBLIC FORUM
SUPPORT FORUM

### Affected Component

APIM

### Version

4.1.0

**Comment by nisan-abeywickrama** [comment]
Closing issue as PR is merged and issue is fixed
