### ISSUE TITLE
Callback URL textbox is enabled for any grant type

### ISSUE THREAD

**Issue by dilshanfardil** [wso2/api-manager#3088]
### Description

Hi Team,  

We can enter a callback URL in the Dev Portal even when only the client credentials grant type is enabled. While this does not cause any functional issues, we believe it to be a UI issue.

### Steps to Reproduce

1. Start the APIM Manager server
2. Log into Dev Portal
3. Go to Applications -> Production Keys and uncheck all the grant types except the "Client Credentials"
4. Can observe that the "Callback URL" is enabled and can insert a value
5. Insert a value and click "Generate Keys"
6. Can observe that the callback URL is successfully saved

### Affected Component

APIM

### Version

3.1.0

**Comment by Oshanath** [comment]
Closing this issue as the fix is already available in public.
