### ISSUE TITLE
Persisted aggregation improvements

### ISSUE THREAD

**Issue by PrabodDunuwila** [wso2/api-manager#3113]
### Problem

Develop APIM-analytics 2.6.0 product with the persisted aggregation improvements.

### Solution

Add persisted aggregation improvements.

### Affected Component

Analytics

### Version

2.6.0

**Comment by nisan-abeywickrama** [comment]
Requested peer test for applicable products from IAM, OB and EI teams.

**Comment by nisan-abeywickrama** [comment]
The optimisation is available in the latest version.
