### ISSUE TITLE
[APIM 4.1.0] Problems Arising from Nested Schemas in API Product Creation

### ISSUE THREAD

**Issue by SameeraSI** [wso2/api-manager#3132]
### Description

Hi Team,

When an API product is created using a resource of an API that includes a nested schema (where one schema references another), the referenced schema is excluded from the API product’s definition, leading to an faulty API product definition.

Thanks,
Sameera

### Affected Component

APIM

### Version

4.1.0

**Comment by hisanhunais** [comment]
The fix has been done via [1]. Hence, closing the issue.

[1] https://github.com/wso2/carbon-apimgt/pull/12694
