### ISSUE TITLE
UI bugs in publisher portal when read-only user logged in

### ISSUE THREAD

**Issue by BiyonFernando** [wso2/api-manager#3150]
### Description

In read-only mode the following UI bugs are identified in publisher portal

1. API Product menu item in nav bar doesn't appear in read-only mode
<img width="493" alt="image" src="https://github.com/user-attachments/assets/9e1071b0-483c-4c6c-9688-7f6a93eb42fe">

2. In try-out section of publisher portal the API resources are not loaded. The UI is stuck with a loading spinner. 
<img width="493" alt="image" src="https://github.com/user-attachments/assets/2a92ee14-6c81-471c-afc8-572d04718204">

### Steps to Reproduce

step 1 - log into carbon portal and create a user with only internal/observer and internal/everyone (read-only user)
step 2 - log into publisher portal as admin, create pizzashack API and log out
step 3 - log into publisher portal with read-only user

1. API Product menu item in nav bar doesn't appear in read-only mode
> step 4 - Click the hamburger icon on left 

2. In try-out section of publisher portal the API resources are not loaded. The UI is stuck with a loading spinner. 
> step 4 - click on pizzashack API and click try-out tab in the left menu

### Affected Component

APIM

### Version

4.4.0-alpha

**Comment by ashera96** [comment]
When logged into the Publisher portal with a user that has `Internal/creator` role, the api-products page crashes if there are no available API Products.

<img width="1426" alt="image" src="https://github.com/user-attachments/assets/88e6b1fb-1103-4a07-ab9d-a244ae805f1b">

Also, in a scenario where there are API Products, when clicked on `Create an API Product` button, the user is getting redirected to the `APIs` tab. Ideally that button should be disabled for users who does not have the necessary privileges to create an API product.
