### ISSUE TITLE
General Endpoint Configurations: Certificates

### ISSUE THREAD

**Issue by kajal1410** [wso2/api-manager#3167]
### Description

Hi team,

In distributed setup or in active-active deployment, when we update endpoint certificate from publisher portal of node 1 it should be reflected to the another node.
Also it will be pesisted in client-truststore and AM_CERTIFICATE_METADATA table of apim_db.
But we have observed below behaviour in active-active deployment and distributed setup of APIM:4.1.0
For Node1:
Publisher portal UI: Certificate details is their as shown in below image.
<img width="1397" alt="publisher1_view" src="https://github.com/user-attachments/assets/e612bc48-5097-4df2-9948-e297bd417c3b">

client-truststore: Certificate with specified alias is present in both client-truststore.jks and client-truststore-temp.jks.

For Node2:
Publisher portal UI: For certificate details it is showing null as shown in below image.
<img width="1357" alt="publisher2_view" src="https://github.com/user-attachments/assets/65524e16-8e63-4a40-80dd-e430bbab877c">

client-truststore: Certificate with specified alias is not present in client-truststore.jks but it is there in client-truststore-temp.jks.

Database Check:
Certificate is present in AM_CERTIFICATE_METADATA table with specified alias.

### Steps to Reproduce

1. Configuring an Active-Active Deployment using [document](https://apim.docs.wso2.com/en/4.1.0/install-and-setup/setup/single-node/configuring-an-active-active-deployment/).
2. Create one API and add endpoint certificate by following steps in the [document](https://apim.docs.wso2.com/en/4.1.0/design/endpoints/certificates/#adding-a-certificate-for-an-endpoint).
3. Verify by login to another node publisher portal.

### Affected Component
APIM

### Version
4.1.0

Thanks & Regards,
Kajal

**Comment by Oshanath** [comment]
Closing the issue as the fix is already available in public.
