### ISSUE TITLE
Minor Bug on Setting API level logs

### ISSUE THREAD

**Issue by piyumaldk** [wso2/api-manager#3169]
### Description

When setting API logs [1] using below call,

```
curl -X PUT 'http://<HOST_NAME>:<PORT>/api/am/devops/v0/tenant-logs/{tenant-domain}/apis/{api-id}' -H 'Authorization: Basic <base64Encode(username:password)>' -H 'Content-Type: application/json' -d '{"logLevel": "<logLevel>"}' -k
```

However even if we did not had the right tenant in {tenant-domain} and add a wrong tenant, if API Manager cannot find a right tenant on that name, it updates the carbon.super's API if ID is right.

This is not actually a major bug, but will report this for future references.

[1] https://apim.docs.wso2.com/en/latest/observe/api-manager/monitoring-api-logs/

### Steps to Reproduce

```
curl -X PUT 'http://<HOST_NAME>:<PORT>/api/am/devops/v0/tenant-logs/{tenant-domain}/apis/{api-id}' -H 'Authorization: Basic <base64Encode(username:password)>' -H 'Content-Type: application/json' -d '{"logLevel": "<logLevel>"}' -k
```

### Affected Component

APIM

### Version

4.3.0

**Comment by Piumal1999** [comment]
Hi @piyumaldk ,
I couldn't reproduce this error. Could you please check it again and verify?

**Comment by AnuGayan** [comment]
This issue is reproducing in beta pack
