### ISSUE TITLE
Introduce a common config to enable SHA-256 across the product

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/api-manager#3172]
### Description

We have introduced SHA-256 support in APIM with https://github.com/wso2/api-manager/issues/2848. But to complete enable S256 hashing everywhere, we need to set multiple configurations in the toml. We need to introduce a common config and infer rest of the configurations for the sake of ease.

### Steps to Reproduce

Enable S256 product-wide

### Affected Component

APIM

### Version

4.4.0

**Comment by AnuGayan** [comment]
Added a property to enable sha256 globally by https://github.com/wso2/carbon-apimgt/pull/12672/files#diff-088555df3dd2624705c4194a56fb6b0cba1f52ba32ec535c8ecfd8deb9065e24R35. But all the configurations has not been refered for this yet untill we can enable SHA-256 by default for all the other scenarios
