### ISSUE TITLE
Failed to generate keys with IS 6.1 Key Manager

### ISSUE THREAD

**Issue by piyumaldk** [wso2/api-manager#3174]
### Description

Failed to generate keys in the application with IS 6.1 Key Manager

### Steps to Reproduce

Follow - https://apim.docs.wso2.com/en/4.3.0/administer/key-managers/configure-wso2is-connector/

Try to generate a key using created KM

### Affected Component

APIM

### Version

4.4.0

**Comment by RakhithaRR** [comment]
The issue cannot be reproduced
