### ISSUE TITLE
Cannot subscribe to a Pre-Released API/API Product from the Application's Subscription page

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/api-manager#32]
### Description:
Pre-Released APIs/API Products are not getting listed in the Application's Subscription page

### Steps to reproduce:
1. Sign in to the Publisher Portal and create a Pre-Released API/API Product.
    ![image](https://user-images.githubusercontent.com/25246848/165452559-1de98c98-ba1d-414a-a759-e80451f07ae2.png)
    ![image](https://user-images.githubusercontent.com/25246848/165452591-1d228d3e-472b-402f-908a-b3cb1248d9ff.png)
2. Go to the Developer Portal, and you can see that those are listed there.
    ![image](https://user-images.githubusercontent.com/25246848/165452502-b8f94b67-0c8f-40ad-abc9-b43d9d53c215.png)
3. Create a new application and go to the Subscriptions page of that.
4. Click on SUBSCRIBE APIS and you can notice that the Pre-Released APIs/API Products are not getting listed there.
    ![image](https://user-images.githubusercontent.com/25246848/165452838-2e009b92-ca65-4766-8f1f-2fa7a11922ed.png)

**Comment by shnrndk** [comment]
Fixed already
