### ISSUE TITLE
[AI API] API download and export/import related errors 

### ISSUE THREAD

**Issue by ashera96** [wso2/api-manager#3200]
### Description

The downloaded and exported (using APICTL) AI API contains an encrypted value as the key under `api.yaml` file.

```
    endpoint_security:
      sandbox:
        apiKeyValue: <encrypted value>
```

When trying to import the exported AI API using APICTL, we are trying to encode this key value assuming that it is not already encrypted at [1].

We need to fix this behavior so that either we export an un-encrypted value, so that import will work as is. If not, we have to export an encrypted value and import flow should assume the value that is being passed is already encrypted.

[1] https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1.common/src/main/java/org/wso2/carbon/apimgt/rest/api/publisher/v1/common/mappings/PublisherCommonUtils.java#L1147-L1148

### Steps to Reproduce

- Create, deploy and publish an AI API
- Download the API using either or both of these options:

> - Download the created API using the Publisher portal UI
> - Also exported the created AI API using APICTL

- Attempt to import the AI API using either or both of these options:

> - Import using API import REST API
> - Import AI API using APICTL

### Affected Component

APIM

### Version

4.4.0

**Comment by AnuGayan** [comment]
This is the expected behavior
