### ISSUE TITLE
MistralAI AI API tryout returns 401 error

### ISSUE THREAD

**Issue by Piumal1999** [wso2/api-manager#3204]
### Description

When following the tutorial in [1] to create an AI API with MistralAI, the tryout doesn't work and returns 401 Unauthenticated errors with a 'Bearer token not found' error message.

<img width="822" alt="image" src="https://github.com/user-attachments/assets/9de7aab4-eb20-4c59-ba8d-75533984a037">

The same issue occurs with the OpenAI API as well. Maybe some steps are missing in the documentation.

[1] https://apim.docs.wso2.com/en/4.4.0/design/create-api/create-ai-api/create-an-ai-api/

### Steps to Reproduce

follow the above mentioned tutorial and tryout any of the endpoints.

### Affected Component

APIM

### Version

4.4.0

### Environment Details (with versions)

MacOS 
Chrome

**Comment by RakhithaRR** [comment]
You need to add the Bearer keyword as well when adding endpoint security for AI APIs
