### ISSUE TITLE
CPU Spin Issues with APIM in Latest JDK and HTTP Core

### ISSUE THREAD

**Issue by Nirothipan** [wso2/api-manager#321]
### Description

$subject

### Steps to Reproduce

Please refer 

1. https://github.com/wso2/api-manager/issues/320
2. https://github.com/wso2/product-apim/issues/11954
3. https://github.com/wso2/api-manager/issues/325
4. https://github.com/wso2/api-manager/issues/326
5. https://github.com/wso2/api-manager/issues/341
6. https://github.com/wso2/api-manager/issues/522
7. https://github.com/wso2/api-manager/issues/199

**Comment by rosensilva** [comment]
Closing as all the sub-tasks are completed
