### ISSUE TITLE
Publisher Try out resources section keeps loading for observer

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#3211]
### Description

When trying to access the Publisher Try out console by an Observer user, the resources section keeps loading as follows. The reason is a 401 for generating keys. We can stop showing the loading icon for observer if possible.

<img width="1512" alt="Screenshot 2024-10-08 at 11 03 47" src="https://github.com/user-attachments/assets/43b8f170-b275-42b4-b8ef-492ad44c8b0f">

### Steps to Reproduce

1. Create a user with observer role through the management console.
2. Login to publisher and create an API using Admin or a privileged user.
3. Now login to Publisher with the observer user.
4. Access the Try out page.

### Affected Component

APIM

### Version

4.4.0

**Comment by AnuGayan** [comment]
Fixed by https://github.com/wso2/apim-apps/pull/786
