### ISSUE TITLE
Admin portal Key Managers page UI issue

### ISSUE THREAD

**Issue by ashera96** [wso2/api-manager#3215]
### Description

Admin portal Key Managers tab related UI issue.

### Steps to Reproduce

- Visit the Admin portal
- Navigate to the Key Managers tab
- Configure the global key manager by following along the documentation [1]
- On creation, the following UI appears which has a chip alignment issue. However, this issue occurs only for smaller screen sizes (MacBook Air's default screen size shows this UI)

<img width="1153" alt="Screenshot 2024-10-08 at 12 31 05" src="https://github.com/user-attachments/assets/1f517a3a-957a-401d-9573-a00072774710">

[1] https://apim.docs.wso2.com/en/latest/administer/key-managers/configure-global-key-manager/

### Affected Component

APIM

### Version

4.4.0

**Comment by AnuGayan** [comment]
Fixed by https://github.com/wso2/apim-apps/pull/786
