### ISSUE TITLE
Multiple UI issues in Publisher portal

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/api-manager#3216]
### Description

The Visibliity in Devportal info icon is missing

<img width="462" alt="Screenshot 2024-10-08 at 12 01 36" src="https://github.com/user-attachments/assets/ee7acac3-c34e-40e7-8ee3-a8629d63c818">

`+` sign is not centered properly 

<img width="583" alt="Screenshot 2024-10-08 at 12 02 09" src="https://github.com/user-attachments/assets/a581d6fe-7a8e-4b81-8ea9-9eb40ad83221">

### Steps to Reproduce

.

### Affected Component

APIM

### Version

4.4.0

**Comment by Krishanx92** [comment]
<img width="1728" alt="Screenshot 2024-10-08 at 14 40 35" src="https://github.com/user-attachments/assets/a293a9d3-56c4-449c-8391-a166b0472ee7">
