### ISSUE TITLE
API Configuration Local Scopes page crashes

### ISSUE THREAD

**Issue by Piumal1999** [wso2/api-manager#3220]
### Description

The local scopes page crashes when the steps below are followed.

<img width="80%" alt="image" src="https://github.com/user-attachments/assets/b8d9b4aa-b251-4269-97e3-b82396373008">

<img width="80%" alt="image" src="https://github.com/user-attachments/assets/a5e99836-f884-44b7-b9db-6dd82ce00ed9">

---

Sometimes, the stacktrace is different:
<img width="80%" alt="image" src="https://github.com/user-attachments/assets/efdce510-4a28-496c-9904-19fe49042aa8">

### Steps to Reproduce

1. Create an deploy an API (use the PizzaShack API)
2. Go to local scopes and add a new local scope
3. Go to policies page
4. Go back to the local scopes page

### Affected Component

APIM

### Version

4.4.0

### Environment Details (with versions)

Distributed setup

**Comment by lasanthaS** [comment]
Fixed in https://github.com/wso2/apim-apps/pull/798
