### ISSUE TITLE
Application Sharing Failed in Distributed Setup 

### ISSUE THREAD

**Issue by DivyaPremanantha** [wso2/api-manager#3230]
### Description
In a distributed setup Application sharing feature is not working.

Note: This is an issue only in the distributed setup, locally this feature is working fine
Doc reference: https://apim.docs.wso2.com/en/latest/consume/manage-application/sharing-applications/sharing-applications/

### Steps to Reproduce

1. Create a tenant
2. Create User1 in Org1
3. Sign in to the devportal as User1
4. Create an Application in Org1 and logout
5. Create User2 in Org1
6. Sign in to the devportal as User2
8. The Application created by User1 is visible to User2 but it is not accessible, no changes can be made to this application by User2

### Affected Component

APIM

### Version

4.4.0

### Environment Details (with versions)

Distributed Setup

**Comment by PasanT9** [comment]
Hi @DivyaPremanantha,

This is the default behavior as only the owner of the application can update an application. The same behavior can be seen in both in all-in-one and distributed setups.
