### ISSUE TITLE
JSON Schema Validation Fails in Distributed Setup

### ISSUE THREAD

**Issue by DivyaPremanantha** [wso2/api-manager#3231]
### Description

JSON Schema Validation Fails in Distributed Setup. This is working fine in the local setup.

Doc: https://apim.docs.wso2.com/en/latest/design/api-security/api-request-response-schema-validation/json-schema-validator/

### Steps to Reproduce

1. Sign in to the API Publisher Portal.
2. Click on the API for which you need to enable JSON validation.
3. Click API Configurations.
4. Click Runtime.
5. Enable Schema Validation.
6. Try invoking the API with an invalid type in the payload, (Ex: for PizzaShackAPI invoke the POST /order API with a string for the quantity) 
```
{
  "customerName": "Divya",
  "delivered": true,
  "address": "No 15, Colombo",
  "pizzaType": "Veg",
  "creditCardNumber": "12345",
  "quantity": "Test",
  "orderId": "12345"
}
```
7. Expected a schema validation failed response but the request sent a successful response

### Affected Component

APIM

### Version

4.4.0

### Environment Details (with versions)

Distributed Setup

**Comment by PasanT9** [comment]
Hi @DivyaPremanantha,

The payload you provided correctly fails the schema validation and returns the following error in the distributed setup.

```
{
  "code": "400",
  "message": "Bad Request",
  "description": "Schema validation failed in the Request: [Path '/quantity'] Instance type (string) does not match any allowed primitive type (allowed: [\"integer\",\"number\"]), "
}
```

Will close the ticket. Please reopen if the issue persist for you.
