### ISSUE TITLE
[Publisher Portal] Add proper error handling for API thumbnail upload failure

### ISSUE THREAD

**Issue by ashera96** [wso2/api-manager#3243]
### Description

When attempting to add a thumbnail to an API using an image exceeding the allowed file size, UI shows no error message.

### Steps to Reproduce

1. Create an API and navigate to the `Basic Info` tab under `Portal Configurations`
2. Click the edit icon to upload your own thumbnail
3. You will then be navigated to the below UI. Click on `Click or drag the image to upload.` and upload an image exceeding 1MB. Notice how the UI shows no error message in this scenario.
 
<img width="1416" alt="image" src="https://github.com/user-attachments/assets/b31ebb0f-9fd9-40bc-a536-2c10bb480ba4">

### Affected Component

APIM

### Version

4.4.0

**Comment by lasanthaS** [comment]
Fixed by https://github.com/wso2/apim-apps/pull/798
