### ISSUE TITLE
Async API Definition goes missing when creating a new version if the original API has been updated

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#3247]
### Description

Async API Definition goes missing when creating a new version of an Async API if the original API has been updated. This is the same for any Async type API (Websocket, Websub etc.). The `asyncapi.json` file is missing when checked through the Management console.

The Async API Definition window of the newly created version is seen as follows.
<img width="1512" alt="Screenshot 2024-10-11 at 15 21 01" src="https://github.com/user-attachments/assets/0a5e2897-49c2-4d05-bc4b-95f8053a9d10">

And the Topics page is seen loading like below.
<img width="1512" alt="Screenshot 2024-10-11 at 15 22 08" src="https://github.com/user-attachments/assets/944ec619-b9d7-49d1-8202-03e10418e9dd">

Both the above issues are the result of the missing asyncapi.json file.

### Steps to Reproduce

1. Create a websocket API (Can be any async api type) - **Do not publish it**.
2. Save the API by navigating to the `Basic Info` page.
3. Then create a new version from this API.
4. Access the `Async API Definition` and `Topics` pages of the newly created API version.

### Affected Component

APIM

### Version

4.4.0

**Comment by RakhithaRR** [comment]
Could be related to https://github.com/wso2/api-manager/issues/2899
