### ISSUE TITLE
Test Postgres 17 compatibility 

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/api-manager#3260]
### Problem

Need to test APIM 4.4.0 compatibility with Postgres 17

### Affected Component

APIM

### Version

4.4.0

**Comment by dakshina99** [comment]
I tested APIM 4.4.0 Beta with PostgreSQL 17, using the existing PostgreSQL database scripts and JDBC driver version 42.7.4. The tests were successful, and APIM 4.4.0 is confirmed to work with PostgreSQL 17 without any issues. Therefore, this issue can be closed.
