### ISSUE TITLE
[Publisher Portal] Local Scopes page crashes when navigating from Policies page

### ISSUE THREAD

**Issue by ashera96** [wso2/api-manager#3275]
### Description

The `Local Scopes` page crashes with the below error message when navigating from the `Policies` tab. Also, this behavior was noticed for users with `Internal/creator` role. Note that this was not reproducible when logged in as an admin user (checked in both super tenant and tenant flows)

<img width="1428" alt="image" src="https://github.com/user-attachments/assets/31932c57-317e-4d65-881c-15f156b34421">

### Steps to Reproduce

1. Create a new user with `Internal/creator` role (say creator)
2. Login to Publisher portal with the newly creator user (login with creator user)
3. Create an API and navigate to `Policies` page
4. Now navigate to `Local Scopes` page
5. Notice how the page crashes in this instance. However, this is not the case if the logged-in user is an admin. Also, this behaviour is not observed if navigated to the `Local Scopes` page from any other tab other than `Policies`.

### Affected Component

APIM

### Version

4.4.0

**Comment by AnuGayan** [comment]
Already fixed by https://github.com/wso2/apim-apps/pull/798
