### ISSUE TITLE
Internal Server Error When the Response Body is Empty for the AI API Chat Resource Invocation

### ISSUE THREAD

**Issue by dakshina99** [wso2/api-manager#3285]
### Description
When making a request to the AI API chat resource, an internal server error (HTTP 503) occurs when the response body is empty. This behavior is unexpected, as the server should handle empty responses gracefully rather than returning a 503 error.

<img width="1278" alt="image" src="https://github.com/user-attachments/assets/0b1f7594-ab32-4bb8-9b65-f88d7c55fdd0">

### Steps to Reproduce

1. Make a request to the MistralAIAPI chat resource for the default given parameters.
2. Ensure that the server sends an empty response body.

### Affected Component

APIM

### Version

4.4.0

**Comment by AnuGayan** [comment]
This cannot be fixed as this is coming from the backend.
