### ISSUE TITLE
Can invoke Production with Sandbox key and visa versas

### ISSUE THREAD

**Issue by ashera96** [wso2/api-manager#3289]
### Description

Can invoke Production key type with a sandbox token and visa versa

### Steps to Reproduce

1. Create and publish an API from the Publisher Portal
2. Login to the Developer Portal and create a new application (say App)
3. Generate Sandbox keys to get an access token
4. Subscribe to the newly created API
5. Navigate to the API and try to invoke it by specifying the key type as Production
6. Paste in the token that was generated from step 3 and invoke the API

<img width="1426" alt="image" src="https://github.com/user-attachments/assets/ad8a5191-e245-47d6-b7af-a8a33bd7d30d">

Notice how the API invocation is successfully done.

### Affected Component

APIM

### Version

4.4.0

**Comment by RakhithaRR** [comment]
This is working as expected. This observation could be due to the fact that the same endpoint was used for both Production and Sandbox endpoints
