### ISSUE TITLE
Log improvements to the JMS connection between the GW and the TM

### ISSUE THREAD

**Issue by charithjayasanka** [wso2/api-manager#3323]
### Problem

Hi Team,

Request for addition of the following JMS logs to identify the traffic manager which gets connected to the Gateways.

1. Log the connected TM server over the JMS connection during the start-up of the GW server.
2. Log the failover scenarios.

Thanks & regards,
Charith

### Solution

Logging the Traffic manager which has connected upon Gateway start & log the traffic manager which has been connected upon a fail over scenario 

### Affected Component

APIM

### Version

3.2.1

**Comment by hisanhunais** [comment]
The fix is available from andes version 3.3.34. Need to bump andes version in product-apim
