### ISSUE TITLE
Status 404 with default APIs In APIM-4.0.0

### ISSUE THREAD

**Issue by NishanthiWi** [wso2/api-manager#3364]
### Description

The default version of the API fails to work when a similar pattern to the version is present in the API context.

### Steps to Reproduce

Create an API with 

- context = test/1234/abc
- version = 1

### Affected Component

APIM

### Version

4.0.0

**Comment by lahirugmg** [comment]
Team,

We have a request from the customer to check on possibility of getting this Best Case Estimate: 2024-11-28 provided in the ticket.

Thanks.
