### ISSUE TITLE
[APIM4.0.0] Missing j2 template for HttpCoreNIOSender configuration

### ISSUE THREAD

**Issue by LayaniMal** [wso2/api-manager#358]
### Description

Need to add a j2 template to configure the HttpCoreNIOSender configuration in the axis2.xml file.

### Steps to Reproduce

- Try to configure the below HttpCoreNIOSender in deployment.toml file.

```
<transportSender name="http" class="org.apache.synapse.transport.nhttp.HttpCoreNIOSender">
        <parameter name="non-blocking" locked="false">true</parameter>
        <parameter name="http.proxyHost" locked="false">****</parameter>
        <parameter name="http.proxyPort" locked="false">****</parameter>
    </transportSender>
```

- No j2 template in axis2.xml.j2 file.

### Affected Component

APIM

### Version

4.0.0

### Related Issues

https://github.com/wso2-enterprise/wso2-apim-internal/issues/229

**Comment by Nirothipan** [comment]
ETA information for the fix will be as follows.

Product: wso2am 4.0.0 full
Public git issue: https://github.com/wso2/api-manager/issues/358
Best Case Estimate: 2022-07-14
Most Likely Estimate: 2022-07-18
Worst Case Estimate: 2022-07-22
