### ISSUE TITLE
Review Publisher UI changes

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#378]
### Description

This is a modification to the Enhanced hybrid approach discussed during a previous review in https://github.com/wso2/api-manager/issues/323. This addresses few User Experience issues.

[EndpointPageUI4.pdf](https://github.com/wso2/api-manager/files/9083362/EndpointPageUI4.pdf)

**Comment by tharikaGitHub** [comment]
At the review it was decided to move ahead with the previous design - **Enhanced hybrid approach.**
[Endpoint Page UI 2 - Page 1.pdf](https://github.com/wso2/api-manager/files/9127030/Endpoint.Page.UI.2.-.Page.1.pdf)
