### ISSUE TITLE
Adding an extension point for REST API authentication

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/api-manager#399]
### Problem

When trying to invoke RESTful APIs available in APIM-4.0.0 using an access token received from the IS(A third party Key Manager), getting the below error response even with the correct scopes in place. 

```
{
    "code": 401,
    "message": "",
    "description": "Unauthenticated request",
    "moreInfo": "",
    "error": []
}
```

Further, we found out that when we invoke the RESTful APIs with a token obtained from IS, it checks if the token is available on the APIM side and not from the IS side. This isn't an issue if we have WSO2AM_DB shared with IS, but in this case, the IS is configured as a 3rd party KM, in which we don't share any DBs with IS. 

### Solution

Need to implement an extension point which would allow accessing APIs with an access token generated from third party Key managers.

### Affected Component

APIM

### Version

4.0.0

### Implementation

Create a base interface and use that as an extension point to implement the default and third party KM authentications

### Related Issues

https://github.com/wso2-enterprise/choreo/issues/4453

**Comment by tgtshanika** [comment]
Master fix https://github.com/wso2/carbon-apimgt/pull/11443
