### ISSUE TITLE
'ORA-01722: invalid number' when creating an API revision

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/api-manager#405]
### Description

The below error is throwing when creating a new API revision with Oracle DB in the APIM v4.0.0.124 U2 level.
```
Error while adding new API Revision for API : xxxx"
ORA-01722: invalid number
```

It is trying to retrieve the relevant client certificate details via the below query and while executing the query above error is thrown.
```
SELECT ALIAS, CERTIFICATE,TIER_NAME FROM AM_API_CLIENT_CERTIFICATE WHERE API_ID = '?' AND REVISION_UUID='Current API' AND REMOVED='FALSE';
```

This is due to a difference between the data type of the 'REMOVED' column between the Oracle script and other scripts(ex: h2, MySQL)

Oracle:
```
REMOVED INTEGER DEFAULT 0 NOT NULL,
```

H2:
```
REMOVED BOOLEAN NOT NULL DEFAULT 0,
```

### Steps to Reproduce

- Config the APIM 4.0.0.124 with Oracle DB
- Enable Mutual SSL with client certificate
- Add a new revision and deploy the API

### Affected Component

APIM

### Version

4.0.0

**Comment by prasa7** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/11652/files
