### ISSUE TITLE
Generate API Documenetation portal automatically from the OpenAPI deefinition

### ISSUE THREAD

**Issue by tmkasun** [wso2/api-manager#420]
### Problem

Users must provide the documentation content to show them up in the developer portal. This feature aims to provide automatic documentation generation capability to developer portal

- [ ] #482
- [ ] #483
- [ ] #484
- [ ] #485
- [ ] #486
- [ ] Implementing automatic documentation generation for OpenApi specifications
- [ ] Implementing automatic documentation generation for AsyncApi specifications
- [ ] Implementing automatic documentation generation for Graphql SDL 
- [ ] Implementing automatic documentation generation for WSDL
- [ ] Documentation for 

automatic generation feature

### Solution

Some example libraries

- https://github.com/Redocly/redoc
- https://github.com/slatedocs/slate
- https://github.com/stoplightio/elements
- https://github.com/facebook/docusaurus
- https://github.com/Azure/API-Portal
- https://github.com/yosriady/api-development-tools#api-developer-portal

### Affected Component

APIM

@chanikag Thanks for breaking up into tasks and organizing the GitHub issue 🙇🏼‍♂️

**Comment by tmkasun** [comment]
We could evaluate this library too https://github.com/hoppscotch/hopp-doc-gen

**Comment by tmkasun** [comment]
sample design for new doc page in publisher 
@chanaka3d any comments ?

![image](https://user-images.githubusercontent.com/3313885/180429222-385907c3-27de-47b3-8cc1-0ebd14ef645c.png)

source: https://excalidraw.com/#json=i0pwM7dszKQAOPeAW0hN_,39QFBdIz-541-m3_58oOGw

**Comment by rmsamitha** [comment]
@Kirishikesan Let's update each subtask(git issues) with descriptions while you are working on each.
And also keep sub tasks opened for the tasks that we decided as to-do in post-4.2.0 releases.

**Comment by Kirishikesan** [comment]
@chanaka3d @tmkasun 
Sample design for Publisher portal and Developer portal. Any comments?

![GenerateDocumentV4](https://user-images.githubusercontent.com/46290313/188855994-52361262-bc50-4539-ab2b-485a136f23d7.png)

![GenerateDocumentDevportalV4](https://user-images.githubusercontent.com/46290313/188855902-44e0f245-c5a5-4178-8257-a95b1df80d6d.jpeg)

**Comment by tharikaGitHub** [comment]
Closing as the feature is completed with the required tasks.
