### ISSUE TITLE
[APIM4.0.0] Regexp in Callback URLs

### ISSUE THREAD

**Issue by LayaniMal** [wso2/api-manager#43]
### Description:
Callback URLs are not accepted as valid URLs when trying to use the regexp in the Devportal Applications.

### Steps to reproduce:

- Log in to the APIM 4.0.0 Devportal and create a new Application.
- Enable Authorization code grant type
- Add Callback URL with regexp format
>  regexp=(http://localhost:4200/cadaahome|http://localhost:4200/home)

### Affected product version:
API Manager 4.0.0

**Comment by dushaniw** [comment]
same as https://github.com/wso2/product-apim/issues/11252

**Comment by dushaniw** [comment]
fixed with https://github.com/wso2/apim-apps/pull/11/files
