### ISSUE TITLE
Required to disable the access logs for the HTTP Servlet transport via a deployment.toml configuration. 

### ISSUE THREAD

**Issue by cbabey** [wso2/api-manager#449]
### Problem

We will be required to disable the access logs for the HTTP Servlet transport, especially in the gateway profile. However, there is no specific deployment.toml configuration to disable access logs for the HTTP Servlet transport.

### Solution

According to “org.apache.catalina.valves.AccessLogValve” valve definition, we identified that it has a modifier/parameter enabled="false" to disable this component.

```
<Valve className="org.apache.catalina.valves.AccessLogValve" directory="/repository/logs"
                       prefix="http_access_" suffix=".log" pattern="%h %l %u %t %r %s %b %{Referer}i %{User-Agent}i %T" enabled="false"/>
```

Can you provide a .j2 mapping  (introduce new deployment.tom configuration) for the enabled parameters to disable the access logs for the HTTP Servlet transport. 

### Affected Component

APIM

### Version

4.0.0

**Comment by tgtshanika** [comment]
This has been fixed with https://github.com/wso2/product-apim/pull/13082
