### ISSUE TITLE
Redirecting issue on logout when using OKTA as external IDP on APIM 4.1.0

### ISSUE THREAD

**Issue by nuwankng** [wso2/api-manager#452]
### Description

Hi,

I have followed the documentation to setup OKTA as OIDC identity provider for the version of APIM 4.1.0. Although login process completed as expected, logout process gets redirected back and fourth between APIM and OKTA. OKTA has been configured as the External IDP in the OIDC protocol following the documentation. [1].

Attached below is the network trace of the troublesome scenario.

[1]. https://apim.docs.wso2.com/en/latest/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc/

Thanks,
NuwanK

### Steps to Reproduce

- Setup OKTA as OIDC Identity provider for the APIM 4.1.0.
- Set developer or publisher portal to be authenticated via OKTA.
- Login to one of the portal.
- Logout from the portal and observe the behaviour

[4.1.0oktaIDP.har.zip](https://github.com/wso2/api-manager/files/9094686/4.1.0oktaIDP.har.zip)

### Affected Component

APIM

### Version

4.1.0

### Suggested Labels

APIM

**Comment by 1akshitha** [comment]
Closing the issue as the update is released and the fix is merged.
