### ISSUE TITLE
Problem with deploying artifact to EI6.6 remote server via Integration studio

### ISSUE THREAD

**Issue by nelkon** [wso2/api-manager#495]
### Description

Cannot deploy Artifacts for the EI remote servers (EI6.6.0) After removing from endores.dir flag from integration studio 8.1 - 'publishing to WSO2 Server Error'

### Steps to Reproduce

1. Add a remote server instance in Integration Studio[i].
2. Remove endores.dir flag from VM arguments in the server (in run configuration)
3. Start the remote server instance
4. Deploy/Redeploy the Artifacts to the added remote instance.

[i] https://ei.docs.wso2.com/en/7.2.0/micro-integrator/develop/using-remote-micro-integrator/

### Affected Component

IntegrationStudio

### Version

8.1

### Environment Details (with versions)

Reproducible with Windows. Mac and linuxLinux environments.

<img width="1728" alt="180143890-68b0ec07-563c-410e-b3e0-8597c39392a5" src="https://user-images.githubusercontent.com/32818289/180365637-d8e54484-bc20-46a2-b8e4-f61a89e1a891.png">

### Related Issues

Related git issue for MI servers: https://github.com/wso2/integration-studio/issues/875

### Suggested Labels

IntegrationStudio

**Comment by rosensilva** [comment]
PR: https://github.com/wso2/integration-studio/pull/1183
