### ISSUE TITLE
Unable to map the fields in the data mapper mediator after changing schema type from 'null' to other type

### ISSUE THREAD

**Issue by Thidasala** [wso2/api-manager#501]
### Description

When we use json to xml mapping in the data mapper mediator, if there is a field with 'null' schema type in the input json, and if we change the schema type to other (Ex: string/number/boolean), mapping arrow is not visible in the runtime (we need to close and reopen the entire mapping diagram to do the mapping after the schema type is changed from 'null' to other type)

### Steps to Reproduce

N/A

### Affected Component

IntegrationStudio

### Version

8.1.0

**Comment by Tharsanan1** [comment]
PR: https://github.com/wso2/integration-studio/pull/1140
