### ISSUE TITLE
Anonymous array elements are not mapped to xml in data mapper mediator

### ISSUE THREAD

**Issue by Thidasala** [wso2/api-manager#502]
### Description

When we map from json to xml in the data mapper mediator, if we include anonymous array elements in the input.json, those elements are not getting mapped to xml

Ex: 
input.json
```
{
   "tickers": [
      "GIB"
   ]
}
```

output.xml
```
<filingHistory>
    <tickers>
        <ticker>GIB</ticker>
    </tickers>
</filingHistory>
```

### Steps to Reproduce

N/A

### Affected Component

IntegrationStudio

### Version

8.1.0

**Comment by Tharsanan1** [comment]
Fixed with: https://github.com/wso2/integration-studio/pull/1136
