### ISSUE TITLE
Error while saving the integration project for the first time

### ISSUE THREAD

**Issue by Thidasala** [wso2/api-manager#503]
### Description

When we create an integration project using below reproducing steps, and try to save all the artifacts for the first time after the step 6, below error has occured.

<img width="586" alt="Screenshot 2022-07-22 at 17 26 33" src="https://user-images.githubusercontent.com/45654571/180434716-fdd320a8-417f-4fed-9f3a-23b21bcda0a6.png">

### Steps to Reproduce

1. Create a new integration project
2. Create a new rest API
3. Add a post method to the API
4. Add a Data Mapper mediator to the API Compartment
5. Load sample  testin.json and  testout.xml files to the data mapper mediator and map the fields

**testin.json**
```
{
   "tickers":"GIB"
}
```
**testout.xml**
```
<filingHistory>
    <tickers>
        GIB
    </tickers>
</filingHistory>
```
6. Add a respond mediator after the data mapper mediator
7. Go to the file-> SaveAll to save the artifacts

### Affected Component

IntegrationStudio

### Version

8.1.0

**Comment by IsuruMaduranga** [comment]
This issue is fixed via https://github.com/wso2/integration-studio/pull/1153
