### ISSUE TITLE
High CPU usage noticed for Slow writing clients

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/api-manager#522]
### Description

High CPU is observed when a slow writing client sends an HTTPS GET request with a large payload.

### Steps to Reproduce

1. Deploy the API [HTTPCoreTestAPI.xml.txt](https://github.com/wso2/api-manager/files/9179555/HTTPCoreTestAPI.xml.txt) in Micro Integrator.
2. Invoke the API using the client [testclient 2.zip](https://github.com/wso2/api-manager/files/9179567/testclient.2.zip).

### Affected Component

MI

### Version

4.0.0, 4.1.0

### Environment Details (with versions)

JDK: 1.8.0_312

**Comment by GDLMadushanka** [comment]
Resolving the issue since the master branch does not have lot of fixes and the new fix cannot be applied.
