### ISSUE TITLE
[APIM-3.2.0]-Denying policy not working with WebSocket API

### ISSUE THREAD

**Issue by nuwankng** [wso2/api-manager#525]
### Description

When we apply deny policy using the admin portal in the WSO2 API manager, It doesn't block the requests which in turn gives the ability to invoke the WS API regardless of the blocking condition.

### Steps to Reproduce

- Follow the documentation to create a WebSocket API 
- Add a deny policy using the context of the created WebSocket API
- Try to invoke the API

[1]. https://apim.docs.wso2.com/en/3.2.0/learn/tutorials/create-and-publish-websocket-api/

### Affected Component

APIM

### Version

3.2.0 

### Environment Details (with versions)

Latest Update Level

**Comment by YasasRangika** [comment]
The public fix is tracked in a separate internal ticket due to the severity of the fix. Hence closing this issue.
