### ISSUE TITLE
HTTP/2 support for Micro Integrator

### ISSUE THREAD

**Issue by thuva9872** [wso2/api-manager#529]
### Problem

All the websites are moving from HTTP/1.1 to HTTP/2.

### Solution

HTTP/2 is far better than HTTP/1.1. It solves many drawbacks that are in HTTP/1.1. It increases bandwidth efficiency by using a binary compressed format for headers, decreases latency by multiplexing requests on the same TCP connection, and allows the client to specify priorities for requests.

### Affected Component

MI

### Implementation

https://docs.google.com/document/d/1gP4TM9yZhx2sd8B-uMltdbHyXzqkVXUvuE8SEQ0NC6g/edit?usp=sharing

### Related PRs
https://github.com/wso2/wso2-synapse/pull/1949
https://github.com/wso2/wso2-synapse/pull/1978
https://github.com/wso2/micro-integrator/pull/2711

**Comment by thuva9872** [comment]
#https://github.com/wso2/wso2-synapse/pull/1978

**Comment by thuva9872** [comment]
#https://github.com/wso2/wso2-synapse/pull/1978

**Comment by amerireza** [comment]
The  google doc link is private. Please update it with the public link.

**Comment by YasasRangika** [comment]
Public fix: https://github.com/wso2/wso2-synapse/pull/1978 has already been merged into the master branch.
