### ISSUE TITLE
Misleading Error Message Prompted When Publishing an API with Duplicate Resource

### ISSUE THREAD

**Issue by Abshan** [wso2/api-manager#53]
### Description:
Product Version: APIM 3.2.0

When we try to publish an API with duplicate resources in APIM 2.6.0, we are prompted with the following error message on the UI.
`"PUBLISHED":
"Production and Sandbox":"Error while Deploying API: Error while publishing API to the Gateway. Two resources cannot have the same path mapping and methods"`
But in APIM 3.2.0, when we try to publish an API with duplicate resources, we are prompted with just the following message, which is very uninformative.
`response status is 500`

### Steps to reproduce:
1. Deploy a sample API with duplicate resources.
2. Try publishing the API and the above error will be thrown in APIM 3.2.0

### Affected product version:
APIM 3.2.0 (Last tested on version 3.2.0.153)

**Comment by HeshanSudarshana** [comment]
Closing since this is not reproducible in the latest pack
