### ISSUE TITLE
Endpoint password of the Basic auth (Backend) is getting replaced - APIM 4.0.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/api-manager#547]
### Description

Endpoint password of the Basic auth (Backend) is getting replaced with the variable name after the migration from API Manager 2.6.0 to 4.0.0

### Steps to Reproduce

- Configure a WSO2 API Manager 2.6.0 environment with an RDBMS database.
- Start the server and go to the publisher portal.
- Publish APIs with the basic authentication for the backend authentication.
- After that, go to the carbon console and browse the API meta artifact.
- Under the **Endpoint Secured** section, able to see the value **true**, and the **Endpoint Username** section has the username. But the **password** is empty there.
![181396999-6feb38de-3f37-4ce4-9157-2228e90db33b](https://user-images.githubusercontent.com/18566908/182214423-4f88e343-1b87-4318-8ea0-69d1f84680c5.png)
- Stop the server.
- Perform migration from API Manager 2.6.0 to API Manager 4.0.0 by following the documentation [1].
- After the migration, Start the API Manager 4.0.0 server and go to the carbon console.
- Browse the API meta artifact and able to notice that the artifact did not change during the migration.
- Immediately after the migration, invoke the API and be able to see the expected value under the **authorization** header of the backend request.
- Go to the publisher and select the API.
- Click on the **Save** button under the **Runtime** section without doing any changes.
- Check the API meta file again through the carbon console and be able to notice that the artifact got changed as below. (**Endpoint Secured :false, Endpoint Username: empty**)
- But under the **Endpoint Config** section, able to see the endpoint security configs are there and the password has an empty string as below JSON.
![181397035-a597db1f-b0c0-441d-bd0a-367f0b4f8e52](https://user-images.githubusercontent.com/18566908/182214597-6705292c-bd96-4217-bc13-5d3b8a5388fb.png)

```
{"endpoint_type":"http","sandbox_endpoint":{"config":null,"url":"null"},"sandbox_endpoints":{"template_not_supported":false,"config":null,"url":"http:\/\/webhook.site\/a121c3a1-adf5-4eb4-865d-6118594f61d5"},"endpoint_security":{"production":{"password":"","customParameters":"null","type":"BASIC","enabled":true,"username":"admin"},"sandbox":{"password":"","customParameters":"null","type":"BASIC","enabled":true,"username":"admin"}},"production_endpoints":{"template_not_supported":false,"config":null,"url":"http:\/\/webhook.site\/a121c3a1-adf5-4eb4-865d-6118594f61d5"}}
```

- Again go to the publisher portal and deploy a new API revision.
- After that, able see the **$endpointsecurity.base64EncodedPassword** as the value under the **authorization** header as below.
![181397098-4d4c1478-e939-4649-9015-564008a95b19](https://user-images.githubusercontent.com/18566908/182215383-3936b13c-df35-45c8-890b-fc5f3ec78ffa.png)

[1] https://apim.docs.wso2.com/en/4.0.0/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400/

### Affected Component

APIM

### Version

4.0.0

**Comment by Sumudu-Sahan** [comment]
Hi @shilmyhasan,

Can we get an ETA for this?

Thanks and Regards,
Sumudu W.

**Comment by shilmyhasan** [comment]
@HiranyaKavishani Can we assign some body to work on this?

**Comment by Tharanidk** [comment]
Hi, 
Please find the below ETA for this.
Best Case Estimate: 2022-08-16
Most Likely Estimate: 2022-08-30
Worst Case Estimate: 2022-09-13

**Comment by Tharanidk** [comment]
Public PR : https://github.com/wso2/carbon-apimgt/pull/11384
