### ISSUE TITLE
 IP Whitelisting won't work for the API context : /*/{version}/*

### ISSUE THREAD

**Issue by ksankeerth** [wso2/api-manager#552]
### Description

**Analysis**

- When API context is webhook/{version}/axp,

- Throttling information were sent to TM

- TM has notified the correct throttling decision

- But GW doesn't apply the throttling decision as the code return null at [code](https://github.com/wso2-support/carbon-apimgt/blob/fdbe65b707a05732e67723ccbbeaef9230a0ea61/components/apimgt/org.wso2.carbon.apimgt.jms.listener/src/main/java/org/wso2/carbon/apimgt/jms/listener/utils/JMSMessageListener.java#L226)

### Steps to Reproduce

**Steps to reproduce the issue**

- Create a IP whitelisting policy

- Create an API with context with version eg: "webhook/{version}/axp"

- Apply created policy to created API

- Publish the API

- Invoke API from non whitelisted IPs. (eg X-Forwarded-For: )

### Affected Component

APIM

### Version

2.5.0

**Comment by RakhithaRR** [comment]
This is not reproducible with the latest code. Hence closing the issue.
