### ISSUE TITLE
Roles with white spaces are considered to be invalid

### ISSUE THREAD

**Issue by ragwap** [wso2/api-manager#553]
### Description

I have configured a Read only LDAP as the secondary user store which contains role values with spaces.
When trying to restrict access or visibility to an API with such a role, an error is prompted as shown below.
![publisher-access-control-role-error](https://user-images.githubusercontent.com/27797008/182529116-57b24d84-2b3d-49b8-8ea4-d197853507ff.png)

### Steps to Reproduce

1. Configure any type of a secondary/primary user store.
2. Make sure that user store has role names with white spaces.
3. Try to use such roles to restrict access or visibility to an API from the Runtime Configurations of the Publisher portal.
4. The above error will prompt when you try to save changes.

### Affected Component

APIM

### Version

wso2am-3.2.0

**Comment by chameerar** [comment]
Fixed in https://github.com/wso2/carbon-apimgt/pull/11379
