### ISSUE TITLE
ORA-00972: identifier is too long when executing APIM dbsripts in Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production

### ISSUE THREAD

**Issue by alloh** [wso2/api-manager#554]
### Description

Getting ORA-00972: identifier is too long when executing db sripts in Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production.
CREATE SEQUENCE AM_OPERATION_POLICY_DEFINITION_SEQ START WITH 1 INCREMENT BY 1
Error at line 3358
ORA-00972: identifier is too long

CREATE OR REPLACE TRIGGER AM_OPERATION_POLICY_DEFINITION_SEQ
                    BEFORE INSERT
                    ON AM_OPERATION_POLICY_DEFINITION
                    REFERENCING NEW AS NEW
                    FOR EACH ROW
                    BEGIN
                    SELECT AM_OPERATION_POLICY_DEFINITION_SEQ.nextval INTO :NEW.DEFINITION_ID FROM dual;
                    END;
Error at line 3361
ORA-00972: identifier is too long

CREATE TABLE AM_API_OPERATION_POLICY_MAPPING (
   OPERATION_POLICY_MAPPING_ID INTEGER,
   URL_MAPPING_ID INTEGER NOT NULL,
   POLICY_UUID VARCHAR(45) NOT NULL,
   POLICY_ORDER INTEGER NOT NULL,
   DIRECTION VARCHAR(10) NOT NULL,
   PARAMETERS VARCHAR(1024) NOT NULL,
   FOREIGN KEY (URL_MAPPING_ID) REFERENCES AM_API_URL_MAPPING(URL_MAPPING_ID) ON DELETE CASCADE,
   FOREIGN KEY (POLICY_UUID) REFERENCES AM_OPERATION_POLICY(POLICY_UUID) ON DELETE CASCADE,
   PRIMARY KEY(OPERATION_POLICY_MAPPING_ID)
)
Error at line 3417
ORA-00972: identifier is too long

CREATE SEQUENCE AM_API_OPERATION_POLICY_MAPPING_SEQ START WITH 1 INCREMENT BY 1
Error at line 3431
ORA-00972: identifier is too long

CREATE OR REPLACE TRIGGER AM_API_OPERATION_POLICY_MAPPING_SEQ
                    BEFORE INSERT
                    ON AM_API_OPERATION_POLICY_MAPPING
                    REFERENCING NEW AS NEW
                    FOR EACH ROW
                    BEGIN
                    SELECT AM_API_OPERATION_POLICY_MAPPING_SEQ.nextval INTO :NEW.OPERATION_POLICY_MAPPING_ID FROM dual;
                    END;
Error at line 3434
ORA-00972: identifier is too long

### Steps to Reproduce

Excecute oracle.sql in folder /wso2am-4.1.0/dbscripts/apimgt

### Affected Component

APIM

### Version

4.1.0

### Environment Details (with versions)

Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
PL/SQL Release 11.2.0.1.0 - Production
CORE	11.2.0.1.0	Production
TNS for Linux: Version 11.2.0.1.0 - Production
NLSRTL Version 11.2.0.1.0 - Production
Windows 10/Redhat Linux

### Suggested Labels

Severity/Critical

**Comment by chamilaadhi** [comment]
APIM 4.1.0 does not support 11g. Please refer https://apim.docs.wso2.com/en/latest/install-and-setup/setup/reference/product-compatibility/ . you need to use 12c release 2 for that
