### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/api-manager#557]
### Description

There is java.util.ConcurrentModificationException error intermittently while invoking the APIs in apim 4.0.0.
 
{"instant":{"epochSecond":1658153663,"nanoOfSecond":917000000},"thread":"PassThroughMessageProcessor-35","level":"ERROR","loggerName":"org.apache.synapse.transport.passthru.ServerWorker","message":"Error processing POST request for : /services/tfm/tfldata_party/v1/api/1.0.0/parties/ids. ","thrown":{"commonElementCount":0,"name":"java.util.ConcurrentModificationException","extendedStackTrace":[{"class":"java.util.LinkedHashMap$LinkedHashIterator","method":"nextNode","file":"LinkedHashMap.java","line":719,"exact":false,"location":"?","version":"1.8.0_251"},{"class":"java.util.LinkedHashMap$LinkedValueIterator","method":"next","file":"LinkedHashMap.java","line":747,"exact":false,"location":"?","version":"1.8.0_251"},{"class":"org.apache.synapse.api.AbstractApiHandler","method":"dispatchToAPI","file":"AbstractApiHandler.java","line":58,"exact":false,"location":"synapse-core_2.1.7.wso2v227_33.jar","version":"2.1.7-wso2v227.33"},{"class":"org.apache.synapse.api.rest.RestRequestHandler","method":"dispatchToAPI","file":"RestRequestHandler.java","line":84,"exact":false,"location":"synapse-core_2.1.7.wso2v227_33.jar","version":"2.1.7-wso2v227.33"},{"class":"org.apache.synapse.api.rest.RestRequestHandler","method":"process","file":"RestRequestHandler.java","line":70,"exact":false,"location":"synapse-core_2.1.7.wso2v227_33.jar","version":"2.1.7-wso2v227.33"},{"class":"org.apache.synapse.rest.RESTRequestHandler","method":"process","file":"RESTRequestHandler.java","line":54,"exact":false,"location":"synapse-core_2.1.7.wso2v227_33.jar","version":"2.1.7-wso2v227.33"},{"class":"org.apache.synapse.core.axis2.Axis2SynapseEnvironment","method":"injectMessage","file":"Axis2SynapseEnvironment.java","line":344,"exact":false,"location":"synapse-core_2.1.7.wso2v227_33.jar","version":"2.1.7-wso2v227.33"},{"class":"org.apache.synapse.core.axis2.SynapseMessageReceiver","method":"receive","file":"SynapseMessageReceiver.java","line":101,"exact":false,"location":"synapse-core_2.1.7.wso2v227_33.jar","version":"2.1.7-wso2v227.33"},{"class":"org.apache.axis2.engine.AxisEngine","method":"receive","file":"AxisEngine.java","line":180,"exact":false,"location":"axis2_1.6.1.wso2v63_3.jar","version":"?"},{"class":"org.apache.synapse.transport.passthru.ServerWorker","method":"processNonEntityEnclosingRESTHandler","file":"ServerWorker.java","line":375,"exact":false,"location":"synapse-nhttp-transport_2.1.7.wso2v227_36.jar","version":"?"},{"class":"org.apache.synapse.transport.passthru.ServerWorker","method":"processEntityEnclosingRequest","file":"ServerWorker.java","line":434,"exact":false,"location":"synapse-nhttp-transport_2.1.7.wso2v227_36.jar","version":"?"},{"class":"org.apache.synapse.transport.passthru.ServerWorker","method":"run","file":"ServerWorker.java","line":182,"exact":false,"location":"synapse-nhttp-transport_2.1.7.wso2v227_36.jar","version":"?"},{"class":"org.apache.axis2.transport.base.threads.NativeWorkerPool$1","method":"run","file":"NativeWorkerPool.java","line":172,"exact":false,"location":"axis2_1.6.1.wso2v63_3.jar","version":"?"},{"class":"java.util.concurrent.ThreadPoolExecutor","method":"runWorker","file":"ThreadPoolExecutor.java","line":1149,"exact":false,"location":"?","version":"1.8.0_251"},{"class":"java.util.concurrent.ThreadPoolExecutor$Worker","method":"run","file":"ThreadPoolExecutor.java","line":624,"exact":false,"location":"?","version":"1.8.0_251"},{"class":"java.lang.Thread","method":"run","file":"Thread.java","line":748,"exact":true,"location":"?","version":"1.8.0_251"}]},"endOfBatch":true,"loggerFqcn":"org.ops4j.pax.logging.jcl.JclLogger","threadId":437,"threadPriority":5}

But it is not available in
https://github.com/wso2-support/wso2-synapse/blob/9422a623d20660df2d8b67fa4b8de21faeb4ee64/modules/core/src/main/java/org/apache/synapse/api/AbstractApiHandler.java#L47

### Steps to Reproduce

Create and Invoke an API

### Affected Component

APIM

### Version

4.0.0

**Comment by rmsamitha** [comment]
This issue is not reproduced locally. Hence will be keeping the priority as "Normal".
