### ISSUE TITLE
Error when saving API definition from editor drawer

### ISSUE THREAD

**Issue by imsuneth** [wso2/api-manager#558]
### Description

Under API Definition tab in the publisher portal, after opening the editor drawer (make changes or not), an error occurs. A 415 error was shown in the console.

https://user-images.githubusercontent.com/18381372/182764571-9c71fc43-9fa2-47f6-9456-835c0b1b640a.mov

### Steps to Reproduce

1. Go to the publisher portal and create the Sample Pizza Shack API
2. Go to API Definition tab under API Configurations
3. Click Edit from the tool bar on top
4. Click Update content and Select Save from the dialog box.

### Affected Component

APIM

### Version

4.2.0

### Environment Details (with versions)

OS: macOS Monterey 12.4

### Relevant Log Output

```shell
Failed to load resource: the server responded with a status of 415 (): :9443/api/am/publish…/validate-openapi:1 

APIDefinition.jsx:577 Error: response status is 415 : APIDefinition.jsx:577 Error: response status is 415
    at _callee$ (index.js:168:1)
    at tryCatch (regeneratorRuntime.js:105:1)
    at Generator._invoke (regeneratorRuntime.js:85:1)
    at Generator.next (regeneratorRuntime.js:139:1)
    at asyncGeneratorStep (asyncToGenerator.js:5:1)
    at _next (asyncToGenerator.js:27:1)
```

**Comment by chanaka3d** [comment]
This issue is fixed with the introduction of the lining feature. https://github.com/wso2/apim-apps/pull/330
