### ISSUE TITLE
Muiltiple aggregation intializtions for the aggregation 'ApiUserPerAppAgg'

### ISSUE THREAD

**Issue by janithcmw** [wso2/api-manager#561]
### Description

When an APIM-Analytics-3.2.0-Worker(U2-39) server is configured with alerts following log lines are visible frequently(within one-minute intervals).

```
INFO {io.siddhi.core.aggregation.AggregationRuntime} - Starting initialization of executors for aggregation: ApiUserPerAppAgg
INFO {io.siddhi.core.aggregation.AggregationRuntime} - Finished initialization of executors for aggregation: ApiUserPerAppAgg
```

As per the logs, it seems there are continuous initializations for the aggregation 'ApiUserPerAppAgg' and hope this should be one-time initialization.

### Steps to Reproduce

Configure an APIM-Analytics server with alerts and monitor the logs.

### Affected Component

Analytics

### Version

APIM - Analytics -3.2.0

### Environment Details (with versions)

N/A

**Comment by janithcmw** [comment]
Hi All,

Was this released? kindly update.

Best Regards,
Janith.

**Comment by GihanAyesh** [comment]
U2 update is released, working on the WUM update. Will update soon.

Yours sincerely,
Gihan
