### ISSUE TITLE
API's document link in Devportal opens a blank page

### ISSUE THREAD

**Issue by ragwap** [wso2/api-manager#565]
### Description

Documents link in Devportal displays a blank page in the latest U2 level.

### Steps to Reproduce

1. Update to wso2am-4.1.0.21 (or latest as of now 4.1.0.23).
2. Navigate to the publisher and create an API or select an existing API.
3. Navigate to the 'Documents' section and add a document.
4. Save changes and navigate to the Devportal.
5. Try to view the uploaded document.
6. A blank page will appear.

### Affected Component

APIM

### Version

wso2am-4.1.0

**Comment by npamudika** [comment]
Fixed with https://github.com/chanaka3d/apim-apps-1/commit/620bc9a953fd59f5ef37ed8254955ad1902ebeb4

**Comment by npamudika** [comment]
No public fix is required as the issue was with U2 system.
