### ISSUE TITLE
api#am#admin#v0.14.war gets removed during server optimisation.

### ISSUE THREAD

**Issue by AshenJayasuriya** [wso2/api-manager#589]
### Description

The api#am#admin#v0.14.war gets removed when optimizing the APIM-2.6.0 server to any profile. Hence the api#am#admin#v0.14.war webapp needs to be added to the publisher and devportal profiles. 

### Steps to Reproduce

- Go to the wso2am-2.6.0/bin/ location.
- Run the profileSetup.sh and optimize the server to any profile.
- Check the  **wso2am-2.6.0/repository/deployment/server/webapps/** directory for the **api#am#admin#v0.14.war** webapp.

### Affected Component

APIM

### Version

wso2am-2.6.0

**Comment by YasasRangika** [comment]
The same issue has been duplicated at https://github.com/wso2/product-apim/issues/6686 and has been resolved with the public fix found at https://github.com/wso2/product-apim/pull/6786, which subsequently closed the issue.
