### ISSUE TITLE
The method 'handleResponseOutFlow' invocation even with the health check request.

### ISSUE THREAD

**Issue by janithcmw** [wso2/api-manager#59]
### Description:
The method 'handleResponseOutFlow' will be engaged when a synapse handler is added to the system even when the '/healthz' (readiness probe) is invoked.

### Steps to reproduce:
Create a synapse handler and add it to the MI and then invoke the health check API. You can see that the invocation of the relevant method 

### Affected product version:
WSO2MI-1.2.0

### Affected component:
WSO2MI-1.2.0 - U2-90

### Environment details (with versions):
- OS: N/A
- Client: N/A
- Env (Docker/K8s): N/A

**Comment by gspadotto** [comment]
Will this issue be fixed for the 4.x MI runtime versions too?
