### ISSUE TITLE
Need updates to Twilio connector as they're deprecating the /SMS/Messages ep

### ISSUE THREAD

**Issue by Menuka-Senevirathne** [wso2/api-manager#592]
### Problem

Twilio will shut down the /sms/messages resource endpoint on November 28, 2022. The SMS/Messages resource has been deprecated, replaced by the Messages resource, and may be removed in future versions of the Twilio API [1]

[1] https://support.twilio.com/hc/en-us/articles/223181028-Switching-from-SMS-Messages-resource-URI-to-Messages-resource-URI-

### Solution

Upgrade the Twilio connector to support the new Message resource.

### Affected Component

EI/MI

**Comment by chamilaadhi** [comment]
Latest version released with https://github.com/wso2-extensions/esb-connector-twilio/pull/4
