### ISSUE TITLE
Add IDN_UMA table script changes for Oracle, DB2

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#603]

**Comment by tharikaGitHub** [comment]
This issue is fixed with https://github.com/wso2/docs-apim/pull/6129

**Comment by dushaniw** [comment]
@tharikaGitHub do we need this in 4.1 and 4.x as well?

**Comment by tharikaGitHub** [comment]
Yes we need to check and add to 4.1 and 4.x.

**Comment by msm1992** [comment]
Fixed in 4.0.0 and 4.1.0 with below PRs.
4.0.0 : https://github.com/wso2/docs-apim/pull/6129
4.1.0 : https://github.com/wso2/docs-apim/pull/6187

Will be fixed in 4.x.x with https://github.com/wso2/docs-apim/issues/6192.
