### ISSUE TITLE
Token API call failure returning stack trace with details from DB

### ISSUE THREAD

**Issue by isurul28** [wso2/api-manager#61]
### Description:
In APIM 3.2.0 update level 153 when we invoke the Token API call when the Database is down we are getting a proper error message as below 

Response to the client : 
```

{
    "error_description": "Internal Server Error.",
    "error": "server_error"
}
```
But after around 15 min  if we invoke the same Token API call while the Database is down we are getting the below response from the APIM to the client 
```
<ns1:XMLFault xmlns:ns1="http://cxf.apache.org/bindings/xformat"><ns1:faultstring xmlns:ns1="http://cxf.apache.org/bindings/xformat">org.wso2.carbon.identity.base.IdentityRuntimeException: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.</ns1:faultstring></ns1:XMLFault> 
```

As you can see in the above response the database information(host, port) and the JDBC error is given as the response to the client.

### Steps to reproduce:
1.Get a WSO2 APIM 3.2.0 updated pack
2.Change the defualt database of APIM 3.2.0 to any RDBMS database [1]
3.Create an API 
4.Subscribe to that API and invoke the Token API call

```
curl --location --request POST 'https://localhost:8243/token' \
--header 'Authorization: Basic VFJZTjFnVkJycGFDa3N4ckl0RHJBR0VXamhFYTozRUdENEVpTWlhVmxLYWpMTDBfWkN0V2RWeVVh' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'username=admin' \
--data-urlencode 'password=admin'
```
 you will see access token, refresh token information as the response.
5. Now shutdown the RDBMS database
6. invoke the token API call 

```
curl --location --request POST 'https://localhost:8243/token' \
--header 'Authorization: Basic VFJZTjFnVkJycGFDa3N4ckl0RHJBR0VXamhFYTozRUdENEVpTWlhVmxLYWpMTDBfWkN0V2RWeVVh' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'username=admin' \
--data-urlencode 'password=admin'
```
 you will see the below response

```
{
    "error_description": "Internal Server Error.",
    "error": "server_error"
}
```
7. Now wait for 15 min and try the same, now you will see the below response not the internal server error
```
<ns1:XMLFault xmlns:ns1="http://cxf.apache.org/bindings/xformat"><ns1:faultstring xmlns:ns1="http://cxf.apache.org/bindings/xformat">org.wso2.carbon.identity.base.IdentityRuntimeException: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.</ns1:faultstring></ns1:XMLFault> 
```

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Madhuka** [comment]
@dushaniw / @isurul28 Any Updates on this?
