### ISSUE TITLE
Replace react-safe-html with a new npm library

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/api-manager#621]
### Problem

The `react-safe-html library`[1] used in APIM portals is no longer maintained and the latest release of this was 4 years ago. This has come up in several reports as this is an outdated library.

[1] - https://www.npmjs.com/package/react-safe-html

### Solution

We need to find an alternative for `react-safe-html`.

### Affected Component

APIM

### Version

4.x.x

**Comment by chanaka3d** [comment]
![Screen Shot 2023-01-19 at 9 05 08 PM](https://user-images.githubusercontent.com/3424539/213485271-fc107339-063f-40f8-881f-1ae7061ae8cc.png)

According to the above we can select html-react-parser as the choice base on it's active development and usage. 

No vulnerabilities are reported at the moment.
