### ISSUE TITLE
Update "what has changed" section on JWT kid claim changes

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#623]

**Comment by msm1992** [comment]
Added note with commit https://github.com/wso2/docs-apim/pull/6156/commits/e37fcb98172d9ea0e3cad2655af427ec54c1479d

**Comment by dushaniw** [comment]
Need to add this to 4.1.0 and 4.x.x

**Comment by msm1992** [comment]
Fixed in 4.1.0 with https://github.com/wso2/docs-apim/pull/6188/files.
Will be fixed in 4.x.x with https://github.com/wso2/docs-apim/issues/6192
