### ISSUE TITLE
Update "what has changed" section on resource level security changes from 2.6

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#626]

**Comment by msm1992** [comment]
Added a note with https://github.com/wso2/docs-apim/pull/6156/commits/a8024ba35ba090646d28154f3a80c68486ba81bd

**Comment by msm1992** [comment]
Fixed in 4.1.0 with https://github.com/wso2/docs-apim/pull/6188/files.
Will be fixed in 4.x.x with https://github.com/wso2/docs-apim/issues/6192
