### ISSUE TITLE
Modify APIM 4.0.0 migration docs to be structurally similar to 4.1.0

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#642]
### Problem

APIM 4.0.0 migration documentation should be structurally changed to be similar to APIM 4.1.0 migration docs. This is to improve usability.

### Solution

Restructure the 4.0.0 migration docs.

### Affected Component

APIM

**Comment by msm1992** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/6167
