### ISSUE TITLE
Add global sequence copying to the migration docs

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#654]
### Problem

There is no note in the migration document on how the global sequences are migrated. Need to add this to the documentation after testing the below solution.

### Solution

The global sequences should be copied to the file system as before from the older version.

And they should be added to the excluded sequences list as follows for example in the skip list in `deployment.toml`.

apim.sync_runtime_artifacts.gateway.skip_list.sequences

```
[apim.sync_runtime_artifacts.gateway.skip_list]
apis = ["api1.xml","api2.xml"]
endpoints = ["endpoint1.xml"]
sequences = ["post_with_nobody.xml"]
local-entries = ["file.xml"]
```

### Affected Component

APIM

### Version

4.x.x

**Comment by dushaniw** [comment]
@1akshitha Any idea how this affects to 4.1.0 migration with introduction of operation policies?

**Comment by 1akshitha** [comment]
For global policies, this would stay same. We don't handle global mediation policies through the policy framework.

**Comment by dushaniw** [comment]
This will be added to 4.x docs once we sync doc master branch with 4.1.0.
