### ISSUE TITLE
Fault while sending an incorrect bearer token

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/api-manager#666]
### Description

JWT token contains three sections separated by dots. (header.payload.signature)

**Scenario 01**: Authorization header = Bearer header.
`Response: Correct`
```
{
    "fault": {
        "code": 900901,
        "message": "Invalid Credentials",
        "description": "Invalid JWT token. Make sure you have provided the correct security credentials"
    }
}
```

**Scenario 02**: Authorization header = Bearer header.payload.
`Response: Incorrect`
```
<soapenv:Reason xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">
    <soapenv:Text xml:lang="en-US">2</soapenv:Text>
</soapenv:Reason>
```
`Error in logs`
```
[2022-08-22 17:50:24,567] ERROR - ServerWorker Error processing GET request for : /pizzashack/1.0.0/menu.
java.lang.ArrayIndexOutOfBoundsException: 2
        at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.getSignedJwt_aroundBody62(OAuthAuthenticator.java:561) ~[org.wso2.carbon.apimgt.gateway_6.7.206.336.jar:?]
        at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.getSignedJwt(OAuthAuthenticator.java:559) ~[org.wso2.carbon.apimgt.gateway_6.7.206.336.jar:?]
```

**Scenario 03**: Authorization header = Bearer header.payload.signature (Invalid token)
`Response: Correct`
```
{
    "fault": {
        "code": 900901,
        "message": "Invalid Credentials",
        "description": "Invalid Credentials. Make sure you have provided the correct security credentials"
    }
}
```
We need to fix and validate if the token has 2 dots. 

### Steps to Reproduce

1. Create an API.
2. Invoke the API with a JWT like below.
`eyJ4NXQiOiJNell4TW1Ga09HWXdNV0kwWldObU5EY3hOR1l3WW1NNFpUQTNNV0kyTkRBelpHUXpOR00wWkdSbE5qSmtPREZrWkRSaU9URmtNV0ZoTXpVMlpHVmxOZyIsImtpZCI6Ik16WXhNbUZrT0dZd01XSTBaV05tTkRjeE5HWXdZbU00WlRBM01XSTJOREF6WkdRek5HTTBaR1JsTmpKa09ERmtaRFJpT1RGa01XRmhNelUyWkdWbE5nX1JTMjU2IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJhZG1pbiIsImF1dCI6IkFQUExJQ0FUSU9OIiwiYXVkIjoiUU93UTJZdW1UVnA0UE9sWXdkOEZkdm1QcjJzYSIsIm5iZiI6MTY2MTI1MTEwNywiYXpwIjoiUU93UTJZdW1UVnA0UE9sWXdkOEZkdm1QcjJzYSIsInNjb3BlIjoiZGVmYXVsdCIsImlzcyI6Imh0dHBzOlwvXC9sb2NhbGhvc3Q6OTQ0M1wvb2F1dGgyXC90b2tlbiIsImV4cCI6MTY2MTI1NDcwNywiaWF0IjoxNjYxMjUxMTA3LCJqdGkiOiIzYWNlYjQxNi05ZDU1LTQ5YTctYjEyZi1kYWU0ZDJkODA0OGUifQ.`

### Affected Component

APIM

### Version

3.2.0

### Suggested Labels

APIM-3.2.0

**Comment by Tharanidk** [comment]
Hi @niranRameshPeiris ,
Please find the below ETA for this.
Best Case Estimate: 2022-09-09
Most Likely Estimate: 2022-09-16
Worst Case Estimate: 2022-09-30
