### ISSUE TITLE
Jar, War version mismatch between wso2apim-is-plugin-3.2.0 and wso2 APIM 3.2.0 

### ISSUE THREAD

**Issue by riyazathali** [wso2/api-manager#678]
### Description

After updating the product to the 191st update level, we could notice the following related to KeyManager plugins:(This is about APIM-IS connector commented at this documentation link: https://apim.docs.wso2.com/en/3.2.0/administer/key-managers/configure-wso2is-connector/)

Patch 191: /repository/componentes/plugins:

size - name
33800 - wso2is.notification.event.handlers_1.0.16.14.jar
28534 - wso2is.key.manager_1.0.16.6.jar
54142 - wso2is.key.manager.core_1.0.16.22.jar

/repository/deployment/server/webapps:

842574 - keymanager-operations.war

But, After updated wso2apim-is-plugin 3.2.0 to 191 which appears the following jar and war

wso2apim-is-plugin-3.2.0: /dropins:

cksum - size - name

1181318651 - 54116 - wso2is.key.manager.core-1.0.16.18.jar
1376394919 - 33879 - wso2is.notification.event.handlers-1.0.16.21.jar

/webapps:

140845260 - 842276 - keymanager-operations.war

It seems, both have different versions of jars and war between wso2apim-is-plugin and plugins from APIM.

Thanks,
Riyazath Ali.

### Steps to Reproduce

1. Update the APIM 3.2.0 and wso2apim-is-plugin  to 191 
2. Check the version mismatch of the jars and wars

### Affected Component

APIM

### Version

3.2.0

**Comment by binodmx** [comment]
Closing the issue as this is fixed now.
