### ISSUE TITLE
Websocket API not able to consume using Opaque token-Fix-Issue 1,2 and 3 [Public]

### ISSUE THREAD

**Issue by amiladeshapriya** [wso2/api-manager#688]
### Description

Hi Devs,

Product: WSO2AM-3.2.0

The customer returned after testing the WebSocket scenario using the opaque flow, and now it seems to be working.

And they have observed a couple more issues related to opaque flow, which were also reproduced locally.

1. Token validation is not working correctly. After one hour (After the token expires), the client does not get any 401 error code with reason, and the connection is not getting closed either. Instead of getting the error code 401, we see the following as a response on the client side.
{"payload":[{"code":0}],"type":"error"}

2. Even when we close the connection from the client side, the connection is still active between the client to the gateway and the gateway to the backend application. The connection is not getting closed properly.

3. I was able to reproduce the below issue on both 186 and latest (192) U2 update levels.

_In addition to the above-listed issues, the customer informed us that in the request flow log, they couldn't see any other information except api path name value. application name,API name, username,API type values are coming as null value. This behaviour is also only observable only in the opaque token flow. For example,_

`INFO BNYMWebSocketLoggingHandler Request Flow: {"Request Path":"/PRODUCTION/pingpong/v2","Application Name":"","API Name":"","API Version":"","API Type":"","Username":"","Origin":"","Host":"","X-Forwarded-Host":"","transactionId":"","Close Code":"","X-Forwarded-For":""}`

When the Websocket API is invoked using the JWT, the details are available in the "API_PROPERTIES" HashMap in the "messageContext" object[1].

Log produced:
`[2022-08-26 18:15:04,172] INFO - BNYMWebSocketLoggingHandler Request Flow: {"Request Path":"/PRODUCTION/ifelse/1.0.0","Application Name":"Test1","API Name":"ifelseWebSocket","API Version":"1.0.0","API Type":"API","Username":"[admin@carbon.super](mailto:admin@carbon.super)","Origin":"localhost:9099","Host":"localhost:9099","XFFhost":"","TransactionId":"","Close Code":"","X-Forwarded-For":""}`

But when the Websocket API is invoked using the opaque token (jti in the JWT), the details are not available in the "API_PROPERTIES" HashMap in the "messageContext" object[2].

Log produced:
`[2022-08-26 18:17:18,676] INFO - BNYMWebSocketLoggingHandler Request Flow: {"Request Path":"/PRODUCTION/ifelse/1.0.0","Application Name":"","API Name":"","API Version":"","API Type":"","Username":"","Origin":"localhost:9099","Host":"localhost:9099","XFFhost":"","TransactionId":"","Close Code":"","X-Forwarded-For":""}`

Could you please check on this and provide an ETA to fix the issue 3?

Best Regards,
Amila.

[1] https://drive.google.com/file/d/1Bo1o3gv_5cCFeoW-cpGv_ay10--jNWfr/view?usp=sharing
[2] https://drive.google.com/file/d/1hxeZ-f3lXPrEdqTDR1FqcMgXsl1klb4h/view?usp=sharing

Product : wso2am-3.2.0
Update level : 186
Public Git Issue : https://github.com/wso2-enterprise/wso2-apim-internal/issues/517

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

3.2.0.186

### Related Issues

https://github.com/wso2-enterprise/wso2-apim-internal/issues/517
https://github.com/wso2-enterprise/wso2-apim-internal/issues/567
https://github.com/wso2-enterprise/wso2-apim-internal/issues/575

**Comment by amiladeshapriya** [comment]
Hi Team,

Any update on this?

Regards,
Amila.

**Comment by wasuradananjith** [comment]
Hi all,

Created separate issues [1] to track this. Hence, closing this.

[1] https://github.com/wso2/api-manager/issues/710
[2] https://github.com/wso2/api-manager/issues/714 

Thanks,
Wasura Wattearachchi
