### ISSUE TITLE
event_waiting_time is not applied in the gw in-memory updation flow

### ISSUE THREAD

**Issue by riyazathali** [wso2/api-manager#702]
### Description

We could find that the event_waiting_time is only applied in the runtime artefacts retrieval internal API call flow. This delay is not applied in the gateway in memory update flow.

### Steps to Reproduce

1. Add an event_waiting_time as 30s in deployment.toml
2. The GW map is getting updated at once and the synapse artifact is created after the 30s.

### Affected Component

APIM

### Version

4.0.0

**Comment by nuwankng** [comment]
Hi Team,

Seems like the fix is not available on the APIM 4.1.0. I have checked on the latest update level. Is it possible to port this fix to the APIM 4.1.0 Version as well.

Thanks,
NuwanK
