### ISSUE TITLE
Remove the http_endpoint from apim.gateway.environment

### ISSUE THREAD

**Issue by akila95fernando** [wso2/api-manager#704]
### Description

Removing http gateway endpoint from publisher UI and tryout consoles 

### Steps to Reproduce

In api manager 3.2.0 we were able to remove http endpoints by commenting out the following from deployment.toml

[[apim.gateway.environment]]
#http_endpoint = "[http://localhost:8280)"

When trying out the same approach in apim 4.1.0 , http endpoint still appears with in deployment section of publisher without a port .

### Affected Component

APIM

### Version

4.1.0

### Suggested Labels

apim 4.1.0

**Comment by YasasRangika** [comment]
closing as the master fix: https://github.com/wso2/apim-apps/pull/374 has already been merged.
