### ISSUE TITLE
API Configurations have no Message Mediation tag

### ISSUE THREAD

**Issue by yang12xin489** [wso2/api-manager#705]
### Description

I need the Message Mediation feature, but I don't see the Message Mediation option in the API Configurations, how can I enable it?
![1662443563672](https://user-images.githubusercontent.com/56429015/188557052-899f2835-57ce-4b59-9363-4826a285f8e9.jpg)

### Affected Component

APIM

### Version

4.1.0

### Environment Details (with versions)

windows 11
jdk 1.8

**Comment by binodmx** [comment]
HI @yang12xin489, 

Message mediation can be done using API Policies [1] in APIM 4.1.0 onward. Please refer to attaching policies documentation [2] for more information.

[1] https://apim.docs.wso2.com/en/latest/design/api-policies/overview/
[2] https://apim.docs.wso2.com/en/latest/design/api-policies/attach-policy/
