### ISSUE TITLE
[4.0.0] Migrated Prototype APIs with no GW environment configured give errors

### ISSUE THREAD

**Issue by msm1992** [wso2/api-manager#706]
### Description

**description**
When there are prototype APIs with no gateway environment selected were there in the 2.6.0 setup, During 3.2.0 APIM revision related migration, environment name picked from registry artiafct has 'none' and it is used to create the APIRevisionDeployment object. Thus when deploying the revision, DB is updated with gateway as 'none' but no real API deployment takes place

**suggested fix**
In order to fix this in the migration client, can we log and skip revision deployment for Prototyped APIs with no gateways

### Steps to Reproduce

1. In APIM 2.6.0 create a prototype api and deselect all gateway environments before saving it.
2. Migrate to APIM 4.0.0
3. Go to publisher, explore the prototype API and try to deploy it.

```
ERROR - ApisApiServiceImpl Error while adding retrieving API Revision for api id : 153ea023-1ac6-4e2c-b1e1-0f31f32f1a6b - Configured read only environment not found: non
```

### Affected Component

APIM

### Version

4.0.0

**Comment by dushaniw** [comment]
Need to fix in 4.1 and 4.x.
