### ISSUE TITLE
Multiple APIs cannot be created with the same sub context

### ISSUE THREAD

**Issue by lathlk** [wso2/api-manager#71]
### Description:
Multiple APIs cannot be created with the same sub context

### Steps to reproduce:
1. Create an API with the context "o2c/rlslineitem".
2. Then create another API with another context "rlslineitem".
3. We get the error "/rlslineitem context already exists".
![image](https://user-images.githubusercontent.com/20392682/168125740-b3957178-0234-4f85-9343-8161460636bc.png)
We further checked the network trace and observed the context validation is performed based on the publisher rest API request (/api/am/publisher/v2/search?limit=1&offset=0&query=context%3A%2Frlslineitem%22) and it returning the APIs with the same subcontext. Please refer to the below image.
![image](https://user-images.githubusercontent.com/20392682/168125779-3cd326a9-8910-4bc6-9c76-2e3e7c65ab6e.png)

### Affected product version:
APIM 4.0.0

**Comment by shilmyhasan** [comment]
Public PR https://github.com/wso2/apim-apps/pull/300
