### ISSUE TITLE
Error in deprecation information in SOAP section

### ISSUE THREAD

**Issue by ramindu90** [wso2/api-manager#73]
### Describe your problem(s)
Since depreciation is only for generation of SOAP to REST APIs, the deprecation message should only visible when the SOAP to REST option is clicked. Otherwise it implies the whole SOAP passthrough and SOAP to REST both are deprecating
 
![Screenshot 2022-05-13 at 1 22 51 PM](https://user-images.githubusercontent.com/10056966/168237989-9d27494a-a0f3-408d-9c08-38fa4cd48e90.png)

**Comment by lkokila** [comment]
The message has been updated through U2 as follows.

![Screenshot 2023-08-04 at 11 50 54](https://github.com/wso2/api-manager/assets/5971789/ec3ef043-9284-47f2-a11a-aaa7062177a9)

**Comment by GihanAyesh** [comment]
Fixes with the PR: https://github.com/wso2/apim-apps/pull/488
