### ISSUE TITLE
Issue while calling APIs with default version

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/api-manager#733]
### Description

Resource not found (404) errors thrown while invoking the default versions of the API without the version number in the request url.

### Steps to Reproduce

- Create an API
- Invoke the default version of the API without version in request url.

### Affected Component

APIM

### Version

4.0.0

**Comment by rmsamitha** [comment]
@shilmyhasan please close this if this is fixed in master branch.

**Comment by shilmyhasan** [comment]
https://github.com/wso2-enterprise/wso2-apim-internal/issues/751 includes the public fix. Hence closing this issue
