### ISSUE TITLE
Updating an API Using Swagger Doesn't Refresh Browser Session

### ISSUE THREAD

**Issue by shavinsenadheera** [wso2/api-manager#74]
### Description:
This issue happens when updating the already created new version of API (with scope assignments) by uploading the updated swagger definition file after removing all scope configurations.

The "securityDefinitions" property of the uploaded swagger file was empty and there was nothing in the "security" property also which is the expected behavior. This behavior was also observed in the swagger request of the browser network tab while we went to the "Resources" and "Scopes" tabs as in figure_1, figure_2, figure_3 and figure_4.

But when we checked the "Scopes" tab, we were able to see the scopes that were created for the previous API version. When we tried to assign the scopes to resources that were available, we received a bad request response since we haven't created any scopes for the current version of the API.

This behavior is observed only when we do not refresh the browser page right after we import the swagger file. Once we refresh the page we can see that the scopes that were previously present in the "Scopes" tab are gone and no scopes were listed under resources as well. This seems to be an issue related to browser sessions.

### Steps to reproduce:

- Create or deploy a sample API in the Publisher Portal.
- Create some scopes and assign them to the resources.
- Download the API Definition (API Definition -> DOWNLOAD DEFINITION).
- Create a new version of API.
- Remove all scope configurations in API Definition.
- Import the modified swagger file to the new version of API (API Definition -> IMPORT DEFINITION).
- Go to "Resources" tab
- No scopes are assigned to the resources.
- Scopes are still available in "Operation scope".
- Go to "Scopes" tab
- Scopes are still available.
- Go to resources and assign a scope to some resource.
- You will receive a "Bad Request" as in figure_5.

### Affected product version:
APIM 3.0.0
![figure_5](https://user-images.githubusercontent.com/42552426/168286424-744a680c-bb82-407a-84a0-b099fafd1042.png)
![figure_2](https://user-images.githubusercontent.com/42552426/168286430-a4c32d21-1c33-40dd-ab6d-5460348cde79.png)
![figure_3](https://user-images.githubusercontent.com/42552426/168286433-e90bdbe9-597e-4596-b384-20cfcf334bf5.png)
![figure_4](https://user-images.githubusercontent.com/42552426/168286441-36ee3023-f5c1-4564-a1db-22dad52fd15b.png)
![figure_1](https://user-images.githubusercontent.com/42552426/168286445-40134f8c-1800-4368-a137-da9eeae96807.png)

**Comment by RakhithaRR** [comment]
This issue is not reproducible in master
