### ISSUE TITLE
[APIM][4.1.0] Can not dynamically update the operationPolicyCount in the Publisher Portal

### ISSUE THREAD

**Issue by pasindu-sandima** [wso2/api-manager#756]
### Description

In the publisher portal, a [limit is set for the number of operation policies](https://github.com/wso2/apim-apps/blob/main/portals/publisher/src/main/webapp/site/public/conf/settings.json#L20:~:text=%22operationPolicyCount%22%3A%20500%2C) that can be viewed from the publisher portal. We should be able to dynamically update this limit. But we can not dynamically update the limit using the /repository/deployment/server/webapps/publisher/site/public/conf/settings.json file.  

The issue seems to be in this [line](https://github.com/wso2/apim-apps/blob/main/portals/publisher/src/main/webapp/source/src/app/data/api.js#:~:text=import%20Configurations%20from%20%27../../../../site/public/conf/settings.json%27%3B). This line has been changed in this [PR](https://github.com/wso2/apim-apps/pull/202). 

Related : https://github.com/wso2/api-manager/issues/731

### Steps to Reproduce

Open the publisher portal. Check the network tab for the operation policy request's limit. Change the operationPolicyCount in the  /repository/deployment/server/webapps/publisher/site/public/conf/settings.json. Check reload the page and check whether the limit has been changed in operation policy request using the network tab. 

![image](https://user-images.githubusercontent.com/37769828/191896596-4af9202d-7141-45e8-92e5-e9968b0dec48.png)

### Affected Component

APIM

### Version

4.1.0

**Comment by rmsamitha** [comment]
@DinithHerath Please fix https://github.com/wso2/api-manager/issues/731 as well with this. (that is fixed in u2, hence should be available in next release)
