### ISSUE TITLE
Receiving 404 message error after we deploy a new API revision.

### ISSUE THREAD

**Issue by Hamool-Nizar** [wso2/api-manager#789]
### Description

Hi Team,

In the APIM 4.0.0 we are facing the following error when invoking the API after performing API revision

 {"code":"404","type":"Status report","message":"Not Found","description":"The requested resource is not available."}
 
We have observed these 404 error messages in 2 scenarios as follows:

Case 1: Deploy a new Revision; After that, Make 10K requests with 20 threads/seconds

For this case we have tested on a lower environment where there was no extra traffic beside the one created by us. We tested the below scenario:

Run 10.000 API calls
Wait for 5 minutes (no traffic)
Deploy a new API revision
Wait for 3 minutes (no traffic)
Run 10.000 API calls --> we received 404 on 50% of the calls

Case 2: Makes 10,000 API calls with 20 threads/seconds and changes the revision (deploy and un-deploy) at the same time

If the number of Initializing and Destroying Api logs are the same we will not encounter any issue during 10.000 API calls.
If the number of Initializing logs is less the Destroying API logs --> we encounter 404 error message

Could you please provide your inputs on these above observations of the customer and your suggestions on how we can resolve these issues.

### Steps to Reproduce

Case 1: Deploy a new Revision; After that, Make 10K requests with 20 threads/seconds

For this case we have tested on a lower environment where there was no extra traffic beside the one created by us. We tested the below scenario:

Run 10.000 API calls
Wait for 5 minutes (no traffic)
Deploy a new API revision
Wait for 3 minutes (no traffic)
Run 10.000 API calls --> we received 404 on 50% of the calls

### Affected Component

APIM

### Version

4.0.0

**Comment by tharikaGitHub** [comment]
Closing as the fix is already merged to master branch.
