### ISSUE TITLE
UPDATE is re-enabled after DevPortal page is refreshed when Provisioned Oauth Client credentials are provided

### ISSUE THREAD

**Issue by Krishanx92** [wso2/api-manager#792]
### Description

After provisioning the OAuth Keys the UPDATE button is disabled, upon refreshing the DevPortal page or clicking on the Production/Sandbox Keys, the UPDATE button is re-enabled. 

### Steps to Reproduce

Configure IS-KM and APIM
Create a Service Provider in IS-KM as external OAuth2 client
Add the OAuth Client Key to the Service Provider Description
Create a new application in DevPortal with the same Service Provider name
Subscribe to an API
Under Production/Sandbox Keys in Devportal provide the OAuth Client Key and Client Secret of the Service Provider as the Consumer Key and Secret under “Provide Existing OAuth Keys”
After clicking Provide, the Update button appears as disabled, but is re-enabled when the page is refreshed.

### Affected Component

APIM

### Version

3.1.0

**Comment by tharikaGitHub** [comment]
Closing as the public fix is already available.
