### ISSUE TITLE
Error when login to the APIM Publisher portal - {Error while retrieving OAuth application information for the provided client id : null}

### ISSUE THREAD

**Issue by dilshanfa** [wso2/api-manager#796]
### Problem

When we are trying to log in the APIM publisher portal. We can log in to the APIM publisher portal but there was an log with this ERROR

**TID: [-1234] [] [2022-09-20 10:49:27,684] ERROR {org.wso2.carbon.identity.oidc.session.servlet.OIDCSessionIFrameServlet} - Error while retrieving OAuth application information for the provided client id : null, Cannot find an application associated with the given consumer key : null**

Even though I got this error I was able to log into the publisher portal.

So, we have enabled and analyzed the debug logs and we observed that there are a couple of more instances where the consumer key is changed. In this case the consumer key is assigned to the username.

Screenshot 2022-09-29 at 11 49 32

APIM Version - 4.1.0 and Update Level - 31

**DEBUGGING OBSERVATIONS**

When login to the publisher portal OAuthClientAuthenticationProxy#handleMessage [1] will hit multiple times with different kinds of requests.

1. /oauth2/authorize
2. /oauth2/token
3. /oauth2/userinfo
4. /oauth2/introspect

So each and every request this method will authenticate the client. OAuthClientAuthnService#authenticateClient [2]. In that flow when we check the extracting part of the client id and the client secret in the BasicAuthClientAuthenticator#getClientId [3] will get details from the request header.

So, the above 4 mentioned requests are going through this method. /authorized request doesn’t have a Authorized header so the clientid and the secret will be null, /token will have the Authorization header so the clientId and the client secret will be extracted from the header, next the /userinfo request Authorization header has a bearer token so it will not execute with the BasicAuthClientAuthenticator.

The problem is with the last request /introspect. This has a Basic Authorization Header with the username and the password [4]. As per the screenshot below this will also behave like a base64enoded(clientId:clientSectret) type and decodes as the username and password as the client id and client secret.

<img width="1118" alt="Screenshot 2022-09-29 at 15 58 26" src="https://user-images.githubusercontent.com/113980488/195525626-8348942c-6d36-49bd-ba39-a12a63ada436.png">

Then this will first check in the cache. There is no client id as the “admin” as per this case, and this will hit the db to get the client secret from there. In the DB also there is no recode as the “admin” then from the code this will log the error saying OAuthAppDAO#getAppIdByClientId [5]

So depending on the request the clientId is changing

- /oauth2/authorize → clientID = null
- /oauth2/token → clientID = correct client id
- /oauth2/userinfo → clientID = null
- /oauth2/introspect → clientID = userName

Highly appreciate your input regarding this because these logs are very confusing eventhoue we can log in successfully to the publisher portal and also can we improve the code segments ?

[1] (https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/854debbc4456fe46b7c0cfdb74fe76c0a9ea40cf/components/org.wso2.carbon.identity.oauth.client.authn.filter/src/main/java/org/wso2/carbon/identity/oauth/client/authn/filter/OAuthClientAuthenticatorProxy.java#L70)

[2] (https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/f5afde187f4d51f8ef35583466ebe3e08e999758/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/client/authentication/OAuthClientAuthnService.java#L60)

[3] (https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/9e1d9cc0bb7787f4925533874de252ccf9e2af09/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/client/authentication/BasicAuthClientAuthenticator.java#L160)

[4] (https://is.docs.wso2.com/en/latest/guides/access-delegation/invoke-oauth-introspection-endpoint/#validate-the-token)

[5] (https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/7e6d7217267bb1be35bed0aadf34201d96658ed3/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/dao/OAuthAppDAO.java#L1155)

### Solution

The same implementation is used for different kind of API calls that have different Authorized headers, Need to differentiate the generic calls and need to handle those separately. 
But it seems like this method is calling from different kind of places I only encountered this scenario only as for a MVP solution we can improve the logs here so the users will not get confused with the unwanted ERROR messages.

### Affected Component

APIM

### Version

APIM 4.1.0, Update Level : 31

**Comment by tharikaGitHub** [comment]
Closing as this fix is not applicable to master branch.
