### ISSUE TITLE
Pagination number change is not persisted in the Publisher portal

### ISSUE THREAD

**Issue by Methma** [wso2/api-manager#798]
### Problem

Hi Team,

The pagination choice [1] is not persisted in the Publisher portal (APIM 4.0.0).

Explanation: Let's say if we choose 15 items per page. But, if we go to some links after picking the choice and return back, the items per page will be reset to the default number 10.

But this is working as expected in the Dev portal.

[1]. 
![image](https://user-images.githubusercontent.com/11593733/195631594-5a129e20-19b7-474d-ad08-f459eb725b07.png)

Thanks,
Methma

### Solution

Persist the pagination choice in the Dev portal.

### Affected Component

APIM

### Version

4.0.0

**Comment by lakshithagunasekara** [comment]
Fixed with https://github.com/wso2/apim-apps/pull/361
