### ISSUE TITLE
Introduce custom fields in OAuth2-Token-Error-Respone

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/api-manager#808]
### Problem

When implementing a custom grant handler it is possible to add parameters to the success response but it is not possible to add custom parameters to error responses.

### Solution

Provide Method to Add Custom Parameters to OAuth error response to make it consistent across both success token responses and error responses

### Affected Component

APIM

### Version

latest

### Related Issues

https://github.com/wso2-enterprise/wso2-apim-internal/issues/758
https://github.com/wso2/product-is/issues/8155
https://github.com/wso2/product-is/issues/3194

**Comment by dulanjalidilmi** [comment]
Triggered PR builder. Awaiting to merge this once the build is passed.

**Comment by tharikaGitHub** [comment]
Closing as the fix is already added to APIM with a version bump.
