### ISSUE TITLE
[4.1.0] Imported API's thumbnail is not visible in the publisher portal.

### ISSUE THREAD

**Issue by 1akshitha** [wso2/api-manager#81]
### Description:
When we import an API with thumbnail and the preserve status is enabled, the thumbnail is not visible in the publisher portal. However we can see the thumbnail in the devportal. If we imported the API in the created status, the thumbnail can be seen.

This is due to an RXT field that we have in the API object getting replaced when we change the lifecycle during the import process.

### Steps to reproduce:
1. Create an API with thumbnal.
2. Change the lifecycle to publish
3. Export the API with preserve-status
4. Import the API to another environment.

### Affected product version:
4.1.0
### Affected component:
Import export

**Comment by chamilaadhi** [comment]
@1akshitha shall we close this issue since fix is merged
