### ISSUE TITLE
Endpoint Security not getting changed in Carbon console

### ISSUE THREAD

**Issue by Kirishikesan** [wso2/api-manager#812]
### Description

For an endpoint secured api, 
Api details in the carbon console shows that the endpoint is not secured and the username credentials are also not visible but the endpoint configuration json has the correct configuration in the **API Manager 4.1.0** pack

### Steps to Reproduce

1. Create an api from the publisher portal

2. Go to the endpoint section for the relevant api in the publisher

3. Set the API Endpoint Security to Basic Auth and set the username and password.
<img width="1497" alt="Screenshot 2022-10-19 at 12 31 54" src="https://user-images.githubusercontent.com/46290313/196621193-98b3fd39-cb01-4a4c-857c-71dd72ed7b5f.png">

4. Go to carbon console api meta data.

5. The endpoint secured will be false and the username password will be empty, but the endpoint configuration will have the correct configuration.
<img width="1487" alt="Screenshot 2022-10-19 at 12 23 47" src="https://user-images.githubusercontent.com/46290313/196622117-f1c1dfd2-efae-4a44-874c-22b6adfeb79f.png">

endpoint configuration: 
{"endpoint_type":"http","sandbox_endpoints":{"url":"http:\/\/webhook.site\/a121c3a1-adf5-4eb4-865d-6118594f61d5"},"endpoint_security":{"production":{"password":"admin","tokenUrl":"","clientId":null,"clientSecret":null,"customParameters":"{}","type":"BASIC","grantType":"","enabled":true,"username":"admin"},"sandbox":{"password":null,"tokenUrl":"","clientId":null,"clientSecret":null,"customParameters":"{}","type":"NONE","grantType":"","enabled":false,"username":""}},"production_endpoints":{"url":"http:\/\/webhook.site\/a121c3a1-adf5-4eb4-865d-6118594f61d5"}}

### Affected Component

APIM

### Version

4.1.0

### Environment Details (with versions)

OS: Mac OS
Browser: Safari

**Comment by BLasan** [comment]
Hi,

Closing this since the functionality works properly.

Thanks,
Benura
