### ISSUE TITLE
High CPU usage observed for GET requests with larger payloads

### ISSUE THREAD

**Issue by Thidasala** [wso2/api-manager#816]
### Description

When the request payload is larger than the buffer for HTTPS get requests, high CPU usage is observed in gateway

### Steps to Reproduce

1. Create a sample API in APIM
2. Use the following HTTPS mock backend for the API
[Mock_Java_Backend.txt](https://github.com/wso2/api-manager/files/9821567/Mock_Java_Backend.txt)
3. Invoke the API with a HTTPS get request with the below payload
[Request_Payload.txt](https://github.com/wso2/api-manager/files/9821442/Request_Payload.txt)

### Affected Component

APIM

### Version

3.2.0.179

### Environment Details (with versions)

JDK version: open jdk 11.0.15

**Comment by binodmx** [comment]
Closing this issue as a patch type issue is already created https://github.com/wso2-enterprise/wso2-apim-internal/issues/902.
