### ISSUE TITLE
There is no any health check for websocket transport in wso2 apim 4.0.0

### ISSUE THREAD

**Issue by selakap** [wso2/api-manager#822]
### Problem

Need to implement a WebSocket health check to wso2 apim 4.0.0 similar to 3.2.0 and 4.1.0

https://apim.docs.wso2.com/en/latest/install-and-setup/setup/deployment-best-practices/basic-health-checks/#

### Solution

You can back/front port the feature from 3.2.0 or 4.1.0

### Affected Component

APIM

### Version

4.0.0

**Comment by tharikaGitHub** [comment]
Closing the issue as the fix is already done via https://github.com/wso2/carbon-apimgt/pull/10973 to the master branch.
