### ISSUE TITLE
Custom User Store Manager

### ISSUE THREAD

**Issue by yquintana** [wso2/api-manager#827]
### Description

i am created a connection of user store JDBC and consuming by oauth:

![image](https://user-images.githubusercontent.com/4763898/197278695-94215eb2-6641-4387-b84d-c938dd80d38d.png)

AUDIT_LOG: Action=Get-User-Claim-Values Target=domain/xxxxx Data={"Claims":["http://wso2.org/claims/identity/accountLocked"],"Profile":"default"} Outcome=Failure Error={"Error Message":"Un-expected error while getting claim values, Error Occurred while getting property values for user : xxx & profile name : default","Error Code":"33002"}

 Action=Authentication Target=domain.comT/XXXX Data=null Outcome=Failure Error={"Error Message":"TUn-expected error while post-authentication, Error when handling event : POST_AUTHENTICATION","Error Code":"31004"}

Action : PostTokenIssue | Target : PasswordGrantAuditLogger | Data : { "AuthenticatedUser" : "N/A","AuthenticatedUserStoreDomain" : "N/A","AuthenticatedUserTenantDomain" : "N/A","ServiceProvider" : "xxxxxxxx_SANDBOX","RequestType" : "oauth2","RelyingParty" : 

### Affected Component

APIM

### Version

4.0.0

**Comment by lakshithagunasekara** [comment]
Provided information is not sufficient to identify the requirement. Please reopen with more information.
