### ISSUE TITLE
High CPU usage for certain pattern of HTTP requests

### ISSUE THREAD

**Issue by AshenShalitha** [wso2/api-manager#866]
### Description:
CPU usage increases and persist even for a small load of requests which has the following pattern. 

DEBUG - wire HTTPS-Listener I/O dispatcher-6 >> "GET /services/Version HTTP/1.0[\r][\n]"
DEBUG - wire HTTPS-Listener I/O dispatcher-6 >> "[\r][\n]"
DEBUG - wire HTTPS-Listener I/O dispatcher-6 >> "[\r][\n]"

### Steps to reproduce:

- Design a request which has the above mentioned pattern (With extra set of [\r][\n]). 
- Send few requests while monitoring the CPU usage.

### Affected Product Version:
APIM-4.0.0

**Comment by rosensilva** [comment]
Please verify whether the issue is fixed with the dependency update

**Comment by rosensilva** [comment]
The current http-core version is 4.4.16.wso2v1 and the issue is fixed.
