### ISSUE TITLE
Customizing JWT generation not working in WSO2 APIM 4.0.0

### ISSUE THREAD

**Issue by yquintana** [wso2/api-manager#869]
### Description

I tried to implement the steps given in WSO2 4.0.0 documentation https://apim.docs.wso2.com/en/4.0.0/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway/ for customizing JWT Claims.

As given in the documentation, I created the custom JWT generator java class, generated the jar and placed it under WSO2 Home/repository/components/lib folder . Did the necessary configurations in deployment.toml for enabling JWT and restarted the server.

Need suggestions on this as i have followed the steps given in the documentation.

I execute the examples CustomGatewayJWTGenerator,CustomJWTGenerator of [repo](https://github.com/wso2/samples-apim) official examples.

### Affected Component

APIM

### Version

4.0.0

### Related Issues

[deployment.toml]
![XXoCw](https://user-images.githubusercontent.com/4763898/198711550-78ffbe92-4089-44c4-abac-f60cebf17013.png)

[api-manager.xml]
![TF0Rw](https://user-images.githubusercontent.com/4763898/198711655-25dd8438-9648-4422-8bf3-04086cb33ed0.png)

[repository\components\dropins]
![n7rWM](https://user-images.githubusercontent.com/4763898/198711700-1de0df42-1f25-48eb-86bc-592a47addbd4.png)

[repository\components\lib]
![tYUBv](https://user-images.githubusercontent.com/4763898/198711769-713e7bed-e250-4ac2-8de9-68f01c2fb03e.png)

**Comment by lakshithagunasekara** [comment]
Need to verify this for APIM 4.2.0 release.

**Comment by Kirishikesan** [comment]
CustomGatewayJWTGenerator and CustomJWTGenerator are working as expected in APIM-4.2.0 pack. Therefore closing this issue.
