### ISSUE TITLE
APIM WebSub subscription try-out not using form-url-encoded type request

### ISSUE THREAD

**Issue by PasanT9** [wso2/api-manager#871]
### Problem

APIM supports form-url-encoded type requests which is the standard way of subscribing to a WebSub API[1]. Still the try-out scenario in APIM DevPortal uses the older way of invoking a WebSub implementation which is passing the hub parameters as query parameters in the POST request. 

This needs to be updated so that try-out scenario generates a curl which **passes the hub parameters in the request body as form-data** and the POST request **content type is of 'application/x-www-form-urlencoded'**. This will make sure API Manager WebSub implementation adhere to the standards specified by W3C[1].

[1] https://www.w3.org/TR/websub/

### Solution

Modify APIM WebSub try-out scenario in DevPortal so that, it generates a curl which passes the hub parameters in the request body as form-data and the POST request content type is of 'application/x-www-form-urlencoded'.

### Affected Component

APIM

### Version

4.1.0

### Related Issues

https://github.com/wso2/api-manager/issues/775

**Comment by Tharanidk** [comment]
update- 2023-01-09

- Analyzed the task to be done
- Installed necessary software and managed to create webhook APIs
- work on finding a suitable fix for the issue
- Started testing the fix

**Comment by Tharanidk** [comment]
update- 2023-01-10

- Tested the fix
- Put the PR after doing necessary fixes and getting confirmation
