### ISSUE TITLE
Getting 900906 for GraphQL Query API invocation

### ISSUE THREAD

**Issue by SupunTharakaSandaruwan** [wso2/api-manager#89]
### Description:

Once the APIM GraphQL API is invoked with query, 900906 issue occurs

### Steps to reproduce:

- Publish two GraphQL APIs.
- First Invoke the API 1 (API_1) and then invoke the second API (API_2).
- Again invoke the First API (API_1) and you will get 900906 issue

### Affected product version:

APIM 3.2.0

**Comment by msm1992** [comment]
This is N/A for the public branch.
