### ISSUE TITLE
Add yaml documents in the publisher portal is not working

### ISSUE THREAD

**Issue by sanethd** [wso2/api-manager#895]
### Description

Hi Team,

As per the update summary doc [1], it seems we have enabled adding additional media types for the documents, such as excel and yaml can be added as the document types in the publisher portal. (2021-10-12 update)

Even though the "yaml" type is not working in the update level  145. Could you please check?

Product : wso2am-4.0.0
Update level : 145

![aaaaaa](https://user-images.githubusercontent.com/9712144/199962324-97353c40-cc10-4edd-a1a2-abae7f178863.png)
<img width="843" alt="aaa11" src="https://user-images.githubusercontent.com/9712144/199962350-b7bd5f4e-97b2-40d7-b3c3-505a38b5804e.png">

### Steps to Reproduce

Steps to Reproduce

Create an API in APIM 4.0.0
Go to Publisher -->Portal Configurations --> Documents and try to attach a yaml file.
The yaml files are not allowed.

### Affected Component

APIM

### Version

4.0.0

**Comment by SavinduDimal** [comment]
Please note that [wso2/carbon-apimgt](https://github.com/wso2/carbon-apimgt) master branch fix was already added by https://github.com/wso2/carbon-apimgt/pull/10882
