### ISSUE TITLE
Error while updating the API definition

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#921]
### Description

The following error page is shown when updating the API Definition after clicking the Edit button in Publisher portal > API Definition page.

<img width="1680" alt="Screenshot 2022-11-13 at 18 46 19" src="https://user-images.githubusercontent.com/8557410/201523594-abf1c95b-689c-4f1d-aba6-d33542c69d3c.png">

The Network call in error is as follows. No errors shown in terminal and this happens for both tenant and super tenant.

<img width="1680" alt="Screenshot 2022-11-13 at 18 48 44" src="https://user-images.githubusercontent.com/8557410/201523738-c3970592-e2e7-4b89-bfb5-3c00e69febc0.png">

### Steps to Reproduce

1. Create an API
2. Go to API Definition page in Publisher portal
3. Click on Edit 
4. Click on Update Content button
5. Click on Save

### Affected Component

APIM

### Version

APIM 4.2.0 M1 testing pack

**Comment by hisanhunais** [comment]
The merging of the PR related to this issue is on-hold due to some test failures in the apim-apps repo.
