### ISSUE TITLE
Table of contents not shown in Cookie policy and Privacy Policy

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#922]
### Description

The table of contents section is empty in the Cookie policy and Privacy policy found in the Login page to portals.

<img width="1426" alt="Screenshot 2022-11-13 at 19 34 55" src="https://user-images.githubusercontent.com/8557410/201526062-8ec5f37c-7f99-4255-af96-f7050f09148c.png">

### Steps to Reproduce

Click on Cookie Policy and Privacy Policy links in the login page to portals.

<img width="803" alt="Screenshot 2022-11-13 at 19 38 56" src="https://user-images.githubusercontent.com/8557410/201526096-2fb9d975-b18b-45ee-8f69-63a30f356189.png">

### Affected Component

APIM

### Version

APIM 4.2.0 M1 testing pack

**Comment by chanaka3d** [comment]
This issue is fixed in the latest branch after merging the following PR. The missing jQuery plugin link is fixed.

https://github.com/wso2/product-apim/pull/13011

**Comment by tharikaGitHub** [comment]
Closing based on the above comment
