### ISSUE TITLE
Message after self signing up a new user is not appropriate

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#923]
### Description

The following message is shown after self signup. This is not appropriate as we have not configured email confirmation. But the user can be successfully log in without any confirmation and no email is received.

<img width="1680" alt="Screenshot 2022-11-13 at 19 33 15" src="https://user-images.githubusercontent.com/8557410/201526258-85c98195-0ee2-4ace-89e3-e862114124ed.png">

### Steps to Reproduce

Self signup a user in the developer portal and see the message.

### Affected Component

APIM

### Version

APIM 4.2.0 M1 testing pack

**Comment by GihanAyesh** [comment]
Comparing APIM 4.2 against IS 6.0 and APIM 4.1 against IS 5.11 to determine which UI change affected for the aforementioned bug.

**Comment by GihanAyesh** [comment]
Added the PR https://github.com/wso2/product-apim/pull/13049 for the fix

**Comment by tharikaGitHub** [comment]
Closing as the PR is merged.
