### ISSUE TITLE
[4.1.0][APICTL]Hidden files processing when APICTL deploy an API 

### ISSUE THREAD

**Issue by isuru-udayanga** [wso2/api-manager#928]
### Description

`Deploying Projects (1)... APIs (1) ... 1: CommonLoggingAPI-1.0.0: (CommonLoggingAPI-1.0.0) Error importing API. Status: 500 Response: {"code":500,"message":"Internal server error","description":"The server encountered an internal error. Please contact administrator.","moreInfo":"","error":[]} Error... 500 Rolling back to the last successful revision as there are failures.. apictl: There are project deployment failures. Failed to rollback. Reason: Failed to rollback as there are no previous successful revisions Exit status 1`

As we analysed, this happens due to the .gitkeep file processing inside in the Docs directory when deploying the API. Not only .gitkeep, If someone uses a Mac, there will be a chance to add a .DS_Store file as a hidden file and this issue can happen due to that also. So can't we ignore these hidden files processing when apictl vcs deploy?

### Steps to Reproduce

- Create project using apictl init command.
- Keep .gitkeep or any hidden file in the Docs directory.
- Deploy the API using apictl vcs deploy

### Affected Component

APICTL

### Version

4.1.0

### Relevant Log Output

```shell
Deploying Projects (1)... APIs (1) ... 1: CommonLoggingAPI-1.0.0: (CommonLoggingAPI-1.0.0) Error importing API. Status: 500 Response: {"code":500,"message":"Internal server error","description":"The server encountered an internal error. Please contact administrator.","moreInfo":"","error":[]} Error... 500 Rolling back to the last successful revision as there are failures.. apictl: There are project deployment failures. Failed to rollback. Reason: Failed to rollback as there are no previous successful revisions Exit status 1
```

**Comment by lakshithagunasekara** [comment]
fixed with https://github.com/wso2/carbon-apimgt/pull/11655
