### ISSUE TITLE
[4.2.0][APICTL] Delete Artifact Shown in Status Before Committing in Git Integration

### ISSUE THREAD

**Issue by hisanhunais** [wso2/api-manager#930]
### Description

vcs status command shows the deleted artifact from the repository as a change before committing the changes to git

### Steps to Reproduce

1. Set --vcs-deletion-enabled=true [1]
2. Create an API in dev environment
3. Export the API from dev environment
4. Extract and add it to source repository
5. Set source repository
6. Commit it (git add & git commit)
7. apictl vcs init
8. apictl vcs deploy -e prod. The API will be deployed to the prod environment
9. Delete the API from the source repository (Do not commit the changes to git)
10. apictl vcs status -e prod. The changes will be shown the status command.

Related Documents
[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/api-controller/advanced-topics/configuring-git-integration/#enabling-project-deletion-via-git-integration
[2] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/api-controller/cicd-using-cli/

### Affected Component

APICTL

### Version

APICTL 4.2.0 M1 testing pack

### Environment Details (with versions)

OS: Ubuntu 20.04 LTS
JDK Version: openjdk version "17.0.5"

**Comment by lakshithagunasekara** [comment]
This is a limitation in the tool as underneath, it uses `git diff` with the previous commit id. This returns all the changes done to the repo which includes committed changes as well as non committed changes. However this will only be visible with status check and will not be propagated with `vcs deploy`.

Therefore closing this issue.
