### ISSUE TITLE
Wrong url generated for the service catalog page/menu in Api Publisher

### ISSUE THREAD

**Issue by AshenJayasuriya** [wso2/api-manager#933]
### Description

After configuring to access the server through a custom proxy path (eg. /apim) according to the document[1], the Service Catalog page is not loading in the publisher portal.

[1]https://apim.docs.wso2.com/en/latest/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path/

### Steps to Reproduce

- Configure the APIM server to access through a custom proxy path with Nginx as per the document.
- Start the Nginx and APIM server.
- Login to the Publisher portal.
- Go to the Services menu/page.
- Observe the redirected URL as below 
`https://<hostname>/api/am/service-catalog/v1/services`
- Go to the other menus/pages.
- Observe the redirected URL with the custom proxy name as below.
`https://<hostname>/apim/api/am/publisher/v3/api-products`

### Affected Component

APIM

### Version

4.1.0

**Comment by YasasRangika** [comment]
closing as the public fix: https://github.com/wso2/apim-apps/pull/391 has already been merged to the main branch.
