### ISSUE TITLE
Allow passing scopes in the application registration call from the dev portal with Forgerock - APIM 4.0.0

### ISSUE THREAD

**Issue by akila95fernando** [wso2/api-manager#940]
### Problem

Cannot parse the client type and scopes when registering applications with the ForgeRock key manager via the dev portal of the API Manager 4.0.0 (DCR POST request)

### Solution

Adding a custom UI field at generate keys window.  

### Affected Component

APIM

### Version

4.0.0

### Related Issues

https://github.com/wso2/api-manager/issues/860

### Suggested Labels

APIM 4.0.0

**Comment by Tharanidk** [comment]
Hi,
Please find the ETA for this fix below,
Best Case Estimate: 2022-11-28
Most Likely Estimate: 2022-12-05
Worst Case Estimate: 2022-12-19

Thanks.
