### ISSUE TITLE
HTML error response pages contain WSO2 license header

### ISSUE THREAD

**Issue by PasanT9** [wso2/api-manager#943]
### Problem

To handle error responses APIM uses HTML error pages (error_500.html, error_400.html, ...). These pages contains the WSO2 license header. Since curl cannot sanitize HTML comments, if such a HTML page returns as a response to a curl request, the response will contain the license header as well.

### Solution

Remove WSO2 license headers from HTML error response pages.

### Affected Component

APIM

### Version

4.1.0

### Related Issues

https://github.com/wso2/api-manager/issues/906

**Comment by lakshithagunasekara** [comment]
@PasanT9 Can you share the public resolution for this issue?

**Comment by PasanT9** [comment]
Hi @lakshithagunasekara,

This is a duplication of https://github.com/wso2/product-is/issues/15558. WSO2 IS team has started working on the issue.

Therefore closing the issue.
