### ISSUE TITLE
Prepare and test APIM IS Migration Client for APIM 4.2 IS 6.0

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#960]
Need to sync apim-identity-migration client with identity-migration client for IS 6.0.0 migration.

Branches will separated as follows.
APIM versions prior to 4.2 -> use 5.x.x branch 
APIM versions from 4.2 -> use master branch

**Comment by dushaniw** [comment]
IS Migration client updated to 6.0.0 with https://github.com/wso2-extensions/apim-identity-migration-resources/pull/16

**Comment by Lakith-Rambukkanage** [comment]
Smoke tests :

- [ ] 2.6.0 to 4.2.0
- [ ] 3.0.0 to 4.2.0
- [ ] 3.1.0 to 4.2.0
- [ ] 3.2.0 to 4.2.0
- [ ] 4.0.0 to 4.2.0
- [ ] 4.1.0 to 4.2.0

**Comment by dushaniw** [comment]
closing as fixed with https://github.com/wso2-extensions/apim-identity-migration-resources/pull/16
