### ISSUE TITLE
[Connector] Add file metadata fetch support to msazurestorage connector

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/api-manager#963]
### Problem

We have introduced download blob support to msazurestorage via [1].
While we are doing the feature, we noticed that we can also retrieve file metadata details.
We need a new connector operation to fetch these metadata details 

[1] https://github.com/wso2-extensions/esb-connector-msazurestorage/pull/15

### Solution

Add new operation to fetch blob metadata

### Affected Component

MI

**Comment by pabloa2022** [comment]
**Status**:
Local test
Thanks

**Comment by pabloa2022** [comment]
Done. Changes in the code and the documentation sent.
I'll be waiting for feedback on this,
Thanks!
