### ISSUE TITLE
Execution plan deployment held back messages during server startup

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/api-manager#969]
### Description

The following logs are printed during server startup. `Execution plan deployment held back`
![image](https://user-images.githubusercontent.com/8557410/202846915-80723b5a-0742-4fb8-8b2b-99c19483ae8a.png)

### Steps to Reproduce

Start the server and observe the logs

### Affected Component

APIM

### Version

4.2.0-M1

**Comment by rosensilva** [comment]
Fixed with https://github.com/wso2/product-apim/pull/13110 and https://github.com/wso2/carbon-event-processing/pull/327
