### ISSUE TITLE
Create a Jenkins pipeline for APIM-4.2.0 integration tests

### ISSUE THREAD

**Issue by prasa7** [wso2/api-manager#971]
## Description
The new test grid does not natively support running integration tests on pre-release versions of the product. But here the requirement is to run the pre-release APIM-4.2.0 pack on the test grid and test with different databases. To fulfill this requirement following sub-tasks need to be completed.

- [x] Study the test grid implementation and identify an approach to support pre-release versions

## Approach

- [x] #1120
- [x] Create a new branch in [testgrid](https://github.com/wso2/testgrid) called apim-pre-release
- [x] #1121

**Comment by IsuruMaduranga** [comment]
05/12/2022 Update

- Had a discussion with Janeth
- Studied test-grid codebase
- Did necessary changes to add a new parameter to the test-grid code base to support pre-release versions ( https://github.com/wso2/testgrid-jenkins-library/pull/243 )

**Comment by IsuruMaduranga** [comment]
06/12/2022 Update

- Studied [apim-test-integration](https://github.com/wso2/apim-test-integration) and [test-grid](https://github.com/wso2/testgrid) to understand how it works and find a methodology to onboard pre-release versions
- Found a possible alternative method to our current approach by modifying https://github.com/wso2/apim-test-integration/blob/4.2.0/run-int-test.sh

**Comment by IsuruMaduranga** [comment]
08/12/2022 Update

- Alternative method doesn't work as expected.
- Added necessary changes to the test grid ( https://github.com/wso2/testgrid/pull/1416 )

**Comment by IsuruMaduranga** [comment]
09/12/2022 Update

- Running pre-release versions still gives errors on the test grid. The solution is not working as expected with added changes ( https://github.com/wso2/testgrid-jenkins-library/pull/243 & https://github.com/wso2/testgrid/pull/1416 ).
- Finding cause for the issue

**Comment by IsuruMaduranga** [comment]
12/12/2022 Update

Fixing the bugs with the following PRs 

1. https://github.com/wso2/testgrid/pull/1417
2. https://github.com/wso2/testgrid/pull/1418
3. https://github.com/wso2/testgrid/pull/1419

**Comment by IsuruMaduranga** [comment]
13/12/2022

Fixing the bugs with the following PRs

1. https://github.com/wso2/testgrid/pull/1420
2. https://github.com/wso2/testgrid/pull/1421

Now integration tests are running fine on APIM-4.2.0 pre-release version
