### ISSUE TITLE
[MI][MI-Dashboard] Alpha release tasks

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/api-manager#978]
Alpha Release Tasks
- [x] https://github.com/wso2/api-manager/issues/976
- [x] https://github.com/wso2/api-manager/issues/983
- [x] https://github.com/wso2/api-manager/issues/991
- [x] https://github.com/wso2/api-manager/issues/992
- [x] https://github.com/wso2/api-manager/issues/1107
- [x] https://github.com/wso2/api-manager/issues/1108
- [x] https://github.com/wso2/api-manager/issues/1119

**Comment by SanojPunchihewa** [comment]
Closing this issue since MI and MI Dashboard Alpha is released
