### ISSUE TITLE
No Validation for Wrong Username Formats in "Forgot Password" Option and Throw a Exception When Trying with a Username with"@"

### ISSUE THREAD

**Issue by piyumaldk** [wso2/api-manager#982]
### Problem

When a user try to change his/her password through "Forgot Password" Option, But Mistakenly add a "@" for the username or an email as the username, APIM will not handle the exception in a proper way. User will  be redirected to "unable to handle this request" page.
![username-format-wrong-2](https://user-images.githubusercontent.com/38649090/203016192-b497d355-dbf4-426a-9189-966a11f934fa.png)
![username-format-wrong](https://user-images.githubusercontent.com/38649090/203016229-29ed409d-5b32-4b6b-9969-46c3058f926f.png)

### Solution

Add Field Validation to stop users from adding emails and usernames with @ will be one solution. Showing an error after trying to reset the password will be another solution.

### Additional Note

In order to try the Forgot Password option in APIM, you can follow [this](https://apim.docs.wso2.com/en/4.2.0/consume/user-account-management/recover-password/) documentation. 
Since it may need a minor improvement, you may also read [this](https://github.com/wso2/docs-apim/issues/6456) issue which is related to the above documentation.

### Affected Component

APIM

### Version

4.2.0-M1

**Comment by GihanAyesh** [comment]
Added the PR with the fix : https://github.com/wso2/product-apim/pull/13038
