### ISSUE TITLE
APIM 4.2.0 Pre Alpha Release Testing

### ISSUE THREAD

**Issue by piyumaldk** [wso2/api-manager#985]
### Description

This is to track APIM 4.2.0 release testing progress of @piyumaldk 

### Tests

- [x] API Categories
- [x] Pass a Custom Authorization Token to the Backend
- [x] External Stores
- [x] Subscription blocking/unblocking
- [x] SOAP APIs Creation/Invocation
- [x] Create api from OpenAPI definition
- [x] Application properties 
- [ ] Identity management features
    - [x] Forgot Password

### Created Issues

1. https://github.com/wso2/api-manager/issues/981
2. https://github.com/wso2/api-manager/issues/982
3. https://github.com/wso2/api-manager/issues/984

### Created Documentation Issues

1. https://github.com/wso2/docs-apim/issues/6424
2. https://github.com/wso2/docs-apim/issues/6426
3. https://github.com/wso2/docs-apim/issues/6451
4. https://github.com/wso2/docs-apim/issues/6456

### Affected Component

APIM

### Version

4.2.0-M1

### Related Issues

https://github.com/wso2/api-manager/issues/1073

**Comment by tharikaGitHub** [comment]
Closing as the tasks are complete.
