### ISSUE TITLE
Check pending public pull requests

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/api-manager#991]
### Description

Review public pull requests

### Affected Component

MI

**Comment by sajinieKavindya** [comment]
Let's merge the following open PRs in the following repos for APIM-4.2.0 alpha release.

- Synapse 

- [ ] https://github.com/wso2/wso2-synapse/pull/1947

- Mediation 

- [ ] https://github.com/wso2/carbon-mediation/pull/1621, https://github.com/wso2/carbon-mediation/pull/1643

- MI 

- [ ] https://github.com/wso2/micro-integrator/pull/2801 
- [ ] https://github.com/wso2/micro-integrator/pull/2802
- [ ] https://github.com/wso2/micro-integrator/pull/2803
- [ ] https://github.com/wso2/micro-integrator/pull/2805

**Comment by SanojPunchihewa** [comment]
Need to upgrade synapse and mediation in MI with the following PRs,

- [ ] https://github.com/wso2/micro-integrator/pull/2810
