### ISSUE TITLE
Upgrade component versions for Micro Integrator

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/api-manager#992]
### Description

We need to upgrade the internal component versions in MI.

### Affected Component

MI

**Comment by sajinieKavindya** [comment]
So far, we have upgraded the following components:

- Synapse to 2.1.7-wso2v316 - https://github.com/wso2/micro-integrator/pull/2791
- Axis2-transport to 2.0.0-wso2v67 - https://github.com/wso2/micro-integrator/pull/2795
- Carbon kernel to 4.8.0-m2 - https://github.com/wso2/micro-integrator/pull/2795
- HTTPCore-NIO to 4.4.15-wso2v2 - https://github.com/wso2/micro-integrator/pull/2790

**Comment by sajinieKavindya** [comment]
The following components have been upgraded to these versions so far.

- Synapse to **4.0.0-wso2v1** - https://github.com/wso2/micro-integrator/pull/2794
- Carbon-mediation to **4.7.147** - https://github.com/wso2/micro-integrator/pull/2794

**Comment by sajinieKavindya** [comment]
- Carbon-analytics-common to **5.2.49** - https://github.com/wso2/micro-integrator/pull/2797

**Comment by madushadhanushka** [comment]
Shared MI and MI-Dashboard latest master packs for pre-alpha release testing on the GDrive.

**Comment by SanojPunchihewa** [comment]
The following components have been upgraded to these versions.

- Synapse to **4.0.0-wso2v4** - https://github.com/wso2/micro-integrator/pull/2810
- Carbon-mediation to **4.7.153** - https://github.com/wso2/micro-integrator/pull/2811
- HTTPCore-NIO to **4.4.16.wso2v1** - https://github.com/wso2/micro-integrator/pull/2801
- Carbon-analytics-common to **5.2.50** - https://github.com/wso2/micro-integrator/pull/2803

**Comment by SanojPunchihewa** [comment]
Closing this issue since all the components related to the MI 4.2.0-alpha release are updated.
