### ISSUE TITLE
Bump wso2-synapse version to 4.x

### ISSUE THREAD

**Issue by isudana** [wso2/api-manager#996]
### Description

Currently, wso2-synapse version is in 2.x range. 2.x is the version of Apache Synapse when we were forking it a long time ago. Now, wso2-synapse has evolved a lot and contains many features and improvements compared to Apache Synapse. So I think it makes much sense to increase the version to something beyond 3.x at this point.

### Affected Component

MI

**Comment by prasa7** [comment]
Hi This is to give the status update of the ticket

REPO | PR | STATUS | GIT TAG 
| ------------- | ------------- | ------------- |------------- |
wso2-synapse | https://github.com/wso2/wso2-synapse/pull/2032 | Merged | https://github.com/wso2/wso2-synapse/releases/tag/v4.0.0-wso2v1
carbon-mediation | https://github.com/wso2/carbon-mediation/pull/1651 | Merged | https://github.com/wso2/carbon-mediation/releases/tag/v4.7.147
micro-integrator | https://github.com/wso2/micro-integrator/pull/2794 | Merged |  N/A
carbon-apimgt | https://github.com/wso2/carbon-apimgt/pull/11681 | Merged | Release inprogres
product-apim |https://github.com/wso2/product-apim/pull/13026| OPEN | Waiting for the carbon-apimgt to get released

**Comment by prasa7** [comment]
HI,

carbon-apimgt build and micro integrator builds were sucessful with the changes.


REPO | PR | STATUS | GIT TAG 
| ------------- | ------------- | ------------- |------------- |
wso2-synapse | https://github.com/wso2/wso2-synapse/pull/2032 | Merged | https://github.com/wso2/wso2-synapse/releases/tag/v4.0.0-wso2v1
carbon-mediation | https://github.com/wso2/carbon-mediation/pull/1651 | Merged | https://github.com/wso2/carbon-mediation/releases/tag/v4.7.147
micro-integrator | https://github.com/wso2/micro-integrator/pull/2794 | Merged |  N/A
carbon-apimgt | https://github.com/wso2/carbon-apimgt/pull/11681 | Merged | **https://github.com/wso2/carbon-apimgt/releases/tag/v9.28.7**
product-apim |https://github.com/wso2/product-apim/pull/13026| Open | **Waiting for git action build to be successful**
Thanks

@prasa7

**Comment by tharikaGitHub** [comment]
Closing as the upgrade is completed.

Related Issue : https://github.com/wso2/api-manager/issues/1093
